[레거시 코드 리팩터링 - 3단계] 나봄(윤보민) 미션 제출합니다.
woowacourse/jwp-refactoring pull request #165
Opened 2021-11-10 03:41 UTC by qhals321

안녕하세요 영이!! 이번에도 잘 부탁드립니다 헤헤헤
이번 미션에서 한 일은 다음과 같아요!
1. 패키지 분리 (order -> menu -> product). 단방향으로 의존하게끔 구성해봤어요! 아쉬웠던 부분은 table 을 order 에서 나눠주고 싶었는데 양방향을 끊기가 너무나 힘들더라고요.. 그래서 일단 3단계는 내고 멀티모듈로 나누면서 생각해보고 싶어요! 영이가 아신다면 힌트를 주신다면 감사하겠습니다 =]
2. 메뉴 변경 시 오더에는 아무 영향이 가지 않게 하기. 
  이 부분은 메뉴 변경 시 이벤트를 발생시켜 오더에서 변경 전 메뉴를 새로운 메뉴로 등록해 해당 메뉴를 들고있던 오더의 메뉴 아이디를 전부 새로운 메뉴로 변경시키는 로직으로 진행했습니다!

남은 기간 영이도 파이팅하세요!!

2021-11-13 06:56 UTC, qhals321 commented
table 과 order 사이의 양방향 의존을 끊었습니다~!
order 가 table 을 의존하도록 설계했습니다.
table 이 변할 수 있는 조건을 담고 있는 컨디션 컨테이너를 만들고 order 에서 구현하고 넣어주는 방식으로 설계했습니다!

2021-11-15 03:40 UTC, choijy1705 requested changes
안녕하세요 나봄
스프링 이벤트를 활용하여 의존성을 줄이는 부분이 인상깊었습니다.
많은 부분을 배울 수 있었어요...
아직 잘 이해가 안되는 부분이 많아서 궁금증들을 리뷰로 남겼습니다.

2021-11-15 03:40 UTC, choijy1705 commented on src/main/java/kitchenpos/order/application/MenuUpdateEventHandler.java
> +package kitchenpos.order.application;
menuUpdate인데 order package에 둔 이유가 있을까요?

2021-11-15 03:40 UTC, choijy1705 commented on src/main/java/kitchenpos/order/application/OrderTableConditionInjector.java
> +    }
어떤 과정에서 사용이 되는지 설명해주실수 있나요...?

2021-11-15 03:46 UTC, qhals321 commented on src/main/java/kitchenpos/table/domain/OrderTable.java
> +//    }
오우... 감사합니닼ㅋㅋㅋㅋ

2021-11-15 03:49 UTC, qhals321 commented on src/main/java/kitchenpos/order/domain/repository/OrderRepository.java
> +    List<Order> findByOrderTableId(Long orderTableId);
개인적으로 jpql 을 선호하게 되네요!
메서드네이밍으로 쿼리를 작성하게 되면 join fetch 와 같은 부분이 한 번에 눈에 띄지 않아서 좀 불편한 부분도 있더라고요!!
그래서 직접 쿼리를 작성하는 버릇이 있네요!

2021-11-15 03:55 UTC, qhals321 commented on src/main/java/kitchenpos/order/application/MenuUpdateEventHandler.java
> +    }
이미 해당 메뉴로 등록되어있는 주문이 존재한다면 다음 이벤트가 발생됩니다! (없을 시에는 바로 return 입니다~!)
해당 메뉴로 등록되어 있는 주문 자체를 한 번 복제하고 다시 등록을 합니다!
(order - menu1 로 등록되어 있고 menu1 의 정보를 바꾼다면 menu1 을 임시로 저장하는 방식입니다!)
이후에 기존 메뉴를 바라보고 있던 주문은 전부 복제된 메뉴를 바라보게끔 했습니다!
주문 전부 바꾼 이유는 나중에 영수증 다시 끊어달라고 할 때 당시 주문했던 금액과도 같아야하므로 이전 주문들은 모두 바꾸게 했습니다.

이후에 기존 메뉴의 정보를 업데이트 하는 방식으로 구현했습니다!

2021-11-15 03:55 UTC, qhals321 commented on src/main/java/kitchenpos/menu/domain/MenuUpdateEvent.java
> +    }
이 부분은 그냥 이벤트 발생 시 이벤트 처리에서 필요한 데이터를 모아둔 거에요! DTO 개념처럼요!

2021-11-15 03:56 UTC, qhals321 commented on src/main/java/kitchenpos/order/application/MenuUpdateEventHandler.java
> +package kitchenpos.order.application;
메뉴가 업데이트 될 시에 주문 처리에서 해당 이벤트를 받아서 처리를 해야되기 때문에 주문 패키지에 위치했습니다!
주문 자체가 존재하지 않다면 메뉴를 이렇게 이벤트 처리를 할 필요가 없기에 주문에 속하는 것이 맞다고 판단했습니다~!

2021-11-15 05:23 UTC, qhals321 commented on src/main/java/kitchenpos/order/application/OrderTableConditionInjector.java
> +    }
이 부분은 Table 이 Order 를 의존하는 부분을 없애기 위해 만들었습니다~!
기존에는 table <-> order 서로 의존하는 부분이 있었습니다.
order 의 상태가 COOKING 이거나 MEAL 일 때에는 table 을 ungroup 하는 것이 불가능하게 해야했습니다!
그런데 table -> order 의존성을 끊고 싶었습니다!

그래서 table 입장에서는 ungroup 할 수 있는 컨디션들을 관리하는 컨테이너를 만들었고
order 부분에서 해당 컨디션을 추가해주는 방식으로 진행했습니다.
아래는 table 에서 ungroup 할 수 있는지 컨디션 체크하는 부분입니다!
```
        if (orderTableCondition.isUnableToUngroup(tableGroupId)) {
            throw new IllegalArgumentException();
        }
```

2021-11-15 07:04 UTC, choijy1705 approved these changes
리뷰 답글 남겨주신거 확인했어요
나봄 코드를 보면서 미션 요구사항을 좀 더 명확하게 이해할 수 있었던것 같아요
이번 단계는 머지하겠습니다
남은 기간 화이팅입니다

2021-11-15 07:04 UTC, merged