[레거시 코드 리팩터링 - 1단계] 범고래(조충범) 미션 제출합니다.
woowacourse/jwp-refactoring pull request #224
Opened 2022-10-24 09:18 UTC by cndqjacndqja

안녕하세요 애쉬~!
마지막 미션 잘 부탁드립니다 :)

2022-10-25 08:31 UTC, dongho108 requested changes
안녕하세요 범고래~
코드 잘 봤습니다. ㅎㅎ
몇가지 리뷰 남겼는데 제가 범고래의 생각과 다르게 이해했거나, 제 의견과 다르다면 언제든지 답글 남기거나 슬랙주시거나 직접 말씀해주셔도 좋아요!

혹시 RCA 룰 처음 받아보셨을까봐 설명남깁니다.
RCA 룰
* r : 반영해주세요
* c : 꼭 반영하지 않아도 되지만 고려해주세요.
* a : 반영하지 않으셔도 좋습니다.

2022-10-25 08:31 UTC, dongho108 commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +    void createThrowExceptionWhenNotExistMenuId() {
c: DisplayName이 달린 테스트도 있고 아닌 것도 있는데 어떤 기준으로 작성하셨나요?

2022-10-25 08:31 UTC, dongho108 commented on src/main/java/kitchenpos/application/OrderService.java
> +                .orElseThrow(() -> new IllegalArgumentException("주문 테이블을 입력해야 합니다."));
r: `입력`이라는 메세지는 view에 의존적인 이름인 것 같아요!

2022-10-25 08:31 UTC, dongho108 commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +        Order order = Order.of(1L, "", LocalDateTime.now(), List.of(orderLineItem));
a: 테스트만 읽고는 어떻게 테스트가 돌아갈 수 있었는지 몰랐고, 프로덕션 코드에 존재하는 flywayV2 -> orderTable -> empty -> true인 것을 확인해야 했습니다.
현재 구조에서 테스트만 보고도 주문 테이블이 비어있을 때 create하면 예외가 발생한다는 테스트인 것을 알 수 있도록 개선할 수 있을까요?

물론 다른 테스트 코드들도 V2에 의존하고 있어서 코드가 많이 변해야한다면 안바꿔도 될 것 같아요. 선택입니다.

2022-10-25 08:31 UTC, dongho108 commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +        assertThat(changedOrder.getOrderedTime()).isEqualTo(changedOrder.getOrderedTime());
r: A를 A로 검증하고 있어요!!

2022-10-25 08:31 UTC, dongho108 commented on src/test/java/kitchenpos/application/TableServiceTest.java
> +    }
r: 아무 검증을 하지 않는 테스트네용

2022-10-25 08:31 UTC, dongho108 commented on src/main/java/kitchenpos/application/TableService.java
> +            throw new IllegalArgumentException("Guest는 0명 이하일 수 없습니다.");
r: 로직을 봤을땐 `0명 미만일 수 없습니다`가 맞아 보이네요.

2022-10-25 12:42 UTC, cndqjacndqja commented on src/main/java/kitchenpos/domain/Product.java
> +        }
Service에서 domain이 책임져야 할 로직이 꽤 많은데, 일단 이번 단계에서는 테스트를 작성하는 것에만 집중했습니다!
다만 Product 같은 경우는 변경 사항이 크지 않을 것 같아서, 이 부분만 도메인으로 옮겼습니다 :)

2022-10-25 12:44 UTC, cndqjacndqja commented on src/test/java/kitchenpos/application/ProductServiceTest.java
> +    }
전 도메인에서 검증하는 로직이여도 ServiceTest에서 검증하는 것을 선호하는데요!
현재 Service 테스트를 도메인과 함께 통합해서 테스트 하고 있기 때문에, 발생할 수 있는 예외 상황을 함께 테스트 해줄 수 있다면
추가하는 편입니다 :)

2022-10-25 12:47 UTC, cndqjacndqja commented on src/main/java/kitchenpos/domain/Menu.java
> +    }
`현재는 테스트에서 밖에 사용하고 있지 않지만, id를 제외한 값으로 객체를 생성할 일이 꼭 생기지 않을까?` 라고 생각해서 추가했었습니다 :)
하지만 당장 사용하지 않는 부분을 추가하는 것은 지양하는게 좋을 것 같다고 생각하여 제거했습니다 :)

2022-10-25 12:51 UTC, cndqjacndqja commented on src/main/java/kitchenpos/application/OrderService.java
> +                .orElseThrow(() -> new IllegalArgumentException("주문 테이블을 입력해야 합니다."));
공감합니다 👍 
반영했습니다 ~ :)

2022-10-25 12:53 UTC, cndqjacndqja commented on src/test/java/kitchenpos/application/TableServiceTest.java
> +    }
추가했습니다 :)

2022-10-25 12:56 UTC, cndqjacndqja commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +    void createThrowExceptionWhenNotExistMenuId() {
이번에는 `@DisplayName`을 사용하지 않고 작성했는데, 통일이 안된 하나의 메서드가 존재해서 변경했습니다 :)

2022-10-27 11:25 UTC, dongho108 approved these changes
반영해주신부분들 다 확인했습니다.

고생하셨어요! 2단계 진행해주세요~

2022-10-27 11:25 UTC, merged