[레거시 코드 리팩터링 - 1단계] 아키(허영운) 미션 제출합니다.
woowacourse/jwp-refactoring pull request #240
Opened 2022-10-24 12:19 UTC by yeongunheo

클레이 안녕하세요!
1단계에서는 컨트롤러 테스트와 서비스 테스트를 작성해보았습니다.
잘부탁드립니다 🙆🏻‍♂️

2022-10-25 07:41 UTC, yangdongjue5510 requested changes
안녕하세요 아키!!
전체적으로 깔끔하게 잘 작성해주셨네요.
다만 예외 케이스가 다뤄지지 않은 부분이 꽤 있어서 이 부분 한번 체크해주시고 다시 리뷰 요청해주세요!
그 외 궁금한 점은 코멘트로 달아놨습니당

2022-10-25 07:41 UTC, yangdongjue5510 commented on src/main/java/kitchenpos/domain/MenuGroup.java
> +    }
불변하지 않은 필드를 포함해서 hashcode를 재정의하는게 문제가 있을 수 있을 것 같아요.
https://kwonnam.pe.kr/wiki/java/equals_hashcode

2022-10-25 07:41 UTC, yangdongjue5510 commented on src/main/java/kitchenpos/domain/MenuGroup.java
> +    }
테스트를 위해 여러 생성자를 만드셨네용.
대신 기존에 있던 생성자만 사용하고 대신 픽스처를 만들어서 활용하는 방법도 있을 것 같아요.

2022-10-25 07:41 UTC, yangdongjue5510 commented on README.md
> +
요구사항에 예외 상황도 정리하면 예외 케이스를 빼먹지 않고 테스트 코드로 작성할 수 있을 것 같아용

2022-10-25 07:41 UTC, yangdongjue5510 commented on src/test/java/kitchenpos/ui/TableRestControllerTest.java
> +@WebMvcTest(TableRestController.class)
오 컨트롤러 테스트도 하셨네요!!! 좋아용

2022-10-25 07:41 UTC, yangdongjue5510 commented on src/test/java/kitchenpos/ui/ControllerTest.java
> +    private WebApplicationContext ctx;
오 `@WebMvcTest` 어노테이션이 없어도 이런식으로 필드를 선언해놓을 수 있었는지 몰랐었는데 신기하네요

2022-10-25 07:41 UTC, yangdongjue5510 commented on src/test/java/kitchenpos/application/TableServiceTest.java
> +@Transactional
오 테스트 독립성을 위해서 `@Transactional`을 사용하셨네요
truncate 문을 활용한 sql 파일보다 `@Transactional`을 사용하신 이유가 있을까요??

2022-10-25 07:41 UTC, yangdongjue5510 commented on src/test/java/kitchenpos/application/ProductServiceTest.java
> +    @DisplayName("상품을 생성할 때 가격이 음수이면 반환한다.")
`예외를 반환한다`가 맞을 것 같아요

2022-10-25 07:41 UTC, yangdongjue5510 commented on src/test/java/kitchenpos/application/TableGroupServiceTest.java
> +
단체 지정하려는 테이블이 이미 다른 그룹에 지정되어 있으면 예외를 반환하는 테스트도 있을 수 있지 않을까요?
혹은 해제하려는 그룹에 속한 테이블이 조리나 식사 상태일 수도 있을 것 같아요

2022-10-25 07:41 UTC, yangdongjue5510 commented on src/test/java/kitchenpos/application/TableServiceTest.java
> +    }
테이블을 빈 테이블로 수정할 때 그 테이블이 그룹에 속해있으면 예외가 발생할 것 같아요.

2022-10-26 00:23 UTC, yeongunheo commented on build.gradle
> +sourceCompatibility = '11'
`List.of` 가 자바8에서 쓸 수 없어서 11로 올렸습니다.

진짜 회사의 레거시코드였다면 신입인 제가 버전을 맘대로 올릴 수 없을테니 
원래버전인 자바8로 다시 되돌리고 리팩토링을 진행해봐야겠어요!

2022-10-26 00:37 UTC, yeongunheo commented on src/main/java/kitchenpos/domain/MenuGroup.java
> +    }
기존에 담았던 HashMap, HashSet 객체의 hashCode가 변경될 여지가 있어서 문제가 되는 코드인거군요.
재정의한 equals&hashCode는 모두 지우고 동등성 비교가 필요할 땐 `usingRecursiveComparator`를 한번 써볼게요!

> **Mutable(변경가능한) 필드에 대한 equals/hashCode 구현은 하면 안 된다**
변경가능한 필드에 대해 equals, hashCode를 구현한 상태에서 해당 필드 값을 변경하면 동일 객체라도 hashCode가 바뀌게 된다.
이 상태로 필드 변경전에 HashSet에 값을 넣었다면, 필드 값을 변경한 후에는 해당 객체를 HashSet에서 찾을 수 없게 된다. hashCode로 bucket을 결정하는데 hashCode가 바뀌었기 때문이다.
출처 : https://kwonnam.pe.kr/wiki/java/equals_hashcode

2022-10-26 00:37 UTC, yeongunheo commented on src/main/java/kitchenpos/domain/MenuGroup.java
> +    }
프로덕트 코드의 변경 없이 테스트할 수 있도록 테스트 픽스처를 만들어 활용했습니다.

2022-10-26 06:46 UTC, yeongunheo commented on README.md
> +
모든 예외케이스를 꼼꼼히 README.md에 적고 하나하나 테스트코드를 작성해봐야겠네요.

2022-10-26 10:53 UTC, yeongunheo commented on src/test/java/kitchenpos/ui/TableRestControllerTest.java
> +@WebMvcTest(TableRestController.class)
예외 케이스는 일단 서비스에만 빡세게 해두었습니다ㅠ

2022-10-26 10:54 UTC, yeongunheo commented on src/test/java/kitchenpos/application/TableServiceTest.java
> +@Transactional
당장 테스트격리를 위해 truncate문은 필요없다고 생각해서 `@Transactional`을 사용했습니다.

2022-10-26 10:56 UTC, yeongunheo commented on src/test/java/kitchenpos/application/TableGroupServiceTest.java
> +
다음 2가지 경우에 대한 예외테스트도 생성했습니다!
- 그룹화할 때 개별 주문테이블의 테이블그룹은 null이어야 한다.
- 그룹화를 해제할 때 상태가 `COOKING` 또는 `MEAL`인 개별주문테이블이 하나라도 있다면 예외를 발생한다.

2022-10-26 10:57 UTC, yeongunheo commented on src/test/java/kitchenpos/application/TableServiceTest.java
> +    }
다음 경우에 대한 테스트코드도 모두 추가해두었습니다!
- 빈 테이블 상태를 수정한다.
  - 수정하려는 주문테이블이 단체 지정되어있으면 예외를 발생한다.
  - 상태가 COOKING 또는 MEAL이라면 예외를 발생한다.
- 테이블 인원을 수정한다.
  - 방문한 손님 수는 0 이상이어야 한다.
  - 수정하려는 테이블이 비어있으면 예외를 발생한다.

2022-10-27 01:36 UTC, yangdongjue5510 commented
아키 반영된 부분 확인했습니다!
빠르게 피드백 잘 반영해주신 것 같네요!
머지 하고 다음 단계 때 또 뵐게용!

2022-10-27 01:36 UTC, merged