[레거시 코드 리팩터링 - 1단계] 리버(구동희) 미션 제출합니다.
woowacourse/jwp-refactoring pull request #243
Opened 2022-10-24 12:30 UTC by gudonghee2000

안녕하세요 루나! 리뷰를 부탁드릴 리버입니다!😊

1단계 미션을 진행하면서 프로덕션 코드를 수정하지 않고 테스트 코드를 작성하려고 하니 
많이 복잡했던 미션인것 같아요😔

그래도 두가지 측면에 집중해서 작성해보았어요!

### 1. 어떻게 하면 테스트 코드를 볼 때, 재밌게 볼 수 있을까?
프로젝트를 하면서도 테스트 코드를 보는것은 많이 지루했던 경험이 있었어요!
그래서 이번에 테스트 코드를 작성하면서 나름의 재밌는 요소들을 넣어보았는요!!
테스트 코드를 보는건 항상 지루하지만 조금이나마 재밌는 테스트 코드가 되었으면 해요😊😊

### 2. 테스트 코드와 관련한 fixture를 최소화 하는 방법은 어떤게 있을까?
이 부분 또한, 프로젝트를 하면서 느낀 부분이예요! 
프로젝트를 하면서 매번 필요할때마다 fixture를 생성하니 무분별한 fixture들이 많이 생겼었는데요!

이번에 테스트 코드를 작성하면서 fixture를 최소화하기 위해 builder 패턴을 적용해보았어요!!
그런데 오히려 코드를 복잡하게 만든게 아닐까하는 걱정이 많이 들어요😔

이번 리뷰 잘부탁드립니다 루나!! 
감사합니다~~😊

2022-10-24 17:07 UTC, RunaNam requested changes
안녕하세요 리버! 
전체적으로 코드 고치시느라 많이 고생하셨겠구나... 하면서 봤던 것 같습니다. 제가 대충 넘겼던 부분도 꼼꼼하게 작성해주셔서 보면서 많이 배웠어요.
테스트코드에서 한글 변수명을 쓰는걸 저는 가독성 측면에서 나쁘지 않다고 생각하는 편이라서읽기도 편하고, 재밌게 읽었습니다 ㅎㅎ 👍👍👍
fixture나 builder에 대한 생각은 따로 comment 에 적었으니 확인 부탁드려요!
모든 리뷰를 반영하실 필요는 없고, 리버가 생각하기에 적절한 방향으로 적용해주시면 될 것 같습니다. 
+전체적으로 EOF 줄띄움이 없는 부분이 있는데 몇개는 comment로 달았지만 너무 반복되는 comment가 될 것 같아서 중간부터는 달지 않았습니다...! 한번 전체적으로 확인 부탁드려요!

2022-10-24 17:07 UTC, RunaNam commented on src/test/java/kitchenpos/common/builder/MenuBuilder.java
> +public class MenuBuilder {
각각의 Builder를 만드시는게 정말 꽤 품이 많이 드는 작업이었을 것 같은데 제 경우에는 보기 좋았던 것 같아요. 다만 해당 부분이 테스트에서 이뤄져야하는 부분인가에 대해서는 개인적으로 약간 의문이 들긴 합니다. (물론!!! 프로덕션을 고치지 않고 진행하고자 하셨기 때문에 그러셨을 거라고 생각합니다.... 고생많으셨습니다...)

2022-10-25 11:23 UTC, gudonghee2000 commented on src/test/java/kitchenpos/application/MenuGroupServiceTest.java
> +}
전체 클래스에 EOF에 줄바꿈을 추가하였어요!

2022-10-25 11:24 UTC, gudonghee2000 commented on src/test/java/kitchenpos/application/MenuGroupServiceTest.java
> +    private MenuGroup 루나세트;
루나세트!!🔥

2022-10-25 11:25 UTC, gudonghee2000 commented on src/test/java/kitchenpos/application/ServiceTest.java
> +}
도메인 별 `ServiceTest` 객체의 `@SpringBootTest` 애노테이션을 한곳에서 관리하고자 부모 `ServiceTest`를 만들어보았어요!

2022-10-25 11:41 UTC, gudonghee2000 commented on src/test/java/kitchenpos/common/fixtures/MenuGroupFixtures.java
> +    public static String 루나세트_이름 = "루나세트";
피드백 감사합니다 루나!😊

저도 다시한번 고민을 해보다가 `Constants`라는 객체에서 테스트와 관련한 모든 `원시값` 상수들만 관리하도록 구성을 해보았어요!

이렇게 구현한 이유는
테스트를 구현하다보니, 각 테스트 코드에서 다른 용도로 상수를 재활용 할 수도 있더라구요!

예를들어 `야채곱창_이름` 이라는 상수는 `Producet.name`, `MenuProduct.name` `Menu.name`에 사용 할수 있다는 생각이 들었어요.

그래서 모든 테스트 코드들이 Constants라는 하나의 객체만 의존하도록 `원시값 fixture`들을 `Constants` 객체에 모아보았어요!

2022-10-25 11:43 UTC, gudonghee2000 commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +    void 메뉴를_등록한다() {
프로젝트를 진행하면서 `@DisplayName`의 내용과 메서드 명을 통일 시키는 규칙이 있었는데요!

그때,  테스트 메서드 명을 고민할 시간을 줄일수 있어서 만족했던 경험이있었어요!
그래서 위와 같이 `displayName`과 테스트명을 통일해보았어요~

2022-10-25 11:44 UTC, gudonghee2000 commented on src/test/java/kitchenpos/application/TableServiceTest.java
> +}
추가하였어요!

2022-10-25 11:45 UTC, gudonghee2000 commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +        Order actual = orderService.create(야채곱창_주문);
네! given절과 네이밍이 겹치는 부분이 있어서 actual로 네이밍해보았습니다!

2022-10-25 11:54 UTC, gudonghee2000 commented on src/test/java/kitchenpos/common/builder/MenuBuilder.java
> +public class MenuBuilder {
맞습니다.. 프로덕션을 고치지 않고 진행하려다 보니 `buidler`의 위치를 테스트 코드에 위치시키게 되었어요!

2022-10-25 12:00 UTC, gudonghee2000 commented on src/test/java/kitchenpos/application/TableGroupServiceTest.java
> +        tableGroupService.ungroup(단체_테이블.getId());
조금 더 명확한 로직 검증을 위해서 `tableGroupService.ungroup()` 이후에 
각 `orderTable`의 `tableGroupId`가 없어졌음을 테스트 하도록 변경해보았어요!

2022-10-25 12:38 UTC, gudonghee2000 commented
안녕하세요 루나! 다시한번 리뷰를 부탁드릴 리버입니다!! 

루나가 남겨주신 피드백과 오늘 제이슨의 강의 내용을 기반으로 테스트 코드를 리팩터링해보았어요😊
이번 리뷰도 잘부탁드려요~~🚀🚀

2022-10-25 12:45 UTC, closed without merging