[레거시 코드 리팩터링 - 1단계] 알파(배철환) 미션 제출합니다.
woowacourse/jwp-refactoring pull request #249
Opened 2022-10-24 12:53 UTC by bcc0830

안녕하세요 스컬!
우선 README.md를 작성하고 현재 Service 클래스들에 대한 테스트 코드만 작성하였습니다
추가적으로 DTO 계층을 만들어 원래 Service 클래스들의 코드가 약간 수정되었으니 참고바랍니다
지금은 테스트환경을 sql파일로 하고 있는데 이 부분도 추후 fixture로 리팩토링할 예정입니다
마지막 미션 잘부탁드립니다!

2022-10-25 06:33 UTC, skullkim requested changes
안녕하세요 알파! 1단계 미션 잘 구현해 주셨네요. 리뷰 남겼으니 확인하고 수정해주세요😁

2022-10-25 06:33 UTC, skullkim commented on src/main/java/kitchenpos/application/TableGroupService.java
> +        }
이건 어때요?
```suggestion
               List<OrderTable> orderTables = orderTablesIds.stream()
                .map(orderTableDao::findById)
                .map(orderTable -> orderTable.orElseThrow(IllegalArgumentException::new))
                .collect(Collectors.toList());

```

2022-10-25 06:33 UTC, skullkim commented on src/main/java/kitchenpos/domain/OrderLineItem.java
> +        if (o == null || getClass() != o.getClass()) return false;
euqals 재정의에서 getClass를 사용하는 것은 리스코프 치환 원칙을 위배하는 대요. [이팩티브 자바 Item.10](https://iskull-dev.tistory.com/260) 을 참고해 수정해주세요

2022-10-25 06:33 UTC, skullkim commented on src/test/java/kitchenpos/service/MenuGroupServiceTest.java
> +    @Test
테스트에 @DisplayName()을 이용해 해당 테스트가 어떤 목적을 가지는지를 보다 자세하게 설명하는건 어떤가요🧐?

2022-10-25 06:33 UTC, skullkim commented on src/test/java/kitchenpos/service/MenuServiceTest.java
> +        MenuCreateRequest menuCreateRequest = new MenuCreateRequest(
이렇게 공통적으로 들어가는 인스턴스는 fixture로 빼는게 어떨까요?

2022-10-26 00:51 UTC, bcc0830 commented on src/main/java/kitchenpos/application/OrderService.java
> +        if (CollectionUtils.isEmpty(groupByMenuIds.keySet())) {
Service 관련 로직의 리팩토링은 2단계에서 진행해도 괜찮을까요?

2022-10-26 00:54 UTC, bcc0830 commented on src/main/java/kitchenpos/application/TableGroupService.java
> +        }
수정하였습니다

2022-10-26 02:44 UTC, bcc0830 commented on src/test/java/kitchenpos/service/MenuGroupServiceTest.java
> +    @Test
수정하였습니다

2022-10-26 03:39 UTC, bcc0830 commented on src/main/java/kitchenpos/domain/OrderLineItem.java
> +        if (o == null || getClass() != o.getClass()) return false;
equals와 hashcode 삭제하였습니다

2022-10-26 07:20 UTC, bcc0830 commented on src/test/java/kitchenpos/service/MenuServiceTest.java
> +        MenuCreateRequest menuCreateRequest = new MenuCreateRequest(
중복이긴 하지만, 만약 beforeEach로 빼게 된다면 읽는 입장에서 해당 fixture를 기억하고 있어야 한다는 점때문에 개인적으로는 최대한 fixture를 쓰지 않으려고 하는데 스컬의 생각은 어떠실까요? 추가로 sql로 테스트 격리를 관리하던 것을 가짜 객체로 전부 수정하였습니다

2022-10-27 05:53 UTC, merged