[레거시 코드 리팩터링 - 1단계] 후디(조동현) 미션 제출합니다.
woowacourse/jwp-refactoring pull request #250
Opened 2022-10-24 12:54 UTC by devHudi

안녕하세요, 아리 👋
조금 촉박하게 미션을 진행하느라 테스트 코드가 깔끔하지 않네요 ㅠ-ㅠ 리팩토링 해야겠어요.
아직 도메인 이해도가 많이 낮은 상태에요. 계속 개선하면서 도메인을 파악해보겠습니다!

### 참고

- 테스트 작성의 편의를 위해 도메인 클래스에 생성자를 조금 추가했습니다.
- 요구사항이 business object 에 대한 테스트 코드 작성이었으므로, 일단은 서비스 테스트만 작성했어요.

### 개선 예정

- (테스트 대상 도메인을 제외하고) 어떤 테스트는 DAO를 주입받고, 다른데선 Service를 주입받고있어요. 통일이 필요할 것 같아요.
- DatabaseCleaner 리팩토링이 필요합니다.
- 도메인 이해도가 더 높아지면 테스트 픽스처 생성도 조금 깔끔하게 정리할 필요가 있어보이네요 🤔

2022-10-25 05:36 UTC, ulimy requested changes
안녕하세요 후디! 아리입니다⭐️
빠르게 리뷰요청 주셨는데 리뷰가 늦어서 죄송해요.
미션 기한이 넉넉하지 않은만큼 앞으로는 최대한 빠르게 해볼게요!
코드를 보면서 궁금했던 점 몇가지 적어보았어요. 개인적인 의견도 있으니 후디의 의견을 들려주세요 :)
dao, service 주입 부분도 함께 리팩토링 해주실거라 믿습니다! 
화이팅🙌

2022-10-25 05:36 UTC, ulimy commented on src/test/java/kitchenpos/application/MenuGroupServiceTest.java
> +        void Should_CreateMenuGroup() {
전체적으로 메서드 이름이 대문자로 시작하는데 이유가 있는지 궁금합니다!

2022-10-25 05:36 UTC, ulimy commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +            assertAll(() -> {
개인적인 취향이지만 create 전후에서 가장 크게 달라지는 점은 id가 생성되는 것이라 생각해요. id가 비어있는지 확인하는 테스트코드가 있다면 어떨까요? 이 부분은 매우 개인적이니 반영하지 않으셔도 괜찮습니다!

2022-10-25 05:36 UTC, ulimy commented on src/test/java/kitchenpos/application/ProductServiceTest.java
> +            assertAll(() -> {
assertThat이 하나라면 assertAll은 필요없을 것 같아요!

2022-10-25 05:36 UTC, ulimy commented on src/test/java/kitchenpos/application/MenuGroupServiceTest.java
> +            assertThat(actual).hasSize(3);
개수만을 검증하고있네요! contains나 usingRecursive() 등으로 내부까지 검증하는 것이 아니라 개수만으로 충분하다고 생각하신 이유가 궁금해요! 잘못되었다는 것이 아니라 후디의 생각이 궁금합니다!!

2022-10-25 05:36 UTC, ulimy commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +    private Menu menu;
어떤 필드는 dao를 이용해 DB에 저장된 객체이고, 어떤 필드는 그렇지 않네요. 이 부분을 네이밍에서 구분없이 사용하면 헷갈리지는 않을까요?

2022-10-26 03:40 UTC, devHudi commented on src/test/java/kitchenpos/DatabaseCleaner.java
> +public class DatabaseCleaner {
`truncate.sql` 혹은 DAO를 사용하는 방법 모두 좋은 방법인 것 같아요. 제가 `DatabaseCleaner` 를 직접 구현해서 사용한 이유는 테이블이 생기거나, 제거되어도 코드를 수정하지 않도록 하기 위함이었어요. `truncate.sql` 과 DAO를 사용한 방법은 테이블이 생기거나 제거될때마다 코드를 수정해야 한다는 점이 조금 불편하더라구요.

2022-10-26 16:34 UTC, devHudi commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +        this.menuGroup = menuGroupDao.save(
`this` 가 꼭 필요한 부분이 아니라면 생략했습니다!

2022-10-26 16:35 UTC, devHudi commented on src/test/java/kitchenpos/application/MenuGroupServiceTest.java
> +        void Should_CreateMenuGroup() {
찾아보니 이렇게 테스트 메소드를 작성하는 컨벤션이 있더라구요. 큰 의미는 없습니다.

2022-10-26 16:36 UTC, devHudi commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +            assertAll(() -> {
공감이 가네요! 엔티티 생성 테스트 한정으로 assertion을 추가했습니다!

2022-10-26 16:39 UTC, devHudi commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +    private Menu menu;
저장된 픽스쳐는 `saved`, 저장되지 않은 픽스쳐는 `created` 접두사로 구분하였습니다.

2022-10-26 16:44 UTC, devHudi commented
안녕하세요 아리! 다시 리뷰 요청 드립니다!
테스트코드 개선에 너무 매몰되다 보니 덜 중요한곳에 시간을 조금 쓴 것 같네요 ㅠㅠ
그리고 도메인이 생성되는 과정을 테스트 작성하며 모두 파악하는 일이 쉽지 않네요!...
아직 맘에들지는 않은데 일단 1단계는 이정도로 만족하고 제출합니다!

2022-10-27 01:37 UTC, ulimy approved these changes
안녕하세요 후디! 아리입니다~!
만들었던 생성자를 전부 다 다시 삭제하셨네요 너무 멋져요...!
그럼 1단계는 여기서 마무리 해봅시당~ 2단계에서 만나요!👋

2022-10-27 01:37 UTC, merged