[레거시 코드 리팩터링 - 1단계] 바니(사현빈) 미션 제출합니다.
woowacourse/jwp-refactoring pull request #268
Opened 2022-10-24 13:42 UTC by HyeonbinSa

안녕하세요! 라쿤!!

이번 미션으로 처음 인사드리는거 같네요!!! ㅎㅎ 
우선, 잘 부탁드리며 늦게 리뷰 요청드려서죄송합니다 ㅠㅠ (이번주 테코톡이라 정신이 없었네요;;;)

먼저 Service 테스트 코드 부터 작성해보았스빈다. 아직 부족한게 많은 코드인데 계속해서 추가하고 리팩터링해나가도록 하겠습니다ㅠㅠ 리뷰 잘 부탁드리겠습니다.

남은 미션도 빠이팅!

2022-10-25 05:34 UTC, nbalance97 requested changes
바니 안녕하세요ㅎㅎ 이번 미션 리뷰어 라쿤입니다~🦝

간단한 리뷰 남겨 드렸으니 확인 부탁드려요! 고생 많으셨습니다~

2022-10-25 05:34 UTC, nbalance97 commented on README.md
> +    - [ ] @ExtendWith(MockitoExtension.class) 단위 테스트
요구사항을 꼼꼼하게 잘 작성해 주셨군요! 나머지 부분도 체크해주시면 좋을 것 같아요~!

2022-10-25 05:34 UTC, nbalance97 commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +        menuProduct.setQuantity(10);
Product가 존재하지 않는데 ProductId를 2L로 설정해 주셨네요~

이렇게 작성하신 이유가 따로 있을까요? 기존 데이터는 테스트 용도로 쓰지 말라는 슬랙 공지가 있었어서요~

2022-10-25 05:34 UTC, nbalance97 commented on src/test/java/kitchenpos/application/TableGroupServiceTest.java
> +        orderTable1.setId(10L);
이부분은 ID를 직접 지정해 주신 이유가 있으신가요?

2022-10-25 05:34 UTC, nbalance97 commented on src/test/java/kitchenpos/application/TableGroupServiceTest.java
> +        TableGroup nweTableGroup = tableGroupService.create(tableGroup);
오타가 있군요!

2022-10-25 05:34 UTC, nbalance97 commented on src/test/java/kitchenpos/application/ProductServiceTest.java
> +        assertThat(products.size()).isEqualTo(6);
이부분에 대해선 저도 고민중이긴 한데.. 사전 데이터 때문에 값을 넣지 않았는데도 6개가 있다는 결과가 도출되네요.

조금 더 잘 표현할 수 있는 방법이 없을까요?

2022-10-27 12:49 UTC, HyeonbinSa commented
안녕하세요! 라쿤!! 테코톡 준비랑 같이 하다보니 또 늦어졌네요 ㅠㅠ 

미션을 하면서 처음에 Fake 객체를 만들어서 테스트하고 싶었는데 요구사항에 `@SpringBootTest` or `Mockito`를 사용하라고 해서 사용했다가 강의를 보면서 Fake 객체를 사용하면 좋을 것 같아 다시 수정하느라 시간이 좀 걸렸습니다.
<img width="960" alt="image" src="https://user-images.githubusercontent.com/36189291/198286896-22473fe5-71d3-4bd7-a743-880bb69bb644.png">

새롭게 DAO를 Fake 객체로 만드느라 테스트 코드가 전체적으로 바뀌었습니다....

우선 Fake 객체를 사용하고자 한 이유는 "기존 데이터를 미사용"하고자 Fake 객체를 사용했고 다른 이유는 SpringBootTest를 사용하니 속도가 늦은 것 같아 사용했습니다.
그리고 작성하다보니 느낀 게 처음 리뷰 요청 드렸을 때 도메인에 대한 이해가 부족했던 것 같습니다. 그래서 존재하지 않는 객체에 ID값을 지정했던 방식을 사용한 것 같습니다....

Fixture를 사용하여 수정한다고 했는데 아직은 부족한 것 같아 Fixture를 어떻게 사용하면 효율적일지 라쿤의 의견을 듣고싶습니다 ㅎㅎ 

다시 한번 리뷰 잘 부탁드리겠습니다. 감사합니다!

2022-10-27 16:12 UTC, nbalance97 approved these changes
바니 안녕하세요~ 1단계 미션 고생 많으셨습니다! 

시간 관계상 Approve 하겠습니다! 2단계에서 뵙겠습니다~

2022-10-27 16:12 UTC, nbalance97 commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +    }
SpringBootTest를 사용하지 않음으로써 테스트 속도가 향상되겠네요! 좋습니다~

프로덕션 데이터를 사용하지 않기 위해서라는 이유는 조금 와닿지가 않네요..ㅎㅎ 프로덕션 데이터는 설정을 통해 얼마든지 사용하지 않도록 할 수 있기 때문에요🤔

2022-10-27 16:12 UTC, nbalance97 commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +        OrderTable emptyOrderTable = generateOrderTable(null, 0, false);
비즈니스 규칙 중에 Empty라는 키워드가 있어서 약간의 혼동이 있네요! 바니의 생각은 어떠신가요?

2022-10-27 16:12 UTC, merged