[레거시 코드 리팩터링 - 1단계] 칙촉(안영윤) 미션 제출합니다.
woowacourse/jwp-refactoring pull request #272
Opened 2022-10-24 15:53 UTC by Youngyoon-1

안녕하세요~ 🦆 
리뷰 잘 부탁드립니다!!

2022-10-26 01:22 UTC, jinyoungchoi95 requested changes
안녕하세요 칙촉 :)

꼼꼼한 요구사항, 테스트 모두 확인했습니다 👍 
몇가지 생각하면 좋은 부분 코맨트 남겨두었으니 확인 부탁드려요 😄

2022-10-26 01:22 UTC, jinyoungchoi95 commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +        final MenuGroup menuGroup = menuGroupService.create(메뉴_그룹_생성("테스트-메뉴-그룹"));
제 생각에는 도메인 구조상 `주문테이블`의 `주문`을 진행하기 위해서는 `단체 지정`이 굳이 필요없다고 생각해요. `MenuGroup`을 생성하는건 현재 테스트에서는 필요없어보이는데 어떻게 생각하세요?

2022-10-26 07:47 UTC, Youngyoon-1 commented on src/test/java/kitchenpos/application/MenuGroupServiceTest.java
> +        assertThat(actual.getName()).isEqualTo("테스트-메뉴-그룹");
앗 수정하겠습니다! given은 테스트 하기위한 사전 준비, when은 테스트할 상황, then은 검증과정이라고 생각하고 나누고 있습니다!

2022-10-26 11:35 UTC, Youngyoon-1 commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +        final Product product = productService.create(상품_생성("테스트-상품", BigDecimal.valueOf(99999)));
service 대신 dao 를 사용해서 given을 세팅하도록 했습니다!!

2022-10-26 11:46 UTC, Youngyoon-1 commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +        final MenuGroup menuGroup = menuGroupService.create(메뉴_그룹_생성("테스트-메뉴-그룹"));
Menu 에서 MenuGroupId 를 외래키로 참조하고 있어서 만들어줬습니다!

2022-10-26 11:53 UTC, Youngyoon-1 commented on src/test/java/kitchenpos/application/ProductServiceTest.java
> +        final List<Product> products = productService.list();
제가 {actual, expected} 를 혼용해서 썼는데 통일해서 써보겠습니다!

2022-10-26 12:12 UTC, Youngyoon-1 commented on src/test/java/kitchenpos/application/ServiceTest.java
> +}
넵! 어노테이션 대신 클래스로 만들어서 사용했습니다!! 피드백 감사합니다!!!

2022-10-27 03:11 UTC, jinyoungchoi95 approved these changes
안녕하세요 칙촉 :) 

반영사항 전부 확인했습니당 2단계도 화이팅!

2022-10-27 03:11 UTC, merged