[레거시 코드 리팩터링 - 1단계] 아스피(신동석) 미션 제출합니다.
woowacourse/jwp-refactoring pull request #282
Opened 2022-10-26 05:25 UTC by shindong96

안녕하세요 파랑! 아스핍니다 :)
이번엔 제가 리뷰를 부탁드리게 되었네요!! 잘 부탁드려요ㅎㅎ

이번 미션을 진행하면서 1단계에 어느 정도 범위까지 리팩토링을 해야할까가 가장 고민이였어요ㅜㅜ
그러다가 일단 지금 코드에서 잘 동작하는 테스트 코드까지만 구현하자라는 결론에 닿았습니다.
최대한 서비스 로직도 안건드리고 구현하다보니 테스트를 위한 생성자도 너무 많고 코드가 지저분해졌어요.

Dao에서 사용하는 set도 생성자로 바꿀까 고민하다가 일단 이번 단계에서는 테스트 코드만 작성하였습니다!
피드백 기다리겠습니다!!

2022-10-26 07:47 UTC, summerlunaa requested changes
아스피! PR 제출 한 번 쉽지 않네요ㅋㅋㅋ 왜 이런 에러가 생기는 건지🤔
리뷰가 늦어 죄송합니다. RCA 룰에 맞춰 리뷰 남겼으니 확인부탁드려요ㅎㅎ. 파이팅~~~

```
r: 꼭 반영해 주세요 (Request changes)
c: 웬만하면 반영해 주세요 (Comment)
a: 그냥 사소한 의견입니다 (Approve)
```

2022-10-26 07:47 UTC, summerlunaa commented on README.md
> +    2. 전체 조회
a: 요구사항 정리 good. 근데 어디는 1과 2 사이가 띄워져 있고 어디는 안 띄워져 있네요!

2022-10-26 07:47 UTC, summerlunaa commented on build.gradle
> +sourceCompatibility = '11'
a: 오.. 11로 올리셨군요 ㅎㅎ

2022-10-26 07:47 UTC, summerlunaa commented on src/main/java/kitchenpos/domain/OrderTable.java
> +    }
r: 생성자 오버로딩을 통해 테스트를 간결하게 만들었네요!
하지만 여기서 만든 대부분의 생성자가 테스트 코드에서만 사용되는군요🥲. 테스트에서 특정 생성자를 필요로 할 때마다 비즈니스 코드가 수정되겠네요. 생성자 개수도 계속해서 늘 것 같구요.
도메인에 생성자를 추가하기 보다는 테스트에 createOrderTable 등의 메서드를 만들어 사용하는 건 어떨까요?

2022-10-26 07:47 UTC, summerlunaa commented on src/main/java/kitchenpos/domain/OrderTable.java
> +
r: 개행이 두 줄이네요

2022-10-26 07:47 UTC, summerlunaa commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +    }
a: beforeEach를 통해 기본 데이터를 세팅하셨네요! 저는 개인적으로 beforeEach에는 given절을 넣지 않는 편이에요. 
첫 번째는 아래 모든 메서드가 공통적으로 사용할 데이터만 세팅하기가 어렵다는 점이에요. 사용하다보면 모든 메서드에서 공통적으로 사용하지 않는 데이터도 계속 추가하게 되더라구요.
두 번재는 가독성입니다. beforeEach를 사용해서 given절을 줄일 수는 있지만 데이터 세팅이 어떻게 되었는지 보려면 위로 가서 확인하고 다시 내려와야 하는 번거로움이 있었어요.
아스피 생각은 어떤가요?

2022-10-26 07:47 UTC, summerlunaa commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +        );
```suggestion
        assertAll(() -> {
                assertThat(savedMenu).usingRecursiveComparison()
                        .ignoringFields("id", "price", "menuProducts")
                        .isEqualTo(menu);
                assertThat(savedMenu.getMenuProducts()).hasSize(1);
        });
```
a: 이런식으로도 할 수 있겠네요 ㅎㅎ

2022-10-26 07:47 UTC, summerlunaa commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +    @DisplayName("구성 상품이 존재하지 않을 경우 예외를 반환한다.")
r: 용어 사전에 따르면 menu product는 메뉴 상품이라 부릅니다😎

2022-10-26 07:47 UTC, summerlunaa commented on src/test/java/kitchenpos/application/TableGroupServiceTest.java
> +    @DisplayName("테이블 그룸화를 진행한다.")
r: 용어 사전에 따르면 table group은 단체 지정이라 부릅니다😎

2022-10-26 07:47 UTC, summerlunaa commented on src/test/java/kitchenpos/application/TableGroupServiceTest.java
> +                .willReturn(true);
a: 여기서만 mocking을 사용한 이유가 있나요?

2022-10-26 07:47 UTC, summerlunaa commented on src/test/java/kitchenpos/application/TableServiceTest.java
> +    @DisplayName("테이블이 존재하지 않으면 사용 여부를 변경할 시 예외를 반환한다.")
c: 예외를 반환한다 VS 변경할 수 없다 
하나로 통일하는 건 어떨까요?

2022-10-26 07:47 UTC, summerlunaa commented on src/test/resources/schema.sql
> +CREATE TABLE orders
a: 테스트용 schema.sql을 만드셨네요! DirtiesContext, `@Sql`, DatabaseCleaner를 만들어 사용하는 등 테스트를 격리할 수 있는 여러 가지 방법이 있는데 트랜잭션 어노테이션과 sql 파일을 사용한 특별한 이유가 있을까요?

2022-10-26 11:24 UTC, shindong96 commented on README.md
> +    2. 전체 조회
매의 눈...!

2022-10-26 11:27 UTC, shindong96 commented on src/main/java/kitchenpos/domain/OrderTable.java
> +    }
애자일하게 생각하면 픽스처를 분리하는게 맞지만 최종적으로 set을 사용하지 않는 코드를 짜는게 목적이라...고민이 되네요ㅜㅜ
더불어 Request DTO가 생기면 도메인 생성자도 줄 거 같은 생각이 드는데 파랑은 어떻게 결론지으셨나요ㅜㅜ

지금은 단계에 맞게 하는게 맞는 거 같아서 수정하겠습니다!

2022-10-26 11:32 UTC, shindong96 commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +        );
혹시 이렇게 하는 것의 장점이 있을까요?? 기존의 방식을 이용하면 두 개의 케이스가 다 돌아가고 파랑의 제안대로하면 순차적으로 진행하다가 기대값이 아니면 멈춘다는 점이 장점일까요? 궁금해요!

2022-10-26 11:34 UTC, shindong96 commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +    @DisplayName("구성 상품이 존재하지 않을 경우 예외를 반환한다.")
반영하겠습니다! 용어 사전도 중요한 컨벤션이네요!

2022-10-26 12:08 UTC, shindong96 commented on src/test/resources/schema.sql
> +CREATE TABLE orders
테스트에서는 Flyway를 사용하지 않게 하고 싶었어요! 그러다보니 test용 yml에 flyway를 끄게 되었고 schema를 생성해줄 sql파일이 필요했습니다!
DatabaseCleanUp의 경우에는 `@Transactional`을 안쓰게 되는 점이 더 알맞는 거 같아요! 반영하겠습니다.

2022-10-26 12:38 UTC, shindong96 commented on src/test/java/kitchenpos/application/TableServiceTest.java
> +    @DisplayName("테이블이 존재하지 않으면 사용 여부를 변경할 시 예외를 반환한다.")
예외를 반환한다로 통일했습니다!!

2022-10-26 12:39 UTC, shindong96 commented on src/test/java/kitchenpos/application/TableServiceTest.java
> +
아차차...

2022-10-26 12:43 UTC, shindong96 commented on src/test/java/kitchenpos/application/TableGroupServiceTest.java
> +                .willReturn(true);
개인적으로 외래키 이슈가 없는 데이터를 굳이 해당 테스트에서 저장하고 싶지 않았어요. 그래서 mocking으로 해결을 하고 싶었습니다!
그런데 지금 MockBean때문에 테스트 환경이 달라져서 ServiceTest 클래스를 빼기가 쉽지 않네요...파랑은 어떻게 생각하시나요?

2022-10-26 12:45 UTC, shindong96 commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +    }
저도 동의합니다!
그런데 지금의 경우 테스트 메서드 내에서 필요한 도메인에 관한 정보가 아니라 외래키 이슈로 인한 것만 세팅해주게 하고 있어요!
외래키를 위해 만드는 로직정도는 BeforeEach로 빼도 되지 않을까라는 생각을 했는데 파랑 생각은 어떠신가요?

2022-10-27 06:57 UTC, summerlunaa approved these changes
아스피~ 수정사항 반영된 거 확인했습니다ㅎㅎㅎ
추가적인 코멘트도 남겼으니 잊지 말고 확인해주세요!! 1단계는 여기서 머지하겠습니다.
2단계도 파이팅💙

2022-10-27 06:57 UTC, summerlunaa commented on src/main/java/kitchenpos/domain/OrderTable.java
> -    }
a: 다시 삭제되었네요! good.

2022-10-27 06:57 UTC, summerlunaa commented on src/main/java/kitchenpos/domain/OrderTable.java
> +    }
확인했습니다 ㅎㅎㅎ 👍

2022-10-27 06:57 UTC, summerlunaa commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +    }
아스피가 본인만의 기준을 가지고 하는 거라면 괜찮다고 봅니다! 결국은 개인 취향 차이니까요 :)

2022-10-27 06:57 UTC, summerlunaa commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +        );
앗 저는 단순히 스타일 차이를 얘기했었는데 아스피덕에 반대로 차이점을 배워가네요 ㅎㅎㅎ 
그냥 이런 방법도 있다~ 정도로만 생각해주시면 될 것 같아요!

2022-10-27 06:57 UTC, summerlunaa commented on src/test/java/kitchenpos/application/TableGroupServiceTest.java
> +                .willReturn(true);
그럼 어떤 기준으로 mocking을 사용하는 건가요? 
추후에 테스트 코드가 더 많아진다면 명확한 기준 없이 mocking이 사용될까 우려되네요🤔

2022-10-27 06:57 UTC, summerlunaa commented on src/test/java/kitchenpos/application/ServiceTest.java
> +    protected DatabaseCleanUp databaseCleanUp;
a: Dao를 모든 서비스 테스트에서 쓰지는 않을텐데 부모 클래스에 선언한 이유가 있을까요?

2022-10-27 06:57 UTC, summerlunaa commented on src/test/java/kitchenpos/application/ServiceTest.java
> +
r: 개행 있네요 ㅎㅎ

2022-10-27 06:57 UTC, summerlunaa commented on src/test/java/kitchenpos/application/ServiceTest.java
> +    }
a: 나중에 repository test나 domain test가 추가되면 다른 곳에서도 이 픽스처를 사용할 수도 있을 것 같아요ㅎㅎ

2022-10-27 06:57 UTC, summerlunaa commented on src/test/java/kitchenpos/application/MenuGroupServiceTest.java
> +    }
r: 부모 클래스로 올리면 중복을 줄일 수 있지 않을까요?

2022-10-27 06:58 UTC, merged