[레거시 코드 리팩터링 - 2단계] 소주캉(강승주) 미션 제출합니다.
woowacourse/jwp-refactoring pull request #289
Opened 2022-10-28 04:33 UTC by sojukang

안녕하세요 써머👋 레거시 코드 리팩터링 미션 다시 리뷰드리는 소주캉입니다. 
1단계에 남겨주신 피드백과 요구사항을 바탕으로 리팩토링 진행하였습니다. 고려한 사항은 다음과 같습니다. 

### JPA Migration
JdbcTemplate을 사용했던 이전 Dao를 Spring Data Jpa를 사용하도록 Migration 했습니다. 과정에서 Domain Entity가 Data Jpa 관련 어노테이션이 붙는 수정이 있었습니다. 두 방식 모두를 동시에 지원하기 위해 Dao Interface를 기반으로 구현하여 남겨두고 JpaDao를 Primary로 등록하여 일부 엔티티만 수정 과정에서도 두 기술을 동시에 적용할 수 있도록 하였습니다. 

### Domain으로 로직 이동
생성, 로직 처리를 Service 계층에서 최대한 Domain Entity 내부로 이동했습니다. 다만 엔티티 설계상 Dao가 필요한 경우 아직 Service에서 처리하는 로직이 남아있습니다. 

### Request 객체 도입, 재사용
Http 요청을 받는 객체를 Domain 별 Request를 하나만 두어 사용하였습니다. API나 Method 방식바다 다른 Request를 사용할 수도 있었으나(프로젝트에서는 그렇게 사용) 늘어나는 Dto로 인한 복잡도와 관리 포인트 증가로 단점이 더 많았다고 생각하여 요청에 없는 값을 Null로 두는 Domain별 단일 Request를 사용하였습니다. 결과적으로 UI 계층에서 `@Valid` 등의 검증은 하지 못하게 되었는데, 이 부분도 이전 프로젝트에서 도메인에서의 검증과 Request에서의 검증이 둘로 나뉘어 관리 포인트가 증가한다는 단점을 느껴서 이번 미션에서는 Domain으로 일원화하였습니다. 

### 테스트에서만 쓰이는 생성자 제거
테스트에서만 쓰이는 생성자를 제거하려다보니 Id에 Null을 외부에서 넣어주는 생성자를 쓰게 되었습니다. 이를 감추는 생성자를 추가할 수도 있지만 프로덕션에서 사용하지는 않는 상황이라 불편함을 조금 감수하고 최대한 테스트만을 위한 코드를 추가하지는 않으려 했습니다. 

이번 리뷰도 잘 부탁드립니다🙇‍♀️

2022-10-29 12:12 UTC, hyewoncc requested changes
안녕하세요 소주캉~🍶
점진적인 JPA 교체를 위해 상속을 사용하신 점이 인상깊었어요!
그리고 2단계 요구사항인 서비스 레이어 리팩터링이 충분히 이뤄졌네요 
검증 로직도 도메인 로직 안으로 정상적으로 옮겨졌고요 
꼼꼼한 테스트 추가까지 👍 고생하셨습니다  

코멘트는 자잘한 것 위주로 남긴 것 같아요
첫번째 리뷰라서 `RC`로 남기도록 할게요!

2022-10-29 12:12 UTC, hyewoncc commented on src/main/java/kitchenpos/domain/TableGroup.java
> +                throw new IllegalArgumentException();
이 로직도 `OrderTable`안으로 넣어서 객체에게 `orderTable.canBeGrouped` 이렇게 물어보는 식으로 할 수 있을 것 같네요!

2022-10-30 08:41 UTC, sojukang commented on src/main/java/kitchenpos/application/MenuService.java
> +        Menu menu = menuDao.save(request.toEntity());
MenuProduct의 MenuId가 Not null이라 Menu가 먼저 있어야 해서 먼저 영속화를 해주었습니다. 그런데 써머가 남겨주신 피드백을 보고 생각해보니 검증을 먼저 하고 영속화를 해도 되겠네요! 수정해보았습니다. 🙇‍♀️

2022-10-30 08:44 UTC, sojukang commented on src/main/java/kitchenpos/application/OrderService.java
> +    }
이미 레거시가 존재하는 Interface를 고치거나 DB Schema를 고치지 않고서 리팩터링을 진행하고 싶었습니다. Dao에 메서드를 추가하면 이전 JdbcTemplateDao도 수정해야 하기 떄문에 Service 계층에서 수행하였는데, 이제 Migration이 끝난 만큼 JdbcTemplate 전부 날리고 Interface를 수정할 시기가 왔다고 판단하여 추가해보겠습니다🌟

2022-10-30 09:25 UTC, sojukang commented on src/main/java/kitchenpos/application/request/OrderLineItemRequest.java
> +public class OrderLineItemRequest implements Serializable {
앗...! 굳이 할 필요 없는 구현인데 넣었네요. Jpa Buddy 측에서 만들어주는 Dto를 사용하다가 들어갔습니다.

2022-10-30 09:27 UTC, sojukang commented on src/main/java/kitchenpos/domain/Order.java
> +        }
물론 현재는 field에서 new ArrayList()로 명시적으로 초기화해주고 있기는 하지만 OrderLineItems가 Null일 가능성까지 최대한 방어적으로 검증하는 것이 좋다고 생각하여 CollectionUtils를 사용했습니다.

2022-10-30 09:29 UTC, sojukang commented on src/main/java/kitchenpos/domain/Order.java
> +        }
이 메서드도 위의  Collecitons.isEmpty와 같은 이유로 사용하였는데, 이 로직에서 OrderStatus.COMPLETION은 절대 Null이 될 수 없으므로 .equals를 사용해도 좋겠군요!

2022-10-30 09:31 UTC, sojukang commented on src/main/java/kitchenpos/domain/OrderTable.java
> +        if (Objects.nonNull(tableGroupId)) {
이건 기존 레거시 검증 코드인 것 같네요! 저도 != null 이 더 좋다고 생각해서 수정하였습니다👍

2022-10-30 10:50 UTC, sojukang commented on src/main/java/kitchenpos/domain/TableGroup.java
> +                throw new IllegalArgumentException();
역시 👍👍 확실히 OrderTable 내부로 옮길 수 있는 검증 로직이었네요!!! 수정해보았습니다🌟

2022-10-30 11:03 UTC, sojukang commented on src/main/java/kitchenpos/application/request/OrderTableCreateRequest.java
> +    }
앗.. 체크하지 못했네요😱 전반적으로 Production을 위해 존재하는 생성자를 사용하도록 변경하였습니다.

2022-10-30 11:04 UTC, sojukang commented on src/main/java/kitchenpos/application/request/OrderRequest.java
> +    }
전반적으로 Production을 위해 존재하는 생성자를 사용하도록 변경하였습니다.

2022-10-30 11:34 UTC, sojukang commented on src/main/java/kitchenpos/application/TableService.java
>          }
OrderTable에 Order에 관한 객체 참조를 추가하고 검증 로직을 옮겨보았습니다!

2022-10-30 11:37 UTC, sojukang commented on src/main/java/kitchenpos/domain/OrderTable.java
>      }
꼼꼼하게 봐주셔서 감사합니다🙇‍♀️ 생성할 때 사용했던 검증을 여기서도 적용해보았습니다.

2022-10-30 13:09 UTC, sojukang commented on src/main/java/kitchenpos/domain/MenuProduct.java
>      private Long menuId;
Jpa를 사용해도 객체를 참조하게 될 경우 상승하는 객체 간 결합도와 기존 코드의 대폭 수정 등을 고려하여 Id를 가지고 있도록 의도하였습니다. 향후 의존성 분리에도 Id를 가지고 있는 편이 유리하더라구요. Cascading을 사용하지 않은 이유는 연관 관계가 복잡해질 경우 명확한 동작을 한눈에 파악하기 어렵고 불필요한 쿼리가 나갈 수 있기 때문에 각 연관객체를 명시적으로 영속화 해주는 방식을 선택해보았습니다

2022-10-30 13:42 UTC, sojukang commented
안녕하세요 써머🌟 레거시 코드 리팩터링 2단계 리뷰 요청드리는 소주캉입니다.
저도 미처 확인 못한 부분 무척 꼼꼼하게 봐주셨더라구요😲 감사드립니다🙇‍♀️
남겨주신 피드백 바탕으로 리팩터링 진행하였습니다. 
최대한 기존  DB 스키마나 Entity를 수정하지 않으려 노력하면서 리팩토링 해보았습니다. 
건드려야 깔끔해질 순간이 다가오네요... 
이번에도 잘 부탁드립니다🙇‍♀️

2022-10-31 02:18 UTC, hyewoncc commented on src/main/java/kitchenpos/application/OrderService.java
> +    }
그런 이유가 있으셨군요, 아주 좋아요!! 👍

2022-10-31 02:20 UTC, hyewoncc commented on src/main/java/kitchenpos/domain/MenuProduct.java
>      private Long menuId;
안그래도 다른 크루들 얘기를 슬적슬쩍 들어보니 `Menu`를 직접 참조한 경우에 이슈가 좀 있나보더라고요 👍 아주 좋습니다

2022-10-31 02:21 UTC, hyewoncc commented on src/main/java/kitchenpos/domain/Order.java
> +        }
아하 `CollectionUtils`를 사용하지 않아서 몰랐는데 방금 확인해보니 `null` 체크도 같이 해주는군요!
덕분에 배워갑니다

2022-10-31 02:41 UTC, hyewoncc approved these changes
안녕하세요, 소주캉~ 
코멘트로 남겨주신 의견 재밌게 읽었습니다 
특히 기존 코드 변경을 최소화하려 했다는 점이 인상깊었어요 👍 
다음 단계도 화이팅입닏다!!!

2022-10-31 02:41 UTC, hyewoncc commented on src/main/java/kitchenpos/application/request/MenuRequest.java
> +            .collect(Collectors.toUnmodifiableList());
저번에도 느꼈지만 컬렉션을 넘겨줄 때 불변으로 만들어 주시는 꼼꼼함 너무 좋네요 👍

2022-10-31 02:41 UTC, hyewoncc commented on src/main/java/kitchenpos/dao/jpa/JpaMenuDao.java
> +@Primary
이제 `@Primary`를 제거해도 될 것 같네요 😁

2022-10-31 02:41 UTC, hyewoncc commented on src/main/java/kitchenpos/dao/jpa/JpaOrderDao.java
> +        return orderRepository.existsByOrderTableIdInAndOrderStatusIn(orderTableIds, orderStatuses);
저는 해당 메서드들이 비즈니스 로직 안으로 이동할 수 있다고 생각하는데 소주캉의 의견이 궁금합니다! 
둘 다 그룹으로 만들려는 테이블들의 상태가 `COMPLETION`이 아닌가? 를 검증하는데 쓰이는데요, 
일단 `OrderTable`을 모두 불러 온 다음에 도메인에서 검증할 수도 있다고 생각해서요

2022-10-31 02:42 UTC, merged