[레거시 코드 리팩터링 - 2단계] 에덴(김성산) 미션 제출합니다.
woowacourse/jwp-refactoring pull request #302
Opened 2022-10-28 11:26 UTC by leo0842

안녕하세요 정! 에덴입니다 😄 

2단계 서비스 및 도메인을 리팩토링하여 코드 리뷰 요청 드립니다!

지난번 남겨주셨던 피드백에 대한 답변과 이번 미션 진행의 특이 사항은 아래에 남겨놓겠습니다.

마지막 레벨 5도 화이팅하시구, 따끔한 리뷰 부탁드리겠습니다 🙇 

---

1. service test 구조의 변화

[given/when/then 에 대한 피드백](https://github.com/woowacourse/jwp-refactoring/pull/208#discussion_r1003138129) 을 보면서 정말 강박처럼 느껴지긴 하더라구요 ㅎㅎㅎ;;

모든 테스트 메서드에 given, when, then 이 주석처리 되어있는 이유는, 프로젝트를 시작하면서 익숙하지 않던 given, when, then 구조를 손에 익히기 위해 live template 으로 등록하여 사용하면서 약 5개월을 이렇게 사용하다보니 주석 괴물이 되어버렸네요 😢 

그래서 정의 피드백을 따라 로직이 많은 service test 부분에 nested 를 적용하고 given, when 을 클래스 단위로 분리해보았습니다. 

처음에는 DCI 를 시도해보았는데, 현재 service test 는 모킹 테스트이기때문에 적용해보니까 더 구조가 이상해지더라구요.
따라서 DCI 보다 한단계 뎁스가 덜한 `@Nested` 하나만 만들어 service test 의 구조를 변경하였습니다.

이와 함께 [테스트 메서드 길이 피드백](https://github.com/woowacourse/jwp-refactoring/pull/208#discussion_r1003154140) 에 대해서도 정의 피드백을 반영하여 공통된 로직들을 private 메서드와 인스턴스 변수로 놓아 메서드 길이도 줄였습니다.

2. JPA 적용

JPA 를 도입하면 대규모 변경이 불가피하단 것을 알고 있었지만, JPA 를 적용해보았습니다. 적용한 이유는 다음 2가지입니다.

- 기존 dao 로 오브젝트를 매핑하던  구조는 도메인의 멤버변수 일부가 변경되면 수정에 용이하지 않기때문에 이에 대한 라이브러리의 도움을 받고자 하였습니다.
- 연관관계가 다소 복잡하게 얽혀 있어 하나의 dao 에서 여러 테이블을 호출하여 join 하는 부분이 결합도가 다소 강하다고 느꼈습니다.

위와 같은 이유로 Spring data JPA 를 적용하였고 file change가 조금 많아졌습니다 😅

2022-10-28 13:11 UTC, bugoverdose requested changes
OOP라는 맥락에서의 개선 사항들 위주로 커멘트 남겼습니다. 
확인하시고 다시 리뷰 요청 주시기 바랍니다.

2022-10-28 13:11 UTC, bugoverdose commented on src/main/java/kitchenpos/domain/Order.java
>      }
새롭게 저장되는 주문 객체를 생성하기 위한 생성자를 만들 경우, 무조건 할당되어야 하는 필드 값들을 생성자 내부에서 지정해주는게 좋지 않나 싶어요.

```suggestion
    public Order(final long orderTableId, final List<OrderLineItem> orderLineItems) {
        this(null, orderTableId, OrderStatus.COOKING, LocalDateTime.now(), orderLineItems);
    }
```

2022-10-28 16:41 UTC, leo0842 commented on src/main/java/kitchenpos/application/TableService.java
> +        orderTable.changeEmpty(request.isEmpty());
저도 `db 에 read 접근 로직 한번 하는 것이 방어 로직을 서비스에서 드러내는 것보다 좋다` 라는 구조에 대해 동의합니다!
따라서 정의 피드백대로 `changeEmpty` 내부에 해당 방어 로직을 숨기는 방식으로 수정하였습니다.

다만 `changeEmpty` 라는 메서드인데, empty 를 change 하기 전에 `tableGroupId` 가 존재하는지 판단하고 예외를 던지는 로직이 두 가지 행동이 담겨있는 느낌이 조금 걸리네요 😢 

이러한 문맥 상의 불일치를 감수해야 하는 것인지, 아니면 조금 더 추상화의 개념을 넓혀서 `table group id 가 존재하지 않는지 판단하는 로직` 은 empty 를 change 하기 전 `orderTable` 도메인의 기본 규칙으로 바라 볼 수 있는 것인지 정의 의견을 여쭙고 싶습니다!

2022-10-28 16:45 UTC, leo0842 commented on src/main/java/kitchenpos/application/TableService.java
> +        orderTable.changeNumberOfGuests(numberOfGuests);
위와 같은 맥락으로, 정의 피드백을 반영하여 해당 방어 로직을 `changeNumberOfGuests` 메서드 내부로 옮겼습니다! 좋은 피드백 감사드립니다 🙇

2022-10-29 02:43 UTC, bugoverdose commented on src/main/java/kitchenpos/application/TableService.java
> +        orderTable.changeEmpty(request.isEmpty());
1. 우선 `changeEmpty`라는 메서드가 empty 필드 수정 로직과 tableGroupId 관련 로직을 모두 지니고 있는게 불편하다면 두 로직을 명시적으로 포함해도 이상하지 않도록 메서드명을 수정하는건 어떠할까 싶어요.

```java
    public void changeEmptyIfNonGrouped(final boolean empty) {
        if (Objects.nonNull(this.tableGroupId)) {
            throw new IllegalArgumentException();
        }
        this.empty = empty;
    }
```

2. `tableGroupId가 null이어야만 empty 필드를 수정할 수 있다`라는 비즈니스 요구사항은 (1) 해당 서비스 메서드에 한정된 규칙으로 볼 수도, 아니면 (2) 주문 테이블이라는 도메인에서 지켜져야 하는 규칙으로 볼 수도 있을 것 같아요.

프로덕션 코드에서 `changeEmpty` 메서드가 한 곳에서밖에 사용되지 않았기 때문에 전자와 후자 중 무엇이 맞는지는 **아직 분명하게 판단할 수 없는 문제라고 생각해요**.

다만, 만약 도메인의 규칙이 맞음에도 불구하고 전자를 기준으로 코드를 작성해놓았다면 향후 다른 곳에서 `changeEmpty` 메서드를 호출할 때 tableGroupId에 대한 방어로직을 누락하는 등의 실수를 일으킬 수 있다고 생각해요. 그래서 일단은 `changeEmpty` 내부에 방어로직을 포함시켜놓고 개발하는게 더 적절하지 않나 싶어요.

2022-10-29 02:46 UTC, bugoverdose commented on src/main/java/kitchenpos/application/TableService.java
> +        orderTable.changeEmpty(request.isEmpty());
반대로 만약 tableGroupId 관련 방어로직이 도메인의 규칙이 아니라, 특정 서비스 메서드에 한정된 로직이더라도 아래와 같이 필요에 따라 메서드들을 다양하게 구현하는게 적절하지 않나 싶어요. 인프라에 종속되지 않는 비즈니스 로직은 전부 도메인 내부로 옮기는게 이상적이라고 생각합니다.

```java
    public void changeEmpty(final boolean empty) {
        this.empty = empty;
    }

    public void changeEmptyIfNonGrouped(final boolean empty) {
        if (Objects.nonNull(this.tableGroupId)) {
            throw new IllegalArgumentException();
        }
        changeEmpty(empty);
    }
```

2022-10-29 08:54 UTC, leo0842 commented on src/main/java/kitchenpos/repository/OrderLineItemRepository.java
> +}
에구,, 이러저리 썼다 지웠다 하다가 이렇게 됐네요 😢 불필요한 주석 모두 제거하였습니다!

2022-10-29 08:56 UTC, leo0842 commented on src/main/java/kitchenpos/application/TableGroupService.java
> +        fillOrderTableGroup(orderTables, savedTableGroup);
해당 방어 로직들을 order tale 에서도, table group 에서도 하기가 힘들어 그대로 서비스에 놔뒀는데 새로 만들면 되는 거였군요 😄 

정의 피드백대로 `orderTables` 객체를 만들고, db 관련 로직을 제외한 모든 메서드들을 `orderTables` 에서 수행할 수 있도록 수정하였습니다 🙇

2022-10-29 08:58 UTC, leo0842 commented on src/main/java/kitchenpos/application/OrderService.java
> +                LocalDateTime.now()));
아래 피드백대로 생성시의 default 같은 느낌의 값들은 해당 엔터티 생성자 내부에서 넣어주는 게 맞는 것 같습니다! 

이에 따라 request에서 엔터티로 바꾸는 메서드에서는 해당 request 에 들어있는 값으로만 만들고 이외의 기본 값들은 생성자에서 만들도록 수정하였습니다!

2022-10-29 09:00 UTC, leo0842 commented on src/main/java/kitchenpos/application/MenuService.java
> +    }
이 부분도 sum 이 product 엔터티를 사용해야하기때문에 어찌할 바를 몰라 service 에 뒀는데, 위의 ordertables 를 생성하는 것처럼 ProductQuantity 라는 새로운 객체를 생성하고 해당 객체 내부로 로직을 넘겼습니다!

2022-10-29 10:02 UTC, bugoverdose requested changes
피드백을 전반적으로 잘 적용해주신 것 같아요. 동어반복이라 생략한 부분들도 알아서 잘 고쳐주셨네요.
커밋도 잘 구분해주셔서 빨리 리뷰할 수 있었네요.

어프루브해도 될 것 같기는 한데, 몇 가지 간단한 커멘트만 남겼습니다.
참고해주시고 다시 리뷰요청 주시기 바랍니다.

2022-10-29 16:59 UTC, leo0842 commented on src/main/java/kitchenpos/domain/Menu.java
>      private List<MenuProduct> menuProducts;
해당 컨퍼런스에서 조영호님이 컬렉션을 변수로 가지는 상황에 대한 이슈에 대한 이유로 두 가지를 언급하고 있습니다.

1. 성능 상의 이슈
2. 객체들의 관계를 관리하기 위한 많은 노력

1번은 RDBMS 와의 관계에서 발생하는 이슈이고, 패러다임이 다르기때문에 RDBMS의 구조와 닮은 ManyToOne 가 직관적임으로 성능상 이점을 가질 수 있다는 점에 동의합니다. 하지만 이번 미션에서는 OOP 의 관점에서 리팩토링을 진행하고자 하기때문에, 성능상의 퍼포먼스를 일단은 배제하려고 합니다.

2번은 다소 조영호님이 본인의 경험을 기반하여 다소 추상적으로 언급하신 것 같습니다. 추측으로는 생성, 수정, 삭제 등의 유지 및 관리에서 B class 에서 A를 의존하는 것이 A 에서 B 클래스를 추가, 수정, 제거 하는 것보다 리소스 소모가 덜 하다라는 뜻으로 생각하고 제 의견을 말씀드리겠습니다.

1. 구조적인 관점
구조적으로 A가 B 를 컬렉션으로 가지는 것이 낫다고 봅니다. A를 `Menu`, B를 `MenuProduct` 로 봤을 때, `MenuProduct` 는 `Menu` 가 생겨야만 생성될 수 있는 객체입니다. 계층적으로 보았을 때 A 의 라이프 사이클이 B 의 라이프 사이클을 포함한다고 볼 수 있고, 이러한 관점에서 유지 및 관리를 고려할 때 A가 B를 관리하는 것이 더 적절하다고 봅니다. 
예를 들어 A를 삭제한다고 했을 때 B가 함께 삭제되는 것은 자연스러운 구조입니다. 이 때 A가 B를 collection 으로 들고 있으면 라이프 사이클을 함께 할 수 있는 반면 B 가 A 를 들고 있으면 A가 삭제되었을 때 B도 삭제하는 로직이 추가되어야 합니다.

2. 비즈니스 관점
`Menu` 와 `MenuProduct` 의 관계도 그렇고 보통의 요구사항에서 1 에 해당하는 객체에서 N을 호출하는 상황이 N 에서 1 을 호출하는 상황보다 빈도가 높습니다. 얼마전 DDD 수업 때 제이슨이 잠깐 언급했던 애그리거트를 대입해볼 때 root entity 가 하위의 entity 를 호출하는 로직은 많지만, 하위 entity 가 root entity 를 호출하는 빈도는 높지 않습니다.
1:N 를 예시로 들 때 가장 만만한 team, member 의 예시를 들어보자면, team 에서 member 를 관리하는 요구사항은 빈번하지만, member 가 team 의 이름을 바꾼다거나 하는 요구사항은 적습니다.

위의 두 가지 이유에서 저는 `OneToMany` 를 선호하는 편입니다!

2022-10-29 17:02 UTC, leo0842 commented on src/main/java/kitchenpos/domain/ProductQuantity.java
> +    private final Map<Product, Quantity> values;
앗 이런 세세한 부분까지 꼼꼼하게 봐주셔서 정말 감사드립니다!! 🙇 바로 반영하였습니다!

2022-10-29 17:05 UTC, leo0842 commented on src/main/java/kitchenpos/application/dto/request/MenuCreateRequest.java
>                  toMenuProducts());
`Price` 객체는 생성되기에 매우 예민한 객체라서 생성 시 외부의 값까지 참조해야 하는 구조를 지니고 있습니다(ProductQuantities). 
`request 에서 price 를 뺀 뒤 다시 request 에 요청하는 방식` 이 저도 되게 어색하다고 느껴져서 아예 service layer 에서 menu/product 객체를 생성하는 로직으로 변경하였습니다1

2022-10-29 17:07 UTC, leo0842 commented on src/test/java/kitchenpos/repository/JdbcTemplateMenuRepositoryTest.java
> +                                                new ArrayList<>()),
앗 침착맨식 코딩을 해버렸네요 😢 불필요한 indent 와 inline 을 줄이기 위해 Fixture 도 생각해 보았지만, 같은 값을 가진 변수를 활용하는 부분이 적어서 따로 Fixture 로 빼지는 않고 메서드로 분리하였습니다!

2022-10-30 07:07 UTC, bugoverdose commented on src/main/java/kitchenpos/domain/ProductQuantity.java
> +    private final Map<Product, Quantity> values;
로컬의 커밋 내역을 푸쉬하지 않으신건가 싶기는 한데, 리뷰할게 더 없는 것 같아서 일단 어프루브할께요.

2022-10-30 07:10 UTC, bugoverdose approved these changes
리뷰하고 싶은 내용은 전부 드려서, 다음 단계 진행하시면 좋을 것 같아요. 수고하셨습니다.

2022-10-30 07:10 UTC, merged

2022-10-30 09:02 UTC, bugoverdose commented on src/main/java/kitchenpos/domain/ProductQuantity.java
> +    private final Map<Product, Quantity> values;
누락된 커밋은 다음 브랜치에 cherry-pick으로 반영해주시면 될 것 같습니다. :)

2022-10-30 09:26 UTC, bugoverdose commented on src/main/java/kitchenpos/domain/Menu.java
>      private List<MenuProduct> menuProducts;
주어진 비즈니스 요구사항에 따라 올바른 구조는 매번 달라진다고 생각해요. 동일한 프로젝트에서도 예전까지는 좋던 구조가 나중에는 좋지 않은 구조가 될 수도 있고요. 주어진 상황에서 본인만의 이유를 지니고 잘 설명할 수만 있으면 충분히 괜찮은 것 같아요.

개인적으로 JPA에서 OneToMany 관계는 성능만이 아니라 다른 연관관계들에 비해 고려해야 하는 JPA 세부 설정이 많아서 다소 인프라에 의존적인 코드가 아닌가?라는 생각도 해볼 수 있을 것 같아요. 

또한 OneToMany만이 아니라 객체 간의 결합도라는 맥락에서 `Menu`와 `MenuProduct` 사이에 연관관계를 아예 설정하지 않고, 서비스에서 명시적으로 menuRepository와 menuProductRepository를 호출하는게 상황에 따라 더 이상적일 수도 있을 것 같아요. 
 
또한 비즈니스 요구사항이 굉장히 다양하다면 `menuProducts` 필드와 같은 연관관계들을 복잡하게 지니고 있는 `FullMenu` 엔티티와 연관관계가 전혀 없는 `Menu` 엔티티를 구현하고, 둘 다 동일한 `menu` 테이블에 대해 맵핑시켜 사용하는 것도 하나의 방법이라고 생각해요. (`FullMenu`라는 엔티티명은 대충 지었습니다)