[레거시 코드 리팩터링 - 2단계] 그린론(유재서) 미션 제출합니다.
woowacourse/jwp-refactoring pull request #312
Opened 2022-10-28 12:37 UTC by jaejae-yoo

범고래 안녕하세요 ~ 
2단계에서는 서비스에 있는 도메인 로직을 최대한 옮기려고 노력했고, jdbcTemplate를 제거하고 JPA로 변환했습니다 ~ 
아직 부족한 부분이 많은 것 같아요.. 계속 리팩터링하겠습니다 ! 
이번 미션도 잘 부탁드려요 ~ 🐳

2022-10-30 11:19 UTC, cndqjacndqja requested changes
안녕하세요 그린론~!
많이 바쁘셨을텐데, 수고하셨습니다 :)
간단한 코멘트 몇 개 남겼습니다!

2022-10-30 11:19 UTC, cndqjacndqja commented on src/main/java/kitchenpos/application/TableGroupService.java
>              }
요 부분은 로직 수정해 볼 수 있을 것 같아요!

2022-10-30 11:19 UTC, cndqjacndqja commented on src/main/java/kitchenpos/application/TableGroupService.java
>              throw new IllegalArgumentException();
위 코멘트와 마찬가지로 메서드 분리나 도메인으로 로직을 옮겨봐도 좋을 것 같아요 :)

2022-10-30 11:19 UTC, cndqjacndqja commented on src/main/java/kitchenpos/domain/OrderTable.java
> +        }
요 부분도 테스트 해볼 수 있을 것 같아요! :)

2022-11-01 03:28 UTC, jaejae-yoo commented on src/main/java/kitchenpos/application/MenuService.java
> +                .map(mp -> productRepository.findById(mp.getProductId()).orElseThrow(IllegalArgumentException::new))
해당 방식이 가독성이 더 좋을 것 같네요! 분리했습니다~

2022-11-01 03:28 UTC, jaejae-yoo commented on src/main/java/kitchenpos/application/OrderService.java
>      public List<Order> list() {
앗 누락된 다른 조회 메서드에도 모두 추가했습니다 ~

2022-11-01 03:30 UTC, jaejae-yoo commented on src/main/java/kitchenpos/application/OrderService.java
검등 로직을 최대한 도메인으로 옮겼습니다! 
생성자에서 검증하기 애매한 부분이 많아서, 검증 메서드를 따로 생성했습니다.

2022-11-01 03:31 UTC, jaejae-yoo commented on src/main/java/kitchenpos/application/TableGroupService.java
>              }
OrderTables 객체로 옮겼습니다! 로직 수정은 잘 떠오르지 않는데.. 좋은 방법이 있을까요?

2022-11-01 03:32 UTC, jaejae-yoo commented on src/main/java/kitchenpos/domain/OrderTable.java
> +        }
도메인 테스트 더 추가했습니다!

2022-11-01 03:34 UTC, jaejae-yoo commented
범고래 안녕하세요 ~
좋은 피드백 남겨주셔서 감사합니다.

- 서비스에 존재하던 검증 로직을 최대한 도메인으로 넘겼습니다. (생성자에서 검증하기 애매한 부분이 많아서, 검증 메서드를 따로 생성했습니다. 좋은 방법이 있다면 공유 부탁드려요 ~)
- 도메인 테스트 코드를 더 추가했습니다.

감사합니다 ~

2022-11-01 03:40 UTC, cndqjacndqja commented on src/main/java/kitchenpos/application/TableGroupService.java
>              }
로직 수정이 도메인으로 옮기려는걸 말하려는 것이였어요!

2022-11-01 03:43 UTC, cndqjacndqja approved these changes
안녕하세요 그린론!
피드백 반영해 주신 것 잘 봤어요 👍 
2단계는 여기서 머지하겠습니다 :)

2022-11-01 03:43 UTC, merged