[레거시 코드 리팩터링 - 2단계] 애쉬(김동호) 미션 제출합니다.
woowacourse/jwp-refactoring pull request #327
Opened 2022-10-28 12:59 UTC by dongho108

안녕하세요 승팡!

MenuProduct에서 매우 고민하다가 요구사항을 아직 못맞췄습니다..
금방해서 다시 리뷰요청하겠습니다.
일단 ProductService, MenuService는 도메인으로 책임을 내려봤습니다.

### 도메인에서 결국 DB에 의존적인 코드
JPA를 안쓰다보니 MenuProduct Entity를 Dao에서  반환할때 생성자 검증에 자꾸 막혀서
리플렉션을 써볼까 고민하다가 일단 검증없는 정적팩터리메서드를 만들었습니다.
도메인에서 결국 DB에 의존적인 코드가 생겨버렸는데요.

이 정적팩터리 메서드를 다른 곳에서 사용이 가능하기 때문에 메서드명이라도 명확하게 forEntity를 붙여놨습니다.
이 부분은 계속 고민해보겠습니다.

### MenuProduct의 price 추가
제이슨의 라이브 코딩을 보고 price를 추가하면 `편하겠다`. 생각을 했었는데,
단순히 편리성을 위해 추가하는 것이 의문이었습니다.
그래서 추가하지 말아야할 이유, 추가해도 괜찮을 이유 여러가지를 생각해봤습니다.

각 객체가 연결된 상태랑 의존도를 생각해봤을때
Menu, MenuProduct는 객체를 직접참조하고 있고 서로에게 영향을 미칠 수 있는데요.
Product MenuProduct와 상관없이 따로 존재해야 했습니다.

2022-10-31 08:49 UTC, Seungpang requested changes
안녕하세요 애쉬!
바쁘신 와중에도 미션을 잘 수행해 주셨네요!
몇가지 코멘트를 남겼으니 확인해주시고
크게 물어보고 싶은 부분이 2가지 있습니다.

### Flyway에 종속적인 테스트
현재 flyway 데이터에 종속적인 테스트가 이뤄지고 있는데 이렇게 하신 이유가 무엇일까요?
데이터가 추가되거나 변경된다면 해당 테스트 전체에 여파가 있을 것 같아요.

### api가 전체적으로 실패하는 문제
api를 테스트 해보시면 전체적으로 실패를 하는데 그 이유는 기본생성자가 없어서 해당 문제가 발생합니다. ㅠㅠ

많이 바쁘시겠지만 파이팅 하시죠!

2022-10-31 08:49 UTC, Seungpang commented on src/main/java/kitchenpos/domain/MenuProduct.java
> +    public MenuProduct(final Long seq,
private으로 바꿀 수 있을것같아요

2022-10-31 08:49 UTC, Seungpang commented on src/main/java/kitchenpos/domain/TableGroup.java
> +    }
해당 validate의 역할이 너무 많은 것 같아요 메서드를 분리해보면 어떨까요?

2022-10-31 09:54 UTC, dongho108 commented on src/main/java/kitchenpos/application/MenuService.java
> +                    return new MenuProduct(null, product.getId(), it.getQuantity(), menuRequest.getPrice());
오 아니져 null 아닌 값만 넣어주고 안에서 생성하도록 수정했습니다.

2022-10-31 09:59 UTC, dongho108 commented on src/main/java/kitchenpos/application/OrderService.java
> +        changeOrderStatus(order);
흠 그럴 수 있겠네요.
메서드 명이랑 파라미터를 읽기좋게 수정했습니다!

2022-10-31 10:03 UTC, dongho108 commented on src/main/java/kitchenpos/application/OrderService.java
> +            throw new IllegalArgumentException("주문 상품 목록이 없으면 주문을 생성할 수 없습니다.");
`validateExistMenus`가 `create` 말고도 다른곳에서 사용되면 NPE가 터질까봐 중복이어도 달아줬습니다

2022-10-31 10:04 UTC, dongho108 commented on src/main/java/kitchenpos/application/TableGroupService.java
> +    public TableGroup getTableGroupWithOrderTables(final Long tableGroupId) {
와 그러네용..; 반영했습니다

2022-10-31 10:11 UTC, dongho108 commented on src/main/java/kitchenpos/domain/MenuProduct.java
> +    public MenuProduct(final Long seq,
실제 프로덕션에서 사용되는 생성자나 정적팩터리 메서드만 public으로 열고 최상위 생성자는 private으로 두었어요

2022-10-31 10:18 UTC, dongho108 commented on src/main/java/kitchenpos/domain/TableGroup.java
> +    }
좋습니다 잘게잘게 쪼개봤어요

2022-10-31 10:49 UTC, dongho108 commented
안녕하세요 승팡!
항상 좋은리뷰 감사합니다~

리뷰 남겨주신 부분들은 다 반영했고 코멘트로 의견주신부분에 대한 답변은 여기에 달겠습니다!
말씀해주신대로 저도 flyway의 데이터가 추가되거나 변경된다면 해당 테스트 전체에 여파가 있을 것 같다고 생각해요!

그런데 flyway는 기존의 data initalize를 위해 사용하는 data.sql등과 약간 다른 느낌으로 실제 프로덕션 DB에 동기화를 시켜주려고 사용하니까 flyway가 변하면 실제로 DB의 구조도 바뀔 수 있는 것이기 때문에 그에따라 테스트가 변하는건 당연하다고 생각해요!

이번 미션에서는 특이하게 insert default data 때문에 약간 data.sql 과 성격이 비슷해 보이지만, flyway 자체에 대해 생각해보면 비즈니스 로직 규칙에 따라서 flyway가 변하면 테스트도 바뀌어도 괜찮을 것 같다고 생각이 듭니다!

2022-11-01 04:36 UTC, Seungpang approved these changes
애쉬 빠르게 피드백 반영 해주셨네요!
애쉬의 의견 들려주셔서 감사합니다.
api에서 몇가지 이슈가 있어서 한번 확인 부탁드려요!
다음 미션도 파이팅하세요!

2022-11-01 04:36 UTC, Seungpang commented on src/main/java/kitchenpos/dao/ordertable/OrderTableRepository.java
> +            final Order order = orderDao.findByOrderTableId(orderTableId)
order를 생성할 때 validateOrderTableEmpty가 실행되는데 이 부분에서 orderDao에 저장된 걸 찾는데 아직 저장된게 없어서 무조건 null이 발생합니다 ㅠㅠ

2022-11-01 04:37 UTC, merged

2022-11-01 05:13 UTC, dongho108 commented on src/main/java/kitchenpos/dao/menu/MenuRepository.java
> +    }
짚어주셔서 너무나 감사합니다 다음단계때 반영할게요!!