[레거시 코드 리팩터링 - 2단계] 루키(최지훈) 미션 제출합니다.
woowacourse/jwp-refactoring pull request #334
Opened 2022-10-28 13:08 UTC by wishoon

안녕하세요 야호..! ~~최대한 도메인 로직으로 넣어보려고 했는데 부족한 부분이 조금 많은 것 같네요..~~ 최대한 옮겨보았습니다!!

이번에 미션하면서 많이 고민했던 부분은 다음 3가지입니다!! (고민하다가 너무 늦어버렸네요..)

1. 인수 테스트의 가독성과 테스트 픽스처
2. 각 객체간의 연관관계
3. 어플리케이션 로직을 도메인 로직으로 이관

3가지 중에서 서로가 생각하는 방법들에 대해서 얘기해보면 재밌을 것 같네요 ㅎㅎ 이번에도 리뷰 잘 부탁드릴게요 😋 

---

밑의 사진은 이번 미션의 각 도메인을 그룹별로 나눠본 사진이에요~~ 야호는 어떻게 도메인 그룹을 생각하고 있는지도 궁금하네요..! https://miro.com/app/board/uXjVPJDiP3U=/?share_link_id=889816662666

<img width="751" alt="image" src="https://user-images.githubusercontent.com/48710213/198824679-6654accf-00f4-4310-b956-0bcb04fe80b5.png">

2022-10-30 11:16 UTC, pup-paw requested changes
안녕하세요 루키!! 야호입니다 :) 
로직도 옮기고, 인수테스트도 작성하고, dto도 만들고, 심지어 JPA까지!! 루키는 정말 괴물 개발자네요...
루키 코드를 하나하나 뜯어보며 공부하며 리뷰를 했더니 리뷰가 조금 늦어졌어요 🤣👍 좋은 코드 감사합니다..ㅎㅎ
그래서인지 이번에도 리뷰가 조금 많습니다.. 하핫.. 루키는.. 괴개니까.. 괜찮을거에요.. ^0^
저번처럼 단순히 루키의 의견을 물어보는 내용도 있고, 사용되지 않는 메서드에 대한 코멘트들도 있으니 너무 걱정 마십쇼!!

루키가 이야기 나누어보고 싶다고 말씀하신 부분이 3가지 있으셨는데요,
1. 인수 테스트의 가독성과 테스트 픽스처
코멘트에 남겨두었으니 확인 부탁드려요 :)

2. 각 객체간의 연관관계
저는 JPA를 사용하지 않았지만 이 부분도 루키의 생각이 궁금해 리뷰 남겨뒀으니 얘기해주세요!! ㅎㅎ

3. 어플리케이션 로직을 도메인 로직으로 이관
저는 이번 미션을 하면서 이 부분이 가장 어려웠던 것 같아요! 그래도 제가 가장 많이 고민했던 내용을 공유해 드리자면,

- `어떻게하면 도메인 내부 로직을 모르더라도 서비스에서 호출된 메서드만 보고도 해당 비지니스 로직의 흐름을 이해할 수 있을까?`
- `우리가 데이터를 db로 관리하지 않더라도 도메인 만으로 만들 수 있는 로직은 어떤게 있을까?`
- `도메인이 능동적으로 행동하게 하기 위해서는 어떻게 해야할까?`

와 같은 고민들을 하면서 레벨 1, 2때를 떠올려봤던 것 같아요! 루키의 팁들도 공유해주시면 감사하겠습니다~~

2022-10-31 13:09 UTC, wishoon commented on src/main/java/kitchenpos/application/dto/MenuProductSaveRequest.java
> +public class MenuProductSaveRequest {
오우.. 제거했습니다~!

2022-10-31 13:14 UTC, wishoon commented on src/main/java/kitchenpos/application/MenuService.java
> +        Menu menu = menuRepository.save(new Menu(request.getName(), request.getPrice(), request.getMenuGroupId()));
사실 이부분에 대해서 고민을 했었는데 결론적으로는 비즈니스 로직에서 생성을 해주기로 했습니다!! `toEntity()`를 사용함으로써 생성 로직을 감출 수 장점이 있기는 한데, 시간이 지나거나 변경점이 많아질수록 각 상황에 따라서 비슷한 메서드를 계속 생성하는 문제가 있더라고요!! 심하면 비즈니스 로직까지 들어가는 경우를 몇변 봤던 것 같아서 사전에 그런 요소를 제거하는게 좀 더 괜찮을 것 같더라고요 ㅎㅎ.. 야호는 어떻게 생각하시나요??

2022-10-31 13:16 UTC, wishoon commented on src/main/java/kitchenpos/application/dto/MenuCreateRequest.java
> +package kitchenpos.application.dto;
application layer에서 presentation layer 알게되면 양방향으로 순환이 될 수 있어서 단방향으로 흐르도록 application에 두었습니다 🙂

2022-10-31 13:19 UTC, wishoon commented on src/main/java/kitchenpos/domain/Menu.java
> +        validateMenuGroup(menuGroupId);
한번 초기화 후에 유효성 검사를 해봤었는데 지금 상황에서는 이렇게 하지 않아도 될꺼 같네요 😅 초기화전에 유호성 검사를 수행하도록 변경하겠습니다~

2022-10-31 13:25 UTC, wishoon commented on src/main/java/kitchenpos/domain/OrderTable.java
> +        }
이부분은 마감 시간이 조금 급해서 당시 저렇게 밖에 생각이 안났던 것 같아요 ㅎㅎ.. 리팩토링 된 코드는 `TableGroup`을 생성하는 시점에 `OrderTable` 들의 상태를 같이 검증하는 방법으로 변경하여, 하나의 생명주기로 관리하기 때문에 이와 같은 코드는 제거했습니다!!

추가적으로 야호의 코멘트에 대한 저의 생각도 비슷해요!! 외부에서 사용하지 않아도 되는 부분들은 접근제어자를 통해 오남용될 여지를 막는게 중요하다고 생각합니다 👍👍

2022-10-31 13:27 UTC, wishoon commented on src/main/java/kitchenpos/application/OrderService.java
> +            .changeOrderStatus(OrderStatus.valueOf(request.getOrderStatus()));
한번 체이닝으로 엮어 보는 건 어떨까 했는데 역시 잘못 사용될 여지가 있어보여서 변경했습니다 😋

2022-10-31 13:28 UTC, wishoon commented on src/main/java/kitchenpos/domain/OrderLineItems.java
> +        validateSize(orderLineItems);
앞선 유효성 검증 코멘트와 동일하게 앞에서 수행하도록 변경했습니다~

2022-10-31 13:29 UTC, wishoon commented on src/main/java/kitchenpos/domain/OrderTable.java
> +    public void addTableGroupId(final Long tableGroupId) {
이부분도 리팩토링을 하면서 tableGroupId를 추가해줄 필요가 없어서 제거하였습니다~

2022-10-31 13:30 UTC, wishoon commented on src/main/java/kitchenpos/domain/TableGroup.java
> +    @Embedded
최근 학생 계정이 풀려서 Commnuity로 강등? 당했는데 변경된 버전이 익숙하지가 않네요 ㅋㅋ.. 변경했습니다

2022-10-31 13:32 UTC, wishoon commented on src/test/java/kitchenpos/domain/ProductTest.java
> +class ProductTest {
급하게 제출한다고 도메인 테스트가 거의 없네요.. 리팩토링 하면서 하나씩 추가하도록 할게요!!

2022-10-31 13:34 UTC, wishoon commented on src/main/java/kitchenpos/application/TableService.java
> +        // Todo: 도메인 로직으로 어떻게 밀어넣을까..?
오우 괜찮은 방법이네요 💯💯

2022-10-31 13:37 UTC, wishoon commented on src/main/java/kitchenpos/application/TableGroupService.java
> +        final List<Long> orderTableIds = orderTables.getOrderTables().stream()
당시 cooking과 meal의 상태를 확인하는 부분을 어떻게 변경해야 할지 잘 생각이 나지 않아서 기존과 동일하게 두었었어요!! 지금 생각해보면 ID 기반으로 받아오고 이를 도메인에서 검증해주는 방식으로 처리하면 될 것 같아요 😄

2022-10-31 13:40 UTC, wishoon commented on src/test/java/kitchenpos/acceptance/fixture/MenuStepDefinition.java
> +        MenuCreateRequest request = new MenuCreateRequest(name, BigDecimal.valueOf(price), menuGroupId, menuProducts);
이번에 작성한 인수 테스트 Fixture 방법이 괜찮다고 생각이 들면 하나씩 적용해보려고 두었었어요~! 이 부분도 조금씩 개선해가려고 합니다 👍 (인수 테스트와 비슷한 방식으로 작성할 것 같아요)

2022-10-31 14:09 UTC, wishoon commented on src/main/java/kitchenpos/domain/OrderTables.java
> +    @OneToMany(mappedBy = "tableGroupId", cascade = CascadeType.PERSIST, fetch = FetchType.LAZY)
이렇게 구현할 경우 객체지향적 관점에서 `테이블 그룹이 주문 테이블 리스트를 가진다`를 자연스럽게 구현할 수 있어서 1 : N 으로 구현을 진행하였습니다. 또한 캡슐화를 할 수 있다는 장점도 가질 수 있고요!!

또한 이렇게 구현할 경우 `TableGroup`과 `List<OrderTable>`의 생명주기를 동시에 하나로 가져갈 수 있는 장점이 있다고 판단되어서 구현하였어요

다만 현재 1 : N 단방향으로 구현되어 있는데 해당 방법을 많이 사용해본건 아니라서 문제 상황은 없을지 조금 고민해봐야 할 것 같아요 😋 야호는 이부분을 어떻게 풀어내셨는지도 궁금하네요 ㅎㅎ

2022-10-31 14:30 UTC, wishoon commented on src/main/java/kitchenpos/domain/MenuProducts.java
> +            sum = sum.add(menuProduct.getPrice().multiply(BigDecimal.valueOf(menuProduct.getQuantity())));
[cec6a38](https://github.com/woowacourse/jwp-refactoring/pull/334/commits/cec6a381eb72dca123e8ef196f105c0b76955279) 에 반영했습니다~

2022-10-31 16:20 UTC, wishoon commented
Q. 어떻게하면 도메인 내부 로직을 모르더라도 서비스에서 호출된 메서드만 보고도 해당 비지니스 로직의 흐름을 이해할 수 있을까?
A. 음.. '도메인 내부 로직을 모른다'와 '서비스에서 호출된 메서드' 라는 말은 아마 캡슐화 측면을 얘기하신 거겠죠?? 저도 배워가는 입장이라 확실하진 않지만 기존처럼 서비스 로직에 나와있는 기능들을 도메인 로직들로 이관하고 각 객체간의 메시지를 통해서 표현한다면 아마 잘 이해가 되지 않을까요 ㅎㅎ

Q. 우리가 데이터를 db로 관리하지 않더라도 도메인 만으로 만들 수 있는 로직은 어떤게 있을까?
A. 제 개인적인 생각으로는 값 객체가 아닐까요?? MenuProducts, OrderTables, OrderLineItems 등이 될 수 있을 것 같네용 ㅎㅎ

2022-11-01 05:58 UTC, pup-paw commented on src/main/java/kitchenpos/application/MenuService.java
> +        Menu menu = menuRepository.save(new Menu(request.getName(), request.getPrice(), request.getMenuGroupId()));
`비즈니스 로직까지 들어가는 경우` 는 어떤게 있었나요??

2022-11-01 06:02 UTC, pup-paw commented on src/test/java/kitchenpos/acceptance/fixture/MenuStepDefinition.java
> +        MenuCreateRequest request = new MenuCreateRequest(name, BigDecimal.valueOf(price), menuGroupId, menuProducts);
코테스트가 뭔가요?? 소개해주세요!! :)

2022-11-01 06:04 UTC, pup-paw commented
안녕하세요 루키~~ 야호입니다 :) 리뷰 반영이 잘 된 것 같아 이만 머지하도록 하겠습니다!
3단계도 화이팅하세요!!

2022-11-01 06:04 UTC, merged