[레거시 코드 리팩터링 - 2단계] 호호(유현호) 미션 제출합니다.
woowacourse/jwp-refactoring pull request #335
Opened 2022-10-28 13:09 UTC by yhh1056

릭 집가서 더할게...

2022-10-29 21:22 UTC, nailseong requested changes
안녕하세요 호호 🤭
application 계층과 domain 계층의 책임을 생각하면서 리뷰를 남겨봤어요. 코멘트가 다소 모호해서 이해하기 어려운 부분이 있다면 언제든지 코멘트나 DM 해주세요. 기다리고 있겠습니다. ㅎㅅㅎ

---

### 질문
1. presentation 계층에서 수행하던 통합 테스트를 applicatio 계층으로 내린 이유는 뭘까요?
2. JdbcTemplate에서 Spring Data JPA로 변경한 이유는 무엇인가요?

---

### 아래 사항들을 확인하고 반영해주세요 :)
1. 깨지는 테스트 & ignore된 테스트 확인
2. 테스트 & 프로덕션 코드에 주석
3. 사용되지 않는 메서드, 필드 등 제거
4. 생성자의 접근 제어자 확인

2022-10-29 21:22 UTC, nailseong commented on src/main/java/kitchenpos/application/OrderValidator.java
> +        }
주문에 주문 항목이 비어있을 수 없다는 규칙이 정작 Order에는 표현되지 않았네요.
이러한 도메인 로직까지 해당 Validator 객체가 가져야할까요? 그것도 application 계층에 있는 객체가요!!!
한번 고민해보면 좋을 것 같아요.

---

아래는 이동욱님 블로그에서 발췌한 도메인 로직 구별법이랍니다. 저는 전에 읽어보고 많은 도움을 받아서 공유해봐요 ㅎㅅㅎ

<img width="1086" alt="도메인로직_구분법" src="https://user-images.githubusercontent.com/68512686/198852175-8ed9ecac-a464-42ae-9a38-03d7115114ab.png">

2022-10-30 03:19 UTC, yhh1056 commented on src/main/java/kitchenpos/ui/TableRestController.java
> +//    }
토요일에 작업한 내용이 푸시가 안되서 반영이 안됐었네요ㅜㅜ

패키지도 엉망인 코드들을 리뷰하게 해서 죄송합니다.....

2022-10-31 04:48 UTC, yhh1056 commented on src/main/java/kitchenpos/application/OrderService.java
>      private final OrderLineItemDao orderLineItemDao;
사용되지 않는 부분과 패키지 부분은 다 변경되었어요!!

2022-10-31 04:59 UTC, yhh1056 commented on src/main/java/kitchenpos/application/OrderValidator.java
> +        }
해당 로직도 도메인으로 이동했어요!!

저도 repository 계층이 필요하지 않은 검증이나 로직에 대해서는 도메인으로 최대한 이동하는게 좋다고 생각해요!

2022-10-31 05:09 UTC, yhh1056 commented on src/main/java/kitchenpos/domain/TableGroup.java
orderTables 가 스스로 단체지정을 해제할수있는 메시지를 수신하도록 변경했어요

2022-10-31 05:10 UTC, yhh1056 commented on src/main/java/kitchenpos/domain/ProductDto.java
> +public class ProductDto {
푸시되지 않아 생긴문제군요ㅜㅜ

2022-10-31 05:19 UTC, yhh1056 commented on src/main/java/kitchenpos/domain/MenuRepository.java
> +    int countByIdIn(@Param("menuIds") List<Long> menuIds);
쿼리메서드로 동작합니다!!!

2022-10-31 05:22 UTC, yhh1056 commented on src/main/java/kitchenpos/domain/MenuGroupDto.java
> +public class MenuGroupDto {
푸시이슈입니다ㅜㅜ 죄송해요ㅜㅜ

2022-10-31 06:56 UTC, yhh1056 commented on src/main/java/kitchenpos/application/ProductService.java
> +    public List<ProductResponse> list() {
JPA를 사용하면 사용하는게 적절하다고 생각이 들어요. readonly 옵션으로 수정할게요!

2022-10-31 07:21 UTC, yhh1056 commented on src/main/java/kitchenpos/application/OrderService.java
> +    public OrderResponse create(final OrderCommand orderCommand) {
이것도 푸시이슈였네요ㅜ

2022-10-31 07:26 UTC, yhh1056 commented on src/main/java/kitchenpos/application/OrderService.java
> +        order.setOrderLineItems(collect);
릭의 의견에 매우 동의합니다! 라이프사이클이 같아서 주문항목과 같이 묶이게되는데요 이것도 푸시가 안되서 제대로 리뷰를 받을수가 없었네요ㅜㅜ

너무너무 좋은 설명 감사합니다😃

2022-10-31 08:57 UTC, yhh1056 commented on src/main/java/kitchenpos/domain/OrderTable.java
> +    public void decideAvailabilityOfOrderRegistration(OrderAble orderAble) {
changeEmtpy() 라는 메서드로 변경했어요

2022-10-31 09:04 UTC, yhh1056 commented on src/main/java/kitchenpos/domain/Menu.java
>      }
굿!

2022-10-31 09:04 UTC, yhh1056 commented on src/main/java/kitchenpos/domain/MenuGroup.java
> +    public MenuGroup(Long id, String name) {
넵!!!

2022-10-31 13:22 UTC, yhh1056 commented on src/main/java/kitchenpos/application/TableGroupService.java
>          }
요청하는 OrderTable의 개수와 데이터베이스에 존재하는 개수가 다른 경우에 대한 검즈이에요.
"요청하는 주문 테이블이 존재하지 않습니다." 라는 예외 메시지로 변경했고 validator를 어플리케이션 레이어에서 도메인레이어로 옮기면서  도메인이 생성될 때 검증할 수 있도록 수정했어요.

2022-11-01 01:55 UTC, merged