[레거시 코드 리팩터링 - 2단계] 파랑(이하은) 미션 제출합니다.
woowacourse/jwp-refactoring pull request #341
Opened 2022-10-28 14:07 UTC by summerlunaa

레넌 안녕하세요 파랑입니다.
늦어서 죄송합니다. 리뷰 잘부탁드립니다!

2022-10-30 14:01 UTC, brorae requested changes
안녕하세요 파랑 2단계도 JPA로 잘 구현해주셨네요 👏
몇가지 궁금한 부분에 커멘트 남겼으니 확인 부탁드립니다 !

2022-10-30 16:53 UTC, summerlunaa commented on src/main/java/kitchenpos/application/ProductService.java
> +                .collect(Collectors.toList());
ProductResponses를 만들어 그 안에서 처리하라는 뜻일까요!?

2022-10-30 16:57 UTC, summerlunaa commented on src/main/java/kitchenpos/domain/product/Product.java
> +    private BigDecimal price;
엇 BigDecimal 타입의 price를 Embedded 타입으로 묶으면 어떤 게 좋을까요?

2022-10-31 16:52 UTC, summerlunaa commented on src/main/java/kitchenpos/application/TableGroupService.java
> +        final List<OrderTable> orderTables = orderTableRepository.findAllByIdIn(orderTableIds);
final을 삭제했습니다.

2022-11-01 10:27 UTC, brorae approved these changes
안녕하세요 파랑~
변경 사항 확인했습니다 !
3단계도 화이팅입니다~~!

2022-11-01 10:27 UTC, merged