[레거시 코드 리팩터링 - 2단계] 어썸오(정수현) 미션 제출합니다.
woowacourse/jwp-refactoring pull request #345
Opened 2022-10-28 14:49 UTC by awesomeo184

안녕하세요 슬로. 예상했던 것보다 시간이 많이 걸리네요... Jpa를 적용하고 있는데 아직 Order와 Table 부분 리팩터링을 진행하지 못했습니다. 토요일 저녁까지 마무리해서 마저 커밋하겠습니다.

2022-11-01 04:23 UTC, hanull requested changes
안녕하세요 어썸오!
간단한 리뷰와 궁금한 부분 코멘트 남겼습니다. 확인 부탁드려요.

테스트가 깨지는 것 같아요.
application 패키지 dto 클래스와 service 클래스를 분리해주면 더 보기 좋을 것 같아요.
Order와 Table 부분 리팩토링 하셨으면 푸시해주세요!

### 질문
- JdbcTemplate에서 spring data JPA로 바꾸신 이유가 있을까요?

2022-11-01 04:23 UTC, hanull commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +        final var PRODUCT_PRICE = BigDecimal.valueOf(1000L);
상수처럼 사용한다는 의미로 변수명을 이렇게 사용하신 건가요?!!
만약 그렇다면 메서드 맨 위가 아니라 메서드 안쪽에 선언하신 이유가 궁금해요

2022-11-01 04:23 UTC, hanull commented on src/test/java/kitchenpos/domain/MenuRepositoryTest.java
> +        System.out.println(save);
오 출력문 비교만으로 데이터 검증을 하신건가요?!
그렇다면 이유가 궁금해요

2022-11-02 15:39 UTC, awesomeo184 commented on src/main/java/kitchenpos/application/MenuService.java
> +    public MenuService(MenuRepository menuRepository, MenuGroupDao menuGroupDao, ProductRepository productRepository) {
수정했습니다!

2022-11-02 15:40 UTC, awesomeo184 commented on src/main/java/kitchenpos/domain/MenuProduct.java
> +    @Column(length = 20, nullable = false)
DB 스키마에 맞춰서 수정했습니다 :)

2022-11-02 15:41 UTC, awesomeo184 commented on src/main/java/kitchenpos/domain/MenuProduct.java
> +    public String toString() {
테스트할때 로그를 편하게 보려고 추가했어요. 양방향 연관관계에서 조심해야곘네여

2022-11-02 15:43 UTC, awesomeo184 commented on src/main/java/kitchenpos/application/TableService.java
> +        savedOrderTable.changeNumberOfGuest(numberOfGuests);
네 맞습니다. 도메인 로직으로 넣었습니다!

2022-11-02 15:44 UTC, awesomeo184 commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +        final var PRODUCT_PRICE = BigDecimal.valueOf(1000L);
해당 테스트를 볼 때 한번에 드러나도록 하기 위해서 메서드에서 final로 추가했었는데요, 전역으로 올리는 것보다는 이게 더 명확하게 드러날 것 같애서 이런 선택을 했습니당...

2022-11-02 15:45 UTC, awesomeo184 commented on src/test/java/kitchenpos/domain/MenuRepositoryTest.java
> +        System.out.println(save);
이 부분은 실수네요 ㅠㅠ, 다시 검증문으로 확인할 수 있도록 수정했습니다!

2022-11-02 15:52 UTC, awesomeo184 commented
슬로! 꼼꼼한 리뷰 감사드립니다. JPA로 변경한 이유에 대해 질문해주셨는데요, 리팩토링을 하다보니, (예를들어)객체로서의 Order와 테이블에 Mapping되는 Order에 차이가 있더라구요. JPA를 사용하면 이런 부분을 쉽게 컨트롤할 수 있겠다는 생각이 들었어요. 또한 Menu에 의해 생명주기가 컨트롤되는 MenuProduct에 대한 제어도 Jdbc를 사용하는 것보다는 JPA의 영속성 전파를 이용하면 쉽게 컨트롤이 될 수 있을 것 같아서 JPA로 전환했습니다. 생각보다는 코드의 변화가 많아서 그냥 JDBC를 쓰는게 낫지 않을까하는 생각도 들긴했는데, JPA를 쓰는 편이 좀 더 객체지향적으로 프로그래밍을 할 수 있다는 생각이 들었어요!

2022-11-03 01:26 UTC, hanull approved these changes
안녕하세요 어썸오!
리뷰 반영해주신 부분 확인했습니다. 이만 머지할게요
3단계로 화이팅

2022-11-03 01:26 UTC, hanull commented on src/main/java/kitchenpos/application/OrderService.java
> +    public List<OrderResponse> list() {
조회 부분에 @Transactional(readOnly = true) 를 사용하는건 어떤가요

2022-11-03 01:26 UTC, merged