[레거시 코드 리팩터링 - 2단계] 스컬(김ㅇ뉴기) 미션 제출합니다.
woowacourse/jwp-refactoring pull request #351
Opened 2022-10-29 01:52 UTC by skullkim

크리스~ 2단계도 잘부탁해요😊

2022-10-29 12:39 UTC, Byeongju-Kong requested changes
스컬~! 리팩토링 하시느라 고생하셨어요!!!
리뷰 남겨두었습니다! 테스트에서 사용하는 "productName", "menuGroup"과 같은 문자열은 픽스쳐로 분리해도 좋을 것 같습니다~!

2022-10-29 12:39 UTC, Byeongju-Kong commented on src/main/java/kitchenpos/application/TableService.java
> +    private void canChangeEmptyStatus(final OrderTable orderTable) {
canChange라고 하니까 true, false를 반환해야 할 것 같아요!

2022-10-29 12:39 UTC, Byeongju-Kong commented on src/main/java/kitchenpos/application/TableGroupService.java
> +    public TableGroupDto create(final TableGroupCreationDto tableGroupCreationDto) {
이 메서드가 길어서, 메서드로 좀 분리해도 좋을 것 같아요~!

2022-10-29 12:39 UTC, Byeongju-Kong commented on src/main/java/kitchenpos/application/TableGroupService.java
> +    public TableGroupDto create(final TableGroupCreationDto tableGroupCreationDto) {
if문으로 예외 처리 하는 부분 등등 분리하면 좋을 것 같아요!

2022-10-29 12:39 UTC, Byeongju-Kong commented on src/main/java/kitchenpos/application/OrderService.java
>          }
이 부분이 2가지 검증이 들어가는데, 저라면 두개의 메서드로 분리할 것 같아요!
고려해보셔도 좋을 것 같아요!

2022-10-29 12:39 UTC, Byeongju-Kong commented on src/main/java/kitchenpos/application/OrderService.java
> +
이 클래스 69번째, 70번째 줄에 개행이 두번 들어가있네요!

2022-10-29 12:39 UTC, Byeongju-Kong commented on src/main/java/kitchenpos/application/OrderService.java
>          }
메서드로 분리해보면 어떨까요?

2022-10-29 12:39 UTC, Byeongju-Kong commented on src/main/java/kitchenpos/application/TableGroupService.java
>          }
메서드로 분리하는건 어떨까요?

2022-10-29 12:39 UTC, Byeongju-Kong commented on src/main/java/kitchenpos/application/MenuService.java
> +                    return new MenuProduct(product, menuProductDto.getQuantity());
Quantity가 0 이하 이면 어떻게 될까요?

2022-10-29 12:39 UTC, Byeongju-Kong commented on src/main/java/kitchenpos/application/OrderService.java
> +                        new OrderLineItem(orderId, orderLineItem.getMenuId(), orderLineItem.getQuantity())))
여기도 Quantity가 0보다 적으면 어떻게 될까요?

2022-10-29 12:39 UTC, Byeongju-Kong commented on src/test/java/kitchenpos/domain/OrderTableTest.java
> +
!!!!

2022-10-29 12:39 UTC, Byeongju-Kong commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +    @DisplayName("주문 상태를 변결할 때 ")
!!

2022-10-29 12:39 UTC, Byeongju-Kong commented on src/test/java/kitchenpos/application/TableGroupServiceTest.java
> +class TableGroupServiceTest {
테이블 그룹을 해제 할때, 발생할 수 있는 예외들에 대한 테스트가 없는 것 같아요~!

2022-10-29 12:39 UTC, Byeongju-Kong commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +class OrderServiceTest {
존재하지 않는 Menu로 생성하려고 할 경우의 예외 테스트가 존재하지 않네요!
간단한 NotFound라서 진행하지 않으신건가요?

2022-10-30 05:38 UTC, skullkim commented on src/main/java/kitchenpos/application/MenuService.java
> +        final List<MenuProduct> savedMenuProducts = saveMenuProductsd(savedMenu.getId(), menuProducts);
수정할게요~

2022-10-30 05:41 UTC, skullkim commented on src/main/java/kitchenpos/application/MenuService.java
> +    @Transactional(readOnly = true)
잘못 걸었네요;;

2022-10-30 05:46 UTC, skullkim commented on src/test/java/kitchenpos/application/MenuGroupServiceTest.java
> +                () -> assertThat(menuGroupDto.getId()).isGreaterThanOrEqualTo(1L),
"테스트니까 id는 무조건 1이겠지" 라는 생각을 한게 아니라 "id가 가질 수 있는 제약 조건이 무었일까"를 생각하나 보니 isGreaterThanOrEqualTo()를 사용하게 되었어요. 테스트를 문서 관점으로 바라봤을 때 id를 실제 코드 상황에 맞게 1보다 크거나 같은지를 검증하고 명시하는 것이 더 좋을거 같아요. 이 관점에 대해 어떻게 생각하세요🧐?

2022-10-30 05:47 UTC, skullkim commented on src/main/java/kitchenpos/application/TableService.java
> +    private void canChangeEmptyStatus(final OrderTable orderTable) {
validateChangeEmptyStatus()로 수정할게요~

2022-10-30 05:55 UTC, skullkim commented on src/main/java/kitchenpos/application/TableGroupService.java
> +    public TableGroupDto create(final TableGroupCreationDto tableGroupCreationDto) {
수정할게요~

2022-10-30 09:01 UTC, skullkim commented on src/main/java/kitchenpos/application/OrderService.java
>          }
분리할게요~

2022-10-30 09:02 UTC, skullkim commented on src/main/java/kitchenpos/application/OrderService.java
> +
수정할게요~

2022-10-30 09:05 UTC, skullkim commented on src/main/java/kitchenpos/application/OrderService.java
>          }
분리할게요~

2022-10-30 09:05 UTC, skullkim commented on src/main/java/kitchenpos/application/TableGroupService.java
>          }
네~

2022-10-30 11:19 UTC, skullkim commented on src/main/java/kitchenpos/application/MenuService.java
> +                    return new MenuProduct(product, menuProductDto.getQuantity());
생성자에서 검증하는 걸로 바꿀게요~

2022-10-30 11:20 UTC, skullkim commented on src/test/java/kitchenpos/domain/OrderTableTest.java
> +
???

2022-10-30 11:20 UTC, skullkim commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +    @DisplayName("주문 상태를 변결할 때 ")
???

2022-10-30 12:05 UTC, skullkim commented on src/test/java/kitchenpos/application/TableGroupServiceTest.java
> +class TableGroupServiceTest {
추가할게요~

2022-10-30 12:13 UTC, skullkim commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +class OrderServiceTest {
추가할게요~

2022-10-31 05:49 UTC, Byeongju-Kong commented on src/test/java/kitchenpos/application/MenuGroupServiceTest.java
> +                () -> assertThat(menuGroupDto.getId()).isGreaterThanOrEqualTo(1L),
테스트 문서 관점에서는 좋은 것 같네요! 사실 id값이 1인 것이 중요한 것이 아니라, 1 이상의 id값이 존재하는지만 체크하면 되니까요!

2022-10-31 05:49 UTC, Byeongju-Kong commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +    @DisplayName("주문 상태를 변결할 때 ")
변`결`할때 !!!!

2022-10-31 05:50 UTC, Byeongju-Kong commented on src/test/java/kitchenpos/domain/OrderTableTest.java
> +
39번째 라인에 개행이 들어가있어요!

2022-10-31 06:02 UTC, Byeongju-Kong commented
스컬~! 리팩토링 잘 진행해주셔서 머지해도 될 것 같습니다! 다른 분들은 JPA를 다 도입했는데, 스컬의 리팩토링의 철학에 맞게 당장 JPA로 변경하지 않고 리팩토링을 하신 것이 인상적이었어요!
인수테스트에 대해서 이야기를 나눴었는데요. API를 사용하는 사용자 시나리오에 대해 작성하는 것이 인수테스트라고 생각해요. 그렇다면 과연 인수테스트에 해피케이스만 존재해도 될지에 대한 고민을 해보셔도 좋을 것 같아요! 사용자가 잘못된 입력을 할 경우도 사용자 시나리오에 포함되는 것이라고 생각해요!

그럼 3단계에서 봐요~~ 안녕~~~~~

2022-10-31 06:56 UTC, Byeongju-Kong approved these changes
스컬! 리팩토링 잘 진행해주셔서 이만 머지하겠습니다~!
답변도 몇개 남겨두었어요! 확인하시면 좋을 것 같아요~!

2022-10-31 06:56 UTC, merged

2022-11-01 06:30 UTC, devHudi commented
안녕하세요 김뉴기씨