[레거시 코드 리팩터링 - 2단계] 승팡(김승래) 미션 제출합니다.
woowacourse/jwp-refactoring pull request #358
Opened 2022-10-29 16:25 UTC by Seungpang

안녕하세요 소주캉!
이번 미션을 하면서 이전에 Fake객체로 테스트코드 짠걸 후회했습니다.
다시 테스트코드는 스프링부트 테스트로 돌아왔습니다.
그리고 flyway와 테스트 환경을 분리 하였습니다.

아직도 만족스럽지 못한 코드라 꾸준하게 리팩토링 하겠습니다!
이번 리뷰도 잘 부탁드립니다.

2022-10-30 08:25 UTC, sojukang requested changes
안녕하세요 씅팡👋 레거시 코드 리팩터링 2단계 리뷰드리는 소주캉입니다. 
빠른 시간에 많은 부분을 반영해서 리팩터링해주셨군요😲 
Repository 패턴으로 연관 객체 영속화 관련 로직을 Service에서 Repository로 이동한 점이 인상깊었습니다 👍
약간의 의견 남겨드렸습니다! 계속 화이팅입니다.

2022-10-30 08:25 UTC, sojukang commented on src/main/java/kitchenpos/application/OrderService.java
> +        order.checkMenuSize(menuDao.countByIdIn(order.getMenuIds()));
반드시 필요한 검증인가? 어떤 걸 검증하기 위한 메서드인가요?

2022-10-30 08:25 UTC, sojukang commented on src/main/java/kitchenpos/application/TableGroupService.java
> +    private void validateOrderStatus(final List<OrderTable> orderTables) {
이 검증 메서드에서 너무 많은 일을 하는 것 같아요! 적절히 분리하면 어떨까요?

2022-10-30 08:25 UTC, sojukang commented on src/main/java/kitchenpos/application/TableService.java
> +        final OrderTable orderTable = new OrderTable(null, null, request.getNumberOfGuests(), request.isEmpty());
생성자에 어떤 값을 null로 넣어줘야할지를 알아야 하는 건 TableService의 책임은 아닌 것 같아요! 적절한 생성 방식을 만들면 어떨까요? OrderTable이나 Request의 변경이 일어나면 TableService의 코드의 수정도 일어나게 되어서 SRP를 지키지 못할 것 같아요.

2022-10-30 08:25 UTC, sojukang commented on src/main/java/kitchenpos/application/TableService.java
>          final OrderTable savedOrderTable = orderTableDao.findById(orderTableId)
이 find는 같은 코드로 다른 메서드에서도 쓰이고 있는데요! 예외 타입, 메시지가 바뀌거나 dao에 호출하는 조회 메서드 변경 등 여러 이유로 변경되면 여러 군데의 코드를 수정해야할 것 같아요! 중복을 제거해보면 어떨까요?

2022-10-30 08:25 UTC, sojukang commented on src/main/java/kitchenpos/application/TableService.java
> +        validateCookingOrMeal(orderTableId);
validateCookingOrMeal인데, Cooking이나 Meal일 경우 예외를 반환하고 있어요. 직관적으로 어떤 검증을 할지 메서드명을 보고 파악하기 힘든 것 같아요!

2022-10-30 08:25 UTC, sojukang commented on src/main/java/kitchenpos/repository/MenuRepository.java
> +public class MenuRepository implements MenuDao {
Repository Pattern을 사용하셨군요! 연관 객체의 관리를 Service에서 Repository로 이동해서 적절하게 책임 분리가 되었다는 느낌이 들었어요👍
대신 Repository 내부 로직을 파악하기가 다소 어렵다는 느낌은 들었어요!

2022-10-30 08:25 UTC, sojukang commented on src/test/java/kitchenpos/application/ServiceTest.java
> +@Transactional
`@Transactional`을 붙여주신 이유는 테스트별 데이터 롤백을 하기 위함인가요?

2022-10-30 08:25 UTC, sojukang commented on src/test/java/kitchenpos/application/MenuGroupServiceTest.java
> +class MenuGroupServiceTest extends ServiceTest {
Fake 다 날아갔군요 ㅋㅋㅋㅋ 어떤 이유로 날리는 게 좋다고 생각하셨나요?

2022-11-01 06:34 UTC, Seungpang commented on src/main/java/kitchenpos/application/MenuService.java
> +    @Transactional(readOnly = true)
1. readOnly 속성을 true 줄 경우 스프링에서 런타임 시점에 최적화를 허용합니다. 각 db 힌트에 맞춰서 동작합니다.
mysql 일 경우 transaction Id를 세팅하는 오버헤드를 줄일 수 있습니다.
다만 h2일 경우에는 해당 옵션이 적용되지 않습니다. 스프링에서는 Transaction manager가 읽기 전용 힌트를 해석할 수 없는 경우 예외를 throw하지 않고 무시합니다!

[공식문서 보기](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/transaction/annotation/Transactional.html#readOnly--)

2022-11-01 06:37 UTC, Seungpang commented on src/main/java/kitchenpos/application/OrderService.java
> +        final Order order = new Order(
각각 orderTableId를 가져오는 부분과 OrderLineItems를 매핑하는 부분으로 나누어 봤습니다.

2022-11-01 06:46 UTC, Seungpang commented on src/main/java/kitchenpos/application/OrderService.java
> +        order.checkMenuSize(menuDao.countByIdIn(order.getMenuIds()));
네! 실제 메뉴와 주문 항목이 일치하는지 확인하는 로직입니다. 모호함이 있어서 checkActualOrderLineItems로 변경했습니다.

2022-11-01 06:47 UTC, Seungpang commented on src/main/java/kitchenpos/application/TableGroupService.java
> +    private void validateOrderStatus(final List<OrderTable> orderTables) {
OrderTable의 id를 List로 만드는 것과 검증하는 부분을 분리했습니다.

2022-11-01 06:48 UTC, Seungpang commented on src/main/java/kitchenpos/application/TableService.java
> +        final OrderTable orderTable = new OrderTable(null, null, request.getNumberOfGuests(), request.isEmpty());
빠르게 리팩토링 하려다보니 세세한 부분을 신경 못썼네요! 좋은 피드백 감사합니다.

2022-11-01 06:48 UTC, Seungpang commented on src/main/java/kitchenpos/application/TableService.java
>          final OrderTable savedOrderTable = orderTableDao.findById(orderTableId)
중복되는 부분을 메소드로 추출했습니다.

2022-11-01 06:49 UTC, Seungpang commented on src/main/java/kitchenpos/application/TableService.java
> +        validateCookingOrMeal(orderTableId);
validateOrderStatusInCookingOrMeal로 수정했습니다. OrderStatus의 상태가 cooking인지 Meal인지 직관적으로 나타나게 했습니다.

2022-11-01 06:50 UTC, Seungpang commented on src/main/java/kitchenpos/repository/MenuRepository.java
> +public class MenuRepository implements MenuDao {
무엇을 생성할때 각각 연관되어있는 객체가 있다보니 내부 로직의 복잡성이 늘어났다는건 인정합니다 ㅠㅠ

2022-11-01 06:50 UTC, Seungpang commented on src/test/java/kitchenpos/application/ServiceTest.java
> +@Transactional
네 맞습니다!

2022-11-01 06:53 UTC, Seungpang commented on src/test/java/kitchenpos/application/MenuGroupServiceTest.java
> +class MenuGroupServiceTest extends ServiceTest {
변경된 부분이 dto와 repository가 생기면서 제가 편하자고 만들어 놨던 부분들이 dto 변경 부분이 많아져서 오히려
새롭게 만드는게 더 빠른 느낌이 들었습니다 ㅠㅠ 한정된 시간안에 해결하려다보니 편한 길을 선택해버렸네요

2022-11-01 06:54 UTC, Seungpang commented
안녕하세요 소주캉!
좋은 피드백 감사합니당

기존에 api들이 다 통과하는줄 알았는데 다시 돌려보니 실패하는 것들이 있어서 그 부분도 수정했습니다.
이번 리뷰도 잘 부탁 드립니다.

2022-11-02 05:33 UTC, sojukang commented
안녕하세요 씅팡👍 레거시 코드 리팩터링 2단계 미션 리뷰드리는 소주캉입니다. 
피드백 반영해주신 사항 전부 확인했습니다👍👍 
댓글도 꽤 달았는데 전부 답해주셔서 감사합니다🙇‍♀️
2단계 요건은 전부 충족하셔서 2단계 마무리하겠습니다!
3단계도 화이팅입니다💃

2022-11-02 05:34 UTC, merged