[레거시 코드 리팩터링 - 3단계] 오찌(오지훈) 미션 제출합니다.
woowacourse/jwp-refactoring pull request #363
Opened 2022-11-01 13:21 UTC by Ohzzi

안녕하세요 디우! 원래 3, 4단계를 같이 해보려고 했는데, 4단계는 고민할 부분이 조금 남기도 했고, 멀티 모듈로 분리하게 되면 필연적으로 file changes가 많아지기 때문에 3단계만 하고 제출해보겠습니다 :)

전체적으로 의존성은 다음과 같습니다.

### 레이어 별
presentation(controller) -> application(service) -> domain(repository)

### 컨텍스트 별
order(Order, OrderLineItem) -> menu(MenuGroup, Menu, MenuProduct) -> product(Product)
order -> table(TableGroup, OrderTable)

해결하기 힘들었던 문제는 order 컨텍스트와 table 컨텍스트가 양방향 의존하고 있다는 문제였는데요, table -> order 쪽 검증 로직을 이벤트 발행을 통해 의존성을 강제로 끊어냈습니다. order -> table 쪽이 아니라 table -> order 쪽을 끊어낸 것은, table 컨텍스트는 생성 시점에 order의 존재를 알지 못하지만, order 컨텍스트는 생성 시점에 table 컨텍스트의 존재를 알아야 하기 때문입니다.

우선은 이렇게 풀어내봤는데, 좋은 방법일지는 조금 더 고민해보도록 하겠습니다 :) 현재 상황에서는 생각나는 가장 좋은 방법이어서 이렇게 구현해보았습니다!

남은 과제로는, dto의 의존성이 양방향이라는 문제입니다. 현재 dto가 서비스 단까지 내려오고 있는데, requestDTO의 경우 생성 책임이 presentation 레이어에 있기 때문에, presentation과 application 레이어가 엄밀히 말해서는 의존성 사이클이 돌고 있다는 문제가 있습니다. 다만 이 부분을 굳이 해결해야 할 지에 대한 고민을 좀 더 해보고, 분리할 필요성이 있다면 presentation 레이어와 application 레이어에서 사용하는 dto를 분리해 볼 생각입니다.

이번 단계에서도 좋은 리뷰 부탁드려요!

2022-11-02 23:27 UTC, tco0427 requested changes
안녕하세요, 오찌!!
어제 저녁에 리뷰 드릴려고 했는데 리뷰가 늦어 죄송합니다!!
요구사항에 맞게 잘 구현해주시고, 바쁘신 와중에도 customException, ControllerTest 등 추가해주셔서 역시 오찌구나 했습니다ㅎㅎ..
몇가지 코멘트 남겨드렸습니다~_~

2022-11-02 23:27 UTC, tco0427 commented on src/main/java/kitchenpos/application/menu/MenuGroupService.java
> +@Transactional(readOnly = true)
`@Transactional(readOnly=true)` 를 클래스 레벨에 선언해주셨네요!!
이전과는 어떤 차이가 있을까요??

2022-11-02 23:27 UTC, tco0427 commented on src/main/resources/db/migration/V5__ADD_OrderStatusRecord.sql
> +);
주문의 상태를 저장하기 위한 새로운 테이블이 추가되었네요!
실제 Order의 status와 불일치하게 되면 어떻게 되나요???
Order 에도 order의 status 가 있는데 외래키로 걸어주지 않은 이유도 궁금합니다!

2022-11-02 23:27 UTC, tco0427 commented on src/main/java/kitchenpos/ui/common/GlobalControllerAdvice.java
> +public class GlobalControllerAdvice {
👍👍

2022-11-02 23:27 UTC, tco0427 commented on src/main/java/kitchenpos/application/table/TableGroupService.java
> +import kitchenpos.domain.table.TableGroup;
도메인 연관관계 포함해서

```
Menu -> Product
Order -> Menu
Order -> Table
```

으로 잘 끊어내주셨네요!!

2022-11-02 23:27 UTC, tco0427 commented on src/main/java/kitchenpos/domain/table/OrderStatusRecord.java
> +public class OrderStatusRecord implements Persistable<Long> {
새로운 테이블과 객체가 추가되었네요..!!
혹시 이 방법 말고 다른 방법으로 Order, Menu, Product, Table 간의 단방향을 유지하면서 OrderTable 이 주문 상태를 가질 수 있는 방법이 있을까요???

저의 경우에는 OrderTable 에서 Order 를 직접 알고 있고, 즉 연관관계가 있기 때문에 끊어내기 힘든 상황에서 Order 쪽에서 생성시에 OrderTable 의 empty 를 검증하는데서 알아내야했어요. 그래서 저는 오찌가 말씀해주신 것처럼 Order생성 시점에 OrderTable 을 알아야하지만 OrderTable -> Order 연관관계를 끊어내기 보다는 검증하는 부분에 대해서 인터페이스를 통해 의존성 방향을 역전 시키는게 쉽다고 판단해서 이렇게 끊어내주었습니다!
그리고 저와 같은 방법으로 했을 때 오찌가 생각하는 문제점은 무엇이 있을지 궁금합니다!

2022-11-02 23:27 UTC, tco0427 commented on src/main/java/kitchenpos/domain/order/OrderedMenu.java
> +    private Price price;
주문 당시의 메뉴 이름과 가격을 가지도록 해서 요구사항을 만족해주셨네요!!👍👍

2022-11-02 23:27 UTC, tco0427 commented on src/test/java/kitchenpos/RepositoryTest.java
> +@AutoConfigureTestDatabase(replace = Replace.NONE)
`replace=NONE` 으로 설정해주신 이유가 궁금합니다! 지금은 별도의 데이터 소스를 지정해주지 않아서 여전히 Any 와 같이 동작할 것 같아서요!! (제가 잘 몰라서 여쭤봅니다...😅)

2022-11-02 23:27 UTC, tco0427 commented on src/test/java/kitchenpos/ui/order/OrderRestControllerTest.java
> +    void 주문에_주문_항목이_존재하지_않으면_400() throws Exception {
400 응답에 대한 Controller 테스트를 Mocking 을 통해서 작성해주셨네요!!
바쁘신 와중에도 꼼꼼하게..👍👍

2022-11-02 23:27 UTC, tco0427 commented on src/main/java/kitchenpos/application/order/OrderService.java
> +        return orderDtoMapper.toOrderResponse(order);
단방향으로 잘 끊어내주셨는데, 2단계를 진행하며 간단해졌던 Service 가 굉장히 무거워진 느낌이 들어요..ㅠ
이전에는 "검증, 생성, 저장, 반환" 이 한 눈에 들어온 반면 지금은 어떤 일을 하는지 파악하기 힘들어진 것 같아요..
어떻게 개선해볼 수 있을까요..ㅠㅠ

2022-11-02 23:27 UTC, tco0427 commented on src/main/java/kitchenpos/domain/order/Order.java
> +
OrderStatus 를 Common 패키지에 둔 이유가 궁금합니다!

2022-11-02 23:27 UTC, tco0427 commented on src/main/java/kitchenpos/domain/table/OrderStatusRecord.java
> +    private OrderTable orderTable;
하나의 패키지(table) 안에 객체 사이에서도 최대한 연관관계를 제거해 객체간의 양방향 연관관계를 제거할 수 있으면 좋을 것 같아요!!
OrderstatusRecore 가 orderTable 을 알지 않아도 될 것 같습니다!
그렇다면 OrderTable 에서 일대달로 가져 update 쿼리가 나가는 사이드 이펙트가 있는데요! 어떻게 해결할 수 있을까요??
각각의 엔티티도 별도의 영속성이 관리되는 것이 아니라 하나의 영속성으로 관리되도록 값 컬렉션을 활용해보면 어떨까요?? (주문 id 와 orderStatus 를 값으로 가지는)

2022-11-03 00:30 UTC, Ohzzi commented on src/main/java/kitchenpos/exception/badrequest/AlreadyGroupedException.java
> +    }
사실 이 부분은 고민을 많이 했는데요, 도메인에서 던지지 않고 서비스 레이어에서 던지는 예외들도 분명히 있고, 서로 다른 도메인 컨텍스트 간에 호출해야 하는 예외들도 있기 때문에 좀 더 유연하게 호출하기 위해서 아예 패키지를 분리했습니다.

2022-11-03 00:32 UTC, Ohzzi commented on src/main/java/kitchenpos/application/menu/MenuGroupService.java
> +@Transactional(readOnly = true)
`@Transactional`이 없는 조회 메서드에서는 OSIV가 꺼져 있으면 지연 로딩을 사용할 수 없는 문제가 있더라고요. 물론 저는 `@BatchSize`를 사용하기도 하고, OSIV도 기본 설정대로 켜져 있기도 하지만 혹시 모를 버그를 대비해 선언해주었습니다.

2022-11-03 00:34 UTC, Ohzzi commented on src/main/resources/db/migration/V5__ADD_OrderStatusRecord.sql
> +);
실제 Order의 status와 불일치하게되면 버그가 나게 되겠네요 :) 이 부분은 배치 스케줄 처리든 다른 방식으로 정합성을 맞춰주는게 좋다고 생각합니다! Order의 status와 외래키를 걸지 않은 것은,
1. 외래키 자체가 성능이 좋지 못함
2. OrderStatusRecord가 Order를 알 필요가 없음
의 이유가 있을 것 같아요!

2022-11-03 00:35 UTC, Ohzzi commented on src/main/java/kitchenpos/domain/table/OrderStatusRecord.java
> +public class OrderStatusRecord implements Persistable<Long> {
인터페이스를 통해 의존성 방향을 역전시키는 것을 코드로 봐야 알 수 있을 것 같은데요 혹시 예시가 있나요??
일단 이렇게 중복되는 새 테이블들이 추가된 것은, 의존성을 끊어내면서도 거의 대부분의 validation 로직이 도메인 안으로 응집될 수 있도록 처리하기 위함이었습니다 :)

2022-11-03 00:36 UTC, Ohzzi commented on src/test/java/kitchenpos/RepositoryTest.java
> +@AutoConfigureTestDatabase(replace = Replace.NONE)
Any를 하게 되면 매번 새 데이터베이스를 생성하기 때문에 어차피 테스트 격리가 잘 되고 있는 입장에서 낭비라고 생각했습니다 :)

2022-11-03 00:36 UTC, Ohzzi commented on src/main/java/kitchenpos/application/order/OrderService.java
> +        return orderDtoMapper.toOrderResponse(order);
이 부분은 가독성 좋게 만들 수 있도록 고민해보겠습니다 :)

2022-11-03 00:37 UTC, Ohzzi commented on src/main/java/kitchenpos/domain/order/Order.java
> +
Order와 OrderStatusRecord 양쪽에서 사용하기 위함입니다! 우발적 중복이 아니냐고 볼 수도 있는데, 저는 이 부분들이 같은 상태라고 보기 때문에 의도적인 중복이라고 판단하고 common에 두어서 재활용할 수 있도록 했습니다 :)

2022-11-03 00:39 UTC, Ohzzi commented on src/main/java/kitchenpos/domain/table/OrderStatusRecord.java
> +    private OrderTable orderTable;
값 타입 컬렉션은 결정적인 문제가 있는데요, 식별자가 없다 보니 값을 수정할 때 데이터베이스에 `모든 값을 전부 delete하고 다시 수정된 값을 전부 insert한다`는 문제가 있습니다. 때문에 값 타입 컬렉션을 엔티티로 대체하는 것이 권장되기도 합니다 :)
객체지향적인 관점에서 봐서는 일대다 단방향 매핑을 하는 것이 맞지만, JPA를 많이 쓰던 입장에서 일대다 단방향은 선뜻 손이 나가지 않더라고요... 어차피 같은 컨텍스트 내에 있으니 부득이하게 양방향 매핑을 하더라도 큰 문제는 없을거라 생각했습니다!

2022-11-04 00:08 UTC, tco0427 commented on src/main/java/kitchenpos/application/menu/MenuGroupService.java
> +@Transactional(readOnly = true)
OSIV 가 꺼져있으면 `SimpleJpaRepository`에 걸린 `@Transactional` 에서만 트랜잭션이 걸려서 조회가 끝나고 나서는 지연로딩이 안되는군요!!

2022-11-04 00:12 UTC, tco0427 commented on src/main/java/kitchenpos/domain/table/OrderStatusRecord.java
> +public class OrderStatusRecord implements Persistable<Long> {
<img width="518" alt="스크린샷 2022-11-04 09 09 56" src="https://user-images.githubusercontent.com/57028386/199858107-2719da9f-9e12-4680-880e-2160637eebe4.png">
OrderTable 에서는 위와 같이 Order 를 알도록 두고, Order쪽에서 OrderTable 에 대한 의존을 다음과 같이 인터페이스로 끊어내볼 수 있을 것 같아요!!

<img width="692" alt="스크린샷 2022-11-04 09 10 12" src="https://user-images.githubusercontent.com/57028386/199858159-f40d64cd-6744-4115-a940-3a65f1a92bad.png">

그리고 Table 쪽에 그 구현체를 직접 두도록 해서 의존성 방향을 단방향으로 끊어내볼 수 있을 것 같아요!!

<img width="206" alt="스크린샷 2022-11-04 09 11 38" src="https://user-images.githubusercontent.com/57028386/199858207-793b238d-17aa-4fb0-8114-0ca52b575d93.png">

2022-11-04 00:15 UTC, tco0427 commented on src/main/java/kitchenpos/application/order/OrderService.java
> +        return orderDtoMapper.toOrderResponse(order);
굉장히 깔끔해졌네요!👍👍
다만, `createAndSaveOrder` 네이밍에서 두 가지 일을 한다는게 느껴져서 추후에 4단계 진행하신다면 조금 더 개선해볼 수는 있겟네요!!

2022-11-04 00:18 UTC, tco0427 commented on src/main/java/kitchenpos/domain/table/OrderStatusRecord.java
> +    private OrderTable orderTable;
맞습니다!!
저희 팀프로젝트에서도 해당 문제를 겪었었는데요, 해결 방법으로는 `@ElementCollection` 에서 다쪽에 `@Column(nullable = false)` 를 주고 컬렉션을 `Set` 을 사용해서 유니크하면서 null이 포함되지 않음을 명시해주면 `모든 값을 전부 delete 하고 다시 수정된 값을 전부 insert한다` 를 해결할 수 있었습니다!!
저는 개인적으로는 JPA 매핑을 위한 불필요한 양방향 관계보다는 객체지향적으로 설계하는것이 유지보수에도 좋다고 생각해서 해당 방법으로 프로젝트를 진행하고 있지만 오찌가 말씀해주신 것처럼 확실히 불편한 부분(?) 혹은 한계는 있는 것 같아요ㅠ.ㅠ

2022-11-04 00:19 UTC, tco0427 approved these changes
안녕하세요 오찌!!
바쁘실텐데 꼼꼼하게 피드백 반영해주셨네요!!
오프라인에서도 토론하시는 모습을 보면서 깊게 고민하시는게 느껴졌습니다!
3단계 고생많으셨어요~_~

2022-11-04 00:19 UTC, merged