[레거시 코드 리팩터링 - 3단계] 파랑(이하은) 미션 제출합니다.
woowacourse/jwp-refactoring pull request #372
Opened 2022-11-02 12:38 UTC by summerlunaa

레넌 안녕하세요!

도메인 객체 간의 의존성과 서비스 계층에서의 의존성을 고려하여 리팩토링 해보았습니다. 아래 그림을 참고해서 봐주시면 될 것 같아요!
아직은 도메인 별로 패키지를 나누지 않아서 큰 의미가 없을 수도 있지만 4단계를 고려하여 양방향 의존을 Validator를 이용하여 끊어냈습니다. 리뷰 잘부탁드립니다!

![image](https://user-images.githubusercontent.com/77425729/199491332-9d5208a5-ce72-4886-a41e-5a2254f86966.png)

각 서비스에서 의존하는 레포지토리의 의존 방향
![image](https://user-images.githubusercontent.com/77425729/199491379-63268664-df67-481a-a24c-8ed709954e39.png)

2022-11-04 04:46 UTC, brorae requested changes
안녕하세요 파랑~
3단계도 잘 구현해주셨네요.
그림까지 그려주셔서 이해하기 편했습니다 !
간단하게 궁금한 부분 몇가지 커멘트 남겨보았어요. 

수고하셨습니다~!

2022-11-04 04:46 UTC, brorae commented on src/main/java/kitchenpos/application/TableService.java
> -        savedOrderTable.changeEmpty(request.isEmpty());
validator를 잘 활용하셨네요 !!

2022-11-04 04:46 UTC, brorae commented on src/main/java/kitchenpos/application/TableService.java
> +        List<Long> orderTableIds = request.getOrderTables().stream()
TableGroupService를 지우고 로직을 여기로 옮기신 이유가 있을까요??

2022-11-04 04:46 UTC, brorae commented on src/main/resources/db/migration/V3__add_columns_order_line_item.sql
> +    ADD menu_price DECIMAL(19, 2) NOT NULL;
👍👍👍👍

2022-11-04 04:46 UTC, brorae commented on src/test/java/kitchenpos/common/FakeOrderTableValidator.java
> +    }
테스트에서는 OrderStatus를 확인하지 않는 이유가 있을까요?

2022-11-04 04:46 UTC, brorae commented on src/test/java/kitchenpos/common/FakeOrderTableValidator.java
> +    }
여기서도 로직이 없는 이유가 있을까용?

2022-11-04 04:46 UTC, brorae commented on src/main/java/kitchenpos/domain/menu/Menu.java
> +    private Long menuGroupId;
연관관계를 끊으시는 기준이 있을까요?? 개인적으로 궁금해서 여쭤봅니다 😄

2022-11-05 16:03 UTC, summerlunaa commented on src/main/java/kitchenpos/application/TableService.java
> +        List<Long> orderTableIds = request.getOrderTables().stream()
Table과 TableGroup이 강하게 결합되어 있다고 생각했습니다! Table은 TableGroup에 관한 로직을 가지고 TableGroup은 Table에 관한 로직을 가져서요. 둘을 나누고 Validator, Event 등으로 의존성을 단방향으로 풀어낼 수도 있겠지만 이 경우엔 TableGroup이 Table의 부가적인 정보처럼 느껴져서 양방향을 그대로 두고 Table이라는 이름으로 합치는 게 더 낫다고 생각했습니다.

2022-11-05 16:04 UTC, summerlunaa commented on src/test/java/kitchenpos/common/FakeOrderTableValidator.java
> +    }
나머지 로직은 레포지토리를 필요로 해서 도메인 테스트에서 springboottest를 사용하지 않으려면 레포를 넣을 수가 없었네요 ㅠ
실제 validator로직은 서비스에서 테스트하고 있습니다. 더 좋은 의견 있으면 남겨주세요!

2022-11-05 16:06 UTC, summerlunaa commented on src/main/java/kitchenpos/domain/menu/Menu.java
> +    private Long menuGroupId;
연관관계가 조회 외에는 필요 없는 경우엔 id로 간접참조하도록 했습니다.

2022-11-07 04:11 UTC, brorae commented on src/main/java/kitchenpos/domain/menu/Menu.java
> +    private Long menuGroupId;
저도 이번에 미션에서 처음으로 시도해보았는데요. 저는 생명주기가 같으면 연관관계를 그대로 두었던 것 같아요 :)

2022-11-08 07:28 UTC, brorae approved these changes
커멘트 확인했습니다 수고하셨어요 !

2022-11-08 07:28 UTC, merged