[레거시 코드 리팩터링 - 3단계] 아리(양유림) 미션 제출합니다.
woowacourse/jwp-refactoring pull request #376
Opened 2022-11-02 13:57 UTC by ulimy

안녕하세요 후니! 부끄러운 코드를 제출하게 된 아리입니다..
이상한 시도를 잔뜩 해보다가 결국 Validator와 Event를 이용하는 방향으로 리팩토링 했습니다.
메뉴 정보가 변경되더라도 주문 항목이 변경되지 않도록 OrderLineItem 클래스 및 데이터베이스도 변경했습니다!
기존에 존재하던 데이터는 그대로 유지될 수 있도록 ddl을 구성했어요.

코드가 정말.. 정말 별로이니.. 화가 나신다면 언제든 찾아와주세요^^..............

2022-11-05 01:37 UTC, jayjaehunchoi requested changes
아리!! 전반적으로 잘 짜주신것 같아요

의존성 분리에 고민이 많으셨을 것 같습니다!!
간단하게 제 의견 하나 남겼으니 확인해보시고 답글 주시면 머지하겠습니다!!

바쁜와중에 수고많으셨어요 ㅎㅎ

2022-11-05 01:37 UTC, jayjaehunchoi commented on src/main/java/kitchenpos/menu/domain/Menu.java
> +        validator.validateCreateMenu(name, price, menuGroupId,menuProducts);
사실 저는 주생성자에 validator를 추가하기 보다는 도메인 용어에 맞게 메서드를 생성하여 validator 를 두는 편입니당!
만약 그게 생성과 관련한 것이라면 주 생성자는 private으로 닫아두는 편인 것 같아요. 

그냥 하나의 의견이고 이 생각에 대한 고민만 한 번 해보셔용

2022-11-05 01:37 UTC, jayjaehunchoi commented on src/main/java/kitchenpos/menu/domain/MenuGroup.java
> +        if (o == null || Hibernate.getClass(this) != Hibernate.getClass(o))
오 이건 뭔가요?

2022-11-05 01:37 UTC, jayjaehunchoi commented on src/main/java/kitchenpos/menu/domain/MenuGroup.java
> +        return getClass().hashCode();
오오 신기하네요, equals와 hashCode에 어떤 이유로 코드와 같이 적용한것이죠? 궁금하네요!!

2022-11-05 01:37 UTC, jayjaehunchoi commented on src/main/java/kitchenpos/menu/domain/MenuValidator.java
> +public class MenuValidator {
이 클래스 덕분에 메뉴는 도메인 만으로 안전한 객체가 된 것 같아요 굿!

2022-11-05 01:37 UTC, jayjaehunchoi commented on src/main/java/kitchenpos/menu/domain/MenuValidator.java
> +    public MenuValidator(MenuGroupRepository menuGroupRepository, ProductRepository productRepository) {
final 키워드 추가해주세영

2022-11-05 01:37 UTC, jayjaehunchoi commented on src/main/java/kitchenpos/order/domain/OrderLineItem.java
> +    private BigDecimal menuPrice;
최고입니다!!! 이제 주문서를 보면 메뉴의 가격 변동이 있더라도 과거 주문했던 내용들이 기록되겠네요.

2022-11-07 13:07 UTC, ulimy commented on src/main/java/kitchenpos/menu/domain/Menu.java
> +        validator.validateCreateMenu(name, price, menuGroupId,menuProducts);
흐음... 생성에 관련된 것이라면 정적 팩토리 메서드를 활용해서 적절한 이름을 짓고 주생성자를 닫아두는 방법도 있겠네요...! 조금만 더 고민해보겠습니다...!!

2022-11-07 13:10 UTC, ulimy commented on src/main/java/kitchenpos/menu/domain/MenuGroup.java
> +        if (o == null || Hibernate.getClass(this) != Hibernate.getClass(o))
JPA를 이용하면서 equals & hascode를 재정의할 경우 프록시 관련 문제가 발생할 수 있습니다. 프록시 객체는 getClass 결과값이 다르기 때문이에요! Hibernate.getClass()를 이용하면 해당 객체가 프록시 객체인 경우 원본 객체의 클래스를 반환함으로써 해당 문제를 예방할 수 있습니다! 혹시 맥북을 사용하고 계씨다면 command + n 을 누르시고 JPA Utilities를 눌러보시면 자동생성 가능합니다!

2022-11-07 13:10 UTC, ulimy commented on src/main/java/kitchenpos/menu/domain/MenuGroup.java
> +        return getClass().hashCode();
https://github.com/woowacourse/jwp-refactoring/pull/376#discussion_r1015402679

여기와 같은 답변이 될 것 같아요!

2022-11-07 13:10 UTC, ulimy commented on src/main/java/kitchenpos/menu/domain/MenuValidator.java
> +public class MenuValidator {
👍

2022-11-07 13:14 UTC, ulimy commented on src/main/java/kitchenpos/menu/domain/MenuValidator.java
> +    public MenuValidator(MenuGroupRepository menuGroupRepository, ProductRepository productRepository) {
넵! 여기 뿐만 아니라 전체적으로 확인하여 추가했습니다~!

2022-11-07 13:14 UTC, ulimy commented on src/main/resources/db/migration/V3__change_order_line_item.sql
> +ALTER TABLE order_line_item DROP menu_id;
👍

2022-11-07 13:14 UTC, ulimy commented on src/main/java/kitchenpos/order/domain/OrderLineItem.java
> +    private BigDecimal menuPrice;
👍

2022-11-08 01:58 UTC, jayjaehunchoi commented on src/main/java/kitchenpos/menu/domain/MenuGroup.java
> +        if (o == null || Hibernate.getClass(this) != Hibernate.getClass(o))
proxy는 MenuGroup의 상속이고, 이럴 경우 instance of를 사용하면 문제가 없을 것 같은데요?
하지만 JPA를 사용할 때 충분히 활용성이 있는 코드네요!

2022-11-08 02:00 UTC, jayjaehunchoi approved these changes
아리 수정한 내용 확인했습니다.

4레벨 미션하시느라 고생 많았습니다. 취업 준비로 많이 힘들었을텐데 열심히 미션을 수행해주셔서 저도 많이 배울 수 있었습니다!

4단계 멀티 모듈 적용은 선택이니 해도, 안해도 좋지만 적용하여 리뷰 요청 주신다면 언제든 리뷰 남기겠습니다. 그리고 바쁘더라도 멀티모듈을 한 번이라도 고민하고 적용해보면 나중에 정말 도움이 될 것 같아요!!

수고 많으셨습니다.

2022-11-08 02:00 UTC, merged