[레거시 코드 리팩터링 - 3단계] 정(정진우) 미션 제출합니다.
woowacourse/jwp-refactoring pull request #406
Opened 2022-11-03 08:52 UTC by bugoverdose

안녕하심까. 정임다.

OrderItem 생성시 Menu를 직접적으로 바라보지 않고, 해당 시점의 Menu와 같은 데이터로 이루어진 최신 MenuHistory 정보를 바라보도록 하였습니다. Menu의 데이터가 변하더라도 MenuHistory 데이터는 동일하므로 요구사항을 충족시킬 수 있습니다. 

처음에는 MenuHistory 개념을 새로 도입하지 않고, Menu가 수정될 때 orderItem이 가리키는 메뉴 데이터를 수정하지 않고, 새로운 메뉴 정보를 저장하는 방식으로 메뉴 수정 로직을 수정하고자 했으나, 애초에 서비스에 메뉴 수정 로직이 존재하지 않더군요.

감사함다.

2022-11-03 14:52 UTC, yeongunheo requested changes
안녕하세요 정! 아키입니다.

MenuHistory를 만들어서 요구사항을 만족해주셨네요.
몇가지 궁금한 점 코멘트 달았는데 확인부탁드려요!

추가로, 레이어드 아키텍처 구조를 유지하면서 도메인 내 패키지만 분리해주셨는데
kitchenpos 패키지를 도메인(menu, order, table)로 나눠보는건 어떨까요?

도메인별로 나누게되면 import를 통해서 패키지간의 의존관계를 쉽게 파악할 수 있다는 장점이 있더라구요.
이 부분에 대해서 이야기해보면 좋을것같아요!

2022-11-03 14:52 UTC, yeongunheo commented on src/main/java/kitchenpos/domain/menu/MenuHistory.java
> +    private Menu menu;
MenuHistory가 Menu를 알고 있네요!

이렇게 되면 OrderLineItem이 MenuHistory를 간접참조로 알게 되고, MenuHistory가 Menu를 알게되면서 Order와 Menu의 의존관계가 발생하다고 생각하는데, 이에대해 정은 어떻게 생각하시나요?

전 3단계 미션을 처음 시작했을 때 Order와 Menu의 의존관계를 끊어야겠다고 생각했어요!
Order와 Menu의 생성시점이 달라 의존관계를 끊어주는게 필요하다고 생각했었습니다.
그래서 OrderedMenu라는 임베디드타입을 만들어서 OrderLineItem이 menuId를 갖지 않도록 만들었습니다.

![image](https://user-images.githubusercontent.com/52141636/199752497-1f422c63-027c-4b7f-8059-fcd8fc920194.png)

2022-11-03 14:52 UTC, yeongunheo commented on src/main/java/kitchenpos/application/dto/response/MenuDto.java
>      }
dto가 여러 군데에서 재활용되고있네요.

전 같은 응답을 하더라도 각 요청, 응답값마다 dto를 새로 만들어주는 편이예요!
프로젝트를 하면서 느낀건데 dto는 자주 바뀌어서 재활용하게되면 오히려 변경에 취약해지더라구요.

정이 dto를 재활용하면서 겪었던 불편함은 없으셨나요?

2022-11-03 14:52 UTC, yeongunheo commented on src/main/resources/db/migration/V3.1__Alter_order_line_item_fk_to_menu_history.sql
> +        FOREIGN KEY (menu_history_id) REFERENCES menu_history (id);
3.0 / 3.1로 나눈 기준은 무엇인가요?

2022-11-04 01:18 UTC, bugoverdose commented on src/main/java/kitchenpos/application/dto/response/MenuDto.java
>      }
저도 레이어 및 맥락에 따라 DTO를 다양하게 작성하는 편이에요. 공교롭게도 필드들이 동일하더라도 다른 CRUD 작업이면 별도로 클래스를 만들고요.

다만, DTO 클래스가 너무 많으면 DTO 변환 로직이 더러워져서 무지성으로 DTO를 만들지는 않고 균형을 유지하려고 하고 있어요.

2022-11-04 01:41 UTC, bugoverdose commented on src/main/java/kitchenpos/domain/menu/MenuHistory.java
> +    private Menu menu;
아 저는 Order가 Menu를 알아도 괜찮다고 생각했어요. 각 주문은 선택한 메뉴들로 구성되서요.

2022-11-04 01:44 UTC, bugoverdose commented
> 안녕하세요 정! 아키입니다.
> 
> MenuHistory를 만들어서 요구사항을 만족해주셨네요. 몇가지 궁금한 점 코멘트 달았는데 확인부탁드려요!
> 
> 추가로, 레이어드 아키텍처 구조를 유지하면서 도메인 내 패키지만 분리해주셨는데 kitchenpos 패키지를 도메인(menu, order, table)로 나눠보는건 어떨까요?
> 
> 도메인별로 나누게되면 import를 통해서 패키지간의 의존관계를 쉽게 파악할 수 있다는 장점이 있더라구요. 이 부분에 대해서 이야기해보면 좋을것같아요!

패키지 구분의 경우 저도 우테코 팀플에서는 도메인별로 패키지를 구분했는데요. 해당 미션의 경우 4단계에서 ui -> application -> repository로 멀티 모듈을 적용하는 것을 가정하고 현재 패키지 구조를 구성했어요.

2022-11-04 02:17 UTC, yeongunheo approved these changes
안녕하세요 정!

패키지 구조가 저랑 달라서 어떤 고민을 통해 이러한 설계가 나왔는지 궁금했는데요,
4단계 멀티모듈을 염두에 두고 설계하셨던거군요!

의존 관계도 클래스 간에 단방향이 되도록 잘 설계해주셔서 이번 단계는 여기서 머지하겠습니다!
다음 단계도 화이팅입니다!

2022-11-04 02:17 UTC, merged