[레거시 코드 리팩터링 - 3단계] 필즈(조성우) 미션 제출합니다.
woowacourse/jwp-refactoring pull request #407
Opened 2022-11-03 09:29 UTC by progress0407

### 그린론 ~.. 안녕하세요!

2단계와 달라진 점은 크게 없어요!

아래와 같이 달라졌답니다...

### QueryDsl 제거

- 리뷰하기 불편한 점이 있기 때문에 다시 제거하여 Spring Data JPA 기반으로 변경했습니다.

### Order와 Menu 도메인 단방향 분리

![image](https://user-images.githubusercontent.com/66164361/199684006-161def6c-da2d-4c1f-9cf4-8082a9839347.png)

- 이전 PR에서 본래 분리되어 있기는 헀으나, menu_name, menu_price 등의 컬럼 정보를 분리한 이후에 의존성을 재확인했어요
- 이렇게 됨으로써 패키지 단위로 멀티모듈을 분리할 수 있을 것 같아요. 
- 그러나, `MenuRepository` 정보를 `Order` 영역이 사용하고 있어서 DB도 분리된 MSA를 생각한다면 의존관계를 끊어야 하는데 이부분은 어떻게 해야할 지 모르겠네요 ㅠㅠ
  - Menu영역에 API를 만들어서 단일조회로 가져오면 될 것 같긴 한데... 혼자만의 고민으로 해도 될 것 같아요

### `Order`와 `Menu`를 분리한 이유

멀티모듈 나누는 것과 동일 맥락인지는 모르겠지만, MSA 영상 몇 가지를 보니 보통 변경을 기준으로 도메인 영역을 나누는 것 같더라구요.
이때 말하는 변경의 기준이 되는 단위는 아마도 비즈니스 요구사항과 관련이 많지 않을까 싶었어요,
서비스 이용자를 나눠보면 상품을 등록하는 가게 사장님, 가게를 이용하는 손님이 있을 것 같아요.
따라서 이 두 역할에 따라 도메인을 나누어 보았어요! (쉽기도 하고 ... ㅠㅠ)

2022-11-07 03:09 UTC, jaejae-yoo requested changes
필즈 안녕하세요! 
이전 단계에서 이미 의존성에 대해 고민하고 적용하신 것 같아서 변경 사항이 많이 없네요 ㅎㅎ 역시 👍
질문 위주로 코멘트 남겨놨어요! 확인 부탁드려요 ~ :D

2022-11-07 03:09 UTC, jaejae-yoo commented on src/main/java/kitchenpos/order/domain/OrderLineItem.java
>      private Long menuId;
menu_id가 남아있는 이유는 response 값을 유지하기 위함일까요?
만약 메뉴의 이름과 가격이 변동되었는데, 개발자가 모르고 menuId를 사용해서 join해서 값을 가지고 오면 주문 항목에 있는 menu 정보와 맞지 않는 문제가 있을 수 있을 것 같아요. 이에 대해 어떻게 생각하시는지 궁금해요!

2022-11-07 11:59 UTC, progress0407 commented on src/main/java/kitchenpos/order/specification/TableGroupSpecification.java
>          if (requestOrderTables.size() != savedTables.size()) {
DDD에서 붙인 이름이에요 ㅎㅎ

2022-11-08 03:57 UTC, jaejae-yoo approved these changes
필즈 안녕하세요 ~
레벨 4 미션 하느라 고생 많으셨어요! 코드 리뷰와 이야기하면서 많이 배울 수 있었어요!
남은 기간도 화이팅하세요! 🙌

2022-11-08 03:57 UTC, merged