[레거시 코드 리팩터링 - 1단계] 무민(박무현) 미션 제출합니다
woowacourse/jwp-refactoring pull request #468
Opened 2023-10-11 19:41 UTC by parkmuhyeun

안녕하세요 🦖디🦕노🦖 
마지막 미션 함께 하게되어서 기쁘네요.

이번에 진짜 테스트 짜다가 돌아갈뻔 했습니다.. 무려 80개나 작성되었는데.. 죄송합니다 ㅋㅋㅋㅋ
저는 classist라 실제로 테스트 하는 걸 선호하는데요 이번에 mockist로 갈아탈 뻔 했습니다.

원래는 다 짜고 나서 한번 더 리팩터링 하려했는데 테스트 80개로 심신미약상태가 되어서 우선 한번 제출하겠습니다.. 디노는 테스트를 어떻게 짰는지도 궁금하네요!?

마지막 미션 잘 부탁드립니다.

2023-10-13 07:57 UTC, jjongwa requested changes
안녕하세요 민무 극락다이노입니다.

그거 아시나요 이번 미션 리뷰이-리뷰어가 
디노 -> 민무 -> 하디 -> 디노 레전드 트라이앵글 리뷰입니다. 하하하

총 79개의 테스트.. 상당한 노력을 들이셨군요..

최대한 꼼꼼하게 리뷰하려 노력했지만 양이 양이다보니 
미처 캐치하지 못하고 넘어가버린 부분이 있을까 걱정이네요..

전체적으로 꼼꼼하게 작성해 주셔서 리뷰는 많이 없구요..!
리뷰 사항에 대해 간단히 코멘트만 작성해 주시면 바로 머지 하겠습니다.!

그리고 올려주신 테이블 관계에서 

OrderTable과 Order
OrderLineItem과 Menu
Menu Product와 Product

부분에 대해서 다시 한 번 확인 부탁드리면 감사하겠습니다.!

2023-10-13 07:57 UTC, jjongwa commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +        final Menu menu = new Menu("디노 세트", new BigDecimal(8000),
맛있네요..

2023-10-13 07:57 UTC, jjongwa commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +
price가 null 이 아닌 것 같습니닷

2023-10-13 07:57 UTC, jjongwa commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +
두 줄

2023-10-13 07:57 UTC, jjongwa commented on README.md
> +    - [x] 메뉴_가격이_메뉴_상품의_가격_합계를_초과하면_예외_처리
여기는 테스트 메서드의 이름을 그대로 가져오신것 같네요ㅎㅎ

2023-10-13 07:57 UTC, jjongwa commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +    }
해당 테스트는 MenuServiceTest에 추기적으로 menu가 save되는 로직의 수에 따라 변경될 것 같은데,
이 부분에 대해서 어떻게 생각하시나요?

2023-10-13 07:57 UTC, jjongwa commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +
현재 서비스에서 분기에 따라 모두 같은 IllegalArgumenetException을 반환하고 있는데요.

이러한 테스트 로직들이 모두 의도한 부분에서 예외를 발생하고 있는지 확인할 수 있는 방법이 있을까요?

제가 생각했을때 이러한 구조에서의 단점은 
원래는 A 분기점에서 예외를 터트리는 테스트였는데
개발자가 실수로 테스트가 A분기점을 통과하고 그 다음 B 분기점을 통과하도록 로직을 작성해 버렸지만,

B 분기점에서 같은 Exception을 반환하기 때문에 해당 부분을 캐치하지 못하고 넘어갔다가 
실제 프로덕션 환경에서 A분기점에서 발생하는 예외를 마주하게 되는 케이스가 발생할 수 있다는 점인데요.
이를 막기 위해선 어떤 조치가 필요할까요?

2023-10-13 07:57 UTC, jjongwa commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +    }
savedOrder를
위에서는  Service를 통해 저장하고,
아래에서는 Dao의 로직을 통해 저장하는데,

이렇게 차이를 둔 이유가 무엇인가요?

2023-10-13 07:57 UTC, jjongwa commented on src/test/java/kitchenpos/application/ProductServiceTest.java
> +class ProductServiceTest extends ServiceTest {
```
@DisplayNameGeneration(DisplayNameGenerator.ReplaceUnderscores.class)
@SuppressWarnings("NonAsciiCharacters")
```

이게 ServiceTest에 선언되어 있는데 소나린트가 파악을 못하고
각 테스트 위에 붙여줘야 경고를 없애주네요..?

<img width="458" alt="image" src="https://github.com/woowacourse/jwp-refactoring/assets/77482065/46ffcfb0-4700-4166-9139-9e5f2e123f60">

<img width="576" alt="image" src="https://github.com/woowacourse/jwp-refactoring/assets/77482065/b92ba5a5-d54d-4fd9-bffc-f9982268f04b">

2023-10-13 07:57 UTC, jjongwa commented on README.md
> +  - [x] 주문 테이블을 비울 수 있다.
서비스 로직을 보면 인자로 받는 주문 테이블의 empty 필드에 true와 false가 모두 올 수 있어서,
테이블을 비울 수 있다 보다는 
테이블의 빈 상태 여부를 변경할 수 있다 느낌이 더 강하지 않을까 싶습니다.!

2023-10-13 07:57 UTC, jjongwa commented on build.gradle
> +    testImplementation 'io.rest-assured:rest-assured:4.5.1'
ohohoh.. 컨트롤러 통합 테스트가 시작되는군요..

2023-10-13 07:57 UTC, jjongwa commented on src/test/java/kitchenpos/dao/JdbcTemplateMenuDaoTest.java
> +        final Menu menu = new Menu("디노통구이", new BigDecimal(20000), 2L, null);
무섭네요 민무.. 🍗🍗

2023-10-13 07:57 UTC, jjongwa commented on src/test/java/kitchenpos/dao/JdbcTemplateMenuGroupDaoTest.java
> +        assertThat(expect).isEqualTo(true);
isTrue() 어떨까요우?

2023-10-13 07:57 UTC, jjongwa commented on src/test/java/kitchenpos/dao/JdbcTemplateMenuGroupDaoTest.java
> +    }
size 4는 어디서 나오는 건가요?
다른 클래스에서 insert한 MenuGroup도 포함되는 상황인가요?

2023-10-13 07:57 UTC, jjongwa commented on src/test/java/kitchenpos/dao/JdbcTemplateOrderLineItemDaoTest.java
> +        assertThat(result).hasSize(0);
isEmpty() 어떤가요우?

2023-10-13 07:57 UTC, jjongwa commented on src/test/java/kitchenpos/ui/MenuGroupRestControllerTest.java
> +                .body(new MenuGroup("디노 극락 메뉴"))
후 드디어 여기까지 왔군요 극락갈 것 같습니다

2023-10-15 16:07 UTC, parkmuhyeun commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +        final Menu menu = new Menu("디노 세트", new BigDecimal(8000),
8000원 입금 부탁드립니다.

2023-10-15 16:11 UTC, parkmuhyeun commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +
그렇게 되는 원인이 다 같은 IllegalArgumentException인데 심지어 던지는 예외 메시지도 없기 때문이라고 생각합니다.

방지하려면 예외메시지를 추가해주거나 커스텀 예외를 사용할 거 같습니다.
만약 모킹을 했다면 verify를 이용해서 다음 메서드가 실행 안 된다고 추가해줄 수도 있을 거 같네요!

2023-10-15 16:18 UTC, parkmuhyeun commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +    }
모두 다 dao를 통해서 통일성 줬는데 저기는 실수로 놓친거 같아용. 꼼꼼디노 👍🏻

2023-10-15 16:21 UTC, parkmuhyeun commented on src/test/java/kitchenpos/application/ProductServiceTest.java
> +class ProductServiceTest extends ServiceTest {
오잉 왜 그러죠

2023-10-15 16:22 UTC, parkmuhyeun commented on build.gradle
> +    testImplementation 'io.rest-assured:rest-assured:4.5.1'
디노의 절망감이 보이는 문장이군요..

2023-10-15 16:24 UTC, parkmuhyeun commented on README.md
> +  - [x] 주문 테이블을 비울 수 있다.
그러게요 로직은 둘 다 세팅할 수 있어서 그게 맞겠네요
왜 이름이 changeEmpty() 일까요...?

변수명 역시 엄청 중요하다는 걸 깨닫고 갑니다..

2023-10-15 16:27 UTC, parkmuhyeun commented on src/test/java/kitchenpos/dao/JdbcTemplateMenuDaoTest.java
> +        final Menu menu = new Menu("디노통구이", new BigDecimal(20000), 2L, null);
조심하세요 🍖

2023-10-15 16:28 UTC, parkmuhyeun commented on src/test/java/kitchenpos/ui/MenuGroupRestControllerTest.java
> +                .body(new MenuGroup("디노 극락 메뉴"))
디노형 사랑해

2023-10-15 16:33 UTC, parkmuhyeun commented
>그리고 올려주신 테이블 관계에서
>
>OrderTable과 Order
>OrderLineItem과 Menu
>Menu Product와 Product
>
>부분에 대해서 다시 한 번 확인 부탁드리면 감사하겠습니다.!

혹시 어떤 부분이 잘못되었을까요!? 

해당 관계가 각각
1:N
N:1
N:1
맞지 않나요!!?

2023-10-15 16:51 UTC, parkmuhyeun commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +    }
통합테스트로 해버리니깐 db.migration의 V2__Insert_default_data의 영향을 받아서 처음에 데이터가 주입되더라구요.(설정을 never로 바꿔도 안 막아지네요.. 혹시 제외하는 방법을 아시나요?)

테스트를 짜면서 해당 파일에 의존하는 거 같아서 마음이 너무 찝찝했습니다..

하지만, 나중에 사용할 거 같아서 해당 파일을 삭제는 안 했습니다.
그래서 현재 list 로직과 관련된 테스트는 해당 데이터의 영향을 받고 있습니다.

dao 테스트 같은 경우 2단계 때 JPA로 이전하게 되면 삭제 될 거같아서 상관없을 것 같고
Service 같은 경우 현재 @Transactional을 이용해서 데이터 리셋을 시키고 있는데 truncate.sql을 이용해서 메서드 시작하기 전에 초기화 하도록 바꿨습니다!

2023-10-15 16:51 UTC, parkmuhyeun commented on src/test/java/kitchenpos/dao/JdbcTemplateMenuGroupDaoTest.java
> +    }
해당 [Comment](https://github.com/woowacourse/jwp-refactoring/pull/468#discussion_r1359911535) 참고 부탁드립니다!

2023-10-16 02:11 UTC, jjongwa commented
어어어 민무 제가 헛걸 봤나봐요 민무가 적어놓은거 맞습니다

2023-10-16 02:11 UTC, jjongwa approved these changes
코멘트 반영해 주셔서 감사합니다 민무
2단계로 고고고고고고

2023-10-16 02:11 UTC, merged