[레거시 코드 리팩터링 - 1단계] 하디(전동혁) 미션 제출합니다.
woowacourse/jwp-refactoring pull request #476
Opened 2023-10-12 03:53 UTC by jundonghyuk

안녕하세요 무민 반가워요 하디입니다 !

연휴 잘 보내셨나요 ?

1단계에서는 리드미 작성과 테스트코드 작성을 해보았습니다.

프로덕션 코드는 하나도 건들지 않았어요. 그로 인해 세터를 사용해서 테스트코드가 조금 지저분해보일 수 있을 것 같아요 !

이번에 모키토를 사용해서 테스트하였는데요, 느낀점은 너무 테스트코드가 프로덕션코드의 구현을 디테일하게 알고있는것같아요.

만약 프로덕션 코드내 메서드 호출 순서나 구현 방식이 변경되게 되면 모킹을 사용한 테스트도 다 바뀌어야 될 것 같은데 이에 대해 어떻게 생각하시

는지 궁금합니다 ! 잘 부탁드려요 ㅇ_ㅇ!

2023-10-13 19:12 UTC, parkmuhyeun reviewed
안녕하세요 하디~
레벨2때 뵙고 못뵌거 같네요.
스탬프크러쉬 요즘 핫하더라구요 🎇멋있습니다.

1단계 테스트코드 짜시느라 너무 고생 하셨습니다. 👍🏻
대량의 테스트 코드라 세부적인 리뷰보단 전체적으로 적용해볼만한 리뷰 남겼습니다!

> 만약 프로덕션 코드내 메서드 호출 순서나 구현 방식이 변경되게 되면 모킹을 사용한 테스트도 다 바뀌어야 될 것 같은데 이에 대해 어떻게 생각하시는지 궁금합니다 !

목을 이용해서 테스트해보시고 느낀점을 잘 표현해주신 것 같아요. 목이나 스텁을 사용한다면 다음과 같은 단점이 존재하는데요.
- 실제와 다른 방식으로 동작되도록 설정되면 실제적이지 않은 테스트를 만들 수 있다.
- 테스트가 구현 세부 정보에 밀접하게 결합하여 리팩터링이 어려워질 수 있다.

그래서 저는 만약 모킹해서 했다면 이 단점들을 최소화 하기 위해 페이크를 사용했을 것 같습니다! (근데 저는 통합테스트로 하긴 했씁니다ㅋㅋㅋ)

2023-10-13 19:12 UTC, parkmuhyeun commented on img.png
오오 ERD까지 👍🏻

2023-10-13 19:12 UTC, parkmuhyeun commented on src/test/java/kitchenpos/application/MenuGroupServiceTest.java
> +    void 메뉴그룹을_추가할_때_이름이_공백일_수_있다() {
혹시 이 테스트는 어떠한 의도로 작성한지 궁금합니다! 공백인 메뉴그룹이 있나요!?

2023-10-13 19:12 UTC, parkmuhyeun commented on src/test/java/kitchenpos/application/MenuGroupServiceTest.java
> +@ExtendWith(MockitoExtension.class)
@DisplayNameGeneration(DisplayNameGenerator.ReplaceUnderscores.class) 도 추가해주면 가독성에 더 좋을 것 같아요.

그리고 추가적으로 요런 공통 애노테이션들을 하나씩 추가하거나 제거할 때마다 전체 서비스 테스트를 수정해줘야되니 하나의 상위 클래스를 만들어 상속해보는 건 어떨까요!?

2023-10-13 19:12 UTC, parkmuhyeun commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +    }
@BeforeEach로 데이터들을 셋팅하게 되면 어떤 사이드 이펙드들이 있을까요!?

2023-10-13 19:12 UTC, parkmuhyeun commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +    }
MenuService는 then, should가 있었는데 이쪽은 왜 없는지 궁금합니다!

2023-10-13 19:12 UTC, parkmuhyeun commented on src/test/java/kitchenpos/application/TableGroupServiceTest.java
> +                                Arrays.asList(OrderStatus.COOKING.name(), OrderStatus.MEAL.name())
@EnumSource 한번 써보시는 건 어떤가요!?

2023-10-13 19:12 UTC, parkmuhyeun commented on src/test/java/kitchenpos/application/TableGroupServiceTest.java
> +        // given
테스트를 파악하기가 힘든 것 같은데 한번 개선 해볼 수 있을까요??

2023-10-13 19:12 UTC, parkmuhyeun commented on src/test/java/kitchenpos/application/MenuGroupServiceTest.java
> +        Assertions.assertThat(actual).usingRecursiveComparison().isEqualTo(expected);
usingRecursiveComparison() 👍🏻

2023-10-13 19:15 UTC, parkmuhyeun requested changes
RC 재요청

2023-10-15 15:12 UTC, jundonghyuk commented on src/test/java/kitchenpos/application/MenuGroupServiceTest.java
> +    void 메뉴그룹을_추가할_때_이름이_공백일_수_있다() {
현재 로직은 메뉴그룹을 추가할 때 별다른 검증이 없는 것으로 보여요 !

후에 검증로직이 추가된다면 해당 테스트는 바꿔야할 테스트가 됩니다. 

즉 이전까지는 공백일 수 있었다는 것으로 이로 인해 다른 부분까지 신경써야할 일은 없는지 체크해보라는 경각심을 주는 테스트 입니다..ㅋㅋ

2023-10-16 03:42 UTC, jundonghyuk commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +    }
다른 테스트 메서드에서는 안쓸 때도 계속 실행되는 단점이 있는 것 같습니다.

혹시 다른 사이드 이펙트가 있을까요 ?

2023-10-16 04:02 UTC, jundonghyuk commented on src/test/java/kitchenpos/application/TableGroupServiceTest.java
> +                                Arrays.asList(OrderStatus.COOKING.name(), OrderStatus.MEAL.name())
프로덕션 코드에서 `COOKING,MEAL`모두 인자로 넘겨주고 있어 모킹을 할 때 두 개 모두 넘겨주어야 하는 것으로 생각했는데,

어떤식으로 `@EnumSource`를 써볼 수 있을까요 ?

2023-10-16 05:52 UTC, jundonghyuk commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +    }
이 부부은 무민과 개인적으로 디엠을 나누어서 스킵하겠습니다 ㅎㅅㅎ

2023-10-16 06:08 UTC, jundonghyuk commented on src/test/java/kitchenpos/application/TableGroupServiceTest.java
> +        // given
한 번 해보겠습니다 !

2023-10-16 06:08 UTC, jundonghyuk commented on src/test/java/kitchenpos/application/MenuGroupServiceTest.java
> +@ExtendWith(MockitoExtension.class)
적용해 보겠습니다 !

2023-10-16 13:03 UTC, parkmuhyeun commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +    }
다음 두 가지의 사이드 이펙트가 있어서 저는 최대한 지양하고 있는 편입니다!
- 모든 테스트에 결합이 되어있어서 변경하게 된다면 모든 테스트에 영향이 간다
- 위처럼 구성하게 되면 메서드마다 given 절이 없을 텐데 해당 테스트 클래스가 매우 길어지게된다면 해당 테스트 메서드만으로 어떤 테스트인지 파악하기 힘들고 계속 위 아래 왔다갔다 불편합니다. 테스트는 해당 서비스의 문서라고도 할 수 있는데 문서로서의 역할이 옅어질 거 같아요!

2023-10-16 13:25 UTC, parkmuhyeun commented on src/test/java/kitchenpos/application/TableGroupServiceTest.java
> +                                Arrays.asList(OrderStatus.COOKING.name(), OrderStatus.MEAL.name())
음 원래는 둘 중에 하나만 되어도 예외가 날아가는 건데 생각해보니깐 모킹이라 서비스와 같게 담아줘야 되서 안될 거 같네요!

2023-10-16 13:51 UTC, parkmuhyeun approved these changes
안녕하세요 하디
코멘트 반영 감사합니다!! 👍🏻

2단계로 가시죠~ 저도 따라 가겠습니다

2023-10-16 13:51 UTC, parkmuhyeun commented on src/test/java/kitchenpos/application/MenuGroupServiceTest.java
> +class MenuGroupServiceTest extends MockServiceTest {
@ExtendWith(MockitoExtension.class)도 이쪽으로 빼줄 수 있지 않나요!?

2023-10-16 13:51 UTC, merged

2023-10-16 23:09 UTC, jundonghyuk commented on src/test/java/kitchenpos/application/MenuGroupServiceTest.java
> +class MenuGroupServiceTest extends MockServiceTest {
그러네요.. ㅎㅎ 감사합니다 !