[레거시 코드 리팩토링 미션 - 1단계] 이오(이지우) 미션 제출합니다.
woowacourse/jwp-refactoring pull request #490
Opened 2023-10-12 07:20 UTC by LJW25

안녕하세요 헤나~오랜만입니당👋

이번 미션은 어려운건 없지만 자잘하게 구현할 게 많았던 것 같아요.
리뷰하기 힘드시겠지만 잘 부탁드립니다. 😁

평소에는 Mock 테스트를 선호하는 편인데, 이번과 같이 이미 프로덕션 코드가 전부 짜여져있고 리팩토링을 위해 테스트코드를 짜는 경우는 통합 테스트가 더 적절하다는 생각이 들었어요.
그래서 SpringBootTest를 이용한 서비스 통합 테스트를 작성하였습니다.
작성한 기능 요구사항과 ERD는 [README](https://github.com/LJW25/jwp-refactoring/tree/step1)를 참고해주시면 감사하겠습니다 :)

오늘도 즐거운 하루 되세요~~🐆 (하이에나 이모티콘을 넣고싶었지만..없어서 표범으로 대체...)

2023-10-13 02:49 UTC, hyena0608 commented on README.md
> +## 🛠️ ERD
ERD 굿굿입니다

2023-10-13 05:24 UTC, hyena0608 requested changes
eo 오랜만이네요! 잘 지내고 계신가요??
마지막 리팩터링 미션 재밌게 해보죠!

ERD도 같이 문서에 올려주시고 작성하신 요구사항도 너무 잘 읽혀서 좋네요 👍
테스트 메서드명도 간단하면서도 어떤 의미인지 파악이 잘돼서 제가 좀 배워가겠습니다.

커멘트는 이번에 미션 진행하면서 제가 궁금했던 부분이 있어서 제 생각이랑 같이 남겼습니다.
테스트 내부에 사용되는 변수명이나 검증 방식도 살짝 같이 남겼는데 개인 취향인 부분인 거 같아서 수정까지는 안해주셔도 좋습니다!

화이팅입니다 25

2023-10-13 05:24 UTC, hyena0608 commented on README.md
> +## 🛠️ ERD
ERD 굿굿이네요

2023-10-13 05:24 UTC, hyena0608 commented on README.md
> +# 🎯 키친포스 요구사항
요구사항 정리가 진짜 깔끔해서 너무 잘 읽혀요
배워가겠습니다 👍👍

2023-10-13 05:24 UTC, hyena0608 commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +class MenuServiceTest {
서비스 테스트 구성 정보를 상속 구조로 가져가면 이후에 관리하기 좋을 수도 있을거 같아요!
개인적인 의견입니다.

```suggestion
class MenuServiceTest extends ServiceTestConfig {
```

2023-10-13 05:24 UTC, hyena0608 commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +    private MenuGroupService menuGroupService;
서비스 테스트에서 서비스끼리 의존해서 진행하셨네요.
저는 DAO를 사용했는데 이오 코드를 보니까 깔끔해서 정말 잘 읽히네요 👍

코드를 보면서 궁금한 점이 생겼습니다!
서비스 계층에서 다른 서비스를 사용해서 테스트를 진행하시게된 이유가 궁금합니다.

개인적으로 저는 같은 서비스에 있는 메서드를 사용하는 하지만 다른 서비스를 사용하지 않았습니다.
다른 서비스에 존재하는 기능을 현재 서비스 테스트를 진행할 때 사용하게 되면 다른 서비스 기능의 내부 구현을 알고 있어야 한다는 점이 서비스(비즈니스 로직)이 개념적으로는 서로 결합되어 있는 상태라고 생각했습니다.

그래서 DAO를 의존해서 서비스 테스트를 진행했습니다.
그렇지만 이것도 테스트를 진행하기 위해 기본 데이터를 구성해야하는 점이 결국 현재 테스트하는 서비스의 내부 로직을 테스트 코드에 하드 코딩하는 느낌을 받았습니다.

그래서 모킹하시는 크루들의 코드를 보았는데 서비스 테스트를 진행할 때 "필요한 데이터가 정상적으로 나온다는 가정"을 하고 내부 로직이 예상한 것처럼 동작하는지 확인하는 테스트라고 느꼈습니다.
때문에 다른 로직을 알고 있어야하는 부분에서 서비스 계층에서 서비스끼리 의존하고 테스트를 진행하는 점이 괜찮을까라는 생각이 들었습니다.

이번에 테스트 작성하면서 서비스에서 다른 서비스를 의존해서 쓸까말까 고민을 많이했는데 어떻게 생각하시는지 이오의 의견도 들어보고싶습니다!

2023-10-13 05:24 UTC, hyena0608 commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +        assertThat(result).hasSize(2);
전체 메뉴 목록 조회에 대한 검증부를 크기(size) 이외에도 의도된 값이 맞는지 내부 데이터도 확인해보시는거는 어떤가요?

2023-10-13 05:24 UTC, hyena0608 commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +        final MenuProduct menuProduct = new MenuProduct(product.getId(), 2);
데이터베이스에 저장된 엔티티를 `saved*`와 같은 변수명을 적어주시는 것도 좋을거 같습니다...!

개인적인이지만 저는 테스트를 진행할 때 메서드 인자로 들어갈 값이 무엇인지 표시해주는 것을 선호합니다.

중간중간에 저장되지 않은 객체들과 네이밍의 차이가 없는데 
현재 서비스 테스트에서 해당 객체가 저장된 것인지 조회된 것인지 아니면 
null이 들어가도 괜찮은지 판단하기 위해서 조금 더 생각하면서 테스트를 읽게 됐습니다.

물론 서비스 테스트를 진행하는 방식의 차이일 수 있어서 문제라는거는 절대 아닙니다!

2023-10-13 05:24 UTC, hyena0608 commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +        assertThat(result.getOrderStatus()).isEqualTo(status);
주문 상태 변경에 대한 검증을 해주셨네요 👍
다른 값들은 변경되지 않았는지도 같이 검증해주시면 좀 더 정확한 테스트가 될 수 있을거 같다고 생각합니다.

2023-10-13 05:24 UTC, hyena0608 commented on src/test/java/kitchenpos/application/TableGroupServiceTest.java
> +        final OrderTable orderTable2 = new OrderTable(0, true);
어떤 게 비어있는 OrderTable인지 변수명만 보고 판단하기는 어려운거 같아요~
좀 더 명확한 변수명이 될 수 있다면 좋을거 같아요!

(다른 테스트 코드들도 같은 생각입니다!)

2023-10-13 05:24 UTC, hyena0608 commented on src/test/java/kitchenpos/application/TableGroupServiceTest.java
> +        });
Optional로 반환되는 OrderTable을 assertSoftly 내부에서 검증과 함께 진행하는 것은 어떠신가요?

```suggestion
        // then
        final List<OrderTable> orderTables = orderTableDao.findAllByTableGroupId(tableGroup.getId());
        final Optional<OrderTable> maybeOrderTable1 = orderTableDao.findById(savedOrderTable1.getId());
        final Optional<OrderTable> maybeOrderTable2 = orderTableDao.findById(savedOrderTable2.getId());
        assertSoftly(softly -> {
            softly.assertThat(orderTables).hasSize(0);
            softly.assertThat(maybeOrderTable1).isPresent();
            softly.assertThat(maybeOrderTable2).isPresent();
            final OrderTable actualOrderTable1 = maybeOrderTable1.get();
            final OrderTable actualOrderTable2 = maybeOrderTable2.get();
            
            softly.assertThat(actualOrderTable1.getTableGroupId()).isNull();
            softly.assertThat(actualOrderTable1.isEmpty()).isFalse();
            softly.assertThat(actualOrderTable2.getTableGroupId()).isNull();
            softly.assertThat(actualOrderTable2.isEmpty()).isFalse();
        });
```

2023-10-13 05:24 UTC, hyena0608 commented on src/test/resources/data/truncate.sql
> +SET REFERENTIAL_INTEGRITY TRUE;
👍

2023-10-13 08:16 UTC, LJW25 commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +    private MenuGroupService menuGroupService;
저는 통합테스트라면 다른 서비스를 호출해도 괜찮다고 생각합니다.

사실 PR 메세지에서 언급한 것 처럼 저는 원래 Mock 테스트를 선호하는 편입니다. 
왜냐면 mocking하지 않으면 DAO든 다른 서비스든, 그것도 아니면 sql을 써서라도 테스트 하기 위한 조건을 만들어 줄수밖에 없고, 이 시점에서 이미 "단위" 테스트가 아니라고 생각하기 때문입니다. (슬라이스 테스트로 완벽히 슬라이스 되지 않은 조각을 테스트 하는 것은 모순이라고 생각합니다.)
그렇기 때문에 각각이 독립된 역할을 잘 수행하고 있는가를 파악하기 위해서는 단위테스트이자 Mock 테스트를 써야한다고 생각합니다.
프로그램 전체가 완성되기 이전 개발단계에서 단위테스트를 주로 사용하는 것 또한 동일한 이유이구요.

다시 돌아와서, 단위테스트와 반대로 실제 사용 케이스에 가까운 동작을 테스트하는 것이 통합테스트라고 생각합니다.
현재와 같이 이미 돌아가고있는 프로그램을 위한 테스트로 필요한 것이 통합테스트라고 느꼈고 현재와 같이 구현했습니다.

> 다른 서비스에 존재하는 기능을 현재 서비스 테스트를 진행할 때 사용하게 되면 다른 서비스 기능의 내부 구현을 알고 있어야 한다는 점이 서비스(비즈니스 로직)이 개념적으로는 서로 결합되어 있는 상태라고 생각했습니다.

라는 부분에서 언급해 주신 것 처럼, 다른 서비스 기능의 내부 구현을 알고 있어야 한다는 점이 있지만,
이미 돌아가는 프로그램이라면 제가 리팩터링을 하더라도 현재와 동일한 동작을 수행해야하고, 하나의 코드를 수정했을 때 다른 테스트에도 영향을 미친다면 그 사이드이펙트까지 파악하는 것이 통합테스트의 역할이라고 생각하기 때문입니다.

즉 서로 결합되어있는 상태, 객체와 서비스, 서비스와 DAO, 그외 기타 등등 사이에서 데이터를 주고받는 모든 과정까지 테스트하는 것이 통합테스트라고 생각합니다.

말이 길어졌네요ㅎㅎ
통합테스트에 대한 제 의견이 잘못되었을 수도 있다고 생각해서, 제 의견은 어떻게 보이는제 헤나에게 물어보고싶습니다.
사실  헤나와 의견 나누는게 너무 재밌어서 더 하고싶어요. 😊

2023-10-13 08:26 UTC, LJW25 commented on src/test/java/kitchenpos/application/TableGroupServiceTest.java
> +        final OrderTable orderTable2 = new OrderTable(0, true);
이부분이...Fixture로...리팩토링이 다 되어있었는데...제가 마지막 commit을 push 안한채로 미션을 제출했다는걸 이 리뷰를 보고서야 알게되었습니다..
리팩토링 안된 몹쓸 코드를 보여드리게되어 죄송합니다 헤나..
가독성이 정말 안좋았을텐데 시간 많이 드셨겠네요..😭
그런데도 이렇게 꼼꼼히 리뷰해주셔서 정말 감사해요. 🙇🏻🙇🏻

2023-10-13 08:35 UTC, LJW25 commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +class MenuServiceTest {
구현하면서 상속으로 뺄까? 하는 생각을 여덟번쯤 했던 것 같은데 역시 빼야겠습니다.

아무 메서드도 없는 클래스가 될 것 같아서 고민했었는데, 사실 저도 상속으로 구현하고 싶었어요 ㅎㅎ

2023-10-13 08:38 UTC, LJW25 commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +        final MenuProduct menuProduct = new MenuProduct(product.getId(), 2);
이 부분도 리팩토링 하면서 수정되었지만 푸쉬되지 않은 부분입니다.. 죄송합니다.. [코멘트](https://github.com/woowacourse/jwp-refactoring/pull/490#discussion_r1357946212)
각 테스트에서 집중적으로 테스트하고 싶은 도메인을 제외한 객체 생성 코드들은 `@BeforeEach` 를 사용하여 별도로 분리해 가독성을 높였습니다.
현재의 구조는 어떤가요? 😊

2023-10-13 08:39 UTC, LJW25 commented on src/test/java/kitchenpos/application/TableGroupServiceTest.java
> +        });
assertSoftly 안에서는 테스트만 수행해야 하는 줄 알았는데, 생각해보니 당연히 안에서 테스트 이외의 동작도 실행할 수 있군요!
덕분에 새로운 방식을 깨달았습니다. 감사합니다.

2023-10-13 08:53 UTC, LJW25 commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +class MenuServiceTest {
[7350c0f](https://github.com/woowacourse/jwp-refactoring/pull/490/commits/7350c0f49e26fbe13a2ff3e0d173a9d383efd466)

2023-10-13 16:32 UTC, LJW25 commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +        assertThat(result.getOrderStatus()).isEqualTo(status);
[a71f263](https://github.com/woowacourse/jwp-refactoring/pull/490/commits/a71f26332b53324f0c8fc7aa72c1db3fc18942e3)

`usingRecursiveComparison().ignoringFields()`를 활용하여 검증을 추가하였습니다! 😄
테스트는 꼼꼼할수록 좋죠ㅎㅎ

2023-10-13 16:33 UTC, LJW25 commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +        assertThat(result).hasSize(2);
[a71f263](https://github.com/woowacourse/jwp-refactoring/pull/490/commits/a71f26332b53324f0c8fc7aa72c1db3fc18942e3)

`usingRecursiveFieldByFieldElementComparator().containsExactly()` 를 사용해서 내부데이터 검증을 추가해 주었습니다!

2023-10-13 16:34 UTC, LJW25 commented on src/test/java/kitchenpos/application/TableGroupServiceTest.java
> +        });
[ae70a76](https://github.com/woowacourse/jwp-refactoring/pull/490/commits/ae70a76459af678bb5b1a8b7affe94e7402f9932)

적용 완!

2023-10-13 16:37 UTC, LJW25 commented
안녕하세요 헤나 🐆

제가 첫 요청때 리팩터링이 하나도 안된 몹쓸 코드를 보여드렸다는 것을 뒤늦게 알게되었습니다..죄송합니다.. ([코멘트](https://github.com/woowacourse/jwp-refactoring/pull/490#discussion_r1357946212))
리뷰하느라 정말 정말 수고 많으셨습니다.
다음부터는 푸쉬 두번 확인하겠습니다.
~~일단 이번엔 확실히 푸쉬 다 되었네요.~~

이번 리뷰도 잘부탁드립니다.
좋은하루되세요!

2023-10-14 09:44 UTC, hyena0608 requested changes
안녕하세요 e5

서비스 통합 테스트에 대한 생각을 정리하다 보니 리뷰가 늦어졌네요 ㅠㅠ 죄송합니다
의견 남겨주신 부분도 이오의 의도를 잘 알 수 있었습니다.
제 생각도 조금 더 남겼으니 확인부탁드리겠습니다!
그리고 말씀해주신 부분이랑 커밋 확인 했습니다 👍

화이팅해요 2o

2023-10-14 09:44 UTC, hyena0608 commented on src/test/java/kitchenpos/Fixture.java
> +    public static final OrderTable ORDER_TABLE_NOT_EMPTY = new OrderTable(0, false);
픽스처를 전역으로 사용할 수 있게 만드셨네요.

내부 상태가 바뀌는거 아닌가 싶었지만 사용하기 전에 영속화시킨 후 새로운 객체를 반환해서 상태에 대한 문제가 없네요 👍

현재로서는 JPA를 사용하지 않지만 도입하게 된다면 현재 픽스처가 이용이 가능할까요? 🤔

2023-10-14 09:44 UTC, hyena0608 commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +                .containsExactly(menu1, menu2);
이렇게 이어서도 검증이 가능하군요 👍

2023-10-14 09:44 UTC, hyena0608 commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +    private static final Order ORDER_STATUS_COOKING = new Order("COOKING");
ORDER_STATUS_COOKING은 Fixture에 두지 않고 OrderServiceTest에서 선언하여 사용하신 이유가 있나요?

2023-10-14 09:44 UTC, hyena0608 commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +    }
필요한 변수를 미리 `@BeforeEach`로 세팅해서 사용하시네요!
중복되는 부분을 테스트에서 계속하는 만드는 것보다 훨씬 간편하고 
현재 서비스에서 어떤 변수들이 사용될지도 미리 알 수 있는 이점이 있는거 같아요. 👍

이것도 취향의 차이일 수 있지만 😂 개인적으로는 테스트 코드에서 중복되는 변수를 클래스 필드로 관리하지 않고 있어요.
조금 더 코드를 작성해야하지만 메서드로 만들어 필요할 때 호출하는 식으로 테스트를 진행하는 것을 선호합니다.

생각되는 부분은 현재 테스트 내부에서 필요한 객체의 상태를 나타내는게 어려운거 같아요.
다시 말하자면, 하나의 테스트를 파악하기 위해서 개발자가 실제로 읽어야하는 범위가 늘어난다는 것도 어느 정도의 비용이 든다고 할 수 있지 않을까...? 싶네요.
그래서 저는 메서드를 구현해서 인자로 필요한 데이터를 넣어 객체를 생성하곤 합니다.

`@BeforeEach`로 테스트마다 예상하지 못한 상태로 인한 실패할 경우는 거의 없을거 같아요.
그래도 억지로 예시를 들어봤습니다.
현재 주문을 하기 위해서 OrderLineItem에 메뉴 수량을 4로 수정한다면 `@BeforeEach`도 같이 수정해야할 거 같아요.
그리고 `@BeforeEach`를 수정하는 순간 다른 테스트들도 모두 영향을 받을 수 있을거 같아요.

물론 현재 클래스 내부에서 필요한 값을 세팅하는게 절대 안좋은거는 아니라고 생각해요.
오히려 현재 서비스에서 필요한 데이터를 알 수 있고 중복을 줄여 테스트 생산성을 높일 수도 있을거 같아요.
이후에 위와 같은 예시 상황이 발생한다면 필요한 데이터나 테스트의 관심에 따라 테스트 클래스를 더 분리하는 방법도 있겠다고 생각합니다.

2023-10-14 09:44 UTC, hyena0608 commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +    }
혹시 변수명을 사용해서 테스트를 진행하는 것은 어떠신가 여쭤보고 싶습니다.

```java
final Long wrongTableId = -1;
final Order order = new Order(wrongTableId, new OrderLineItem(menu.getId(), 1);
```

코드를 보고 어떤 이유로 예외가 발생할까 생각했습니다.
당연히 `-1`이라고 생각합니다.

저는 같은 미션을 진행하고 있기 때문에 `-1`을 Order에 넣어 테이블의 식별자값이 없다는 것을 의미하는 것을 한 번에 알 수 있었습니다.

그렇지만 이번에도 억지로 예시를 들면
현재 리팩터링 미션에서 기존의 Order 객체 내부에 주문의 상태를 나타는 값이 `int`로 존재했고 `-1`은 `주문 전`이라는 상태를 의미하고 있을 수도 있을거 같아요.

결국 테스트 메서드명과 Order를 어떤 식으로 사용하는지 모른다면 
현재 테스트 코드로는 무엇이 잘못되었는지 확실하게 알 수 있는 방법이 없다고 생각합니다.

제가 이렇게 커멘트는 달았지만..!
현재 리팩터링 진행은 모두 개인으로 하고 있고
리뷰하는 저도 같은 미션을 진행하고 있으니 사실 읽는데 아무런 문제가 없긴했습니다. 🙇‍♂️

2023-10-14 09:44 UTC, hyena0608 commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +    void changeOrderStatus(final String status) {
`OrderStatus`가 enum인데 내부 값이 추가되거나 변경될 수도 있으니 `@ValueSource`로 문자열이 아닌 `@MethodSoruce`를 사용해보시는거는 어떤가요?

2023-10-14 09:44 UTC, hyena0608 commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +        });
result, status, saved가 있는데 changed, status를 따로 검증하셨네요.
테스트를 작성하면서 애매한 부분이 생긴거 같아요!

바로 changed를 통해서 검증하지 않은 이유가 궁금해져서 Order 클래스를 보니 생성자가 3개가 있네요.

기본 생성자를 제외한 2개의 생성자를 미리 만들어 두신 이유가 있으신가요?

```java
    public Order() {
    }

    public Order(String orderStatus) {
        this.orderStatus = orderStatus;
    }

    public Order(final Long orderTableId, final List<OrderLineItem> orderLineItems) {
        this.orderTableId = orderTableId;
        this.orderLineItems = orderLineItems;
    }
```

2023-10-14 09:44 UTC, hyena0608 commented on src/test/java/kitchenpos/application/ServiceIntegrationTest.java
> +}
👍

2023-10-14 09:44 UTC, hyena0608 commented on src/test/java/kitchenpos/application/TableGroupServiceTest.java
> +    }
여기서는 BeforeEach가 아닌 메서드로 중복되는 코드를 빼셨네요!
 
기존과 비슷한 코드로 통일성 있는 테스트를 작성할 수도 있었을거 같은데 메서드로 빼시게된 흐름이 궁금하네요 🤔

2023-10-14 09:44 UTC, hyena0608 commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +    private MenuGroupService menuGroupService;
👍👍👍 이오의 생각 잘 읽었습니다.
자세하게 말씀해주셔서 이해가 잘되네요!

이오는 하나의 프로그램에 통합 테스트이니 프로그램 전체를 바라보고 계시는거 같네요!
항상 테스트는 어려운거 같아요 ㅋㅋㅋ

저는 통합 테스트를 이오가 말씀하신대로 데이터베이스와 같은 다른 곳에서의 영향이 있는 것까지 테스트를 진행한다고 생각해요.

다만 다른 서비스의 리팩터링이 현재 서비스 테스트에 영향이 없는게 좋을거 같습니다.

서비스 테스트에서 다른 서비스를 의존해서 진행한다면 아래 그림처럼 될 거 같습니다.

주문 테스트를 진행하기 위해서는 사전 데이터 준비가 필요합니다.

![image](https://github.com/woowacourse/jwp-refactoring/assets/82203978/b8d0c749-4958-4f2d-8953-672dad6967fe)

이 때 다른 서비스에 의존해서 데이터를 준비 아래와 같은 흐름이 나옵니다.

![image](https://github.com/woowacourse/jwp-refactoring/assets/82203978/2cf2b7fe-69a8-457d-838d-6b1dee52a946)

이런 경우 다른 서비스 수정에 대한 여파가 현재 서비스의 테스트까지 영향을 미치게 됩니다.

비즈니스는 그대로지만 코드는 수정하는 경우가 아래 같은 느낌이라고 생각합니다.

먼저 서비스가 서비스를 의존할 때 입니다.

아래와 같이 손님 주문 성공 테스트를 작성해봤습니다.

손님이 주문하기 위해서는 항상 테이블에 앉은 후에 주문할 수 있습니다.

비어있는 테이블을 service에서는 바로 만들 수 없습니다.

때문에 비어있는 테이블을 만든 후 테이블을 상태를 변경하도록 테스트 내부에서 로직을 작성해야 합니다.

```java
    class OrderServiceTest {

        @Test
        void 손님_주문_성공_테스트() {
            // given
            등록된_상품 = productService.create();
            등록된_메뉴 = menuService.create();
            비어있는_테이블 = tableService.create();
            비어있지_않는_테이블 = tableService.changeEmpty(비어있는_테이블.getId(), NOT_EMPTY);

            // when
            orderService.create(5명_주문, 비어있지_않는_테이블.getId());

            // then...
        }
    }

```

그리고 비즈니스는 그대로지만 테이블 서비스에서 비어있지 않은 테이블 바로 생성할 수 있게 수정하라고 합니다.

테이블 서비스에서 테이블을 생성할 때 테이블의 상태를 같이 받을 수 있도록 합니다.
그리고 이제 사용하지 않는 테이블 상태 변경 기능을 삭제합니다.

그리고 테이블 서비스 테스트를 그에 맞게 수정합니다.

하지만 테스트를 돌리면 컴파일 오류가 발생합니다.

OrderServiceTest에도 영향이 있기 때문입니다.

그래서 아래와 같이 OrderServiceTest도 수정하게 됩니다.

```java
    class OrderServiceTest {
        @Test
        void 손님_주문_성공_테스트() {
        // given
        등록된_상품 = productService.create();
        등록된_메뉴 = menuService.create();

        // === 다른 서비스 기능 삭제으로 인한 테스트 코드 영향 ===
        // 비어있지_않는_테이블 = tableService.changeEmpty(비어있는_테이블.getId(), NOT_EMPTY);

        비어있지_않는_테이블 = tableService.createNotEmpty();

        // when
            orderService.create(5명_주문, 비어있지_않는_테이블.getId());

        // then...
        }
    }
```

이런 식으로 주문을 위한 테스트 내용은 같지만 다른 서비스의 변경 여파가 OrderServiceTest까지 넘어오게 됩니다.


만약에 다른 서비스의 의존하지 않고 DAO 에 의존했으면 변경할 이유가 없었을 거 같습니다.

```java
    class OrderServiceTest {

        @Test
        void 손님_주문_성공_테스트() {
        // given
        등록된_상품 = productDao.create();
        등록된_메뉴 = menuDao.create();
        비어있지_않는_테이블 = tableDao.create(NOT_EMPTY);

        // when
        orderService.create(5명_주문, 비어있지_않는_테이블.getId());

        // then...
        }
    }
```

테이블 서비스 수정 후

```java
    class OrderServiceTest {

        @Test
        void 손님_주문_성공_테스트() {
        // given
        등록된_상품 = productDao.create();
        등록된_메뉴 = menuDao.create();
        비어있지_않는_테이블 = tableDao.create(NOT_EMPTY);

        // when
        orderService.create(5명_주문, 비어있지_않는_테이블.getId());

        // then...
        }
    }
```

<br>
<br>
<br>

상황을 작성하느라 커멘트가 길어졌네요.
정리하면 이오가 말씀하신 통합 테스트는 저도 동의합니다.

다른 서비스의 기능 자체가 수정되면 당연히 다른 부분의 테스트도 변경하게 될 수 있습니다.
기능 자체가 달라졌다는 것은 비즈니스가 달라졌다는 것이기 때문입니다.

결국 데이터, 기능의 조건 자체가 달라지는 것이니 다른 서비스에서도 그러한 비즈니스에 맞게 수정되어야 합니다.
DAO를 사용해도 당연히 여파가 있을거 같습니다.

코드 예시를 보시면 알 수 있듯이 `테이블에 앉은 손님만 주문할 수 있다`라는 비즈니스는 변화하지 않았습니다.

저희가 변한 것은 개발자 코드일 뿐이라고 생각합니다....!!

2023-10-16 17:14 UTC, LJW25 commented on src/test/java/kitchenpos/Fixture.java
> +    public static final OrderTable ORDER_TABLE_NOT_EMPTY = new OrderTable(0, false);
JPA로 리팩토링 하더라도 현재와 동일한 구조로 가져갈 수 있을 거라고 생각합니다.
동일한 내부 값만을 가지고 완전히 새로운 객체를 생성해주는 구조이기 때문에, 각자 다른 id를 가진 다른 객체가 될 것이기 때문입니다.

질문의 의도가 이게 맞을까요? 😊

2023-10-16 17:15 UTC, LJW25 commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +    private static final Order ORDER_STATUS_COOKING = new Order("COOKING");
해당 테스트 이외에 외부에서는 사용하지 않았기 때문입니다.
한 클래스에서만 사용되는 변수를 굳이 fixture 로 둘 필요는 없다고 생각해서요. :)

2023-10-16 17:23 UTC, LJW25 commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +    }
저도 `@BeforeEach`를 사용할 경우 해당 코드를 읽을 다른 개발자가 느낄 부담이 커진다는 것에 동의합니다!
그래서 어느 정도 범위에 적용하는지가 중요하다고 생각해요.

예시로, 
저는 `OrderServiceTest`에서 `Product`, `MenuGroup`, `MenuProduct`, `Menu`는 `@BeforeEach`에서 생성하고 
`OrderLineItem`, `OrderTable`, `Order` 등은 각 테스트 내부에서 생성하도록 구현하였습니다. 
해당 서비스테스트에서 검증하고자 하는 `Order`와 관련된 부분은 주의가 필요하기 떄문에 테스트 내부에서 바로 볼 수 있도록 하고, 
메뉴 이하의 생성 로직은 관심 밖이기 때문에 굳이 보지 않아도 된다고 생각해서 `@BeforeEach`로 분리 해 둔것입니다.
이런 구조를 사용할 경우 헤나가 말씀해 주신 것 처럼 테스트에 따라 특정 변수의 값을 변경하더라도, 변경이 필요한 변수는 각 테스트 내부에서 선언을 하기 때문에 다른 테스트에 영향을 미치지 않을 수 있습니다.

결론은 저와 헤나의 의견 모두 어느정도 타당성을 가지고 있고, 이 부분을 어떤 기준으로 분리해서 사용할 것이냐가 가장 중요하다고 생각해요!
이번 미션에서 구현한 내용 중에서는 아직 `@BeforeEach` 사용으로 로직이나 가독성에 손해가 미치는 영향은 적다고 생각합니다. 😃

2023-10-16 17:31 UTC, LJW25 commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +    void changeOrderStatus(final String status) {
`@MethosSource`를 사용하라는 의도가 enum자체를 받거나, enum 내부의 값들을 stream으로 받으라는 게 맞으실까요?

저의 경우 만약 enum 내부의 값이 변경된다면 해당 부분까지 테스트가 검증해 줘야 한다고 생각합니다.
예를 들어, 실수로 `COOKING`이 `COKING` 으로 입력되었을 경우 enum으로 비교한다면 해당 부분이 검증되지 않을 테니까요.
만약 의도적으로 변경해야 할 사항이었다면 영향이 미치는 범위를 테스트에서 인지하고 테스트를 수정해 줘야 할 부분이라고 생각합니다.

2023-10-16 17:38 UTC, LJW25 commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +        });
서비스 테스트를 구현 할 때에, 실제로 들어오는 요청이 무엇인지를 염두에 두고 구현했기 때문에 현재와 같은 구조가 되었습니다.

http 패키지의 orders.http를 확인하면 요청이 들어오는 예시가
```
POST {{host}}/api/orders
Content-Type: application/json

{
  "orderTableId": 1,
  "orderLineItems": [
    {
      "menuId": 1,
      "quantity": 1
    }
  ]
}
```
혹은 
```
PUT {{host}}/api/orders/1/order-status
Content-Type: application/json

{
  "orderStatus": "MEAL"
}
```
으로 되어있습니다.

현재 서비스와 컨트롤러에서 입력으로 `Order` 객체를 받고 있기 때문에 
`status`만 받는 생성자와 `tableId`, `orderlineItems`만 받는 생성자가 각각 필요하다고 판단하였고, 테스트도 이 구조에 맞춰 구현하였습니다.

2023-10-16 17:40 UTC, LJW25 commented on src/test/java/kitchenpos/application/TableGroupServiceTest.java
> +    }
메서드 혹은 `@BeforeEach`로 분리하냐 마냐의 결정은 위의 [코멘트](https://github.com/woowacourse/jwp-refactoring/pull/490#discussion_r1361018529)에서 언급한 대로 해당 테스트의 관심사에 포함이 되느냐 입니다.
분리가 결정 되었을 때, 메서드로 사용하냐 `@BeforeEach`로 사용하냐는 해당 클래스 내에서 80%정도 이상이 해당 변수가 필요하냐가 제 나름의 기준입니다.
이 테스트의 경우에는 딱 한번만 필요하기 때문에 `@BeforeEach`가 아닌 메서드를 사용해 주었습니다.

2023-10-16 17:52 UTC, LJW25 commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +    }
확실히 해당 도메인에 대해 전혀 모르는 사람이 본다면 헷갈릴 여지가 있는 것 같아요!

아예 INVALID_ID fixture를 만들어서 전반적으로 교체해 주었습니다. ☺️ [68d90a4](https://github.com/woowacourse/jwp-refactoring/pull/490/commits/68d90a46a0ea0cf09554be38667d04105bbdf8bc)

2023-10-16 18:38 UTC, LJW25 commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +    private MenuGroupService menuGroupService;
정성 가득한 리뷰 감사드립니다 헤나! 🙇🏻
    
헤나의 코멘트를 다섯번정도 정독하며 고민해 보았는데요,
여전히 저는 서비스 통합테스트에서는 DAO보다는 서비스를 호출해야한다고 생각이 들어요…!! 😂

우선 예시로 들어주신 것 같이, 로직이 포함된 부분 까지는 다른 서비스 테스트에 포함되지 않는 편이 좋다고 생각합니다. 
(안된다고는 생각하지 않긴 합니다)
그런 부분은 해당 객체의 테스트 내부에서 검증해야 할 부분이라고 생각해서요.

하지만 단순 생성 정도라면 DAO보다 서비스를 사용하는 것이 적절하다고 생각합니다. 

--

제가 DAO의 사용을 꺼리는 이유는, 가독성을 해친다고 생각해서이기도 합니다.

Service의 create를 사용하면 기본적으로 입력에 대한 검증을 거칩니다. 
따라서 어떤 값이 저장될 지 어느정도 예측이 가고, 해당 값이 안전한 값이라는 것을 보장할 수 있습니다.

하지만 DAO 를 사용해서 입력하는 경우 매번 모든 필드를 입력해 주어야 하고, (물론 null을 사용해도 되지만 그러면 실제 사용될 환경과 거리가 더욱 멀어진다고 생각해요) 그에 따라 고려해야 할 점이 늘어난다고 생각해요.

예를 들면 지금 입력된 1번 Order가 무난한 order인가? 아니면 메뉴가 이상한 order인가? 등의 고민을 매번 해야할거라고 생각합니다.

즉, service를 사용해 생성해주는 것 만으로도 이미 해당 객체는 지극히 정상적인 (예외가 발생하지 않는) 객체이라는 것을 보증해 준다고 생각해요.

--

또한, 헤나가 언급하신 내용 중에 
> 다만 다른 서비스의 리팩터링이 현재 서비스 테스트에 영향이 없는게 좋을거 같습니다.
> 

를 보고 든 생각인데, 저는 역시 ‘영향이 가는게 정상이다’ 라는 의견입니다..!

예시로 들어주신 것과 같이 `OrderServcieTest`에서 `Table`의 생성 로직에 영향을 받을 필요는 없다 는 관점에서라면, 
차라리 을 `tableService.create`하는 Fixture를 별도로 사용하고 다른 테스트들도 공통된 Fixture를 사용하게 하는 방식을 사용할 것 같습니다. 

코드를 수정한다면 영향은 필연적으로 발생하는 것이고, 이 때 테스트가 터져 줘야 해당 부분이 미칠 영향을 파악해서 놓치는 예외 케이스, 레거시 없이 리팩토링이 가능 할 것이라고 생각해요.

만약 영향이 가지 않는 테스트를 원했다면, 처음부터 슬라이스 테스트를 사용했을 것 같습니다.

2023-10-16 18:48 UTC, LJW25 commented
안녕하세요 헤나!

헤나의 정성이 가득한 리뷰 너무 감사드립니다.
헤나 덕에 테스트란 무엇인가에 대해 많이 생각해 볼 수 있었던 것 같아요.

저는 기본적으로 Mock 테스트를 대부분의 상황에서 선호하는 편이라, (Mockist라고 할 정도로 이 부분에 대해 잘 알고있다고 자신하진 못하지만)
통합테스트를 사용한다는 것을 거의 인수테스트 정도로 간주하고 있는 것 같기도 해요.

애초에 실제와 같은 상황을 테스트 하기 위해서 통합테스트를 사용하는 것이라고 생각해서요.
그게 아니라면 mock 테스트를 사용하는게 더 적절하다고 생각합니다. (특히, 관심사의 분리 측면에서요.)

그렇다 보니 헤나의 리뷰에 거의 반박하는 코멘트만 단 것 같아 죄송스럽지만😂
테스트에 대한 주관이 이렇게 다른 사람과 이야기 나눌 수 있는 기회여서 즐겁기도 했습니다 ㅎㅎ

덕분에 제가 생각하는 테스트가 잘못된 건가? 과연 장점보다 단점이 큰 방식인가? 에 대해 깊이 고민 해 볼 수 있었습니다.
아마 앞으로도 계속 고민해 볼 것 같아요.

아직 미션이 남았으니, 계속해서 고민해 보도록 하겠습니다. 😁

이번 리뷰도 잘부탁드립니다.
좋은 하루 되세요!

2023-10-17 13:58 UTC, hyena0608 commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +    private MenuGroupService menuGroupService;
👍👍👍
저는 이오 코드보고 깔끔해서 제 코드 바꿔볼까 고민했습니다. ㅋㅋㅋ
이오가 말씀해주시는 통합 테스트라는 범위를 저는 좀 더 넓게 가져가서 인수 테스트로 데이터의 흐름까지 시나리오 형태로 진행해서 
서비스에서는 항상 최대한 범위를 적게 하나의 메서드만을 테스트한다고 생각하게 된거 같아요.

말씀해주신 의견 너무 맞는 말이고 dao를 이용하면 굉장히 생산성이 낮아지긴 하는거 같아요.
그래서 따로 테스트용 편의 메서드를 만들곤하는데 이것도 결국 서비스와 비슷한 형태가 되는거 아닌가 싶기도 하네요.
또 1번 Order, 메뉴가 이상한 order을 표현하기 위해 변수명도 많이 고민하고 있는데 뜨끔했습니다.

오늘 들은 제이슨의 강의가 생각나기도하고 재밌는 통합 테스트 감사합니다 🙇‍♂️

2023-10-17 14:01 UTC, hyena0608 commented on src/test/java/kitchenpos/Fixture.java
> +    public static final OrderTable ORDER_TABLE_NOT_EMPTY = new OrderTable(0, false);
AServiceTest 에서 PRODUCT를 가져와 영속화 시킨 후 이름을 "Product2" 변경한 후에 테스트가 끝난 후 table을 truncate합니다.
BServiceTest 에서 PRODUCT를 가져와 영속화 시킨 후 상품 이름을 조회하면 "Product2"로 되어 있을거 같습니다!

2023-10-17 14:06 UTC, hyena0608 commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +    void changeOrderStatus(final String status) {
상태를 추가했을 때 테스트가 실패하면 자연스럽게 해당 테스트를 수정하게 되겠지만 통과된다면 자연스럽게 넘어가게 될 수도 있으니
최대한 자동으로 추가될 수 있도록 하는 거는 어떤가 싶었습니다!

2023-10-17 14:10 UTC, hyena0608 approved these changes
안녕하세요 이오~

1단계 미션 고생하셨어요!
사실 훨씬 전에 머지해도 괜찮았지만 의견을 나누다 보니 머지가 늦어졌네요..!
저도 덕분에 더 깊게 생각해볼 수 있어서 재밌었어요 감사합니다 👍

다음 단계도 화이팅입니다. eo

2023-10-17 14:10 UTC, merged