[레거시 코드 리팩토링 미션 - 1단계] 로건(정다빈) 미션 제출합니다.
woowacourse/jwp-refactoring pull request #507
Opened 2023-10-12 08:41 UTC by 70825

안녕하세요 글렌!

이번 단계에서 통합 테스트를 만들지, 단위 테스트를 만들지 고민하다가 현재 팀프로젝트가 통합테스트로 되어 있어서 오랜만에 단위테스트를 만들어볼겸 Mockito를 사용했어요

그리고 미션을 시작하면서 README.md에 Controller와 Service에 기능 목록을 생성했는데, 혹시 제가 잘못 이해한 부분이 있는지도 리뷰를 해주시면 감사드리겠습니다

감사합니다!

2023-10-13 08:41 UTC, seokjin8678 requested changes
안녕하세요 로건!
전체적으로 테스트 코드 꼼꼼하게 매우 잘 구현해 주셨어요!!! 👍👍
게다가 Mockito의 기능들을 잘 알고 사용하신 것이 인상 깊네요!

본문에 남겨주신 기능 목록에 대한 것에 답변을 남기자면...
우선 컨트롤러의 API 목록을 상세하게 적어주신 것은 매우 좋은 것 같아요!
어떤 API가 있는지, 무슨 역할을 하는지 쉽게 알 수 있을 것 같네요!

다만 비즈니스 로직 같은 부분은 조금 부족한 것 같아요.
단순히 결과뿐 아닌, 어떠한 상황이면 예외가 발생하는지에 대한 상황이 없어서, 코드를 봐야만 알 수 있기 때문에 개발자가 아닌 사람이 본다면 이해하기 어려울 것 같아요!

몇 가지 코멘트 남겼으니, 답변 주시고 다시 요청 부탁드립니다!
고생하셨어요!

2023-10-13 08:41 UTC, seokjin8678 commented on README.md
> +   - 주문 테이블에 손님의 수를 변경할 수 있다. (`PUT` - `api/tables/{orderTableId}/number-of-guests`)
본문에 말씀해주신 부분이군요!
이렇게 정리를 해두면 나중에 API가 어떤 것이 있는지, 어떤 동작을 하는지 쉽게 알 수 있을 것 같아요!
이 부분은 추후 API 문서 자동화(Swagger, RestDocs)를 한다면 없어질 것 같네요!
하지만 적용전 수기로 적어두는 것 또한 좋다고 생각해요!

2023-10-13 08:41 UTC, seokjin8678 commented on README.md
> +   - `changeNumberOfGuests` 주문 테이블의 손님의 수를 변경할 수 있다.
마찬가지로 README에 말씀해주신 부분이군요!
로건은 `Service` 클래스가 어플리케이션에서 어떠한 역할을 수행하신다고 생각하시나요?
그렇다면 비즈니스 로직 같은 기능 요구 사항은 어디에 포함되어야 할까요?

2023-10-13 08:41 UTC, seokjin8678 commented on src/main/java/kitchenpos/application/MenuService.java
> +            throw new IllegalArgumentException("[ERROR] 메뉴의 금액이 없거나, 음수입니다.");
예외 메시지를 잘 적어주셨군요! 👍👍
메시지만 보더라도 코드가 어떤 것을 설명하는지 알 수 있겠네요!

2023-10-13 08:41 UTC, seokjin8678 commented on src/test/java/kitchenpos/application/MenuGroupServiceTest.java
> +    }
테스트 코드를 Mock을 사용하여 잘 작성해주셨네요!
다만 생성자의 파라미터로 `"test"`라는 문자열을 넣어주고 있는데, 코드를 처음 본다면 해당 문자열이 무엇을 의미하는지 모를 것 같아요..!

2023-10-13 08:41 UTC, seokjin8678 commented on src/test/java/kitchenpos/application/MenuGroupServiceTest.java
> +    }
빈 테스트를 만들어 두신 것은 추후 검증 로직을 추가할 때 테스트하실 목적일까요?

2023-10-13 08:41 UTC, seokjin8678 commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +        }
중복된 테스트 코드가 있네요!

2023-10-13 08:41 UTC, seokjin8678 commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +            given(menuGroupDao.existsById(1L)).willReturn(Boolean.TRUE);
반환 값으로 레퍼런스 타입을 사용하셨군요!
`menuGroupDao.exitsById()` 메서드의 반환 값은 primitive 타입이던데, 레퍼런스 타입을 사용해주신 이유가 있을까요?

2023-10-13 08:41 UTC, seokjin8678 commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +            final var order = new Order(1L, "COOKING", LocalDateTime.now(), Collections.emptyList());
위의 테스트에서는 `LocalDateTime`을 정적인 값으로 적어주셨는데, 지금 코드에서는 `LocalDateTime.now()`를 사용하셨군요!
이 부분에 대해서 분류하시는 기준이 있을까요?

2023-10-13 08:41 UTC, seokjin8678 commented on src/test/java/kitchenpos/application/TableGroupServiceTest.java
> +            tableGroupService.ungroup(1L);
해당 코드에 Assertion이 없군요!
`assertThatNoException()` 정도의 검증을 사용하는것은 어떨까요?

2023-10-13 08:41 UTC, seokjin8678 commented on src/test/java/kitchenpos/common/ServiceTest.java
> +}
👍👍

2023-10-13 08:55 UTC, 70825 commented on src/test/java/kitchenpos/application/TableGroupServiceTest.java
> +            tableGroupService.ungroup(1L);
엇.. 제출 시간이 급해서 빠르게 하다가 만들고 아예 잊어버린 것 같아요 😅
`SoftAssertions`을 사용해서 `ungroup()`을 수행하면 바뀌는 값들을 검증하는 부분 추가했습니다~

2023-10-13 08:58 UTC, 70825 commented on src/test/java/kitchenpos/application/MenuGroupServiceTest.java
> +    }
네네 맞아요 팀프로젝트에서 이런 컨벤션으로 진행하고 있는데, `@@@_실패_테스트`를 안적어두고 나중에 변경사항이 있을 떄 찾아보려고 하면 생각보다 시간 소모가 좀 컸어요

실패 테스트를 추가해야함 → `@@@_실패_테스트`가 보이지 않음 → 다른 위치에 작성된건가 찾아봄 → 없는걸 확인하고 나서야 `@@@_실패_테스트` 추가
이런 과정을 거쳐야해서 그냥 통일성 있게 실패테스트가 없어도 다 적어두기로 했어요

2023-10-16 07:46 UTC, 70825 commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +            given(menuGroupDao.existsById(1L)).willReturn(Boolean.TRUE);
엇 그러네요 레퍼런스 타입을 사용할 이유는 없을 것 같아요. 관련된 곳들 전부 수정했습니다~

2023-10-16 07:51 UTC, 70825 commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +            final var order = new Order(1L, "COOKING", LocalDateTime.now(), Collections.emptyList());
시간 비교가 필요한 경우라면 LocalDateTime을 따로 값으로 빼두고, 그게 아니라면 LocalDateTime.now()로 설정을 해두었어요!
특정 시간대 값으로 하는건 지금 생각해보니 `final var time = LocalDateTime.now()`로 하거나 `LocalDateTime.of(2023, 10, 12, 15, 34)`이걸로 통일하는게 좋아보이네요
`final var time = LocalDateTime.now()`로 수정했습니다~

2023-10-16 07:58 UTC, 70825 commented on src/test/java/kitchenpos/application/MenuGroupServiceTest.java
> +    }
`메뉴_그룹_이름`으로 수정하고, 다른 부분도 전부 `상품_이름`, `메뉴_이름` 이렇게 수정했어요~

2023-10-16 08:10 UTC, 70825 commented on README.md
> +   - `changeNumberOfGuests` 주문 테이블의 손님의 수를 변경할 수 있다.
> 그렇다면 비즈니스 로직 같은 기능 요구 사항은 어디에 포함되어야 할까요?

이 부분은 잘 이해를 못했는데 자세하게 설명해주실 수 있나여??

> 단순히 결과뿐 아닌, 어떠한 상황이면 예외가 발생하는지에 대한 상황이 없어서, 코드를 봐야만 알 수 있기 때문에 개발자가 아닌 사람이 본다면 이해하기 어려울 것 같아요!

레벨1, 레벨2때 기능 목록을 잊고 있었네요 ! 반영했습니다~

2023-10-16 08:10 UTC, 70825 commented
안녕하세요 글렌!
피드백 받은 부분을 수정하고, 궁금한 부분 다시 코멘트 남겼어요
감사합니다~

2023-10-16 08:33 UTC, seokjin8678 commented on README.md
> +   - `changeNumberOfGuests` 주문 테이블의 손님의 수를 변경할 수 있다.
저는 `Service` 클래스(응용 계층)가 표현 계층과 도메인 계층을 이어주는 징검다리 역할을 하는 계층이라고 생각해요.
따라서 표현 계층 만큼이나 변경이 많고 새로운 기능도 추가될 가능성이 매우 높아요.
그렇기 때문에 주문을 생성한다, 주문의 상태를 변경한다 같은 비즈니스 로직은 Service 보다는 `Order` 같이 도메인 클래스에 규칙을 부여해 주는게 어떤가 싶어 리뷰 남겼어요!
(새로운 서비스가 추가, 삭제 또는 메서드 이름이 변경되면 README 문서도 변경해야 하므로..!)

2023-10-16 08:36 UTC, seokjin8678 commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +            final var order = new Order(1L, "COOKING", LocalDateTime.now(), Collections.emptyList());
지금 같은 경우엔 상관 없지만 테스트 코드에서는 `LocalDateTime.now()` 사용을 지양하는 편이 좋아요!
https://jojoldu.tistory.com/416

2023-10-16 08:36 UTC, 70825 commented on README.md
> +   - `changeNumberOfGuests` 주문 테이블의 손님의 수를 변경할 수 있다.
아하 무슨 말인지 이해했어요!
저는 서비스 기능 목록을 제대로 이해했는지 모르겠어서 서비스도 기능 목록에 작성해서 제가 제대로 로직을 이해했는지 궁금했어요 (ex. empty_table 가 들어간 로직들) 
이거는 문제 없으면 2단계에서 삭제해도 될까요?

2023-10-16 08:39 UTC, seokjin8678 approved these changes
안녕하세요 로건!
리뷰 반영하신 것 확인했습니다! 👍👍
추가적으로 남겨주신 코멘트에 답글 남겨뒀으니 확인 부탁드립니다!
1단계 요구사항은 충분히 반영하셔서 머지하겠습니다! 
2단계 진행 시키시죠!

2023-10-16 08:39 UTC, merged

2023-10-16 08:45 UTC, 70825 commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +            final var order = new Order(1L, "COOKING", LocalDateTime.now(), Collections.emptyList());
엇 저 블로그의 예시는 배송 예정일에 따라 비즈니스 로직에 영향을 줄 수 있는 것이니까 `LocalDateTime.now()`로 하면 안된다는 이야기 아닌가요?
저는 지금 미션이랑 관련이 없어보여서요. 사실 팀프로젝트에서도 테스트에 `LocalDateTime.now()`가 있어서 비슷한 이야기를 꺼냈는데, 그 테스트도 단순히 `usingRecursiveComparison`로 인해 `createdAt`까지 검증하는 용도여서 `LocalDateTime.now()`로 하기로 했었어요