[히히] 2단계 -점진적인 리팩토링 미션 제출합니다.
woowacourse/jwp-refactoring pull request #53
Opened 2020-11-12 09:25 UTC by yelimkim98

점진적인 리팩토링 미션 제출합니다!! 😍 감사합니다!!

2020-11-15 15:12 UTC, dave915 requested changes
히히 안녕하세요! 
몇 가지 피드백 남겼어요! 
확인 해 보시고, 궁금한 점 있다면 언제든 DM주세요!

2020-11-15 15:12 UTC, dave915 commented on src/main/java/kitchenpos/application/OrderService.java
> +        List<OrderLineItemRequest> orderLineItemRequests = request.getOrderLineItems();
`List<OrderLineItemRequest> orderLineItemRequests` 이런 형태의 코드들을 일급 컬렉션으로 변경 한다면 로직들이 그 안으로 이동 가능해 보여요. 
하지만 `OrderLineItemRequest`는 DTO이기 때문에 `OrderLineItemRequest`의 일급컬렉션은 DTO 패키지에 속하겠죠? 
그러면 그 안으로 이동하는 로직들은 dto 로직일까요? 비즈니스 로직일까요? 

예전 미션 할때도 고민 해봤겠지만, DTO가 Service Layer까지 들어올 것인지 들어온다면 어디까지 쓰일 것인지 다시 한번 고민 해보면 좋을 것 같아요 :)

2020-11-15 15:12 UTC, dave915 commented on src/main/java/kitchenpos/application/TableGroupService.java
> +    }
`List<Table>` 의 일급 컬렉션을 만들고 그 내부로 이동시켜도 될 것 같아요!

2020-11-15 15:12 UTC, dave915 commented on src/main/java/kitchenpos/exception/GlobalExceptionHandler.java
> +        logger.info(e.getMessage());
Exception의 log level이 info인 이유가 있을까요? 🤔

2020-11-15 15:12 UTC, dave915 commented on src/main/java/kitchenpos/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler(IllegalArgumentException.class)
현재 코드상에서 직접 정의한 에러상황일때 IllegalArgumentException 만 던지고 있지만, 그렇지 않은 경우에는 에러 처리가 불가 할 것 같아요 ㅜㅜ

2020-11-16 17:13 UTC, yelimkim98 commented on src/main/java/kitchenpos/application/TableService.java
> +            throw new IllegalArgumentException("비어있는 테이블의 손님 수를 바꿀 수 없습니다.");
비어있는 테이블에 대해 손님 수가 0 이 아니게 되는 것은 이상한 상황이라고 생각했습니다!
그래서 테이블을 비우면 무조건 손님 수가 0명이 되도록 코드를 수정했고,
테이블이 비어있을 때 손님 수를 변경할 수 없도록 정책을 가져가고 있습니다!

2020-11-21 10:09 UTC, yelimkim98 commented on src/main/java/kitchenpos/application/TableService.java
> +            throw new IllegalArgumentException("비어있는 테이블의 손님 수를 바꿀 수 없습니다.");
비어있는 테이블의 손님수를 0명으로 바꾸는것은 가능하도록 수정해보았습니다!

2020-11-21 11:15 UTC, yelimkim98 commented on src/main/java/kitchenpos/application/TableGroupService.java
> +    }
validGroupable 메서드는
주어진 테이블들이 그룹으로 묶을 수 있는 집합인지 확인하는 기능이기 때문에
이 로직이 TableGroup 객체의 생성자 안에 있으면 좋을것이라 생각합니다!

문제는 지금 ORM 계층이 없다보니
TableGroupDAO에서 TableGroup 객체를 find 해서 가져오면
TableGroup 객체의 `List<Table> tables` 가 비어있는 상태로 나옵니다.
그러고나서 TableGroupService가 TableDAO를 사용해서
TableGroup 객체의 비어있는 `List<Table> tables`를 채워줍니다...

이러다보니 tables에 대한 검증을 TableGroup 안으로 넣기에는
DB에서 튀어나온 TableGroup 객체는 검증을 안하고 그렇지 않은 TableGroup 객체는 검증을 하고..
이렇게 조금 이상한 모양새가 되어버립니다... ㅠㅠ

ORM을 끼고있지 않아서 발생하는 DB 주도 개발 문제의 일환인것으로 보입니다....ㅠㅠ...

2020-11-21 11:24 UTC, yelimkim98 commented on src/main/java/kitchenpos/exception/GlobalExceptionHandler.java
> +        logger.info(e.getMessage());
코드에서 예외처리를 해놓은 경우 IllegalArgumentException이 나오는데,
이것은 이미 예상해서 대비해놓은 예외상황은 문제상황이 아니라고 생각하여 info 로 했습니다!

2020-11-21 11:32 UTC, yelimkim98 commented on src/main/java/kitchenpos/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler(IllegalArgumentException.class)
그렇군요! 예측하지 못한 예외가 발생하면 error 로그를 남기고 500 에러를 응답하도록 개선해보았습니다!

2020-11-21 11:58 UTC, yelimkim98 commented on src/main/java/kitchenpos/application/OrderService.java
> +        List<OrderLineItemRequest> orderLineItemRequests = request.getOrderLineItems();
List 를 갖지 않는 DTO 들은 편의상 toEntity 로직을 갖게 했었습니다.

같은 맥락에서 List를 갖는 DTO들도 toEntity 로직을 갖게하려고 했는데, 그렇게하면
DTO A안에 DTO B의 일급컬렉션 C가 들어가고
그 일급 컬렉션 C 안에 DTO B가 들어있고... 이런 구조가 나옵니다.

그런데 이러면 DTO A의 toEntity 로직을 불렀을 때
일급컬렉션 C 가의 toEntity가 호출되고
일급컬렉션 C을 구성하는 DTO B 각각의 toEntity가 호출되고...
이렇게
로직이 복잡해져 버립니다.

리스트같은 자료구조를 갖고있지않은 DTO의 toEntity는 로직이 매우 단순하지만,
이 경우 이와 같이 로직이 복잡해져 버리다보니
차라리 그냥 toEntity를 안쓰는게 가독성에도 좋고 깔끔하겠다는 생각이 들었습니다.

만약 그냥 꿋꿋하게 toEntity + 일급컬렉션으로 구현한다면,
그 결과로 나온 엔티티들의 어떤 필드가 누락이 되어있는지도 파악하기가 쉽지 않습니다.

예를들어,
MenuCreateDTO 에서 toEntity로 Menu를 얻으면 필히 id 필드가 null일텐데요,

TableGroupDTO에서 toEntity로 TableGroup을 얻으면
그 안에있는 List<Table> 의 Table 객체는
id 필드 뿐만 아니라 groupId 필드도 누락되어있을 수도 있습니다.

이런식으로 파악하기가 어려워지니 차라리 toEntity를 안쓰는게 낫겠다고 생각했고,
toEntity를 안쓰면 굳이 일급컬렉션을 쓸 이유가 없다고 판단하여
현재의 코드가 탄생했습니다..!

2020-11-21 12:07 UTC, yelimkim98 commented on src/main/java/kitchenpos/application/OrderService.java
> +        List<OrderLineItemRequest> orderLineItemRequests = request.getOrderLineItems();
일급컬렉션을 사용하면 toEntity를 쓸 수 있어서
로직을 toEntity로 일부 옮길 수 있다고 말씀해주신 것 같네요!

그런데 예를들어서
TableGroupCreateDTO 에서 toEntity를 쓰면 TableGroup 객체가 나올텐데,
이 TableGroup 객체는 당연히 id는 누락되어있을 것입니다. (auto increment 필드니까요)
그러면 TableGroup 안에 있는 List<Table> 을 구성하는 Table객체는
id 와 tableGroupId 이렇게 두 개의 필드가 누락되어있을 것입니다.

이렇듯, 계층구조를 이루는 DTO 에 toEntity를 만들게되면
어떤 필드가 누락되어있을지를 예측하기가 어려워집니다.

그리고 List를 갖는 DTO 의 toEntity 는 그렇지 않은 DTO의 toEntity에 비해서 로직이 커진다는 점도 문제라고 생각됩니다.

그래서 그냥 아얘 toEntity 자체를 쓰지 말까 하다가
그래도 toEntity가 있으면 서비스 코드가 예뻐지는건 사실이다보니
DTO 가 DTO를 갖는 구조인 경우에만 toEntity를 쓰지않기로 합의를 봤습니다!

DTO로 로직을 안옮기면 굳이 일급컬렉션을 적용할 필요도 없겠더군요!
그래서 지금의 코드가 나왔습니다!

2020-11-23 23:16 UTC, dave915 commented on src/main/java/kitchenpos/exception/GlobalExceptionHandler.java
> +        logger.info(e.getMessage());
음 이미 대비해 놓은 상황이지만, badrequest로 리턴하고 있어서 정상적인 API 응답은 아닌 것으로 보여요. 
예상한 예외상황이고 개발자가 따로 핸들링하지 않을 것이라면 `warn`으로 하는 것은 어떨까요?

2020-11-23 23:49 UTC, dave915 commented on src/main/java/kitchenpos/application/OrderService.java
> +        List<OrderLineItemRequest> orderLineItemRequests = request.getOrderLineItems();
이 피드백을 남긴 이유는 toEntity를 쓴다기보다 Service로직에서 List를 핸들링하는 로직들을 일급컬렉션을 만들어서, 도메인 Layer로 이동 시켰으면 해서 남긴 피드백이었습니다. 
그러기 위해선 Dto를 도메인 객체로 변환 시켜야 하는데, 현재 구조로는 Dto객체들이 서비스 로직 전반적으로 사용되고 있어서 Dto를 어디까지 쓸 것인가 고민 해보셨으면 했습니다 😭

비즈니스 로직에서 도메인에게 DB내에서의 구분값인 id가 비어있는것이 큰 영향이 있을지는 한번 생각해보면 좋을 것 같아요. 
id는 디비에 저장하면서 생긴 필드이고, 사실 객체들간의 관계에선 id는 필요 없다고 생각이 듭니다.

ps. 아래 피드백도 같은 의미로 다시 한번 생각해 보셨으면 좋겠어요 :) 
https://github.com/woowacourse/jwp-refactoring/pull/53#discussion_r523770763

2020-11-23 23:52 UTC, dave915 approved these changes
히히 안녕하세요 :) 
수정 사항 확인 했어요! 답변 주신 내용에 코멘트 달았어요. 
다음 단계 진행하면서 해당 부분도 다시 한번 고민 해주세요 ㅎㅎ

2020-11-23 23:52 UTC, merged

2020-11-24 06:14 UTC, yelimkim98 commented on src/main/java/kitchenpos/exception/GlobalExceptionHandler.java
> +        logger.info(e.getMessage());
오오 그렇군요!! warn 으로 바꾸겠습니다!! 감사합니다!!!

2020-11-24 07:45 UTC, yelimkim98 commented on src/main/java/kitchenpos/application/OrderService.java
> +        List<OrderLineItemRequest> orderLineItemRequests = request.getOrderLineItems();
아하 제가 이해를 잘못했었군요..!!
DTO가 서비스 로직에서 너무 깊숙히 쓰이고 있네요...!!! 서비스가 DTO들을 가지고 validation을 하고있군요 ㅠㅠ!!! 


DTO들이 서비스의 최상단에서 domain 객체로 변환하도록 전반적으로 수정하고,
서비스에 있는 검증로직을 최대한 domain 객체로 옮겨보도록 하겠습니다!!

다시 설명해주셔서 감사합니다..!! 이해가 잘 됐습니다!! 😍