[레거시 코드 리팩터링 - 1단계] 애쉬(정설희) 미션 제출합니다.
woowacourse/jwp-refactoring pull request #532
Opened 2023-10-12 13:20 UTC by xxeol2

안녕하세요 호이 🫨 🪄
데모데이때마다 이돈이면 발표를 제일 재미있게 봤었는데, 캠퍼스가 달라져서 못봐서 아쉬워요 ...

이번 미션에서는 Service 테스트를 작성해보았습니다.
전부 다 Mocking을 통해 테스트했는데, 하다보니 의미 없는 테스트들이 많아지는 느낌이었어요.
통합테스트보다 Mocking 테스트를 할 때 Service 계층만 테스트가능하다는 장점을 얻을 수 있지만,
given절이 너무 많아지고 의미 없는 테스트가 생긴다는 단점도 존재한다는걸 느꼈어요..

어떤 메서드는 모킹이 좋은 것 같고, 어떤 메서드는 통합테스트가 좋을 것 같은데
일관성 있게 테스트 작성하기와 의미 있는 테스트 작성하기 두마리 토끼를 다 잡을 수 있는 방법이 없을지 고민해봐야겠어요!

추가로 도메인 객체의 생성은 Fixture를 활용했어요!
그 이유는 첫째로는 기존 코드에 변경을 최소화하고자 했고
둘째로는 생성자+setter를 활용하면 이후 리팩터링 미션들에서 변화지점이 너무 많을 것 같아서입니다!!

그럼 리뷰 잘 부탁드립니다 (꾸벅) 🙇🏻‍♀️

2023-10-13 06:14 UTC, This2sho requested changes
안녕하세요 애쉬 🏹

미션 깔끔하게 잘 진행해주셨네요 👍

애쉬의 의견을 들어보고 싶은 부분이 있어서 RC 남깁니다!
이번 미션 잘 부탁드립니다 (꾸벅) 🙇

2023-10-13 06:14 UTC, This2sho commented on README.md
> +    - 메뉴 그룹은 DB에 존재해야한다.
요구 작성 잘 작성해주셨네요 👍

저도 PR을 보내고나서 슬랙 공지를 보니 다음과 같은 내용이 있더라구요..!
> 기술적인 내용보다는 처음 보는 사람도 쉽게 읽을 수 있도록 요구 사항을 정리하였는가?

현재 리팩토링하는 코드가 `포스기 주문` 어플리케이션이니까
가게 사장님이 봐도 이해할 수 있도록 요구 사항을 수정해보는 거 어떨까유?!
`메뉴 그룹은 DB에 존재해야한다.` -> `메뉴는 메뉴 그룹에 속해야한다.` or `메뉴는 메뉴 그룹을 지정해야한다.`...?!

2023-10-13 06:14 UTC, This2sho commented on README.md
> +### 주문 (Or정der)
오정더?!

2023-10-13 06:14 UTC, This2sho commented on README.md
> +        - 빈 테이블이 아니도록 설정한다.
테이블 그룹 해제가 일어나는게 `계산 완료(COMPLETION)` 상태일 때인데
빈 테이블이 아니라고(Empty = false) 설정해주는지  아시나요?!

2023-10-13 06:14 UTC, This2sho commented on src/main/java/kitchenpos/application/MenuService.java
> +            throw new IllegalArgumentException("올바르지 않는 메뉴 가격입니다.");
!! 
프로덕션 코드를 바꿔도 되는 거였군요 !!
(저는 1단계가 프로덕션 코드를 리팩토링 전에 모든 기능에 대한 테스트 코드를 먼저 작성 인줄 알았는데..)

확실히 이렇게 예외 메시지를 적으니까 코드를 이해하기도 쉽고 테스트 할 때
어디서 예외가 터지는지 검증도 쉬워지겠네요 👍

2023-10-13 06:14 UTC, This2sho commented on src/test/java/kitchenpos/supports/MenuFixture.java
> +    private List<MenuProduct> menuProducts;
오홍 저랑 같은 식으로 Fixture를 사용했네요..!
혹시  애쉬가 생각한 `Fixture가 예상치못하게 테스트에 영향을 끼치는 부분이 있을것 같아...` 
이 부분 공유해주실 수 있나요?!

저도 이런식으로 Fixture를 사용하면서 기본 값을 다 채워주고 `menuGroupId` 같은 부분은 `MenuGroupFixture`에서 생성해서 `getId`를 가져오는 형식으로 했습니다..

제가 우려한 부분은 DB 레이어를 진짜 거치는 부분에서 사용하지 못하거나 실제로 저장하고 반환해야겠다는 생각을 했습니다...

2023-10-13 06:14 UTC, This2sho commented on src/test/java/kitchenpos/application/MenuGroupServiceTest.java
> +    }
저도 이런 부분은.. Mock으로 테스트하는게 의미있나 생각이 들더라구요..
이런 부분은.. 통합 테스트로 진행하는게.. 편하기도 하고 의미가 있을 거 같더라구요..

근데, DAO를 테스트해서 지금 모킹한거 처럼 잘 작동하면 의미가 생기지 않을까라는 생각도 들더라구여....

2023-10-13 06:20 UTC, xxeol2 commented on README.md
> +    - 메뉴 그룹은 DB에 존재해야한다.
저도 이 부분을 리뷰하면서 확인했어요..!!
그리고 그 리뷰이(갓 로이스)의 요구사항을 읽는데 확실히 읽기 편하더라구요! 👍
개발 용어를 제외하고 다시 작성해보겠습니다!!

2023-10-13 06:20 UTC, xxeol2 commented on README.md
> +### 주문 (Or정der)
아이코 ㅋㅋ 💤

2023-10-13 06:22 UTC, xxeol2 commented on src/main/java/kitchenpos/application/MenuService.java
> +            throw new IllegalArgumentException("올바르지 않는 메뉴 가격입니다.");
모두 다 IllegalArgumentException이니 어디서 발생하는 예외인지 파악이 어려워, 테스트가 의도한대로 동작하고 있는지 확인하기 어려웠습니다 🥲
그래서 예외 메세지 정도만 추가해보았습니다..!

2023-10-13 06:26 UTC, xxeol2 commented on src/test/java/kitchenpos/supports/MenuFixture.java
> +    private List<MenuProduct> menuProducts;
지금 도메인 객체를 Request로 사용하고 있는데, 픽스쳐를 활용하니 제가 의도한 필드 이외에도 다른 필드들에도 필드 값이 설정되어있는 상태입니다. 여기서 영향을 받을 수 있겠다고 생각했어요!
(나머지 필드를 직접 null로 채워넣자니 픽스쳐 사용 의미가 사라지고..)

2023-10-13 06:33 UTC, xxeol2 commented on src/test/java/kitchenpos/application/MenuGroupServiceTest.java
> +    }
맞아요 이 부분이 제가 PR 본문에서 언급했던 "통합테스트가 더 좋을 것 같은" 메서드입니다!

> 어떤 메서드는 모킹이 좋은 것 같고, 어떤 메서드는 통합테스트가 좋을 것 같은데

그런데 이 메서드는 모킹을 사용하고, 저 메서드는 통합 테스트를 활용하고 하면 그 기준을 정하기가 참 어렵겠더라구요.
그렇다고 더 좋은 방법이 있음에도 '테스트 방법을 하나로 통일하겠다!'는 생각을 유지하는 것도 옳지않은 것 같구요 😭

여러 방법들을 시도해보고 경험을 쌓아 경험기반으로 판단하는게 가장 좋은 방법일 것 같아요

2023-10-16 06:53 UTC, xxeol2 commented
안녕하세요 호이~!🪄
좋은 주말 보내셨나요?!
전 주말에 푸욱 쉬다가 이제서야 1단계 리뷰를 반영했네요!
남겨주신 코멘트들에 대한 제 의견 남겨두었습니다!!

2023-10-16 08:27 UTC, This2sho approved these changes
고생하셨습니다 애쉬!

남겨주신 의견과 수정된 요구사항 확인했습니다! 
확실히 더 이해하기 좋아졌네여👍

다음 미션도 화이팅입니다  🫡

2023-10-16 08:28 UTC, merged