[레거시 코드 리팩터링 - 2단계] 스플릿(박상현) 미션 제출합니다.
woowacourse/jwp-refactoring pull request #553
Opened 2023-10-16 21:58 UTC by splitCoding

안녕하세요 그레이!!😄

리펙토링을 과정에서 변경해야 되는 코드가 너무 많네요...ㅎㅎ

이번 리뷰도 잘부탁드립니다!!🙇

2023-10-18 12:29 UTC, Kim0914 requested changes
안녕하세요 스플릿 ~~ 그레이입니다 ㅎㅎ
리뷰 요청을 일찍 해주셨는데 리뷰가 조금 늦어서 죄송합니다 ㅜㅜ

이번 2단계도 요구사항에 맞게 너무 잘 구현해주셨네요 !
JPA를 사용하지 않고 리팩토링하신 부분도 인상깊어요 ㅎㅎ
궁금한 부분 코멘트 남겼는데 확인부탁드려요 ~~

2023-10-18 12:29 UTC, Kim0914 commented on src/main/java/kitchenpos/application/MenuService.java
> +                .throwIfBiggerThan(menuProductsTotalPrice, IllegalArgumentException::new);
이런 메서드도 있군요?!

이번에도 잘 배워갑니다 ㅎㅎ

2023-10-18 12:29 UTC, Kim0914 commented on src/main/java/kitchenpos/application/MenuService.java
> +                .collect(Collectors.toList());
`menuProducts`를 일급컬렉션으로 만든다면 이 로직을 캡슐화할 수 있을 것 같아요 ㅎㅎ (반영하지 않으셔도 됩니다 !)

2023-10-18 12:29 UTC, Kim0914 commented on src/main/java/kitchenpos/domain/MenuGroup.java
> +        return name;
개인적으로 도메인(엔티티) 객체로 사용하는 것들은 equals and hashcode를 정의해주는게 좋은 것 같더라구요 ㅎㅎ

2023-10-18 12:29 UTC, Kim0914 commented on src/main/java/kitchenpos/application/ProductService.java
> +        return new Product(request.getName(), request.getPrice());
스플릿의 코드를 읽다보니 객체를 생성하는 부분은 모두 메서드로 분리해주셨더라구요 !

저는 객체 생성 로직이 복잡하거나 파라미터가 많은 것이 아니면 `create`메서드 내에서 생성해주는게 직관적인 것 같더라구요 ㅎㅎ (request에서 어떤 값을 꺼내서 생성하는지 한 함수 내에서 볼 수 있다는 장점?)

어떤 기준으로 분리해주시는지 궁금합니다 ~

2023-10-18 12:29 UTC, Kim0914 commented on src/main/java/kitchenpos/application/TableService.java
> +        if (savedOrderTable.getEmpty()) {
OrderTable에게 empty 상태인지 물어보도록 도메인 로직으로 추가해볼 수 있을 것 같아요 !

`savedOrderTable.isEmtpy()`

2023-10-18 12:29 UTC, Kim0914 commented on src/main/java/kitchenpos/domain/OrderTableGuestCount.java
> +public class OrderTableGuestCount {
값객체 포장 👍👍

비즈니스 로직에 있는 가격, 수량 등도 값객체로 포장하면 더 좋을 것 같아요 ㅎㅎ

2023-10-18 12:29 UTC, Kim0914 commented on src/main/java/kitchenpos/domain/TableGroup.java
> +    private static final int MINIMUM_ORDER_TABLES_SIZE = 2;
정말 별건 아니지만...!! (그만큼 비즈니스 코드를 잘 짜셔서ㅎㅎ)

상수와 멤버 변수 공백으로 구분해줘도 될 것 같아요 ~

2023-10-18 12:29 UTC, Kim0914 commented on src/main/java/kitchenpos/domain/OrderLineItems.java
> +public class OrderLineItems {
OrderLineItems 일급 컬렉션으로 설정해주셨네요 ㅎㅎ

2023-10-18 12:29 UTC, Kim0914 commented on src/main/java/kitchenpos/domain/Order.java
> +        this.orderStatus = OrderStatus.valueOf(orderStatus);
`OrderStatus.valueOf()`에 enum에 정의되지 않은 orderStatus가 들어오면 어떻게 될까요?!

DAO에서 꺼내서 변환할 때 사용하는 생성자라 큰 문제는 없을 것 같은데, 외부에서 enum을 변환해서 주입 시켜주거나 enum에게 생성하는 책임을 부여해봐도 좋을 것 같아요 !

2023-10-18 12:29 UTC, Kim0914 commented on src/main/java/kitchenpos/application/OrderService.java
> +        return getCurrentlySavedOrder(orderTable, orderLineItems);
`currently`를 특별히 메서드 명에 정의해주신 이유가 있으신가요 ?!

2023-10-24 08:15 UTC, splitCoding commented on src/main/java/kitchenpos/application/MenuService.java
> +                .throwIfBiggerThan(menuProductsTotalPrice, IllegalArgumentException::new);
제가 만든 메서드를 이렇게 칭찬해시다니 영광입니다😊

2023-10-24 08:25 UTC, splitCoding commented on src/main/java/kitchenpos/application/MenuService.java
> +                .collect(Collectors.toList());
좋은 방법인 것 같아요!! 3단계 때 의존성 분리 진행하면서 같이 반영해보겠습니다!!

2023-10-24 08:35 UTC, splitCoding commented on src/main/java/kitchenpos/domain/MenuGroup.java
> +        return name;
이 부분은 놓쳤군요!! 반영했습니다!!

2023-10-24 08:38 UTC, splitCoding commented on src/main/java/kitchenpos/application/ProductService.java
> +        return new Product(request.getName(), request.getPrice());
코드도 좋지만 최대한 메서드명으로 읽을 수 있도록 하는것이 개인적으로 가독성이 좋더라구요!! 😊
이번엔 이전보다도 더 철저하게 해보자고 했는데 생성자 정도는 코드가 더 직관적일 수도 있겠어요!! 그레이의 의견에도 동의합니다!!😊

2023-10-24 08:40 UTC, splitCoding commented on src/main/java/kitchenpos/domain/TableGroup.java
> +    private static final int MINIMUM_ORDER_TABLES_SIZE = 2;
지금까지 순서만 신경썼는데 공백을 추가하면 훨씬더 잘 구분되겠네요!! 반영하겠습니다!!

2023-10-24 08:47 UTC, splitCoding commented on src/main/java/kitchenpos/domain/Order.java
> +        this.orderStatus = OrderStatus.valueOf(orderStatus);
이 부분을 놓쳤군요!!ㅠ 반영했습니다!!

2023-10-24 08:49 UTC, splitCoding commented on src/main/java/kitchenpos/application/OrderService.java
> +        return getCurrentlySavedOrder(orderTable, orderLineItems);
해당 메서드에서 createdDate 가 설정되는 프로세스가 진행된다는 것을 메서드명에 담고 싶었습니다!!ㅎㅎ

2023-10-24 08:50 UTC, splitCoding commented on src/main/java/kitchenpos/domain/OrderTableGuestCount.java
> +public class OrderTableGuestCount {
이부분도 3단계에서 의존성 분리하면서 반영해 보겠습니다!!

2023-10-24 11:10 UTC, Kim0914 commented on src/main/java/kitchenpos/application/ProductService.java
> +        return new Product(request.getName(), request.getPrice());
좋아요 ㅎㅎ

메서드로 분리하는 것도 매력적인 것 같아요 :)

2023-10-24 11:12 UTC, Kim0914 approved these changes
안녕하세요 스플릿 !

변경해주신 부분 모두 확인했습니다 ㅎㅎ
이번 단계 완성도가 높아서 재밌게 리뷰했는데 다음 단계도 기대하고 있을게요 😉

고생하셨습니다 ~

2023-10-24 11:13 UTC, merged