[레거시 코드 리팩터링 - 2단계] 글렌(전석진) 미션 제출합니다.
woowacourse/jwp-refactoring pull request #566
Opened 2023-10-18 17:00 UTC by seokjin8678

안녕하세요 땡칠! 0️⃣7️⃣

2단계 미션 완료하고 미션 제출합니다!
이번 단계에서 기존의 JdbcTemplate를 사용하고, 단순 값 타입으로만 사용되던 도메인 모델들을 JPA 기반의 엔티티로 전부 재설계하여 리팩터링(이라하고 처음부터 다시 만든)하였습니다.

기존의 구조는 `legacy` 패키지로 이동시켜 마차가 달릴 수 있도록 하였고, 새로운 설계는 기존 패키지 경로에 추가하여 레거시 코드에 영향이 없도록 하였습니다.

저번 미션에서 Mock을 사용하여 테스트를 했는데, 이번 미션에서 깨달은 점은 차라리 통합 테스트로 구현할 걸 그랬나 싶습니다.. 😂

말이 리팩터링이지, 처음부터 재설계한 것과 다름이 없는 것 같아, 미션을 하며 제대로 하는 건지 고민이 많이 들었네요...

클린 코드의 초반부에 `타이거 팀`에 관한 내용이 나오는데(강의에서도 잠깐 나온) 저는 리팩터링을 하고 있다고 생각했지만, 그냥 재설계하고 있던걸까 라는 생각도 들고.. 암튼 그렇습니다.

DB 스키마의 변경은 없어서, 사이드 이펙트는 없지만... 잘 모르겠네요. 😂

표현 계층의 검증은 미션의 학습 범위에 벗어난 것 같아 따로 적용하지는 않았습니다.
같은 이유로 도메인의 검증 로직 또한 요구 사항이나 기존 코드의 명세에 없던 것을 따로 추가하지는 않았습니다.

README에 클래스 다이어그램을 추가했으니, 리뷰 전에 보시면 엔티티 간의 참조가 어떻게 이뤄졌는지 쉽게 아실 수 있을 것 같네요.

리뷰 기다리겠습니다!
감사합니다!

2023-10-22 08:36 UTC, 0chil reviewed
안녕하세요 글렌~ 최종 데모데이는 어떠셨나요?
페스타고에서 푸우랑 예매하기 게임 한게 엄청 재밌었는데, 글렌은 못뵌 것 같네요.

제가 일정 관리를 잘 못해서 리뷰가 많이 늦었어요 🙇🏻 많이 기다리셨을 것 같아 죄송합니다.
최선을 다해서 리뷰해볼게요!

우선 작성해주신 내용부터 같이 얘기 나눠보도록 할게요.

> 이번 단계에서 기존의 JdbcTemplate를 사용하고, 단순 값 타입으로만 사용되던 도메인 모델들을 JPA 기반의 엔티티로 전부 재설계하여 리팩터링(이라하고 처음부터 다시 만든)하였습니다.
> 기존의 구조는 legacy 패키지로 이동시켜 마차가 달릴 수 있도록 하였고, 새로운 설계는 기존 패키지 경로에 추가하여 레거시 코드에 영향이 없도록 하였습니다.
>
>말이 리팩터링이지, 처음부터 재설계한 것과 다름이 없는 것 같아, 미션을 하며 제대로 하는 건지 고민이 많이 들었네요...
>클린 코드의 초반부에 타이거 팀에 관한 내용이 나오는데(강의에서도 잠깐 나온) 저는 리팩터링을 하고 있다고 생각했지만, 그냥 재설계하고 있던걸까 라는 생각도 들고.. 암튼 그렇습니다.
>DB 스키마의 변경은 없어서 사이드 이펙트는 없지만... 잘 모르겠네요. 😂

글렌이 고민한 부분이 무엇인지 잘 이해했습니다.
중요한 것은 마차가 달리는 상태를 유지하는 것인데, 이 부분은 잘 동작하고 있기 때문에 1차적으로는 문제가 없습니다.

다만 '타이거 팀'과 같은 상황인지가 고민인 것 같은데요!
'타이거 팀'은 프로덕트 자체를 새로 만들기 때문에 리팩터링의 범위가 너무 큰 것이 문제였습니다.
새로 설계하는 서비스가 기존 서비스의 변화를 따라가야 하기 때문에 문제가 되는 것이었죠!
(인력 등 리소스가 2배로 들게 되는 것은 덤이구요)

변경 범위가 꽤 커서 글렌이 걱정한 '타이거 팀'의 문제가 재현된 것이 맞다고 생각해요.
실제 상황이라면 이정도 규모의 리팩터링을 진행하는 것은 '타이거 팀'이 되었을 것이라고 생각합니다.
다만 미션은 서비스가 고정되어 있는 상황이므로 큰 문제가 없다는 것이 차이겠네요!

글렌이 이렇게 판단을 한 것은 의식적으로든, 무의식적으로든 서비스가 변하지 않는다는 믿음이 있기 때문일거라 생각해요.
실제 상황이고, 서비스가 변화할 가능성이 있었다면 글렌도 작은 단위로 점진적인 리팩터링을 진행했을거라고 생각합니다.
이미 작성해주신 코드는 가지고 가되, 상황이 어떻게 달랐는지를 인지하고 가면 더 좋겠네요!

>저번 미션에서 Mock을 사용하여 테스트를 했는데, 이번 미션에서 깨달은 점은 차라리 통합 테스트로 구현할 걸 그랬나 싶습니다.. 😂

저도 공감합니다 🥲 하위 객체들이 변화할 상황이기 때문에 내부 구현을 모르는 상태로 진행하는 '블랙박스 테스팅'이 더 효과적이었을 것 같아요.

>표현 계층의 검증은 미션의 학습 범위에 벗어난 것 같아 따로 적용하지는 않았습니다.
>같은 이유로 도메인의 검증 로직 또한 요구 사항이나 기존 코드의 명세에 없던 것을 따로 추가하지는 않았습니다.

네 이해했습니다!

>README에 클래스 다이어그램을 추가했으니, 리뷰 전에 보시면 엔티티 간의 참조가 어떻게 이뤄졌는지 쉽게 아실 수 있을 것 같네요.

실제로 도움이 많이 되네요. 패키지를 레거시로 분리해주신 점도 이해하기에 편했습니다.

2023-10-22 11:43 UTC, 0chil requested changes
Files Changed 124! 바쁜 와중에 정말 고생 많으셨습니다.

리뷰하고나니 '타이거팀이 된 것 같다'는 글렌의 고민이 와닿네요.
저에게도 'API 리팩터링과 서비스 리팩터링을 별도로 진행했다면 어땠을까' 하는 아쉬움이 남습니다.
기존 테스트를 그대로 활용해 '새 객체가 기존 서비스 객체를 정확히 대체할 수 있음'을 보장하면 더 안전했겠네요.

글렌이 고민하신 부분에 대한 커멘트는 위에 남겼어요.
그외에 얘기 나눠볼 수 있는 커멘트 몇개 남겼고,
현재 어플리케이션이 실행이 안되는 상태인데, 고쳐주셨으면 합니다!

2023-10-22 11:43 UTC, 0chil commented on src/main/java/kitchenpos/repository/OrderTableRepository.java
> +    List<OrderTable> findAllByTableGroupId(@Param("tableGroupId") Long tableGroupId);
`OrderRepository.findByOrderTableId(Long orderTableId);`는 OrderTable 객체의 id를 찾아서 동작하는데,

이 메서드에서는 TableGroup 객체의 id를 못 찾는게 좀 이상하네요.

뭐가 다른걸까요?

2023-10-22 11:43 UTC, 0chil commented on src/main/java/kitchenpos/repository/OrderTableRepository.java
> +    List<OrderTable> findAllByTableGroupId(@Param("tableGroupId") Long tableGroupId);
아래는 주관적인 영역이니 걸러서 들어주세요:

여기서 JPQL이 꼭 필요할까 라는 의문이 듭니다.
쿼리를 작성하기 시작하면, 텍스트로 관리되는 부분들이 생길텐데 좀 아쉬워서요.

1. `@Param`은 제거해도 잘 동작합니다.
2. `findAllByTableGroup_Id()`로도 같은 역할을 할 수 있습니다.

2023-10-22 11:43 UTC, 0chil commented on src/main/java/kitchenpos/application/MenuGroupService.java
> +        MenuGroup menuGroup = new MenuGroup(null, request.getName());
id를 명시적으로 null로 넣어주는 이유가 있나요?

2023-10-22 11:43 UTC, 0chil commented on src/main/java/kitchenpos/application/MenuService.java
> +    }
예외가 참 친절해서 좋네요 👍

2023-10-22 11:43 UTC, 0chil commented on src/main/java/kitchenpos/domain/Order.java
> +    private OrderStatus orderStatus;
이 부분 때문에 어플리케이션 실행이 안되고 있어요!
`@Enumerated(value = EnumType.STRING)` 추가가 필요해 보이네요!

2023-10-22 11:43 UTC, 0chil commented on src/main/java/kitchenpos/application/TableGroupService.java
> +        throw new KitchenPosException("존재하지 않는 주문 테이블이 있습니다. notExistOrderTableIds=" + notExistProductIds);
당장은 어렵겠지만 3단계에서는 이렇게 서비스에만 존재하는 비즈니스 규칙들도 잘 분리해보면 좋겠습니다.

2023-10-22 11:43 UTC, 0chil commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> -
(이 부분은 바꿔주실 필요는 없지만, 이야기를 나눠봤으면 합니다!)

이런 비즈니스 규칙에 대한 테스트는 왜 사라졌을까요?
'리팩터링 전의 Service 객체를 1:1로 대체할 수 있다'를 보장하기 위해서는 꼭 필요한 내용인 것 같아요!

관련 로직이 도메인 객체로 내려갔더라도, 중복되는 테스트라도, 
서비스 계층의 테스트 코드를 유지해야 안전하지 않을까요?

2023-10-22 11:43 UTC, 0chil commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +                new MenuProductCreateRequest(1, 4885L),
![image](https://github.com/woowacourse/jwp-refactoring/assets/39221443/b0dd3f33-6a45-4ff5-8695-cf8929875d9f)
"야 4885, 너지?"

2023-10-22 12:21 UTC, seokjin8678 commented on src/main/java/kitchenpos/repository/OrderTableRepository.java
> +    List<OrderTable> findAllByTableGroupId(@Param("tableGroupId") Long tableGroupId);
1. 제 실행 환경은 IntellJ로 실행하고 있는데요, 이때 다음과 같은 예외가 발생해요.
```
org.springframework.dao.InvalidDataAccessApiUsageException:
For queries with named parameters you need to provide names for method parameters; 
Use @Param for query method parameters, or when on Java 8+ use the javac flag -parameters; nested exception is java.lang.IllegalStateException:
For queries with named parameters you need to provide names for method parameters;
Use @Param for query method parameters, or when on Java 8+ use the javac flag -parameters
```
따라서 `@Param` 어노테이션을 붙여줬어요!
2. 뒤에 언더스코어를 붙이면 해결이 되는군요! 이 부분은 처음 알았네요!!

2023-10-22 12:22 UTC, seokjin8678 commented on src/main/java/kitchenpos/repository/OrderTableRepository.java
> +    List<OrderTable> findAllByTableGroupId(@Param("tableGroupId") Long tableGroupId);
그리고 문제의 원인을 찾았네요.
```java
class OrderTable {
   ...
   public Long getTableGroupId() {
        if (tableGroup == null) {
            return null;
        }
        return tableGroup.getId();
    }
}
```
해당 메소드가 원인이었습니다.!!!
이 부분은 메서드 명을 바꾸던가 해서 해결해야겠네요

2023-10-22 13:04 UTC, seokjin8678 commented on src/main/java/kitchenpos/application/MenuGroupService.java
> +        MenuGroup menuGroup = new MenuGroup(null, request.getName());
엔티티의 생성자에서 Id가 없는 생성자를 따로 만들지 않아서 그렇습니다..!
식별자의 생성을 RDB에 의존하기 때문에 직접 만들지 않고 null을 넣어주었네요!

2023-10-22 13:05 UTC, seokjin8678 commented on src/main/java/kitchenpos/domain/Order.java
> +    private OrderStatus orderStatus;
테스트만 돌리고 실행을 보장해봐서, 실제 어플리케이션을 돌릴 생각을 못했네요. 😂

2023-10-22 13:21 UTC, seokjin8678 commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> -
해당 테스트는 `MenuTest`로 옮겨졌습니다! (지워진 부분에 대한 테스트 코드는 `kitchenpos.legacy.application/LegacyMenuServiceTest`에 존재합니다!)
이유는 `Menu`를 생성할 때 가격에 대한 검증은 서비스 계층이 하는 것이 아닌 `Menu` 라는 도메인 그 자체가 수행합니다. (검증 로직이 도메인으로 이동했으므로)

지금 서비스 테스트는 Mock을 사용한 계층의 단위 테스트라고 볼 수 있는데요, 여기서 수행하는 테스트 자체는 서비스 내의 비즈니스 로직이 정상적으로 작동하는지를 봐야 한다고 생각합니다.

따라서 서비스에서 `Menu`에 잘못된 값을 입력했을 때 어떠한 예외를 발생한다 라고 기대하는 것은 서비스 단위 테스트가 가지는 책임을 벗어난 것이라 생각하여 해당 테스트는 중복된 테스트라고 판단하고 제거하였습니다!
(만약 이 부분에 대해 검증이 필요하다면 Service 보단 통합 테스트로 이동하는 것이 좋아보이네요.)

2023-10-22 16:52 UTC, seokjin8678 commented on src/main/java/kitchenpos/application/TableGroupService.java
> +        throw new KitchenPosException("존재하지 않는 주문 테이블이 있습니다. notExistOrderTableIds=" + notExistProductIds);
Validator를 적용해보던가 해야겠군요!

2023-10-22 18:46 UTC, seokjin8678 commented
안녕하세요 땡칠! 0️⃣7️⃣

많은 작업을 하느라, 변경과 추가가 많았을 텐데, 실제로 코드 돌려보시느라 고생 많으셨습니다..!  🙇‍♂️
남겨주신 피드백에 제 생각을 남겨봤어요!
프론트가 없는 프로젝트이다 보니, 실제 어플리케이션을 실행해 볼 생각을 못 하고 테스트만 실행하고 잘 돌아간다고 생각해버렸네요. 😂
JPQL에 관한 부분 수정했고, 남겨주신 피드백을 바탕으로 블랙박스 테스팅을 위해 통합 테스트를 추가했습니다!

리뷰 기다리겠습니다!
감사합니다!

2023-10-24 05:44 UTC, 0chil commented on src/main/java/kitchenpos/repository/OrderTableRepository.java
> +    List<OrderTable> findAllByTableGroupId(@Param("tableGroupId") Long tableGroupId);
1 - 환경마다 다른가보네요. 지금까지는 잘 동작해서 몰랐던 내용이네요. 앞으로 주의해서 사용해야겠습니다!
3 -  오... getter를 인식해서 그런거였군요.

JPA 스펙 문서를 보면, Access Type은 field-access / property-access 둘 중 하나이고,
매핑 어노테이션(`@Id` 등..)을 어디 붙이냐에 따라 결정된다고 쓰여 있는데요:
<img width="615" alt="image" src="https://github.com/woowacourse/jwp-refactoring/assets/39221443/aa94cde7-de90-4e52-9a83-53bd47e49c8b">

따라서 글렌의 경우에는 field-access로 접근될 것이라고 예상되는데, 왜 getter를 통한 property access가 일어나는지 의아하네요..
이 부분은 우선 중요한 내용은 아니니 넘어가도록 하고, 제가 연구해보고 알게 되면 알려드리겠습니다!

2023-10-24 05:46 UTC, 0chil commented on src/main/java/kitchenpos/application/MenuGroupService.java
> +        MenuGroup menuGroup = new MenuGroup(null, request.getName());
Id가 없는 생성자를 생성하지 않고, 직접 null을 넣은 이유가 궁금했어요!
이건 본인 스타일이라서 어느 쪽도 괜찮다고 생각합니다~

2023-10-24 05:54 UTC, 0chil commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> -
확인했습니다!
글렌의 Service 테스트들은 모킹을 통해 Service 계층만을 테스트하는 것이 목적이셨군요.
그 이하 객체들이 가지는 책임은 테스트하지 않는다는 글렌 말씀 잘 이해가 되었습니다.

> '리팩터링 전의 Service 객체를 1:1로 대체할 수 있다'를 보장하기 위해서는 꼭 필요한 내용인 것 같아요!
>> 만약 이 부분에 대해 검증이 필요하다면 Service 보단 통합 테스트로 이동하는 것이 좋아보이네요.

여기서 걱정되었던 부분이 IntegrationTest 들에 구현이 되었네요! 꼼꼼한 테스트 정말 멋있습니다.

2023-10-24 06:50 UTC, 0chil approved these changes
안녕하세요 글렌! 땡칠입니다.
통합 테스트 작성해주신것, JPQL 제거해주신 것 잘 확인했습니다. 새벽에 정말 고생 많으셨어요!
통합 테스트가 있으니까 든든하네요.

마지막으로 커멘트 몇 개 남겼습니다! 필요하다고 생각되면 반영해주세요 😄
드디어 의존성 리팩터링이네요!! 두근두근.. 다음 단계에서 만나요!

2023-10-24 06:50 UTC, 0chil commented on src/main/java/kitchenpos/domain/Menu.java
> +    private Money price;
`@AttributeOverride`는 하위 객체에 지정된 Column을 '완전히' 오버라이드한다고 합니다.
precision 및 scale을 잘 챙겨주셨는데, 이곳에서도 적용해야 할 것 같네요!

2023-10-24 06:50 UTC, 0chil commented on src/main/java/kitchenpos/domain/Menu.java
>      }
지금보니 reducer를 너무 잘 사용해주셨네요! 👍

2023-10-24 06:50 UTC, 0chil commented on src/main/java/kitchenpos/domain/OrderLineItem.java
> +
`OrderLineItem`에 order 필드를 제거해도 된다고 생각합니다.
현재 `orderLineItem.getOrder()`는 사용하지 않는 것으로 보이네요!
<img width="308" alt="image" src="https://github.com/woowacourse/jwp-refactoring/assets/39221443/c8bc6ee9-3d76-4635-b41e-529fe9f7bcef">


글렌이 생각하시기에도 order가 불필요하다면,
`Order.orderItems` 필드만 존재하도록 단방향 매핑을 하여 개선해볼 수 있겠네요!

2023-10-24 06:50 UTC, 0chil commented on src/main/java/kitchenpos/domain/MenuProduct.java
> +    private Menu menu;
여기도 `OrderLineItem` 객체와 같은 커멘트를 달고 싶습니다!

`MenuProductResponse` 객체에서 getMenu().getId()를 사용중이긴 하지만, 이미 `MenuReponse`에서 id를 제공하고 있기 때문에 제거해도 괜찮아 보입니다!

2023-10-24 06:50 UTC, 0chil commented on src/main/java/kitchenpos/repository/OrderTableRepository.java
> +    List<OrderTable> findAllByTableGroupId(Long tableGroupId);
이렇게 사소하지만 귀찮은 부분도 반영해주시다니..! 정말 감동입니다 🥹

2023-10-24 06:51 UTC, merged

2023-10-24 06:52 UTC, seokjin8678 commented on src/main/java/kitchenpos/domain/Menu.java
> +    private Money price;
와우 선택적으로 오버라이딩 하지 않나보네요!!!
감사합니다!

2023-10-24 11:27 UTC, seokjin8678 commented on src/main/java/kitchenpos/domain/OrderLineItem.java
> +
양방향 연관 관계를 설정하여, update 쿼리가 발생하지 않도록 했는데 이 경우 `@OneToMany` 연관 관계에 `@JoinColumn`으로 설정해봐야겠네요!