[쿨라임] 2단계 - 서비스 리팩터링 미션 제출합니다.
woowacourse/jwp-refactoring pull request #57
Opened 2020-11-14 15:52 UTC by icyMojito

안녕하세요, 휴님! 2단계 미션 구현을 완료하여 리뷰를 요청드립니다.
미흡한 부분이 많을 것 같네요..😅
이번 미션에도 많은 피드백 부탁드립니다 🙏🏻 감사합니다!

2020-11-15 10:00 UTC, Hue9010 requested changes
쿨라임! 2단계 진행하시느라 고생하셨어요.
몇가지 수정이 필요한 부분 피드백 남겼는데 확인해주세요!

2020-11-24 15:07 UTC, icyMojito commented on src/main/java/kitchenpos/dto/menu/MenuCreateRequest.java
> +    private BigDecimal price;
DTO에서는 null 여부(String형 데이터는 비어있는지 여부까지)만 검증을 하고, “가격은 0 이상이어야 한다.”같은 로직이 필요한 요구사항은 도메인 레이어에서 검증하는 식으로 구현을 했습니다~
그런데 휴님 리뷰를 보고 다시 생각해보니 이런 식으로 검증을 나눠서 하는 게 좋은 방식일까 고민이 되네요 😅
DTO에서 요청 데이터의 Null 여부를 검증하더라도 다른 레이어에서는 Null 검증이 된 상태인지 알 길이 없어 보이고,
현재 DTO에서 반드시 검증을 해야 할 이유가 없다고 판단했습니다.
그래서 서비스 레이어와 도메인 레이어에서 null 여부부터 검증하는 방식으로 수정하였습니다!

2020-11-24 15:08 UTC, icyMojito commented on src/main/java/kitchenpos/dto/ordertable/OrderTableChangeRequest.java
> +public class OrderTableChangeRequest {
OrderTable 관련 DTO들이 이상한 형태였네요😥 정신 똑바로 차리고 코딩을 했어야 하는데..리뷰를 더욱 번거롭게 해드려 죄송합니다 😭

2020-11-24 15:29 UTC, icyMojito commented on src/main/java/kitchenpos/domain/product/ProductPrice.java
> +public class ProductPrice {
상품 가격과 메뉴 가격의 요구사항이 달라질 수 있고, 가격 검증 실패 시 발생하는 예외를 다르게 처리하고 싶어서 ProductPrice와 MenuPrice를 따로 생성하였습니다.
하지만 지적해주신 대로 두 클래스가 가격 검증 실패 시 발생하는 예외 클래스를 제외하고는 동일한 형태인지라 
Price를 사용하는 것이 유지보수 측면에서 나을 것 같아 변경하려고 했었습니다!
그런데 2차 리팩토링을 진행하다보니 MenuPrice에만 필요한 검증 메서드가 생겨 일단 두 클래스를 사용하는 상태를 유지하였습니다~

2020-11-24 15:31 UTC, icyMojito commented on src/main/java/kitchenpos/repository/MenuGroupRepository.java
> +public interface MenuGroupRepository extends JpaRepository<MenuGroup, Long> {
말씀주신 것처럼 JPA로 바꾸는 과정이 수월했는데요🤣 
JPA로 바꾸는 것을 최우선으로 고려하기보다 현재 프로젝트의 환경에 맞게 데이터를 잘 처리하는 방법이 있는지 좀 더 고민해본 후 적용해야겠네요!
이런 부분까지 꼼꼼하게 짚어주시고 자세히 설명해주셔서 감사합니다 🙇🏻‍♀️

2020-11-24 16:00 UTC, icyMojito commented on src/main/java/kitchenpos/exception/MenuNotFoundException.java
> +public class MenuNotFoundException extends RuntimeException {
ControllerAdvice에서 @ExceptionHandler 안에 모든 커스텀 예외를 넣어주거나, 부모 클래스인 RuntimeException을 넣을 것 같은데
그렇게 되면 RuntimeException이 상위에 있는 예외다 보니 제가 예상치 못한 예외도 해당 메서드에서 처리하게 될 것 같네요!
그렇다고 일일이 커스텀 예외를 추가해주는 것도 번거롭고 또 누락될 가능성이 있으니..
커스텀 예외들을 묶어주는 상위 개념의 커스텀 예외를 만들어 모든 커스텀 예외가 이 예외를 상속하게 한 후 @ExceptionHandler에 넣어주는 것이 나을 것 같습니다!
혹은 커스텀 예외들에 요구사항(예를 들면 에러 코드 출력?)이 생기면 RuntimeException으로는 처리하기가 곤란할 수도 있겠다는 생각이 들었습니다~
의도하신 어려움(?)이 맞는지 모르겠네요 😅

2020-11-25 17:02 UTC, Hue9010 approved these changes
잘 구현해주셨네요. 다음 단계 진행해주세요! 👍 
간단한 피드백을 남겼는데 다음 단계를 진행하실 때 같이 반영해주시면 될 것 같아요.

2020-11-25 17:10 UTC, Hue9010 commented
몇가지 사항 안내드릴게요! 우선 이번주 수료한다는 소식 들었는데 고생 많으셨어요!! 👏 👍 
오늘도 그렇지만(아마 저번도.. 😢 🙏 ) 빠르게 피드백을 드리지 못하는 경우들이 있어 수료후에도 pr 보내주시면 리뷰 진행하도록 할게요. 그러니 너무 급한 마음에 촉박하게 하지 마시고 편히 보내주세요! (수료 후 잠깐 자유를 만끽하시고 일이주 뒤에 보내셔도 돼요. 그만큼 편히 생각해 주시길 바래요. 😉)

그리고 또하나는 3단계 학습은 [[우아한테크세미나] 190620 우아한객체지향 by 우아한형제들 개발실장 조영호님](https://www.youtube.com/watch?v=dJ5C4qRqAgA) 참고하시면 좋을 것 같아요. (이미 보셨을 수도 있을 것 같네요ㅎㅎ)

2020-11-25 17:11 UTC, merged