[레거시 코드 리팩터링 - 2단계] 하디(전동혁) 미션 제출합니다.
woowacourse/jwp-refactoring pull request #574
Opened 2023-10-19 12:42 UTC by jundonghyuk

안녕하세요 무민 ! 2단계로 찾아왔습니다.

JPA로 바꾸느라 오래걸렸네요. 저는 리팩토링이 이렇게 오래걸릴줄 몰랐어요.

최대한 객체지향적으로 짜려고 노력했고, fetch join등을 이용해 성능적인 문제도 해결하려고 해봤어요.

그리고 쿼리에 비지니스로직이 녹아있는 것이 싫어서 그런 쿼리는 모두 없앴습니다.. 

수정 부분이 많은 만큼 커밋을 작게 나누기 위해 노력했습니다 !

잘 부탁드려요 !

2023-10-19 12:45 UTC, cpot5620 commented
아니 무민.. file changed 117개라고 저한테 하디 욕을 하시면 어떻게 해요..

2023-10-19 13:15 UTC, parkmuhyeun commented
<img width="157" alt="image" src="https://github.com/woowacourse/jwp-refactoring/assets/76938931/83ac4b33-c9ab-4bd2-903a-cf3b5794751d">

..?

2023-10-21 15:51 UTC, parkmuhyeun requested changes
안녕하세요 하디~!
최종 데모데이 여파 때문에 늦게 리뷰하게 되었네요ㅠㅠ🙇🏻‍♂️🙇🏻‍♂️
최종 데모데이 마무리는 잘하셨나요!?

2단계 군더더기 없이 리팩터링 엄청 깔끔하게 잘 해주셔서 놀랐습니다! protected(), fetch join 등 꼼꼼함까지 👍🏻

3단계 가기 전 몇가지 코멘트 남겨봤고 1단계때 테스트를 모킹으로 하셨는데 2단계 리팩토링 할 때 어땠는지 하디 체감이 궁금하네요!

2023-10-21 15:51 UTC, parkmuhyeun commented on src/main/java/kitchenpos/exception/MenuException.java
> +public class MenuException extends RuntimeException {
도메인별로 예외를 만들어놓으셨군요 👍🏻

2023-10-21 15:51 UTC, parkmuhyeun commented on src/main/java/kitchenpos/application/MenuService.java
> +        List<Menu> menus = menuRepository.findAllWithMenuProducts();
N+1 고려까지 👍🏻👍🏻👍🏻

2023-10-21 15:51 UTC, parkmuhyeun commented on src/main/java/kitchenpos/application/OrderService.java
> +    public OrderDto create(final CreateOrderDto createOrderDto) {
final 안 붙이시는거 같으니 여기도 제거하시죠!

2023-10-21 15:51 UTC, parkmuhyeun commented on src/main/java/kitchenpos/application/OrderService.java
> +    }
이부분도 OrderStatus한테 역활을 넘기는 건 어떨까요

2023-10-21 15:51 UTC, parkmuhyeun commented on src/main/java/kitchenpos/application/TableGroupService.java
> +        return tableGroupRepository.findById(tableGroupId)
존재만 확인하고 따로 사용은 안하는 것 같은데 existsById는 어떠신가요? 어차피 기본 메서드라서 따로 생성비용은 없을 거 같아요.

아니면 혹시 후에 해당 메서드를 사용할 수도 있을 것 같아서 확장성 측면에서 이렇게 작성하셨나요!?

2023-10-21 15:51 UTC, parkmuhyeun commented on src/main/java/kitchenpos/application/dto/OrderDto.java
> +    public OrderDto(Long id, Long orderTableId, String orderStatus, LocalDateTime orderedTime, List<OrderLineItemDto> orderLineItems) {
private!

2023-10-21 15:51 UTC, parkmuhyeun commented on src/main/java/kitchenpos/domain/menu/Menu.java
> +    }
Menu 도메인에 MenuProducts 관련 로직이 많아졌는데 일급컬렉션을 한번 만들어 보는 건 어떨까요

2023-10-21 15:51 UTC, parkmuhyeun commented on src/main/java/kitchenpos/domain/menu/MenuName.java
> +    protected MenuName() {}
엔터 한번만..
별거아니지만 이런거에 은근히 꽂히네요ㅋㅋㅋㅋㅋ

2023-10-21 15:51 UTC, parkmuhyeun commented on src/main/java/kitchenpos/domain/order/Order.java
> +        if (this.orderStatus == OrderStatus.COMPLETION) {
58번째 줄에 isComplete가 이미 있으니까 쟤로 사용하는 건 어떠신가요?

2023-10-21 15:51 UTC, parkmuhyeun commented on src/main/java/kitchenpos/domain/order/OrderTable.java
> +        this.empty = Boolean.FALSE;
static 어떤가요

2023-10-21 15:51 UTC, parkmuhyeun commented on src/main/java/kitchenpos/domain/order/TableGroup.java
> +    }
여기도 한번!

2023-10-21 15:51 UTC, parkmuhyeun commented on src/main/java/kitchenpos/repository/OrderTableRepository.java
> +    List<OrderTable> findAllByTableGroupIdWithOrders(@Param("tableGroupId") Long tableGroupId);
@param 생략해도 되지 않나요!?

2023-10-21 15:51 UTC, parkmuhyeun commented on src/test/java/kitchenpos/domain/menu/MenuTest.java
> +
첫 줄에 개행이!

2023-10-21 15:51 UTC, parkmuhyeun commented on src/test/java/kitchenpos/BaseTest.java
> +public class BaseTest {
테스트 전체적인 코멘트라 여기에다가 작성합니다. 현재 도메인 별로 익셉션을 잡고 있어서 에러 메시지까지 체크를 안 해주면 해당 부분에서 발생했는지 알 수가 없어서 메시지까지 체크해주면 더 좋을거 같아요!

2023-10-21 15:51 UTC, parkmuhyeun commented on src/test/java/kitchenpos/repository/MenuRepositoryTest.java
> +class MenuRepositoryTest extends BaseTest {
repositoryTest도 상위 클래스 빼서
@DataJpaTest나 EntityManager 넣어줄 수 있을거 같아요!

2023-10-21 15:51 UTC, parkmuhyeun commented on src/test/java/kitchenpos/repository/MenuRepositoryTest.java
> +    private EntityManager em;
오.. 혹시 Transactional를 사용하고 있어서 엔티티 매니저로 플러시해주고 있는 건가요?
🫢👍🏻👍🏻👍🏻

2023-10-23 04:37 UTC, jundonghyuk commented on src/main/java/kitchenpos/application/OrderService.java
> +    public OrderDto create(final CreateOrderDto createOrderDto) {
감사합니다 ㅎㅎ !!

다른 부분도 수정했어요 !

2023-10-23 04:40 UTC, jundonghyuk commented on src/main/java/kitchenpos/application/OrderService.java
> +    }
좋은 생각인것 같습니다 ! 적용해보겠습니다

2023-10-23 04:44 UTC, jundonghyuk commented on src/main/java/kitchenpos/application/TableGroupService.java
> +        return tableGroupRepository.findById(tableGroupId)
체크만 하는 것을 의도한겁니다 !
좋은 것 같아요 ! 스프링데이터jpa를 많이 안써봐서.. 알려주셔서 감사합니다 !!

2023-10-23 05:01 UTC, jundonghyuk commented on src/main/java/kitchenpos/domain/order/Order.java
> +        if (this.orderStatus == OrderStatus.COMPLETION) {
적용해보겠씀다 ㅎㅅ

2023-10-23 05:04 UTC, jundonghyuk commented on src/main/java/kitchenpos/domain/order/OrderTable.java
> +        this.empty = Boolean.FALSE;
불필요한 this 제거를 이야기하시는게 맞을까요 ?

2023-10-23 05:12 UTC, jundonghyuk commented on src/test/java/kitchenpos/repository/MenuRepositoryTest.java
> +    private EntityManager em;
DataJpa테스트를 쓰는 상황에서 fetchJoin이 제대로 되었는지를 확인을 해야했습니다.

그러려면 페치 조인을 이용한 조회메서드를 사용하기전에 영속성 컨텍스트를 밀어버려야 해서 엔티티 매니저를 주입받았습니다.

만약 페치조인이 제대로 되었다면 detach를 시켜도 lazyInit 예외가 나지 않습니다 !

그점을 검증하려고 의도했습니다 !

2023-10-23 05:13 UTC, jundonghyuk commented on src/test/java/kitchenpos/repository/MenuRepositoryTest.java
> +    private EntityManager em;
테스트 트랜잭션은 무조건 롤백이 되어가지고.. 강제 플러시후 영속성 컨텍스트를 클리어했습니다 !

2023-10-23 05:18 UTC, jundonghyuk commented on src/main/java/kitchenpos/repository/OrderTableRepository.java
> +    List<OrderTable> findAllByTableGroupIdWithOrders(@Param("tableGroupId") Long tableGroupId);
```
Java8 이상부터는 리플렉션을 통해 메서드의 매개변수 이름에 접근할 수 있다.

이러한 방식으로 스프링이 메서드 파라미터의 이름에서 JPQL 파라미터의 이름을 추론할 수 있다.

이 때  -parameters  flag를 컴파일과 함께 사용해야한다.

만약 Java8보다 버전이 낮거나 위 옵션을 설정하지 않았다면  @Param  을 사용하여 이름을 바인딩하자.
```

이런 이야기가 있어서.. 사실 명시적으로 주면 이런 상황까지 생각하지 않아도 되어서 명시적으로 주었습니다 !

무민은 어떻게 생각하시나요 ?

2023-10-23 06:16 UTC, jundonghyuk commented on src/main/java/kitchenpos/domain/order/TableGroup.java
> +    }
넵 일급컬렉션을 얘기하시는거죠 ?

2023-10-23 06:39 UTC, jundonghyuk commented
사실 모킹을 사용해서그런가.. 처음부터 테스트를 다시 구현하는 느낌이었어요.

그런데 JdbcTemplate -> JPA로 바꾸는 것은 제가 생각하기에 굉장히 큰 작업이라고 생각합니다.

그래서 테스트가 깨지는건 어쩔 수 없다고 생각해요 ! 테스트까지 리팩토링하면서 방향성을 잘 잡을 수 있었습니다.

그런데 Mockito를 이용하는게 구현에 의존적인건 어쩔 수 없는 것 같아요..

2023-10-24 10:19 UTC, parkmuhyeun commented on src/main/java/kitchenpos/domain/order/OrderTable.java
> +        this.empty = Boolean.FALSE;
Boolean.FALSE에서 FALSE였습니닷!

2023-10-24 10:46 UTC, parkmuhyeun commented on src/main/java/kitchenpos/repository/OrderTableRepository.java
> +    List<OrderTable> findAllByTableGroupIdWithOrders(@Param("tableGroupId") Long tableGroupId);
![image](https://github.com/woowacourse/jwp-refactoring/assets/76938931/9ae09f28-9786-4be6-bc8f-2d050d6f617f)

스프링부트를 사용하면 자동으로 켜져있는거 같아서 안 써줄거 같긴한데 요건 취향차이인거 같네요!

2023-10-24 10:56 UTC, parkmuhyeun approved these changes
안녕하세요 하디 😎
바쁘실텐데 이번에도 코멘트 잘 반영해주셔서 감사합니다~!

2단계 요구사항은 만족해서 이만 머지하겠습니다.
2단계 깔끔하게 잘 구현해주셔서 3단계 어떻게 설계하고 구현하실지 너무 궁금하네요!

다음단계때 봐요🚀

2023-10-24 10:56 UTC, parkmuhyeun commented on src/main/java/kitchenpos/domain/order/OrderStatus.java
> +        }
저는 개인적으로 try catch가 뭔가 지저분해보여서 다음과 같은 방법으로 했었는데요.
리뷰는 아니고 요런 방법도 있다 참고해주시면 좋을거 같아요!

```java
public static OrderStatus from(String name) {
        return Arrays.stream(values())
                .filter(orderStatus -> orderStatus.name().equals(name.toUpperCase()))
                .findAny()
                .orElseThrow(() -> new IllegalArgumentException("존재하지 않는 주문 상태입니다."));
}
```

2023-10-24 10:56 UTC, merged