[레거시 코드 리팩토링 - 3단계] 테오(최우성) 미션 제출합니다.
woowacourse/jwp-refactoring pull request #577
Opened 2023-10-20 16:47 UTC by woosung1223

안녕하세요 제이~
요즘 많이 바쁜 시기인데 리뷰하느라 늘 고생하십니다!

이번 step3는 의존성 리팩토링을 진행했습니다.
대략적인 변경사항은 다음과 같습니다.

1. 도메인 객체 간의 양방향 의존성을 제거했습니다.
2. 도메인 객체가 같은 제약사항을 공유하거나, 유사한 라이프사이클을 가지는 경우 하나의 그룹으로 묶었습니다.
3. 서로 다른 그룹의 도메인 객체들끼리는 ID 참조를 수행하도록 변경했습니다.

이렇게 도메인 객체의 경계는 분리했지만, 서비스는 어떻게 리팩토링 할 수 있을지 크게 감이 오지 않는 것 같습니다. Spring Event를 사용할지도 고민해봤는데, 익숙하지 않아서 그런 것인지 딱히 사용처가 보이지는 않는 것 같네요 😅 그래서 이 부분은 조언을 듣고 싶습니다!

또한, 1번과 3번에 해당하는 작업을 수행하면서 핵심 비즈니스 로직이 서비스로 많이 드러나게 되었는데, 이 부분도 자연스러운 현상인지 여쭤보고 싶네요!

2023-10-23 05:58 UTC, sosow0212 requested changes
안녕하세요 테오!

역시 이번에도 빠르게 잘 구현해주셨네요~
이미지 덕분에 구조를 쉽게 파악해서 리뷰하기 수월했습니다. 감사합니다 👍

이번 단계에서 의존성에 많이 신경 쓰신 게 느껴졌습니다.

몇 가지 코멘트를 남겨놨는데 테오의 생각이 궁금합니다!
수고하셨습니다 😀

2023-10-23 05:58 UTC, sosow0212 commented on README.md
> +![image](https://github.com/woosung1223/jwp-refactoring/assets/78679830/7d8f6933-a351-4f24-b485-0cf4abae8c7b)
와 구조 이미지 감사합니다 ㅎㅎ 보기 편하네요!

2023-10-23 05:58 UTC, sosow0212 commented on src/main/java/kitchenpos/table/domain/OrderTable.java
> +    private Long tableGroupId;
약결합 👍

2023-10-23 05:58 UTC, sosow0212 commented on src/main/java/kitchenpos/menu/domain/Menu.java
> +public class Menu {
이 부분은 궁금한게

MenuProduct가 있어야 Menu를 생성할 수 있기에 저는 Menu, MenuProduct는 세트라고 생각하고 라이프사이클도 동일하게 가져가야된다고 생각합니다~

그래서 OneToMany로 MenuProduct를 가지고 있어야 된다고 생각하는데 테오는 MenuProduct에서 ManyToOne으로 단방향 참조를 하게끔 설계하신 이유가 있나요??

테오의 생각이 궁금합니다 ㅎㅎ

2023-10-23 05:58 UTC, sosow0212 commented on src/main/java/kitchenpos/common/event/OrderEventListener.java
> +    private OrderService orderService;
```suggestion
    private final OrderService orderService;

    public OrderEventListener(final OrderService orderService) {
        this.orderService = orderService;
    }
```

2023-10-23 05:58 UTC, sosow0212 commented on src/main/java/kitchenpos/common/event/OrderEventListener.java
> +public class OrderEventListener {
이벤트로 풀어주는 거 너무 좋네요 👍

이벤트에 대한 테스트는 따로 안해도 될까요?! 

이미 기능에 대한 건 다른 부분에서 검증을 하고 계신 것 같은데 그래도 이벤트도 하나의 책임을 가지기 때문에 저는 하는게 좋다고 생각하는 편입니다 ㅎㅎ

2023-10-23 05:58 UTC, sosow0212 commented on src/main/java/kitchenpos/table/service/TableService.java
> +        eventPublisher.publishEvent(new ValidateAllOrderCompletedEvent(orderTable.getId()));
끊어주는 거 너무 좋네요!

2023-10-23 05:58 UTC, sosow0212 commented on src/main/java/kitchenpos/menu/repository/MenuRepository.java
>  public interface MenuRepository extends JpaRepository<Menu, Long> {
이 부분도 위에서 리뷰한 것처럼 Menu와 양방향 매핑을 해주고, Menu에서만 Repository를 가지면서 라이프사이클을 공유할 수 있지 않을까요?! 혹시 제가 놓친 부분 있다면 편하게 말씀해주세요 ㅎㅎ

2023-10-23 05:58 UTC, sosow0212 commented on src/main/java/kitchenpos/order/domain/OrderLineItem.java
>      private Order order;
이 부분도 Order와 OrderLineItem은 라이프사이클을 공유할 수 있을 것 같아요~

2023-10-23 05:58 UTC, sosow0212 commented on src/main/java/kitchenpos/order/domain/OrderLineItem.java
> +    private Long menuId;
약결합으로 의존성 덜어내기 아주 좋습니다 👍

2023-10-23 05:58 UTC, sosow0212 commented on src/main/java/kitchenpos/order/service/OrderService.java
> +public class OrderService {
여기다가 남겨둘게요!

> 그리고 1번과 3번에 해당하는 작업을 수행하면서 핵심 비즈니스 로직이 서비스로 많이 드러나게 되었는데, 이 부분도 자연스러운 현상인지 여쭤보고 싶네요!

비즈니스 로직이 서비스로 드러나게 되는 문제점을 저도 미션을 하면서 겪고 있습니다 ㅠㅠ
하지만, 서비스의 두께가 늘어나는 건 어쩔 수 없다고 생각해요. 

대신 이 부분은 어느정도의 트레이드오프라고 저는 생각하고 있습니다.
대신 의존성이 줄어들면 리팩토링이나 다른 부분에서 얻는 점도 많다고 생각합니다~

2023-10-23 06:11 UTC, woosung1223 commented on src/main/java/kitchenpos/menu/domain/Menu.java
> +public class Menu {
이 부분은 양방향 의존을 피하기 위해 MenuProduct에서 Menu로 단방향 매핑을 수행한 것인데요!

말씀해주신대로 `@OneToMany` 로 `Menu` 에서 `MenuProduct` 를 컬렉션으로 관리하는 경우에 단방향으로 구성할 수 있겠지만,
일대다로 관리하는 경우, INSERT 후 UPDATE 쿼리가 날아가기 때문에 menu_id에 대한 NOT NULL 제약조건을 위반하게 됩니다.

기존 레거시는 이미 외래키 참조를 NOT NULL로 수행하고 있고, 제약조건을 제거하는 것은 무리라고 판단해서 MenuProduct에서 단방향 참조를 수행하도록 했습니다!

저도 모든 협력이 `Menu` 통해 시작되고, `Menu`에서 컬렉션 형태로 관리하면 좋을 것 같다고 생각하는데요.
제이는 어떻게 생각하시나요?! 양방향 의존성을 제거하면서도, 외래키 NOT NULL 제약조건을 위반하지 않는 방법이 있을까요?

2023-10-23 06:14 UTC, woosung1223 commented on src/main/java/kitchenpos/common/event/OrderEventListener.java
> +    private OrderService orderService;
이 부분 코드 스타일이 맞지 않았군요 ㅎㅎ 

수정하겠습니다 👍👍

2023-10-23 06:29 UTC, woosung1223 commented on src/main/java/kitchenpos/common/event/OrderEventListener.java
> +public class OrderEventListener {
감사합니다!

말씀해주신 내용 토대로 조금 찾아보았는데요.

`@RecordApplicationEvents`와 `ApplicationEvents` 를 통해 테스트에서 이벤트가 발생하는지를 검증하는게 낫겠다고 판단했습니다.

사실 이전까지는 '이벤트를 통해 수행하고자 하는 기능에 대한 테스트가 존재한다면, 이벤트 발생 여부에 대한 테스트는 할 필요가 없다'고 생각했는데, (Spy와 비슷하다고 생각했습니다)

이벤트는 발생 여부도 상당히 중요한 것 같다는 생각이 들어서 테스트를 작성하게 되었습니다 👍

2023-10-23 06:31 UTC, woosung1223 commented on src/main/java/kitchenpos/menu/domain/Menu.java
> +public class Menu {
조금 알아보니 제가 JPA에 대한 이해도가 부족했다는 생각이 드네요! (nullable = false를 붙여주면 되는거였네요)

일대다 단방향으로 수행하도록 변경해보겠습니다 👍

2023-10-23 06:31 UTC, woosung1223 commented on src/main/java/kitchenpos/menu/repository/MenuRepository.java
>  public interface MenuRepository extends JpaRepository<Menu, Long> {
감사합니다!

말씀해주신대로 양방향 매핑을 수행해주고 Cascade + orphanRemoval로 라이프사이클을 완전히 관리하도록 수정해보겠습니다 👍

2023-10-23 06:32 UTC, woosung1223 commented on src/main/java/kitchenpos/order/service/OrderService.java
> +public class OrderService {
의견 감사합니다~ 저도 이게 어느정도 트레이드 오프라는 생각이 드는 것 같네요!

약결합으로 유지하는 대신 서비스가 두꺼워지는건 진짜 어쩔 수 없네요 😅

2023-10-23 08:49 UTC, sosow0212 commented on src/main/java/kitchenpos/common/event/OrderEventListener.java
> +public class OrderEventListener {
ㅎㅎ 좋습니다~

2023-10-23 08:50 UTC, sosow0212 commented on src/main/java/kitchenpos/order/service/OrderService.java
> +public class OrderService {
저도 이 부분을 어떻게 해소할 수 있을지 계속 고민하고 있는데 생각나면 의견 또 말씀 드릴게요 ㅎㅎ

2023-10-23 10:13 UTC, woosung1223 commented on src/main/java/kitchenpos/menu/repository/MenuRepository.java
>  public interface MenuRepository extends JpaRepository<Menu, Long> {
현재 PERSIST 이외의 Cascade 옵션은 필요하지 않다고 판단해 일단 PERSIST만 지정해두었습니다!

2023-10-23 10:33 UTC, woosung1223 commented
제이!

코멘트를 남길 부분이 없어서 여기에 남겨요~

제가 3단계 요구사항 중 
> 메뉴의 이름과 가격이 변경되면 주문 항목도 함께 변경된다. 메뉴 정보가 변경되더라도 주문 항목이 변경되지 않게 구현한다.

이 부분 빠뜨린 것 같아서, 해당 요구사항도 만족할 수 있도록 변경했습니다.
참고해주시면 감사하겠습니다!

2023-10-24 01:35 UTC, sosow0212 requested changes
테오 안녕하세요~

Merge 하려고 했는데 마지막으로 테오 생각이 궁금해서 한 번 더 RC합니다!

몇 가지 궁금한 게 있는데 편하게 의견 말씀해주세요 🙇🏻‍♂️

2023-10-24 01:35 UTC, sosow0212 commented on src/main/java/kitchenpos/menu/domain/MenuProduct.java
> +    @AttributeOverride(name = "value", column = @Column(name = "product_price_snapshot"))
해당 어노테이션을 이용해서 같은 Money라도 필드 명은 다르게 하시군요! 👍

2023-10-24 01:35 UTC, sosow0212 commented on src/main/java/kitchenpos/menu/dto/response/MenuProductResponse.java
> +    public static MenuProductResponse from(Menu menu, MenuProduct menuProduct) {
Menu를 받으면 import에 Menu 의존이 생기는데 그러면 `Long menuId`와 같은 약한 의존를 할 필요가 없을 것 같아요!
차라리 id를 넘겨받는 방식은 어떨까요?

2023-10-24 01:35 UTC, sosow0212 commented on src/test/java/kitchenpos/table/service/TableServiceTest.java
> +    void 빈_테이블로_변경할_때_주문이_모두_마쳤는지에_대한_검증_이벤트가_발행된다() {
이런 방법으로 테스트 하셨네요 👍 저도 배우고 갑니다~

2023-10-24 01:35 UTC, sosow0212 commented on src/main/java/kitchenpos/menu/service/MenuService.java
> +import kitchenpos.menugroup.domain.MenuGroup;
이 부분은 MenuGroupA 가 MenuA를 참조할 수 있고, MenuGroupB도 MenuA를 참조할 수 있다고 생각해서 (라이프 사이클이 다름) 의존하는 것이 맞을까요?!

2023-10-24 01:35 UTC, sosow0212 commented on src/main/java/kitchenpos/menu/service/MenuService.java
> +        Product product = productRepository.findById(menuProductRequest.getProductId())
테오 현재 priceSnapshot 때문에 Product를 꺼내서 금액을 만들어 주는 것 같아요~
이렇게 되면 현재 패키지가 Product 패키징도 의존하게 되는데 혹시 이벤트나 다른 방법을 쓸 순 없을까요?!

2023-10-24 01:35 UTC, sosow0212 commented on src/main/java/kitchenpos/order/service/OrderService.java
> +    private OrderLineItem createOrderLineItem(Order order, OrderLineItemRequest orderLineItemRequest) {
여기 매개변수 Order는 안 쓰이고 있습니다!

2023-10-24 01:35 UTC, sosow0212 commented on src/main/java/kitchenpos/order/service/OrderService.java
>      public OrderService(MenuRepository menuRepository, OrderRepository orderRepository,
현재 서비스에서 Menu, Table 패키지를 참조하는데 의도하신 건지 궁금합니다!

2023-10-25 00:58 UTC, woosung1223 commented on src/main/java/kitchenpos/menu/dto/response/MenuProductResponse.java
> +    public static MenuProductResponse from(Menu menu, MenuProduct menuProduct) {
오 그러네요 ㅎㅎ 해당 방향으로 리팩토링해도록 하겠습니다!

2023-10-25 05:30 UTC, woosung1223 commented on src/main/java/kitchenpos/menu/service/MenuService.java
> +import kitchenpos.menugroup.domain.MenuGroup;
MenuGroup이 어디서 사용되는지 확인해봤는데,

```java
private Menu saveMenu(CreateMenuRequest request) {
    MenuGroup menuGroup = menuGroupRepository.findById(request.getMenuGroupId())
            .orElseThrow(MenuGroupNotFoundException::new);

    return new Menu(menuGroup.getId(), request.getName(), request.getPrice());
}
```
현재 MenuGroup을 찾아서 해당하는 엔티티의 ID를 Menu에 넣어주고 있습니다.

이런 조회 기능은 이벤트로 분리하기도 애매한 것 같은데, 이 부분은 어떻게 처리하는게 나을까요?

단순히 아래와 같이 구성하면

```java
private Menu saveMenu(CreateMenuRequest request) {
    return new Menu(request.getMenuGroupId(), request.getName(), request.getPrice());
}
```

존재하지 않는 메뉴 그룹에 대한 검증은 불가능합니다.
현재 외래키에 대한 NOT NULL 제약조건이 걸려 있으므로 예외가 발생하긴 할텐데, 비즈니스적으로 의미가 있는 예외가 아닌 데이터 접근 계층 관련 예외가 발생하게 됩니다.

어떻게 해결할 수 있을지 가장 큰 고민이 되는 부분이네요 🥲

2023-10-25 05:35 UTC, woosung1223 commented on src/main/java/kitchenpos/menu/service/MenuService.java
> +import kitchenpos.menugroup.domain.MenuGroup;
아 이벤트로 해결할 수 있겠군요!

검증은 이벤트로 하고, ID는 DTO에 있는 값을 그대로 쓰면 될 것 같습니다.

변경해보도록 하겠습니다!

2023-10-25 05:55 UTC, woosung1223 commented on src/main/java/kitchenpos/order/service/OrderService.java
>      public OrderService(MenuRepository menuRepository, OrderRepository orderRepository,
그렇습니다! 이번 단계에서는 패키지 의존성 사이클만 줄였는데요,

생각해보니 패키지 의존성을 최소화하는 것도 좋은 연습이 될 것 같습니다~

최대한 줄여보도록 하겠습니다!

2023-10-25 07:53 UTC, woosung1223 commented on src/main/java/kitchenpos/menu/service/MenuService.java
> +        Product product = productRepository.findById(menuProductRequest.getProductId())
말씀해주신 내용 토대로 고민을 해보았는데요,

MenuProduct를 만들기 위해서는 생성 시점에 Product의 가격이 꼭 필요한데, 어떻게 해결해야 할지 막막하네요 ㅠ

이벤트도 처리하기도 애매한 것 같고, DIP를 적용해 Product의 슈퍼타입을 하나 만드는 편이 나을까요?
그렇지만 그 방법도 크게 안정적이라는 느낌은 못 받는 것 같네요.. 🥲

2023-10-25 07:55 UTC, woosung1223 commented on src/main/java/kitchenpos/order/service/OrderService.java
>      public OrderService(MenuRepository menuRepository, OrderRepository orderRepository,
<img width="697" alt="image" src="https://github.com/woowacourse/jwp-refactoring/assets/78679830/f7a59325-205d-4c22-acf1-f42af16623be">

변경된 패키지 의존성입니다! 대부분을 이벤트로 분리를 했고, 루트를 통한 로직 수행은 해당 애그리거트 내에서만 수행되도록 변경했습니다. 참고로 DTO에서 반환값을 내려줘야 하는 이슈로 `TableGroup` -> `Table` 의존은 남겨뒀습니다!

`Menu` -> `Product` 의존은 위 코멘트에서 말씀드렸다시피 아직 어떻게 해결할지 감이 안오는 것 같습니다! 조금 더 생각해봐야 할 것 같은데 제이의 의견도 궁금하네요!

2023-10-26 01:45 UTC, sosow0212 requested changes
테오 의존성이 많이 줄었네요! 수고하셨습니다.

코멘트로 제 생각을 남겨봤는데 이번 리뷰 단계에서는 서로 의견을 나눠보는 것도 좋을 것 같아요 😎

좋은 질문 덕분에 저도 많은 고민을 할 수 있어서 좋네요!

테오의 생각도 남겨주시고 언제든지 리뷰 요청 주세요~

2023-10-26 01:45 UTC, sosow0212 commented on src/main/java/kitchenpos/common/event/MenuEventListener.java
> +    public void validateMenuExists(ValidateMenuExistsEvent event) {
저랑 방식이 달라서 제 코드를 다시 보니깐 제가 이벤트에서 예외를 다루고 있었네요 😅
테오처럼 이벤트에 비즈니스 로직을 노출시키지 않는 방법이 더 좋은 것 같아요 ㅎㅎ

하나 배우고 갑니다~

2023-10-26 01:45 UTC, sosow0212 commented on src/main/java/kitchenpos/menu/dto/response/MenuProductResponse.java
> +    public static MenuProductResponse from(Long menuId, MenuProduct menuProduct) {
👍

2023-10-26 01:45 UTC, sosow0212 commented on src/main/java/kitchenpos/menu/service/MenuService.java
> -import kitchenpos.menugroup.domain.MenuGroup;
의존성 하나를 줄였네요 👍

2023-10-26 01:45 UTC, sosow0212 commented on src/main/java/kitchenpos/menu/service/MenuService.java
> +    public void validateMenuExists(Long menuId) {
이 부분에서 `ReadOnly=true` 를 하는 것이 좋을 것 같습니다!

2023-10-26 01:45 UTC, sosow0212 commented on src/main/java/kitchenpos/table/service/TableService.java
> +                .collect(Collectors.toList());
이 부분은 레포지토리에 jpa 메서드 하나 만들어서 한 번에 해결할 수 있을 것 같아요~
예외가 있으니 findAllBy~~Ids로 조회한 후에 `List<Long> orderTableIds`의 size비교해서  Exception 하나 날려도 좋아보입니다!

2023-10-26 01:45 UTC, sosow0212 commented on src/main/java/kitchenpos/table/service/TableService.java
> +        if (orderTables.size() < 2) {
상수 처리도 해주세요~

2023-10-26 01:45 UTC, sosow0212 commented on src/main/java/kitchenpos/order/service/OrderService.java
>      public OrderService(MenuRepository menuRepository, OrderRepository orderRepository,
저도 테오랑 비슷한 고민을 겪었는데요.
제 생각은 이렇습니다! (단순 제 생각일뿐 적당히 걸러서 들어주세요 ㅎㅎ)

먼저 지금 MenuService에서 Product를 의존하는 부분은 
`createMenuProduct` 부분에서 존재하는 상품인지 확인하고 있습니다.

이 부분은 제 생각이지만 Event로 보내서 product쪽에 id를 보내고 존재하는지 확인해주면 좋을 것 같습니다!
그리고 Event가 성공적으로 된다면 `return new MenuProduct(menuProductRequest.getProductId(), menuProductRequest.getQuantity(), priceSnapshot);` 이렇게 생성을 해줄 수 있겠네요 ㅎㅎ

이렇게 한다면 현재 Product 패키지 의존이 사라지게 됩니다!

어떻게 생각하시나요? 더 좋은 방법 있다면 공유 부탁드려요 🙇🏻‍♂️

2023-10-26 11:58 UTC, woosung1223 commented on src/main/java/kitchenpos/order/service/OrderService.java
>      public OrderService(MenuRepository menuRepository, OrderRepository orderRepository,
오 좋은 의견 감사합니다 ㅎㅎ

말씀해주신 부분은 이해했습니다!
Product가 존재하는지 확인하는 부분은 이벤트로 분리할 수 있겠네요!

그런데 priceSnapshot을 생성하기 위해서는 product의 price 값을 알아야 하는데, 이를 어떻게 처리할 수 있을까요?

```java
private MenuProduct createMenuProduct(MenuProductRequest menuProductRequest) {
    Product product = productRepository.findById(menuProductRequest.getProductId())
            .orElseThrow(ProductNotFoundException::new);
    Money priceSnapshot = new Money(product.getPrice());

    return new MenuProduct(product.getId(), menuProductRequest.getQuantity(), priceSnapshot);
  }
```

event가 성공적으로 수행되는 경우 어떻게 product의 가격을 저장할 수 있을지 고민이 드는 것 같습니다.

제이의 생각은 어떠신가요?

2023-10-26 12:00 UTC, woosung1223 commented on src/main/java/kitchenpos/menu/service/MenuService.java
> +    public void validateMenuExists(Long menuId) {
아하 이 부분은 클래스 레벨에서 `@Transactional(readOnly = true)` 를 걸어주고 있어서 생략했습니다! 👍

2023-10-26 12:30 UTC, woosung1223 commented on src/main/java/kitchenpos/table/service/TableService.java
> +                .collect(Collectors.toList());
변경했습니다! 👍 훨씬 깔끔하네요!

2023-10-26 12:38 UTC, woosung1223 commented on src/main/java/kitchenpos/common/event/MenuEventListener.java
> +    public void validateMenuExists(ValidateMenuExistsEvent event) {
감사합니다! 그런데 이벤트 관련 로직을 모두 서비스에서 받아서 처리하다보니 서비스가 상당히 뚱뚱해지네요... ㅋㅋㅋ

2023-10-27 01:50 UTC, sosow0212 commented on src/main/java/kitchenpos/order/service/OrderService.java
>      public OrderService(MenuRepository menuRepository, OrderRepository orderRepository,
아 그러네요 제가 반대로 제대로 이해하지 못했네요 😅

코드를 다시 확인해보니 테오 말대로 끊어내기 힘들어보입니다! (혹시 방법이 있다면 저도 알려주세요..! 고민을 해봐도 이 부분은 저도 잘 모르겠네요 ㅠㅠ)

하지만 양방향이 아닌 단방향 참조이고 흐름은 맞으니 이정도는 괜찮지 않을까 싶습니다!

2023-10-27 01:52 UTC, sosow0212 approved these changes
테오 안녕하세요~

3단계 진행 하느라 수고 많으셨습니다! 이번 미션동안 테오한테 배운게 많네요 ㅎㅎ
감사합니다!

다음 단계 바로 진행하시면 될 것 같습니다 👍

2023-10-27 01:52 UTC, merged