[레거시 코드 리팩터링 - 2단계] 우가(윤정욱) 미션 제출합니다.
woowacourse/jwp-refactoring pull request #584
Opened 2023-10-21 16:20 UTC by wugawuga

안녕하세요 쥬니!!

먼저 예비군 다녀오느라 수고 많으셨어요 ㅎㅎ
마지막 데모데이까지 하면서 미션을 진행하다보니 정말 시간이 빠르게 흐른것 같습니다!!

커밋을 잘게 나누고 싶었지만, 리팩터링 진행하다보니 커다란 커밋이 되고 말았네요
먼저 사과드립니다 ㅠㅠ

이번 리뷰도 잘 부탁해용 😚

2023-10-22 18:18 UTC, cpot5620 requested changes
안녕하세요 우가 ! 

이번 주말에는 축구를 이틀이나 다녀와서, 내일 리뷰를 진행할까 했는데..
하염없이 리뷰를 기다리고 있는 우가의 모습이 아른거리더군요.
그래서, 리뷰를 하고 잠을 자야 마음이 편할 것 같아서 바로 노트북을 열었습니다 ㅎㅎ

작성하고 보니, 리뷰 개수가 27개가 되네요..
개수는 많지만 사소한 리뷰가 대부분이라서 다음 단계에서 반영해도 좋을 것 같다고 생각했어요 !
하지만, 이번 단계 목표가 `서비스 리팩토링` 즉, 비즈니스 관련 로직을 최대한 도메인 쪽으로 빼는 거라고 생각이 들었고, 반영 가능한 부분이 존재하는 것 같아서 RC로 결정하게 되었습니다.

바쁘고, 힘들겠지만 끝까지 화이팅입니다 🔥🔥🔥🔥🔥🔥

2023-10-22 18:18 UTC, cpot5620 commented on src/main/java/kitchenpos/application/MenuGroupService.java
> +    public MenuGroupService(MenuGroupRepository menuGroupRepository) {
이 녀석만 final 키워드가 빠져있는 것 같아열

2023-10-22 18:18 UTC, cpot5620 commented on src/main/java/kitchenpos/application/dto/MenuCreateDto.java
> +    private final List<MenuProductCreateDto> menuProductCreateDtos;
해당 필드 명을 `menuProductCreateDtos`라고 두면, 실제 json 형식의 Request Body를 작성할 때에 아래와 같이 작성해야 하지 않나요 ? (잘 모름..)
만약 그렇다면, 조금 어색한 변수(key)명이지 않을까 싶어서요. (물론, 기능적으로 문제가 되는 부분은 없을 것 같습니다)

```
    // 생략
menuProductCreateDtos : [
    {
        productId : 1L
        quantity : 1L
    }
]
```

2023-10-22 18:18 UTC, cpot5620 commented on src/main/java/kitchenpos/application/dto/MenuGroupDto.java
> +public class MenuGroupDto {
해당 클래스가 외부에서 사용되고 있지 않는 것 같아요 !

2023-10-22 18:18 UTC, cpot5620 commented on src/main/java/kitchenpos/application/dto/MenuGroupCreateDto.java
> +}
필드 개수가 2개 이상일 경우에는 기본생성자 없이, Jackson 라이브러리가 getter 메서드를 통해 필드를 초기화 해주는데요.
필드 개수가 1개인 경우, `@RequestBody`를 사용하였을 때, 기본 생성자가 없다는 예외가 발생해요.

그래서 저는 모든 dto에 `private 기본 생성자`를 만들어두는 편인데요. (intellij로 빌드할 경우에도 문제가 발생하기도 함)
우가는 어떻게 생각하세요 ?

2023-10-22 18:18 UTC, cpot5620 commented on src/main/java/kitchenpos/application/exception/MenuAppException.java
> +public class MenuAppException extends KitchenPosException {
커스텀 예외 👍👍👍👍👍👍

2023-10-22 18:18 UTC, cpot5620 commented on src/main/java/kitchenpos/domain/Menu.java
>      }
1. 해당 메서드는 정팩메에서만 호출되고 있어요. 그렇다면, `private`으로 두어도 괜찮을 것 같은데 `public`으로 두신 이유가 있을까요 ? 
2. 메서드 명은 `isOverPrice`인데, 금액이 0원 미만인지도 검증하고 있네요. 의도하신걸까요 ?
3. `Objects.isNull`과 같은 메서드는 docs에 따르면, 다음과 같이 설명하고 있어요.
> API Note: This method exists to be used as a java.util.function.Predicate, filter(Objects::isNull)

즉, 람다식에서 메서드 참조를 사용하기위해 존재한다는 의미인데요.
그렇다는 것은, 위와 같은 상황에서는 `price == null` 이라는 문장을 사용하라는 뜻인 것 같아요.
이에 대한, 우가의 생각이 궁금해요 !

2023-10-22 18:18 UTC, cpot5620 commented on src/main/java/kitchenpos/domain/Menu.java
> +        menuProducts.add(menuProduct);
새로운 menuProduct가 추가됨에 따라, `price`와 관련된 제약 조건이 문제가 발생할 수 있을 것 같아요.
별도의 검증이 필요하지는 않을까요 ?

2023-10-22 18:18 UTC, cpot5620 commented on src/main/java/kitchenpos/domain/MenuProduct.java
> +        this.menu = menu;
연관관계 때문에, 과감하게 setter를 열어주셨군요 !
제 코드에는 `MenuProduct 없이 Menu 생성 -> MenuProduct 생성 -> mneu.addMenuProduct 호출` 과 같이, 어색한 흐름이 존재한답니다. 오히려, setter를 열어주는 편이 나은 것 같기도 하네요 ㅋㅋ

아마 이 부분은 3단계에서 해결되지 않을까 싶네요..

2023-10-22 18:18 UTC, cpot5620 commented on src/main/java/kitchenpos/domain/MenuGroup.java
> +        if (!StringUtils.hasText(name)) {
와.. 이런 방법도 있구나..
배워갑니다 👍👍👍

2023-10-22 18:18 UTC, cpot5620 commented on src/main/java/kitchenpos/domain/Order.java
>      private LocalDateTime orderedTime;
`orderedTime`을 매번 `LocalDateTime.now()`로 초기화해주고 있군요 !
`@CreatedDate`를 사용하는 방법도 있었을 것 같은데요.
사용하지 않으신 다른 이유가 있는지 궁금해요 !

2023-10-22 18:18 UTC, cpot5620 commented on src/main/java/kitchenpos/domain/Order.java
> +        }
검증 시점을 for문 이전으로 앞당기는 것은 어떻게 생각하세요 ?

`orderTable`상태로 인해, 해당 객체를 생성할 수 없는 상태였다면, 불필요한 연관관계 매핑 작업이 수행될 필요가 없을 것 같아서요 ㅎㅎ

2023-10-22 18:18 UTC, cpot5620 commented on src/main/java/kitchenpos/domain/Order.java
>      }
상태를 변경할 때에도 제약조건이 존재하잖아요 ?
ex) COMPLETION 상태일 경우, 다른 상태로 변경하지 못함 등

현재는 Service 계층에서 위와 같은 검증을 수행해주고 있는 것 같아요.
해당 검증을 도메인에서 수행하는 것에 대해서는 어떻게 생각하시나요 ?

2023-10-22 18:18 UTC, cpot5620 commented on src/main/java/kitchenpos/domain/Order.java
> +    @OneToMany(mappedBy = "order", fetch = FetchType.LAZY, cascade = CascadeType.PERSIST)
`@OneToMany`의 패치 타입 기본 값은 지연로딩인데요.
이를 일부러 명시해주신 것인가요 ? 그렇다면, 이유가 궁금해요 !

2023-10-22 18:18 UTC, cpot5620 commented on src/main/java/kitchenpos/domain/OrderRepository.java
> +        final List<OrderStatus> orderStatuses);
파라미터로 `OrderTable`을 넘기는 것과 `OrderTable의 ID`를 넘기는 것은 다르게 동작하나요 ? 잘 모르는데.. 알려주세요 !!

만약, 다르게 동작한다면 ID를 사용하지 않고, 위와 같이 구현하신 이유가 궁금해요 !

2023-10-22 18:18 UTC, cpot5620 commented on src/main/java/kitchenpos/domain/OrderTable.java
>      }
재가 이해한 바로는, 우가는 기본 생성자와 정팩메를 아래와 같은 기준으로 나누고 있는 것 같아요.
기본 생성자 -> id 값과 함께 생성
정팩메 -> id 값 없이 생성

제가 추측한 것이 맞다면, 해당 생성자는 id 값이 빠져있는 것 같은데요 !?

---

아니네.. 연관관계를 맺어주는지에 따라 사용하시나보네요..
ㅠ_ㅠ 무시하셔도 됩니다.

2023-10-22 18:18 UTC, cpot5620 commented on src/main/java/kitchenpos/domain/OrderTable.java
> +
이 녀석도 커스텀 예외를 사용하는 것은 어떨까요 ? + 매직 넘버 제거도 !!

2023-10-22 18:18 UTC, cpot5620 commented on src/main/java/kitchenpos/domain/Product.java
>      }
해당 생성자에서도 `validate` 메서드가 호출되어야 하지 않을까요 ?

2023-10-22 18:18 UTC, cpot5620 commented on src/main/java/kitchenpos/domain/Menu.java
> +        final MenuGroup menuGroup, final List<MenuProduct> menuProducts) {
id 값을 파라미터로 받는 생성자가 `생성자 체이닝`에서만 사용되고 있는데요.
해당 생성자가 `존재해야 하는 이유` 혹은, `존재해야 한다면 public으로 존재해야하는 이유`가 궁금합니다 !

2023-10-22 18:18 UTC, cpot5620 commented on src/main/java/kitchenpos/domain/TableGroup.java
> +        if (CollectionUtils.isEmpty(orderTables) || orderTables.size() < 2) {
매직 넘버 제거해주세요 !!

2023-10-22 18:18 UTC, cpot5620 commented on src/main/java/kitchenpos/domain/TableGroup.java
> +                throw new IllegalArgumentException();
이 녀석도 커스텀 예외는 어때요 !?

2023-10-22 18:18 UTC, cpot5620 commented on src/main/java/kitchenpos/application/TableGroupService.java
> +        System.out.println("--------------------------------");
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
디버깅 sout으로 하는거 딱 걸렸죠?

2023-10-22 18:18 UTC, cpot5620 commented on src/main/java/kitchenpos/application/OrderService.java
>          }
`OrderLineItems`가 존재해야한다는 것은 도메인 제약조건으로 알고 있는데요 !
해당 검증 로직을 도메인쪽으로 빼보는 것은 어떨까요 ?

일급 컬렉션을 사용하면, 조금은 깔끔하게(?) 구현할 수 있을 것 같아요.

2023-10-22 18:18 UTC, cpot5620 commented on src/main/java/kitchenpos/application/OrderService.java
> +        return orderLineItemDtos.stream().map(
한 줄에는 하나의 점(.)만 찍는 컨벤션이 다른 곳에서는 잘 지켜져있어서 박수 쳤는데, 놓친 부분이 있으신 것 같네요 !!

2023-10-22 18:18 UTC, cpot5620 commented on src/main/java/kitchenpos/application/OrderService.java
>          }
해당 검증 로직을 `Order.changeOrderStatus()`에서 수행해준다면, 깔끔해지겠군요 !

2023-10-22 18:18 UTC, cpot5620 commented on src/main/java/kitchenpos/application/TableGroupService.java
>          }
이런 검증도 도메인쪽(TableGroup.ungroup)으로 빼는 것은 어떠세요 !?

2023-10-22 18:18 UTC, cpot5620 commented on src/main/java/kitchenpos/application/TableService.java
>          }
이것도 도메인쪽으로 ? (OrderTable.changeEmpty())

2023-10-22 18:18 UTC, cpot5620 commented on src/main/resources/application.properties
> +spring.jpa.open-in-view=false
OSIV를 비활성화 해주셨군요 !

한 가지 우려되는 부분은 현재 Controller에서 도메인 객체를 반환해주고 있다는 점인데요.
트랜잭션이 종료됨에 따라, 영속성 컨텍스트가 반환(종료 ?)되잖아요 ?
하지만, 도메인 객체 내부에 지연로딩으로 설정되어 있는 필드들은 값이 초기화 되지 않은 상태일 것이고, Controller에서 해당 객체들을 Response Body로 변환해주는 과정에서 문제가 발생할 수 있을 것 같아요.

이러한 문제를 해결하는 방법으로는 
1. OSIV 활성화
2. Service에서 지연 로딩으로 되어 있는 필드들을 모두 초기화 해준 뒤 반환 (DTO 사용)
이 있겠네요 !

사실 저는 OSIV 활성화 해두어도 된다고 생각해요.
대용량 트래픽을 다루어야 하는 상황이 아니고는 발생할 수 있는 문제가 없다고 생각하거든요 !

Controller에서 도메인 객체의 데이터를 바꾸더라도, 영속성 컨텍스트가 flsuh & close가 호출되는 것이 아니라 단순히 close만 호출되니까요 !

2023-10-23 01:22 UTC, wugawuga commented on src/main/java/kitchenpos/domain/Order.java
> +        }
동의합니다!!

2023-10-23 01:24 UTC, wugawuga commented on src/main/java/kitchenpos/domain/Order.java
>      }
이 부분에 대해서는 Application 에서 수행하는게 더 낫지 않을까 판단하였습니다.
이유는 완료 이후에 상태가 추가될 수 있어서
```java
if (savedOrder.isSameStatus(OrderStatus.COMPLETION)) {
    throw new OrderAlreadyCompletedException(orderId);
}
```
이와 같이 완료 상태인지 검증을 먼저 하는 방식으로 구현해 보았습니다.

2023-10-23 01:26 UTC, wugawuga commented on src/main/java/kitchenpos/domain/Order.java
> +    @OneToMany(mappedBy = "order", fetch = FetchType.LAZY, cascade = CascadeType.PERSIST)
명시하는 이유는,

당연히 다들 알겠지만, 기계처럼 사용하다보면 내부 동작을 깜빡할 수도 있다고 생각합니다.
그래서 한번 더 One-to-many 옵션을 보기위해 클래스를 타고가야하는 흐름을 방지할 수 있습니다.

2023-10-23 01:30 UTC, wugawuga commented on src/main/java/kitchenpos/domain/OrderRepository.java
> +        final List<OrderStatus> orderStatuses);
똑같이 동작합니다!
Entity 를 넘겨주는 이유는 조금 더 ORM 답게 사용하기 위해서입니다!

객체를 넘겨준다면 JPA 에서는 id 를 추출해 쿼리가 나가게 됩니다!

2023-10-23 01:33 UTC, wugawuga commented on src/main/java/kitchenpos/domain/OrderTable.java
> +
예리하시군요,,,!!

꼼꼼한 리뷰 합격점 드리겠습니다!!

깜빡했는데 챙겨주셔서 감사합니다 ㅎㅎㅎ

2023-10-23 01:38 UTC, wugawuga commented on src/main/java/kitchenpos/application/TableGroupService.java
> +        System.out.println("--------------------------------");
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2023-10-23 01:39 UTC, wugawuga commented on src/main/java/kitchenpos/application/OrderService.java
>          }
이 부분은 위에서 말씀드린 부분이랑 동일합니다!

2023-10-23 01:40 UTC, wugawuga commented on src/main/java/kitchenpos/application/TableService.java
>          }
좋습니다!

2023-10-23 01:42 UTC, wugawuga commented on src/main/resources/application.properties
> +spring.jpa.open-in-view=false
이부분은 깜빡하고 원복하지 않았네용! 다시 돌렸습니다!

2023-10-23 01:47 UTC, wugawuga commented on src/main/java/kitchenpos/application/TableGroupService.java
>          }
이 부분은 도메인으로 넣게되면 List<OrderTable> 과 매핑되어 있는 N개의 order 쿼리가 전부 호출되게 됩니다.

그 부분을 해결하기위해 application 단에서 findAllByOrderTableIn 로 한번에 해결했습니다.

2023-10-23 01:50 UTC, wugawuga commented on src/main/java/kitchenpos/application/OrderService.java
>          }
dto 이기 때문에 Application 단에서 검증하려고 했습니다!!

Order.of 에서 OrderLineItems 를 한번더 검증하겠습니다!

2023-10-23 02:05 UTC, wugawuga commented on src/main/java/kitchenpos/domain/Menu.java
> +        final MenuGroup menuGroup, final List<MenuProduct> menuProducts) {
기존에 테스트 때문에 필요하여서 했다가 다시 삭제했습니다!

2023-10-23 02:07 UTC, wugawuga commented on src/main/java/kitchenpos/domain/Product.java
>      }
this 로 다른 생성자로 체이닝 되면서 체이닝 된 생성자에서 로직이 수행됩니다!

validate 를 두번해야하는 이유가 궁금합니다!

2023-10-23 02:10 UTC, wugawuga commented on src/main/java/kitchenpos/application/dto/MenuCreateDto.java
> +    private final List<MenuProductCreateDto> menuProductCreateDtos;
변수명을 MenuProducts 로 바꾸었습니다.
dto 로 들어온다면 확실히 조금 어색하네여 ㅎㅎㅎ

2023-10-23 02:14 UTC, wugawuga commented on src/main/java/kitchenpos/application/dto/MenuGroupCreateDto.java
> +}
동의합니다.

하지만 쥬니가 말씀해주신 기본생성자는 final 선언때문에 동작을 하지 않을 것 같습니다!
dto 또한 저는 final 선언을 하기 때문에 JsonCreator 와 같은 매핑이 필요할 것 같습니다.

2023-10-23 02:26 UTC, wugawuga commented on src/main/java/kitchenpos/domain/Order.java
>      private LocalDateTime orderedTime;
Entity 가 시간을 관리해야 된다고 생각합니다.
Entity 객체가 생성될 때 같이 시간이 생성되어야 합니다.
하지만 CreatedDate 는 객체가 저장되는 순간 현재시간을 삽입하기 때문에 관리주체가 JPA 로 바뀌게 됩니다.
그래서 객체가 시간을 관리할 수 없다고 생각해 이렇게 진행했습니다!

2023-10-23 02:27 UTC, wugawuga commented on src/main/java/kitchenpos/domain/MenuProduct.java
> +        this.menu = menu;
3단계에서 의존성을 끊으면서 재밌게 리팩터링 할 수 있을 것 같아요

2023-10-23 02:31 UTC, wugawuga commented on src/main/java/kitchenpos/domain/Menu.java
> +        menuProducts.add(menuProduct);
<img width="977" alt="image" src="https://github.com/woowacourse/jwp-refactoring/assets/91244090/31c19b71-8814-416c-bbe7-e17bf858f792">

isOverPrice 로 검증하고 있습니다!

이 메소드는 validatePrice 로 수정하였습니다

2023-10-23 02:33 UTC, wugawuga commented on src/main/java/kitchenpos/domain/Menu.java
>      }
1. 기존에 도메인 밖에 존재하던 메소드여서 수정을 깜빡했습니다.
2. isOverPrice 는 애매해서 checkPriceCondition 로 수정했습니다.
3. 람다식에서 메서드 참조를 위해 존재하지만, 비교 연산자 같은 경우 숫자만 하려고 합니다. 그리고 커스텀 함수형 인터페이스를 만들 수도 있지만, 이미 있는데 만들어야하나? 라는 생각에 그냥 사용했습니다.

2023-10-23 02:35 UTC, wugawuga commented
안녕하세요 쥬니!!

새벽에도 열심히 리뷰해주셔서 감사합니다!!!

사소한 리뷰라니요,,, 생각이 많아지는 리뷰였습니다.

최대한 반영을 할 부분은 했고 나머지는 코멘트로 답변남겼습니다.

항상 감사합니다 😊

2023-10-23 06:52 UTC, cpot5620 commented on src/main/java/kitchenpos/domain/Menu.java
> +        menuProducts.add(menuProduct);
질문 의도가 잘못 전달된 것 같네요.
해당 `addMenuProduct` 메서드가 public이다 보니, 외부에서 임의로 데이터를 추가해줄 수 있을 거라고 생각했어요.
그래서, 별도의 검증이 필요하지 않을까 싶었습니다.

2023-10-23 06:53 UTC, cpot5620 commented on src/main/java/kitchenpos/domain/Order.java
>      }
관점의 차이인 것 같아요.

`COMPLETION 상태인 Order는 상태를 변경할 수 없다.`를 도메인 규칙으로 보는 것인지 아닌지..?

2023-10-23 06:54 UTC, cpot5620 commented on src/main/java/kitchenpos/domain/Product.java
>      }
ㅏ................ 미안합니당 ㅎㅎ

2023-10-23 06:57 UTC, cpot5620 approved these changes
안녕하세요 우가 ~!

빠르게 반영해주셨네요. 확인했습니다 ㅎㅎ
지난 리뷰에서 놓친 부분이 있어서, 해당 코멘트에 남기도록 할게요.
현재, domain 객체를 Response로 넘겨줌에 따라, 순환 참조 문제가 발생하는 것 같아요.
```
023-10-23 15:49:32.663 ERROR 39462 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.http.converter.HttpMessageNotWritableException: Could not write JSON: Infinite recursion (StackOverflowError); nested exception is com.fasterxml.jackson.databind.JsonMappingException: Infinite recursion (StackOverflowError) (through reference chain: kitchenpos.domain.MenuProduct["menu"]->kitchenpos.domain.Menu["menuProducts"]-
// 생략
java.lang.StackOverflowError: null
```

실제 어플리케이션을 실행시켜, GET 요청을 보내면 위와 같은 예외 메세지가 발생하고 있어요 !
이 부분은 3단계 진행하시면서, 해결해보시면 될 것 같아요 !
화이팅입니다 🔥

2023-10-23 06:57 UTC, merged

2023-10-23 07:14 UTC, wugawuga commented on src/main/java/kitchenpos/domain/Order.java
>      }
저는 도메인이라기 보다 Application 단의 규칙이라고 생각했습니다!

2023-10-23 07:16 UTC, wugawuga commented on src/main/java/kitchenpos/domain/Menu.java
> +        menuProducts.add(menuProduct);
이해했습니다! 해당 addMenuProduct 메소드는 아무곳에서도 사용되지 않아서 삭제했습니다!