[레거시 코드 리팩터링 - 2단계] 제리(권현재) 미션 제출합니다.
woowacourse/jwp-refactoring pull request #585
Opened 2023-10-21 16:26 UTC by hyeonjerry

베베 안녕하세요!!

도메인 지식이 부족했는지 미션을 진행하고 롤백하고 다시 구현하는 것을 반복하다 보니 너무 늦어졌네요 ㅠㅠ

전체 서비스를 리팩터링 하다 보니 PR 단위가 너무 커져서 보기 힘드시겠지만
이번 단계도 리뷰 잘 부탁드립니다🙇‍♂️

2023-10-22 10:56 UTC, wonyongChoi05 requested changes
안녕하세요 제리! 2단계 미션이 워낙 할게 많기도 하고 그동안 일정도 빡빡해서 힘드셨을텐데.. 주말동안 정말 수고 많으셨습니다.. 3단계 미션이 의존성 관련 리팩터링이여서 연관관계나 도메인 관련 코멘트는 이번 단계에서 달지 않았어요! (실제로 도메인 설계는 굉장히 잘했다고 느껴지기도 했습니다..) 변경된 사항이 워낙 많다보니 코멘트도 조금(?)은 많아졌을텐데 천천히 읽어주세요 ㅎㅎ 4레벨 너무 수고하셨고, 남은 주말도 잘 보내세요!

2023-10-22 10:56 UTC, wonyongChoi05 commented on README.md
> +- [ ] 3개 이상의 인스턴스 변수 갖지 않기
2단계 요구사항도 잘 적어주셨군요! 각각의 태스크가 완료되었다면 체크해주는건 어떨까요?

2023-10-22 10:56 UTC, wonyongChoi05 commented on src/main/java/kitchenpos/application/MenuService.java
> +            throw new IllegalArgumentException();
menu에게 가격이 적절한지 물어보고 예외는 서비스 레이어에서 던지네요! 저는 개인적으로 도메인 던질 수 있는 예외라면, 즉 엔티티 자체로만 판단할 수 있는 요구사항이라면 도메인에게 예외를 던지는 책임까지 전가하는데, 제리는 보통 서비스에서 모든 예외를 처리하시나요? 제리의 의견이 궁급합니다.

2023-10-22 10:56 UTC, wonyongChoi05 commented on src/main/java/kitchenpos/domain/menu/MenuProducts.java
> +public class MenuProducts {
오.. 일급 컬렉션으로 한 번 감싼게 인상깊네요! 저도 xToMany 관계에서 조회할 때 일급컬렉션을 사용했을 때 서비스 로직이 훨씬 간결해지는 효과가 있더라구요! 그 과정에서 궁금했던게 "그럼 모든 xToMany 관계에서 일급컬렉션을 사용해야하는걸까?"라는 생각이 들었어요. 제리는 이 부분에 대해서 어떻게 생각하시나요?

2023-10-22 10:56 UTC, wonyongChoi05 commented on src/main/java/kitchenpos/domain/menu_product/MenuProduct.java
> +    private Product product;
Menu와 MenuProduct는 양방향, Product와 MenuProduct는 다대일 단방향 관계를 매핑하신 이유가 궁금합니다!

2023-10-22 10:56 UTC, wonyongChoi05 commented on src/main/java/kitchenpos/domain/menu/Menu.java
> +    @ManyToOne(fetch = FetchType.LAZY)
메뉴가 삭제될 때 메뉴 그룹이 같이 삭제되어야 할 것 같은데 cascade = REMOVE 타입으로 간편하게 관리해주면 어떨까요??

2023-10-22 10:56 UTC, wonyongChoi05 commented on src/main/java/kitchenpos/domain/menu/Menu.java
> +            throw new IllegalArgumentException();
여기서는 예외를 도메인에서 던지는군요!

2023-10-22 10:56 UTC, wonyongChoi05 commented on src/main/java/kitchenpos/domain/order/OrderLineItems.java
> +public class OrderLineItems {
일급컬렉션을 정말 잘 활용하시는군요! 👏👏

2023-10-22 10:56 UTC, wonyongChoi05 commented on src/main/java/kitchenpos/domain/order_table/OrderTable.java
> +public class OrderTable {
해당 테이블이 jpa ddl-auto로 생성되지는 않네요! 관련 로그 남겨드립니다.
```sql
2023-10-22 19:27:15.028  WARN 58233 --- [           main] o.h.t.s.i.ExceptionHandlerLoggedImpl     : GenerationTarget encountered exception accepting command : Error executing DDL "
    create table order_table (
       id bigint not null auto_increment,
        empty bit not null,
        number_of_guests integer not null,
        table_group_id bigint,
        primary key (id)
    ) engine=InnoDB" via JDBC Statement

org.hibernate.tool.schema.spi.CommandAcceptanceException: Error executing DDL "
    create table order_table (
       id bigint not null auto_increment,
        empty bit not null,
        number_of_guests integer not null,
        table_group_id bigint,
        primary key (id)
    ) engine=InnoDB" via JDBC Statement
	at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:67) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
	at ...
Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'empty bit not null,
        number_of_guests integer not null,
        table_gro' at line 3
```

2023-10-22 10:56 UTC, wonyongChoi05 commented on src/main/java/kitchenpos/domain/repository/MenuGroupRepository.java
> +public interface MenuGroupRepository extends JpaRepository<MenuGroup, Long> {
최근에 [재미있는 글](https://velog.io/@ohzzi/JpaRepository-No-Repository-Yes#jparepository%EB%A5%BC-%EC%83%81%EC%86%8D%ED%95%98%EC%A7%80-%EB%A7%90%EC%95%84%EC%95%BC-%ED%95%98%EB%8A%94-%EC%9D%B4%EC%9C%A0)을 봤는데 의견 공유차 말씀드려요!

간단하게 요약하면, 저희가 JPA를 사용할 때 항상 테스트 더블을 비교적 쉽게 만들 수 있고, 의도치 않은 기능으로 인한 사이드 이펙트를 생각해야하는데, Repository를 상속받은 사용자 정의 인터페이스를 사용한다면 해결할 수 있다고 하더라구요!

이거는 그냥 공유차원에서 언급한거니 반영 안하셔도 좋습니다!

2023-10-22 10:56 UTC, wonyongChoi05 commented on src/main/java/kitchenpos/domain/repository/OrderRepository.java
> +    boolean existsByOrderTableIdAndOrderStatusIn(Long orderTableId, List<OrderStatus> list);
크.. 쿼리 메서드를 굉장히 잘 쓰시는군요.. 저는 쿼리가 항상 눈에 보여야한다는 이유로 jpql을 직접 사용하는데, 아무래도 jpa 관점에서는 제리처럼 사용하는게 더 좋긴하죠!? ㅎㅎ 대단합니다..

2023-10-22 10:56 UTC, wonyongChoi05 commented on src/main/java/kitchenpos/domain/order_table/OrderTable.java
> +    }
객체 정보를 수정할 때 set 대신 다른 네이밍을 사용하는건 어떨까요? set이라는 네이밍 자체가 해당 메서드의 의도를 나타내지는 못할 것 같아요!

2023-10-22 10:56 UTC, wonyongChoi05 commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +        final OrderTable orderTable = orderTableRepository.findById(1L).get();
요 부분에서 에러가 발생하네요!
```java
No value present
java.util.NoSuchElementException: No value present
```

2023-10-22 10:56 UTC, wonyongChoi05 commented on src/main/java/kitchenpos/application/OrderService.java
> +    private final MenuRepository menuRepository;
확실히 패키지 구조를 레이어(layer)별로 구분하면 패키지간의 양방향 사이클이 돌지 않는게 좋은 것 같아요 ㅎㅎ

2023-10-22 10:56 UTC, wonyongChoi05 commented on src/main/java/kitchenpos/application/OrderService.java
>          }
TableService처럼 검증하는 부분들을 메서드로 분리해보는건 어떨까요?

2023-10-22 10:56 UTC, wonyongChoi05 commented on src/main/java/kitchenpos/application/OrderService.java
>      public Order create(final Order order) {
Request를 엔티티로 받네요! 변경하지 않으신 이유는 알 것 같습니다..만! 만약 지속적으로 리팩터링을 해야하는 상황이라면 아무래도 dto를 사용하는게 좋겠죠? 

그렇다면 이런 상황과 같이 dto의 뎁스(depth)가 엄청나게 깊은 상황은 어떻게 처리하는게 좋을까요? dto도 엔티티와 동일한 뎁스로 만드는게 좋을까요?

2023-10-22 10:56 UTC, wonyongChoi05 commented on src/main/java/kitchenpos/application/OrderService.java
> +        }
여기도 해당 검증들이 어떤 역할을 하는지 메서드로 분리해서 의도를 표현해주면 좋을 것 같아요!

2023-10-23 09:24 UTC, hyeonjerry commented on README.md
> +- [ ] 3개 이상의 인스턴스 변수 갖지 않기
정신없이 리팩터링 하다 보니 깜빡했네요ㅠㅠ
반영하겠습니다!!

2023-10-23 10:38 UTC, hyeonjerry commented on src/main/java/kitchenpos/application/MenuService.java
> +            throw new IllegalArgumentException();
저도 이 부분을 고민했는데 상태를 확인하고 예외를 던지는 것은 흐름을 제어하는 곳에서 하고 상태를 확인하는 것은 해당 상태를 관리하는 객체에서 하는 것이 자연스럽다고 생각했습니다.
따라서, 예외를 던지는 것은 흐름을 제어하는 서비스에서 하고 상태를 확인하는 것은  도메인 객체에서 하도록 구현하게 되었습니다.
하지만 위와 같은 경우 상품  가격의 합이 메뉴 가격보다 크거나 같아야  한다는 메뉴 도메인 객체의 규칙이므로 도메인 객체에서 처리하는게 더욱 자연스러울 것 같네요!!

2023-10-23 11:13 UTC, hyeonjerry commented on src/main/java/kitchenpos/domain/menu/MenuProducts.java
> +public class MenuProducts {
모든 관계를 포장할 필요는 없지만 일급컬렉션을 사용할 경우 불변으로 사용하는데 이점이 있으니 중요한 도메인은 포장하는게 좋다고 생각합니다.
또한, 일급컬렉션에 가격의 합을 계산하는 것과 같이 역할을 부여할 수 있으므로 도메인 로직이 필요할 경우에도 포장하면 좋을 것 같아요!

2023-10-23 11:18 UTC, hyeonjerry commented on src/main/java/kitchenpos/domain/menu_product/MenuProduct.java
> +    private Product product;
서비스 로직을 보았을 때 Product를 통해 MenuProduct를 탐색할 일이 없기에 양방향 매핑이 불필요하다고 생각했기 때문입니다!!
양방향 매핑을 설정할 경우 객체 그래프를 편리하게 탐색할 수 있지만 의도치 않은 쿼리나 N+1 문제가 발생할 수 있기에 확실한 경우에만 거는게 좋다고 생각했습니다.

2023-10-23 11:27 UTC, hyeonjerry commented on src/main/java/kitchenpos/domain/menu/Menu.java
> +    @ManyToOne(fetch = FetchType.LAZY)
이 부분은 필요에 따라 다를 것 같아요!
예를 들어 메뉴가 삭제될 때 메뉴 그룹이 삭제되도록 하면 하나의 메뉴 그룹에 여러개의 메뉴가 등록되어 있을 경우 이 메뉴 그룹에 속한 메뉴들을 어떻게 해야 할지에 대한 규칙을 먼저 정해야 할 것 같습니다.
반대로 메뉴 그룹이 삭제될 경우 메뉴 그룹에 속하는 모든 메뉴를 삭제한다고 한다면 이 서비스를 사용하는 사용자 입장에서 '고기'라는 메뉴 그룹을 삭제하고 '돼지고기'와 '소고기'로 분류하기 위해 '고기'라는 메뉴 그룹을 삭제했는데 모든 메뉴가 삭제되는 문제가 있을 수 있을것 같아요.

2023-10-23 11:28 UTC, hyeonjerry commented on src/main/java/kitchenpos/domain/menu/Menu.java
> +            throw new IllegalArgumentException();
네, 이 부분은 도메인의 규칙이므로 도메인에서 예외를 던지는 것이 낫다고 생각했기 때문입니다.
근데 위에서 말씀해 주신 것도 도메인 규칙이니 도메인에서 예외를 던지는게 맞는 것 같아요ㅋㅋ

2023-10-23 11:41 UTC, hyeonjerry commented on src/main/java/kitchenpos/domain/repository/MenuGroupRepository.java
> +public interface MenuGroupRepository extends JpaRepository<MenuGroup, Long> {
이 글을 읽고 나니 JPA를 사용하면 불필요한 메서드가 생성되는 것은 어쩔 수 없다고 생각한 제가 불쌍해 지네요,,
심지어 글이 너무 좋아서 작성자 확인해 보니 4기 오찌님ㄷㄷ
스크랩 해 두었다가 다음에 Repository 인터페이스를 생성할 일이 있을 때 꼭 활용해 보겠습니다👍

2023-10-23 11:43 UTC, hyeonjerry commented on src/main/java/kitchenpos/domain/repository/OrderRepository.java
> +    boolean existsByOrderTableIdAndOrderStatusIn(Long orderTableId, List<OrderStatus> list);
(이거 제이슨이 DAO 인터페이스에 선언해 둔 시그니처를 그대로 가져왔는데 직접 쿼리 작성할 필요 없더라고요ㅋㅋ
제이슨 대단합니다...)

2023-10-23 11:46 UTC, hyeonjerry commented on src/main/java/kitchenpos/domain/order_table/OrderTable.java
> +    }
저도 이 부분을 고민했었는데 딱히 생각나는 메서드명이 없더라고요ㅠㅠ
update나 change 정도인데 이렇게 쓸바엔 그냥 set을 쓰는게 낫겠다 싶어서 set을 사용했었습니다,,
이 부분은 좀 더 고민해 볼게요!

2023-10-23 11:54 UTC, hyeonjerry commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +        final OrderTable orderTable = orderTableRepository.findById(1L).get();
?! 제 로컬에서는 예외가 발생하지 않아 몰랐네요...
V2에 테스트 데이터가 들어있어 예외가 발생하지 않는 것 같은데 한 번 확인해 보겠습니다!!

2023-10-23 11:59 UTC, hyeonjerry commented on src/main/java/kitchenpos/application/OrderService.java
>          }
리팩터링 중 놓친 것 같아요,,
다시 보니 확실히 분리할 필요가 있어 보이네요!

2023-10-23 12:07 UTC, hyeonjerry commented on src/main/java/kitchenpos/application/OrderService.java
>      public Order create(final Order order) {
확실히 dto의 도입이 시급해 보이긴 합니다ㅋㅋ
뎁스가 깊어지는 것은 해봐야 알겠지만 dto를 도입하여 데이터를 직렬화(?)해 깊이를 줄일 수 있을 것 같습니다.
예를 들어 Order에서 OrderLineItems의 Menu를 받는다고 하면
```json
{
  "orderStatus": "COOKING",
  "tableGroupId": 1,
  "orderLineItems": [
    {
      "menuId": 1,
      "quantity": 2
    },
    ...
  ]
```
위와같이 표현할 수 있을 것 같아요.

2023-10-25 09:35 UTC, wonyongChoi05 approved these changes
수고하셨어요 제리! 다음 단계에서 만나요 ㅎㅎ

2023-10-25 09:35 UTC, merged