[레거시 코드 리팩터링 - 2단계] 헤나(박현서) 미션 제출합니다.
woowacourse/jwp-refactoring pull request #588
Opened 2023-10-22 04:35 UTC by hyena0608

안녕하세요 스플릿!

먼저 제가 리뷰를 늦게 요청드려서 죄송합니다.
프로젝트랑 데모데이도 고생많으셨어요👍

---

요구사항에 관련해서 바뀐 것은 없습니다.

jdbcTemplate 대신 JPA를 사용했습니다.

이번 2단계에서는 서비스 리팩터링에 집중했고 최대한 도메인에게 일을 넘기려고 했습니다.

이 때 도메인 객체 간의 의존을 수정하지는 않았습니다.

객체를 생성할 때 어떤 상태인지를 나타내기 위해서 정적 팩토리 메서드를 많이 사용했습니다.
OrderTable을 생성할 때 단체로 등록되어 있지 않으니 `OrderTable.withoutTableGroup()`을 이용했습니다.

도메인에게 역할을 넘겨주는게 어려웠던거 같습니다.
특히 Menu와 MenuProduct의 관계 부분을 서비스 계층에서 
MenuProduct를 Menu까지 넣어 생성한 후에 Menu에 추가할지
MenuProduct는 Menu를 모르지만 Menu에 추가될 때 Menu 내부에서 Menu를 주입할지 고민됐습니다.

서비스에서 MenuProduct가 Menu를 알도록 처리할 수 있었지만 
Menu에 추가되는 MenuProduct를 Menu가 직접 자신의 MenuProduct으로 만드는 작업도 도메인에서 수행하는게 
이후에 다른 곳에서 비슷한 로직이 있다면 다시 한 번 서비스에서의 로직을 반복하지 않아도 되고
추가적인 요구사항이 들어왔을 때 한 부분에서 해결할 수 있는 것을 고려하여 Menu에게 역할을 넘겼습니다.

상태를 변경하면서 예외를 검증하는 부분도 도메인에게 넘겨봤습니다.

요청이 늦었지만 잘 부탁드리겠습니다..! 🙇‍♂️

2023-10-24 08:12 UTC, splitCoding requested changes
안녕하세요 헤나!😊 리뷰가 늦어 죄송합니다ㅠㅠ

간단한 코멘트들 남겼으니 반영 혹은 의견 남겨주시면 감사하겠습니다!!😊

2023-10-24 08:12 UTC, splitCoding commented on src/main/java/kitchenpos/domain/Menu.java
Price 의 재사용을 위해서 검증 로직을 Price 를 생성하는 측에 위임하셨군요👍

2023-10-24 08:12 UTC, splitCoding commented on src/main/java/kitchenpos/domain/Menu.java
이 부분은 Price 객체에게 메시지로 물어봐도 좋을 것 같아요!! 😊

2023-10-24 08:12 UTC, splitCoding commented on src/main/java/kitchenpos/domain/Menu.java
>      }
Name, Price VO 의 value 를 전달하지 않고 객체를 전달하게된 이유가 궁금합니다!😊

2023-10-24 08:12 UTC, splitCoding commented on src/main/java/kitchenpos/domain/Order.java
> +        if (orderStatus == OrderStatus.COMPLETION && requestOrderStatus == OrderStatus.COMPLETION) {
변경하려는 주문상태가 완료가 아닌 경우에 대한 검증도 추가되어야 할 것 같아요😊

2023-10-24 08:12 UTC, splitCoding commented on src/main/java/kitchenpos/application/ProductService.java
> +        final Product product = new Product(new Name(request.getName()), new Price(request.getPrice()));
값 객체의 생성 책임을 도메인이 아닌 Service 에 주신 이유가 있을까요??

2023-10-24 08:12 UTC, splitCoding commented on src/main/java/kitchenpos/domain/OrderTables.java
> +
성능을 위한 BatchSize 사용 좋네요👍

혹시 size를 10으로 하신 이유가 있는지 궁금해요 😊

2023-10-24 08:12 UTC, splitCoding commented on src/main/java/kitchenpos/domain/TableGroup.java
메서드로 분리해볼 수 있을 것 같아요!!😊

2023-10-24 08:12 UTC, splitCoding commented on src/main/java/kitchenpos/domain/TableGroup.java
> +        final TableGroup tableGroup = new TableGroup(LocalDateTime.now(), OrderTables.empty());
DB 저장 시간이 아닌 객체 생성 시간으로 createdDate 를 설정하신 이유가 궁금해요😊

2023-10-24 08:12 UTC, splitCoding commented on src/main/java/kitchenpos/ui/MenuGroupRestController.java
> +    public ResponseEntity<MenuGroupResponse> create(@RequestBody final MenuGroupCreateRequest request) {
도메인 대신 Request, Response 사용 👍

2023-10-24 08:49 UTC, hyena0608 commented on src/main/java/kitchenpos/domain/Menu.java
Price에 정적 팩터리를 만들어서 사용하도록 수정했습니다!

2023-10-24 08:52 UTC, hyena0608 commented on src/main/java/kitchenpos/domain/Menu.java
>      }
잘못된 value 가 Menu까지 넘어오지 않고 외부에서 예외가 발생하여 도메인 객체 내부에서의 문제가 아닌 외부에서 넘겨주는 부분의 문제라고 생각했습니다.

때문에 둘 다 같은 String 타입으로 value를 전달해도 괜찮다고 생각하지만
타입이 확실한 Price, Name을 Menu 내부에게 넘겨주는게 더 정확하다고 생각했습니다!

2023-10-24 08:54 UTC, hyena0608 commented on src/main/java/kitchenpos/domain/OrderTables.java
> +
배치 사이즈 기본값이 10이라고 생각해서 10이라고 두었습니다.
확인해보니 100이어서 100으로 수정했습니다!

2023-10-24 08:56 UTC, hyena0608 commented on src/main/java/kitchenpos/domain/TableGroup.java
저는 검증에 대한 부분이 너무 길어지지 않는 이상 따로 메서드로 빼지 않는게 가독성이 좋아보인다고 생각해서 분리하지 않았습니다.
크루마다 취향이 많이 달랐어서 스플릿에게도 혹시 현재보다 메서드로 나누어 놓는게 더 가독성이 좋아보이시는지 여쭤보고 싶습니다!

2023-10-24 09:01 UTC, hyena0608 commented on src/main/java/kitchenpos/application/ProductService.java
> +        final Product product = new Product(new Name(request.getName()), new Price(request.getPrice()));
만약 Name이 생성될 때 예외가 발생한다고 했을 때 해당데이터는 Service에서 잘못된 값을 Product에 넘겨주게 됩니다.
때문에 value가 아닌 Name 객체를 생성한 후에 Product에게 넘겨주는게 도메인에 영향이 가지 않는다고 생각했습니다.

생각해봤을 때 도메인 객체 내부에서 예외가 발생해도 생성시에 문제로 다른 영향을 끼치지 않을거 같습니다.
Product에게 넘겨주는 값 객체는 타입을 가지고 있기에 보다 정확한 값을 넘길 수 있다고 생각했습니다.

2023-10-25 01:03 UTC, hyena0608 commented on src/main/java/kitchenpos/domain/Order.java
> +        if (orderStatus == OrderStatus.COMPLETION && requestOrderStatus == OrderStatus.COMPLETION) {
주문 완료 상태에서 주문 완료 상태로 변경하는 예외를 구현했었는데
주문 완료 상태에서 주문 상태를 변경하는 것 자체에 예외가 발생하도록 기능을 수정했습니다 👍

2023-10-25 01:33 UTC, hyena0608 commented on src/main/java/kitchenpos/domain/TableGroup.java
> +        final TableGroup tableGroup = new TableGroup(LocalDateTime.now(), OrderTables.empty());
기존 코드가 애플리케이션에서 LocalDateTime.now() 를 이용해서 생성시간을 저장하고 있었습니다.
요구사항에 데이터베이스 시간으로 생성시간을 수정해야한다는 말이 없어서 큰 생각을 하지 않았습니다.

스플릿께서 말씀해주셔서 갑자기 두 차이에 대해 궁금증이 생겨 찾아봤습니다.
분산 환경에서 생성시간을 애플리케이션에 진행할 경우 다른 서버와 지역 시간대를 제대로 설정하지 않으면 정확하지 않은 시간으로 저장될 수 있습니다. 때문에 데이터베이스의 시간으로 저장하는 방식을 더 선호한다는 것을 알게 됐습니다 👍

TableGroup는 CreatedDated를 가지고 있어 JpaAuditing을 이용해서 데이터베이스에서 생성시간을 저장하도록 수정했습니다.

2023-10-25 02:28 UTC, splitCoding commented on src/main/java/kitchenpos/domain/TableGroup.java
개인적인 취향으로는 메서드에 작성된 구체적인 구현 코드는 메서드가 하려는 한가지일에 대해서 존재하는 것을 선호합니다 😊

메서드가 하려는 모든 코드를 한 메서드에 한곳에 모음으로 코드의 응집도가 높아질거에요
물론 응집도가 높아짐에 따라 가독성면에서 한곳에서 파악할 수 있는 장점도 저는 무시할 수 없다고 생각합니다😊

하지만 현재 TableGroup 생성을 하는 withOrderTables 메서드에 검증, 생성 에 대한 모든 코드가 존재하는데
비즈니스 요구사항에 따라 변경 가능성이 높은 검증 로직이 변경이 될 때마다 이 메서드가 변경이 되어야하나에 대한 고민을 했을 때는 저는 아닌 것 같다고 느꼈어요

또한 메서드 단위의 코드 응집도를 봤을 때 검증로직과 생성로직들의 변경이 되는 시기가 둘이 동일하다고 보이지는 않는 것 같아요.
그렇다면 이 두개의 코드들은 한 메서드에 응집되어야 할까? 라는 의문도 들어서 저는 검증에 대한 부분을 따로 분리할 것 같아요!!

2023-10-25 02:33 UTC, splitCoding approved these changes
헤나 여러가지 취업 준비, 데모데이 등등.. 요즘 할게 너무 많죠ㅠㅠ😭
2단계 하시느라 고생많으셨습니다👍
저의 의견을 물어보는 부분에 답변 남겼으니 한번 읽어봐주시고 3단계에서 봬요!!😊

2023-10-25 02:33 UTC, merged