[레거시 코드 리팩터링 - 2단계] 아마란스(송세연) 미션 제출합니다.
woowacourse/jwp-refactoring pull request #593
Opened 2023-10-22 13:26 UTC by amaran-th

안녕하세요 매튜!
먼저…44커밋과 138 File Changed라는 숫자에 대해 사과의 말씀 드립니다🥹…

이번 단계는 말씀드렸다시피 코드를 보다 원시적인(?) 형태로 구현하고 싶어서 JPA를 사용하지 않았습니다. 
사실 처음엔 큰 이유 없이 시작했는데, 이렇게 잡고 구현하다보니 계층 간의 메시지 전달에 대해 조금….?더 이해하게 된 것 같아요.
(사실 1, 2레벨 때 터득했어야 하는 내용같지만…😇)
tmi는 각설하고 리팩토링 내용을 설명하겠습니다.

- 1단계 리뷰 내용 반영
- 패키지 구조를 계층형에서 도메인형으로 변경
- Setter 제거(핵심 로직 상 필요한 경우 이름을 다르게 지음)
- 값객체 포장
- 일급 컬렉션 포장
- 도메인 클래스와 요청/응답 DTO 클래스 분리
- Entity 클래스와 도메인 클래스 분리

혹시 리뷰 과정에서 이해가 안되거나, 읽기 어려운 부분이 있으면 언제든지 호출해주세요.
그럼 잘 부탁드립니다!

2023-10-23 07:16 UTC, kpeel5839 requested changes
킹! 마란스

정말이지 환상적인 코드이더군요!

역시 킹! 마란스에요

간단한 코멘트들 몇 개 남겼습니다!

그냥 의견을 제시하는 것일 뿐이니, 반영해주실 것, 아닌 것들을 구분해서 리뷰 반영 진행해주시면 너무 감사할 것 같아요!

그리고 몇가지 질문 남겼습니다! 답변해주시면 너무 감사할 것 같아요!

마지막으로 ,킹! 마란스의 코드를 보면서 정말 많은 고민들이 느껴지더군요! 멋집니다 킹! 마란스 

앞으로 조금만 힘내봐요!

마지막으로 드릴 말씀이 있어요.. 도대체 왜 꽃 이름은 안나오죠?

2023-10-23 07:16 UTC, kpeel5839 commented on README.md
> +    - 상품의 가격은 null이 아니며 0원 이상이어야 한다.
바로 들어주시다닛 킹마란스 멋져부러

2023-10-23 07:16 UTC, kpeel5839 commented on src/test/java/kitchenpos/application/MenuGroupServiceTest.java
> +        () -> assertThat(actualNames).containsExactly("두마리메뉴", "한마리메뉴", "순살파닭두마리메뉴", "신메뉴")
아주 행복한 이름들이네요

2023-10-23 07:16 UTC, kpeel5839 commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +    final Menu menu = 만냥치킨_2마리();
아주 좋습니다! 이전보다 훨씬 직관적이게 된 것 같아요!

2023-10-23 07:16 UTC, kpeel5839 commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +    emptyOrderTableId = 2L;
네이밍도 아주 좋네요!

2023-10-23 07:16 UTC, kpeel5839 commented on src/test/java/kitchenpos/application/ProductServiceTest.java
> +        () -> assertThat(actualNames).contains(깐풍치킨().getName())
똑똑한 검증 방법이네요 👍

2023-10-23 07:16 UTC, kpeel5839 commented on src/main/java/kitchenpos/table/domain/OrderTable.java
> +
Price 와 같이 numberOfGuest 도 감싸서 유효성 검증을 할 수 있지 않을까요??

그렇다면 Service 에서 검증해야 할 로직들도 줄어들 것 같아요!

2023-10-23 07:16 UTC, kpeel5839 commented on src/main/java/kitchenpos/order/domain/OrderStatus.java
> +  public static List<OrderStatus> NOT_COMPLETION_STATUSES = List.of(COOKING, MEAL);
정말 좋은 아이디어네요! 바로 뺏어가겠습니다!

근데, final 을 붙이는 것이 더 좋을 것 같아요 ~ ㅎ

2023-10-23 07:16 UTC, kpeel5839 commented on src/main/java/kitchenpos/menu/application/dto/MenuCreateRequest.java
> +package kitchenpos.menu.application.dto;
DTO 패키지를 볼 때, Request 와 Response 를 한눈에 구별하기가 조금 어렵더라구요!

request 와 resposne 패키지를 나누는 것은 어떨까요?

2023-10-23 07:16 UTC, kpeel5839 commented on src/main/java/kitchenpos/menu/application/dto/ProductQueryResponse.java
> +  public static ProductQueryResponse of(final Product product) {
보통 하나 이하의 인수를 받는 정적 팩토리 메서드는 `from`, 그렇지 않다면 `of` 를 붙이는 것이 관례로 알고 있는데요!

그렇기 때문에 해당 메서드는 `from` 이 더 적절하지 않을까용??

2023-10-23 07:16 UTC, kpeel5839 commented on src/main/java/kitchenpos/menu/application/entity/MenuGroupEntity.java
> +
보통 `getter`, `setter`, `toString`, `hashCode`, `equals` 메서드를 가장 하단에 배치하는 것으로 알고있는데요!

그렇기 때문에 보는 사람이 from 메서드를 못보고 지나칠 수도 있을 것 같아요! (물론 그런 일이 많이 일어나지는 않겠지만요 허허허) 메서드 위치를 변경하시는 것은 어떨까요 ?

2023-10-23 07:16 UTC, kpeel5839 commented on src/main/java/kitchenpos/menu/application/MenuGroupService.java
> +}
`Resposne` 까지 다 바꾸다니... 대단해요 킹! 마란스..

2023-10-23 07:16 UTC, kpeel5839 commented on src/main/java/kitchenpos/menu/application/dto/MenuCreateRequest.java
> +}
우리는 보통 `Response` 의 정적 팩토리 메서드에 `Domain` 객체를 넣어서 쉽게 변환을 하는 것 같아요! (아마란스가 해주신 것처럼)

하지만 그 반대 행위는 이상하게 잘 하지 않는 것 같습니다.

근데 킹! 마란스의 코드를 보고 곰곰히 생각해보니, 도대체 이 방법을 왜 안쓰는거지? 아무런 문제점이 없어 보이고, 오히려 편하기만 해보이는데 말이죠

생각을 계속 이어나가다보니, 간신히 두 가지의 이유가 있을 것 같다는 생각을 했어요.

1. `JPA` 를 사용할 때에는 해당 메서드를 이용해 Domain 객체로 변경하는 것이 불가능 할 수도 있다.

현재 `request` 를 바로 `Domain` 객체로 변경이 가능한 이유는 `menuGroup` 을 `직접참조` 하는 것이 아닌 `간접참조` 하기 때문이라고 생각합니다.

그렇기 때문에 해당 문제는 지금 아마란스 코드에서는 전혀 문제가 되지 않을 것 같아요!

그렇다면 다음 이유로는 무엇이 있을까요?

2. 관리할 포인트가 늘어난다.

`Menu` 에 새로운 `column` 인 `matthew` 가 생겼다고 가정해봅시다.

그 떄 생성자를 아래와 같이 만들었다고 가정해볼게요

```java  
... 다른 컬럼들 생략
private final String matthew;

public Menu(
      String name,
      Price price,
      Long menuGroupId,
      List<MenuProduct> menuProducts
) {
this(null, name, price, menuGroupId, menuProducts, null);
}

public Menu(
      Long id,
      String name,
      Price price,
      Long menuGroupId,
      List<MenuProduct> menuProducts,
      String matthew
) {
this.id = id;
this.name = name;
this.price = price;
this.menuGroupId = menuGroupId;
this.menuProducts = menuProducts;
this.matthew = matthew;
}

```  

이 경우 아마란스가 사용해주신 `toMenu` 를 그대로 사용하더라도 예외는 발생하지 않을거에요!

하지만 `matthew` 가 `null` 인 불완전한 `domain` 객체가 반환되겠죠!

물론 이런 경우가 정상적인 경우도 있겠지만, 그렇지 않은 경우는 심각한 상황을 불러일으킬 수도 있지 않을까요?

이에 대한 아마란스의 의견은 어떠신가요?

2023-10-23 07:16 UTC, kpeel5839 commented on src/main/java/kitchenpos/menu/domain/Menu.java
> +}
사용하지 않는 메서드인 것 같아요!

2023-10-23 07:16 UTC, kpeel5839 commented on src/main/java/kitchenpos/menu/domain/Price.java
> +public class Price {
`VO` 를 굉장히 잘 활용하시는 것 같아요!

`isNull`, `isLessThan`, `isGreaterThan` 들을 보니 저도 이렇게 구현해야 겠다는 생각이듭니다.

다만 한가지 아쉬운 점은 유효성 검증도 해당 객체에서 해줬다면 더 좋았을 것 같다? 라는 생각이 들어요.

그렇게 한다면 `Service` 딴에서 `0` 미만의 가격, 가격이 `null` 인 경우에 대해서는 따로 검증을 진행하지 않아도 되서 편할 것 같다는 생각이 들어요!

2023-10-23 07:16 UTC, kpeel5839 commented on src/main/java/kitchenpos/table/application/TableGroupService.java
> +        orderTableIds, OrderStatus.NOT_COMPLETION_STATUSES)) {
키야 기가막힙니다 역시 킹! 마란스

2023-10-23 07:16 UTC, kpeel5839 commented on src/main/java/kitchenpos/menu/domain/Product.java
> +
개행 2줄!

2023-10-23 07:16 UTC, kpeel5839 commented on src/main/java/kitchenpos/menu/application/entity/MenuEntity.java
> +
해당 메서드가 테스트에서만 사용되는 것 같아요!

2023-10-23 07:16 UTC, kpeel5839 commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +  }
킹마란스 React 고수시라고 indent size 2 로 하시면 안되여어엉

2023-10-23 07:16 UTC, kpeel5839 commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +    validateMenuPrice(price, totalPrice);
저는 처음에 코드들을 보고, `Domain` 로직들이 아직 `Service` 에 머물러 있어서 뭐지 ? 라고 생각했는데, 곰곰히 보면서 생각해보니 현재 `JPA` 를 사용하지 않으면서, `Domain` 객체들이 `직접참조`를 이루지 않고 `간접참조`를 이루고 있기 때문에 그렇다는 것을 깨달았습니다!

저에게 깨달음을 주셔서 너무 감사하고, 아마란스도 코드를 짜시면서 정말 힘들고 많이 깨달으셨겠구나라는 것을 생각했습니다.

그래서 어떻게 하면 `JPA` 를 사용하지 않으면서 `Domain` 로직을 최대한 `Service` 에 두지 않을 수 있을까? 에 대해서 생각해보았는데, 현재 `Domain` 객체들을 직접 참조로 바꾸고 `JDBC` 에서 해당 값들을 채워 넣어주는 방식은 어떤가요?? (물론 해당 방법을 채택하기 보다는 그냥 `JPA` 를 쓰는 것이 나을 것 같긴해요)

물론 `Domain` 로직들을 `Service` 딴이 아닌 `Domain` 으로 옮기는 것에만 집중한 멍청한 방법이지만, 한번 여쭤봅니다!

아마란스는 현재 방법이 나은 것 같아요? 아니면 제가 제시한 방법도 괜찮은 방법 같나요?

2023-10-23 07:16 UTC, kpeel5839 commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +    return savedMenus;
```java
public static MenuQueryResponse from(Menu menu) {
  return new MenuQueryResponse(
          menu.getId(),
          menu.getName(),
          menu.getPrice().getValue(),
          menu.getMenuGroupId(),
          menu.getMenuProducts()
                  .stream()
                  .map(MenuProductQueryResponse::from)
                  .collect(Collectors.toList())
  );
}
```

위와 같이 `MenuQueryResponse` 의 정팩메를 정의한다면, `Service` 에서 아래와 같이 간결하게 `Response` 를 반환할 수 있지 않을까요?

```java
return menuRepository.findAll()
        .stream()
        .map(MenuQueryResponse::from)
        .collect(Collectors.toList());
```

2023-10-24 00:42 UTC, amaran-th commented on src/main/java/kitchenpos/table/domain/OrderTable.java
> +
오 좋은 아이디어 감사합니다!
반영하겠습니다~!

2023-10-24 00:45 UTC, amaran-th commented on src/main/java/kitchenpos/menu/application/dto/MenuCreateRequest.java
> +package kitchenpos.menu.application.dto;
반영하겠습니다!

2023-10-24 00:47 UTC, amaran-th commented on src/main/java/kitchenpos/menu/application/dto/ProductQueryResponse.java
> +  public static ProductQueryResponse of(final Product product) {
헉 찾아주셔서 감사합니다ㅋㅋㅋ
수정했습니다!

2023-10-24 02:20 UTC, amaran-th commented on src/main/java/kitchenpos/menu/application/entity/MenuGroupEntity.java
> +
음 그렇네요...! 처음에 getter를 만들어두고 코드를 짜기 시작했더니 순서가 조금 이상해졌네요ㅋㅋㅋ
반영했습니다!

2023-10-24 02:23 UTC, amaran-th commented on src/main/java/kitchenpos/menu/domain/Menu.java
> +}
생성자에서 호출하고 있습니다!

2023-10-24 02:54 UTC, amaran-th commented on src/main/java/kitchenpos/menu/domain/Price.java
> +public class Price {
흠 처음에는 해당 검증 로직이 Price의 책임이 아니라고 생각해서 Menu, Product 도메인에서 검증 로직을 수행하도록 했었는데, 다시 생각해보니 음수, null 값에 대한 검증은 Price에서 해주어도 어색하지 않는 것 같네요.
반영해서 Price 생성자에 검증 로직을 추가해주었습니다!

2023-10-24 05:03 UTC, amaran-th commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +    return savedMenus;
오 좋은 아이디어 감사합니다! 당장 반영하도록 하겠습니다ㅎㅎ
확실히 서비스 로직이 단순해져서 너무 좋은 것 같아요

2023-10-24 05:15 UTC, amaran-th commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +    validateMenuPrice(price, totalPrice);
사실 이 코멘트를 받기 전까지 직접참조/간접참조 개념도 잘 모르고 있었거든요,...코멘트를 처음 봤을 때 식은땀이 났습니다^^;
그래서 바로 해당 개념을 찾아봤습니다. 지금은 이해가 되어서, 제가 짠 방식에 문제가 있다는 걸 인지하게 됐어요.
덕분에 공부가 많이 됐습니다.ㅎㅎ
매튜가 제시해주신 대로 직접참조 방식으로 구현하면 비즈니스 로직을 도메인에서 처리하도록 할 수 있을 것 같아요. 

혹시 해당 변경 사항은 미션 3단계에서 반영해도 괜찮을까요?
3단계가 의존성 리팩토링이라, 참조 방식에 대한 수정도 함께 진행할 것 같거든요...!

저는 이번 미션에서 jdbc의 한계를 직접 겪어보고 싶어서, 현재 구현 방식을 유지하겠습니다ㅎㅎ

2023-10-24 06:17 UTC, amaran-th commented on src/main/java/kitchenpos/menu/application/dto/MenuCreateRequest.java
> +}
오 고민해보지 못했던 주제인데...매튜는 정말 예리하시군요
저는 첫 번째 이유가 더 큰 것 같아요.
직접 참조를 하는 경우 dto를 도메인으로 변환하는 메서드를 구현할 수 없으니, 사용하는 사례를 볼 수 없었던 게 아닌가 싶어요.

두 번째 의견은 response에서 domain->dto로 변환하는 케이스도 해당되는 이유겠네요!
직접 예시까지 만들어서 설명해주시다니....최고입니다👍👍👍
덕분에 많이 배워갑니다ㅎㅎ

2023-10-24 06:32 UTC, kpeel5839 commented on src/main/java/kitchenpos/menu/application/dto/MenuCreateRequest.java
> +}
껄껄껄

2023-10-24 06:33 UTC, kpeel5839 commented on src/main/java/kitchenpos/menu/domain/Menu.java
> +}
아잇!

제 IDE 에서는 사용하는 곳이 없다고 나왔는데!

역시 제 컴퓨터는 오래된 것 같군요..

2023-10-24 06:34 UTC, kpeel5839 commented on src/main/java/kitchenpos/menu/domain/Price.java
> +public class Price {
근데 아마란스가 말씀해주셔서 다시 생각해보니까, Price 가 음수일 수 있는 경우도 생각해보면 생각할 수 있을 것 같기도.. 허허허허

킹치만 현재 Domain 에서는 그런 경우는 없을 것 같기도 하네요 호ㅓ호호호

2023-10-24 06:34 UTC, kpeel5839 commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +  }
왜 이거에는 따봉 안다세요

2023-10-24 06:36 UTC, kpeel5839 commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +    validateMenuPrice(price, totalPrice);
항상 제 의견에 대해 친절하게 그리고 성의있게 답변해주셔서 정말 감사합니다.

킹!마란스는 소통할 맛이 참 많이 나는 사람이네요!

3단계 때 진행하셔도 됩니다!

그 점은 감안하고 보도록 하겠습니다.

2023-10-24 06:36 UTC, kpeel5839 commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +    validateMenuPrice(price, totalPrice);
그리고 지조... 아주 멋집니다

상여자 킹! 킹! 킹! 마란스

2023-10-24 06:37 UTC, kpeel5839 commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +    return savedMenus;
하하하하하 감사합니두~

2023-10-24 06:55 UTC, amaran-th commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +  }
코드스타일 변경했습니다!

2023-10-24 07:04 UTC, kpeel5839 approved these changes
킹마란스 코드 너무 잘봤습니다.

대단합니다. 이 바쁜데 어떻게 이 많은 것을 단숨에... 당신은 도대체 몸이 몇 개인 것입니까 휴먼..

다음 단계 가시죠!

제안사항 하나 남깁니당~~~~~

2023-10-24 07:04 UTC, kpeel5839 commented on src/main/java/kitchenpos/table/domain/NumberOfGuests.java
> +  public static final NumberOfGuests DEFAULT_NUMBER_OF_GUESTS = new NumberOfGuests(0);
상수 장인이시네요 정말

2023-10-24 07:04 UTC, kpeel5839 commented on src/main/java/kitchenpos/table/domain/NumberOfGuests.java
> +  }
유효성 검증 나이스!

2023-10-24 07:04 UTC, kpeel5839 commented on src/main/java/kitchenpos/table/domain/NumberOfGuests.java
> +  }
생성자를 그대로 사용하기 보다는 정적 팩토리 메서드를 통해 해당 메서드를 사용하면 생성 이외에 검증 혹은 로직이 들어갈 수 있다라는 것을 암시하는 것은 어떨까요?

2023-10-24 07:04 UTC, kpeel5839 commented on src/test/java/kitchenpos/table/domain/NumberOfGuestsTest.java
> +}
당신 몸이 몇개입니까 휴면...

근데... EOF!

2023-10-24 07:04 UTC, kpeel5839 commented on src/main/java/kitchenpos/menu/application/MenuGroupService.java
> +import kitchenpos.menu.application.dto.response.MenuGroupQueryResponse;
훨씬 보기 편해졌어요!

2023-10-24 07:04 UTC, kpeel5839 commented on src/main/java/kitchenpos/menu/application/dto/response/MenuProductQueryResponse.java
> +  }
이제야 마음이 좀 편하네요 후후..

2023-10-24 07:04 UTC, kpeel5839 commented on src/main/java/kitchenpos/menu/domain/Price.java
> +    }
validate 굳!

2023-10-24 07:04 UTC, kpeel5839 commented on src/test/java/kitchenpos/menu/domain/PriceTest.java
> +
테스트 장인... 근데 then 이후에 공백!

2023-10-24 07:04 UTC, kpeel5839 commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +        .collect(Collectors.toList());
훨씬 간결해졌군요!

2023-10-24 07:04 UTC, kpeel5839 commented on src/main/java/kitchenpos/menu/application/entity/MenuEntity.java
> +        this.menuGroupId = menuGroupId;
다음부터 리액트는 안!돼!여!

2023-10-24 07:04 UTC, merged

2023-10-24 07:08 UTC, amaran-th commented on src/test/java/kitchenpos/table/domain/NumberOfGuestsTest.java
> +}
헉! 3단계 할 때 수정하겠습니다

2023-10-24 07:14 UTC, amaran-th commented on src/main/java/kitchenpos/table/domain/NumberOfGuests.java
> +  }
반영하겠습니다~!