[레거시 코드 리팩토링 미션 - 2단계] 포이(김보준) 미션 제출합니다.
woowacourse/jwp-refactoring pull request #595
Opened 2023-10-22 14:08 UTC by poi1649

다즐 안녕하세요! 정말 오랜만입니다...

> 단위 테스트하기 어려운 코드와 단위 테스트 가능한 코드를 분리해 단위 테스트 가능한 코드에 대해 단위 테스트를 구현한다.

이번 미션에서는 위 요구사항을 달성하는 것을 목표로 해보았는데, 하면 할수록 제가 레거시 코드를 만들고 있다는 생각이 드네요🥲

일단은 힌트에 있는대로 비즈니스 로직을 최대한 도메인 객체가 담당하도록 하고, 서비스에서는 최대한 해당 객체의 조회만 이루어지도록 하는건 달성하려고 했습니다.
그 과정에서 JPA 를 사용하며 테이블 수정이 최대한 이루어지지 않게 코드를 작성했더니 객체간 의존관계가 엉망이 되어버렸네요 ㅠㅠ..

또, 객체에서 사용하지 않는 세터라도 빼서 도메인 로직을 보기 편하게 만들고 싶었는데 빼자마자 테스트 코드의 JSON 직렬화 과정에서 에러가 막 발생하는 바람에 바로 롤백때렸습니다.

이래서 response 객체를 따로 써야하는건가 싶어요.......하하하ㅏㅏ하하하하하
이 문제를 다즐은 어떻게 해결하셨는지도 궁금하네요.

---

위에 있는 문제들을 해결하려면 
- flyway를 사용해서 테이블 자체를 수정
- reponse 객체 또는 vo 를 활용해 도메인에서 세터제거

이런 것들을 해줘야 할 것 같은데 더 이상 혼자 잡고 있기엔 제 멘탈이 온전하지 못할 것 같아 테스트가 통과하는 선에서 1차 요청 드립니다.
혹시 다즐에게 더 좋은 방법이 있다면 아주 살짝 공유해주시면 감사할 것 같아요🙇‍♂️
다즐 레거시 코드 리뷰하기 미션 화이팅입니다

2023-10-23 07:07 UTC, woo-chang requested changes
안녕하세요 포이 😀
바쁘신 와중에 2단계 미션까지 잘 구현해주셨네요 ㅎㅎ

> 또, 객체에서 사용하지 않는 세터라도 빼서 도메인 로직을 보기 편하게 만들고 싶었는데 빼자마자 테스트 코드의 JSON 직렬화 과정에서 에러가 막 발생하는 바람에 바로 롤백때렸습니다.

저는 요청, 응답에서 사용되는 도메인을 UI에 사용되는 데이터만 담을 수 있는 `Request`, `Response` 객체로 수정했어요. UI까지 도메인이 전파된다면 예상치 못한 도메인 상태의 변화로 인한 문제가 발생할 수 있다고 판단했어요. 그로 인해서 각각의 서비스 메서드는 요청과 1:1 매칭이 되는 형태가 되어버렸는데요. 도메인을 반환하여 범용성 있게 사용할 수 있는 서비스는 컨트롤러에 노출시키지 않고 서비스 안에서만 사용하도록 할 것 같아요 :)

수정이 필요한 부분보다는 같이 얘기해보고 싶은 부분에 대한 질문 위주로 커멘트 남겨두었으니 확인해주시면 감사합니다 🙇🏻‍♂️

2023-10-23 07:07 UTC, woo-chang commented on src/main/java/kitchenpos/domain/product/ProductName.java
> +    }
`strip` 하기 전의 값을 통해 검증하고 값을 저장할 때 `strip`을 한다면, 사용자 입장에서 혼란이 있을 수도 있을 것 같아요.

예를 들면 strip 하기 전 길이가 `255`보다 작을 때는 strip된 값이 저장되는 것 같아 공백을 신경쓰지 않고 입력했는데 검증 오류가 발생하는 상황이 있을 것 같아요! (의도적으로 이렇게 설정하지 않는 이상 잘 없을 것 같기는 하지만요 😀)

strip된 값을 저장하신다면 검증에서도 strip된 값을 검증하는게 어떨까요?!

2023-10-23 07:07 UTC, woo-chang commented on src/main/java/kitchenpos/domain/product/Price.java
> +    }
꼼꼼하게 검증하셨네요 👍

DB 제약조건에 의해 추가적인 소수점이 존재하더라도 올림, 반올림, 내림 등과 같은 전략에 의해 자동으로 `2`자리에 맞춰 저장될 것 같은데 해당 검증을 추가해주신 이유가 궁금해요 !

2023-10-23 07:07 UTC, woo-chang commented on src/main/java/kitchenpos/domain/product/Product.java
> +    }
`ID`를 직접 세팅하는 일이 존재할까요? 🤓

2023-10-23 07:07 UTC, woo-chang commented on src/main/java/kitchenpos/domain/product/Product.java
> +    }
`setter`를 남겨두신 이유가 있나요? `ResponseBody` 직렬화에는 프로퍼티 방식이 사용되는 것으로 알고 있는데 `NoArgsConstructor`과 `Getter`만 남겨두었을 때 동작하지 않았나요?!

2023-10-23 07:07 UTC, woo-chang commented on src/main/java/kitchenpos/exception/HttpException.java
> +public abstract class HttpException extends RuntimeException {
커스텀 예외까지 꼼꼼하게 작성해주셨네요 👍

2023-10-23 07:07 UTC, woo-chang commented on src/main/java/kitchenpos/dao/MenuDao.java
> +public interface MenuDao extends Repository<Menu, Long> {
불필요한 메서드를 사용하지 않기 위해 `JpaRepository`가 아닌 `Repository`를 상속받도록 하신건가요?!

2023-10-23 07:07 UTC, woo-chang commented on src/main/java/kitchenpos/domain/TableGroup.java
> +    @Id
사소한 궁금증이지만, 순서를 반대로 두시는 이유가 있으신가요 ㅎㅎ

2023-10-23 07:07 UTC, woo-chang commented on src/main/java/kitchenpos/ui/request/MenuProductCreateRequest.java
> +    }
`Request` 객체에 `setter`를 두신 이유가 궁금해요 🤓

2023-10-23 07:07 UTC, woo-chang commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-validation'
검증까지 너무 꼼꼼해요 👍

2023-10-23 07:07 UTC, woo-chang commented on src/main/java/kitchenpos/application/MenuService.java
> +        return new MenuProduct(product, menuProductCreateRequest.getQuantity());
저도 서비스에서 `MenuProduct`를 만드는 작업을 진행하였는데, 한 가지 고민이 들어 포이는 어떻게 생각하는지 궁금해요 :)

`Q` : `MenuProduct`를 생성하는 책임은 `MenuService`, `Menu` 중 어디에 있을까요?

2023-10-23 07:07 UTC, woo-chang commented on src/main/java/kitchenpos/domain/menu/Menu.java
> +    @ManyToOne
`@ManyToOne`의 `fetch` 타입을 지정해주지 않은 이유가 항상 `EAGER`로 함께 조회되기를 의도하신걸까요? 🤓

2023-10-23 07:07 UTC, woo-chang commented on src/main/java/kitchenpos/domain/menu/Menu.java
> +    @JoinColumn(name = "menu_group_id")
`nullable` 설정도 DB 제약조건과 동일하게 해주는건 어떨까요 :)

2023-10-23 07:07 UTC, woo-chang commented on src/main/java/kitchenpos/domain/menu/Menu.java
> +    @OneToMany(mappedBy = "menu", cascade = CascadeType.ALL)
`cascade` 속성을 `ALL`로 지정하신 이유가 궁금합니다 ㅎㅎ

2023-10-23 07:07 UTC, woo-chang commented on src/main/java/kitchenpos/domain/menu/Menu.java
> +    }
`MenuProduct` 목록에 대한 일급객체를 생성해서 해당 책임을 넘길 수도 있을 것 같아요 ㅎㅎ

2023-10-23 07:07 UTC, woo-chang commented on src/test/java/kitchenpos/ui/RollBackExtension.java
> +                txManager.rollback(transactionStatus);
갑자기 궁금한 점 !

`@Transactional`을 사용한 롤백 시 롤백 과정에서 에러가 발생하면 그 이후로의 데이터는 지워지지 않고 남아있게 되는걸까? 🤔

2023-10-23 07:07 UTC, woo-chang commented on src/main/java/kitchenpos/domain/order/Order.java
> +    private List<OrderLineItem> orderLineItems;
`@Cascade` 어노테이션을 사용하면 `@OneToMany`의 `cascade` 옵션과 어떤 차이가 있나요?

2023-10-23 07:07 UTC, woo-chang commented on src/main/java/kitchenpos/domain/ordertable/NumberOfGuests.java
> +    }
기본 생성자의 접근 제어자는 `protected`로 두는건 어떨까요 :)

2023-10-23 07:07 UTC, woo-chang commented on src/main/java/kitchenpos/ui/MenuGroupRestController.java
> +    ) {
응답 요청에 대한 데이터는 `DTO`로 전부 수정해주셨는데 반환데이터는 `DTO`로 수정하지 않고 `Entity`로 그대로 두신 이유가 있을까요? 🤓

2023-10-23 07:07 UTC, woo-chang commented on src/main/java/kitchenpos/application/OrderService.java
> +                                                                  )
별도의 메서드로의 분리를 고려해볼 수 있을 것 같아요 :)

2023-10-23 07:07 UTC, woo-chang commented on src/main/java/kitchenpos/domain/order/Order.java
> +    @JoinColumn(name = "ordered_time", nullable = false, updatable = false)
`ordered_time`이 조인컬럼으로 명시되는 이유가 있으신가요? 😀

2023-10-24 08:41 UTC, poi1649 commented on src/main/java/kitchenpos/domain/product/ProductName.java
> +    }
오... 정말 좋은 피드백이네요. 다즐 의견에 백퍼센트 동의합니다.

2023-10-24 08:46 UTC, poi1649 commented on src/main/java/kitchenpos/domain/product/Price.java
> +    }
돈이 걸려있는 만큼, 입력 자체에서 검증된 값이 들어와야한다고 생각했네요ㅋㅋㅋ...
혹시 반올림이나 내림 같은 규칙에 의해서 1~2원씩 오류가 생길 수도 있다고 생각했어요.

2023-10-24 08:47 UTC, poi1649 commented on src/main/java/kitchenpos/dao/MenuDao.java
> +public interface MenuDao extends Repository<Menu, Long> {
맞습니다~ 필요한 메서드만 적용하고 싶었어요

2023-10-24 08:48 UTC, poi1649 commented on src/main/java/kitchenpos/domain/TableGroup.java
> +    @Id
'근본에 있는 것 일수록 가까이 넣는다' 라는 약간은 애매한 저의 규칙이 있습니다.

2023-10-24 08:52 UTC, poi1649 commented on src/main/java/kitchenpos/domain/order/Order.java
> +    @JoinColumn(name = "ordered_time", nullable = false, updatable = false)
앗.. 실수입니다...

2023-10-24 08:53 UTC, poi1649 commented on src/main/java/kitchenpos/domain/ordertable/NumberOfGuests.java
> +    }
앗.. 좋습니다 다른 객체도 수정했습니다.

2023-10-24 10:13 UTC, poi1649 commented on src/main/java/kitchenpos/domain/product/Product.java
> +    }
ResponseBody로 직렬화하는 과정에서는 문제가 없지만, RestTemplate의 postForEntity 메서드의 역직렬화 과정에서 몇몇 객체들에 세터가 없으니 문제가 발생하더라고요. 대략적인 오류 메시지는 다음과 같습니다.

```
org.springframework.web.client.RestClientException: Error while extracting response for type [class kitchenpos.domain.product.Product] and content type [application/json]; nested exception is org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Cannot construct instance of `kitchenpos.domain.product.Price` (although at least one Creator exists): no int/Int-argument constructor/factory method to deserialize from Number value (1000); nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `kitchenpos.domain.product.Price` (although at least one Creator exists): no int/Int-argument constructor/factory method to deserialize from Number value (1000)
 at [Source: (org.springframework.util.StreamUtils$NonClosingInputStream); line: 1, column: 18] (through reference chain: kitchenpos.domain.product.Product["price"])
	at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:120)
	at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:1043)
	at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:1026)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:784)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:717)
	at org.springframework.web.client.RestTemplate.postForEntity(RestTemplate.java:474)
	at org.springframework.boot.test.web.client.TestRestTemplate.postForEntity(TestRestTemplate.java:441)
```

찾아보니 BigDecimal 에는 int 생성자가 없어서, 1000, 100 처럼 딱 떨어지는 정수형태의 Json 값은 Bigdecimal 값은 역직렬화 하지 못한다고 하네요.🤔
사실 이번 리뷰 반영 단계에서 response 객체를 따로 만들어주었기 때문에 큰 문제는 없지만, 만약 BigDecimal을 가진 객체를 테스트코드에서 활용하고 싶다면 int 생성자나 팩터리 메서드를 만들어주어야 할 것 같아요! 
당시엔 너무 피곤해서 그냥 setter를 맘편하게 다 넣어줬는데, 다즐 덕에 놓치고 갈 수 있는 부분까지 알고 갑니다. 감사합니다즐

2023-10-24 10:35 UTC, poi1649 commented on src/main/java/kitchenpos/ui/request/MenuProductCreateRequest.java
> +    }
부끄럽지만 위에 말씀드린 역직렬화 오류를 제대로 해결할 용기가 안나서 첫 pr에 마구잡이로 setter를 붙였네요.. 레거시 개발자의 정석이었던 것 같습니다. 다시 정신을 가다듬고 좋은 코드를 작성해보겠습니다..

2023-10-24 10:38 UTC, poi1649 commented on src/main/java/kitchenpos/application/MenuService.java
> +        return new MenuProduct(product, menuProductCreateRequest.getQuantity());
저희의 도메인을 봤을 때, 이를 생성하는 책임은 Menu 안에 있어야하는 것 같다는 생각이 드네요. 다만 Menu가 Product를 참조하게 되는 것이 꺼려져, 이를 지양했는데 이러한 의존 관계가 그렇게 어색한 의존은 아닐 것 같다는 생각도 듭니다. 멀티 모듈의 단위를 어디로 잡게될지에 따라서 고통받는 포인트가 될 수도 있겠지만요ㅋㅋㅋ..

2023-10-24 10:39 UTC, poi1649 commented on src/main/java/kitchenpos/domain/product/Product.java
> +    }
이 부분에 대해서는 바로 밑의 커멘트에서 설명하도록 하겠습니다.

2023-10-24 10:41 UTC, poi1649 commented on src/main/java/kitchenpos/domain/menu/Menu.java
> +    @ManyToOne
현재는 그런 의도가 맞습니다. 
최대한 함께 조회하는 객체들끼리만 참조를 갖게할 생각이기 때문에 문제는 없을 것 같아요. 
3단계에서 객체의 의존관계를 더 고민해보고 난 뒤에 한 번 더 생각해 볼 문제 같습니다.

2023-10-24 10:43 UTC, poi1649 commented on src/main/java/kitchenpos/ui/MenuGroupRestController.java
> +    ) {
제이슨의 강의를 듣고 불필요한 DTO 작성을 일부의 도메인과 VO 를 통해 해결할 수 있지 않을까? 하는 생각이 잠시 있었습니다. 
막상 이렇게 해보니 JPA 엔티티를 그대로 도메인 객체로 사용하고 있는 지금은, 반드시 수정해야겠다는 생각이 들어서 수정했습니다.

2023-10-24 10:50 UTC, poi1649 commented on src/main/java/kitchenpos/domain/menu/Menu.java
> +    @JoinColumn(name = "menu_group_id")
좋습니다.. 다즐 덕에 점점 코드가 나아지고 있네요🫡

2023-10-24 10:52 UTC, poi1649 commented on src/main/java/kitchenpos/domain/menu/Menu.java
> +    @OneToMany(mappedBy = "menu", cascade = CascadeType.ALL)
앗 이 부분은 실수입니다.. Persist로 수정해주었습니다.

2023-10-24 10:54 UTC, poi1649 commented on src/main/java/kitchenpos/application/OrderService.java
> +                                                                  )
확실히 람다안에 들어가는 메서드들은 분리해주는 편이 훨씬 좋네요.👍 반영했습니다!
그런데 이것과는 별개로 이 친구의 생성책임도 MenuProduct처럼 고민해볼 수 있겠군요

2023-10-24 13:59 UTC, poi1649 commented on src/main/java/kitchenpos/domain/order/Order.java
> +    private List<OrderLineItem> orderLineItems;
<img width="672" alt="image" src="https://github.com/woowacourse/jwp-refactoring/assets/74969077/441c92fc-7a4b-43d3-9d5e-40633fe7401a">
사실 구분 없이 사용하고 있었습니다. 이번 기회에 찾아봤는데 동일한 기능을 하지만, Hibernate specific 하다고 하네요. 이 부분도 통일해주었습니다.

2023-10-24 15:05 UTC, poi1649 commented on src/main/java/kitchenpos/domain/menu/Menu.java
> +    }
확실히 책임이 명확해질 수 있겠네요! 그런데 아직은 일급 컬렉션을 만들만한 정도로 많은 책임이 있는 것 같지는 않아요. 어떻게 보면 그저 코드의 복잡도를 높이는 일일 수 있겠다는 생각이 들어 일단은 그대로 두고 싶습니다

2023-10-24 15:13 UTC, poi1649 commented on src/test/java/kitchenpos/ui/RollBackExtension.java
> +                txManager.rollback(transactionStatus);
제가 문장을 잘 이해하지 못하고 있는 것 같아요. 다즐이 주신 질문이 `테스트 메서드 실행 후 rollback 과정에서 에러가 발생하면 데이터가 지워지지 않을까?` 가 맞을까요?
그렇다면 지워지지 않을 것 같네요. 테스트용 인메모리 db를 사용한다면 큰 문제로 남지는 않겠지만, 그렇지 않으면 확실히 문제점이 될 수 있겠군🤔

2023-10-25 01:41 UTC, woo-chang approved these changes
답변해주신 질문과 반영해주신 내용 모두 확인했습니다 ㅎㅎ
3단계 미션 진행가시죠 포이 👍

2023-10-25 01:41 UTC, merged