[레거시 코드 리팩터링 - 2단계] 베로(김은솔) 미션 제출합니다.
woowacourse/jwp-refactoring pull request #611
Opened 2023-10-24 02:13 UTC by Cyma-s

안녕하세요 아코... 미션 제출이 너무 늦었죠 ㅠㅠ 커밋 기록도 엉망진창입니다 😂 죄송해요
이번 단계에서 JPA 반영해보았습니다! JDBC 로 해보려고 했는데 너무 어렵더라구요.. JDBC 커밋 이후는 여기서부터 봐주시면 좋을 것 같습니다!
미션 리뷰 잘 부탁드립니다 :)

2023-10-24 10:31 UTC, seokhwan-an requested changes
안녕하세요 베로!

먼저 리팩토링이 깔끔해서 코드 리뷰를 진행하는데 큰 어려움이 없었습니다.
저도 코드를 보면서 많이 배울 수 있었던 것 같아요!
특히, repository에서 default를 이용해서 검증하는 것 인상 깊었습니다.

수정할 부분에 대해서 리뷰 남겼으니 수정하고 요청 보내주세요!

2023-10-24 10:31 UTC, seokhwan-an commented on src/main/java/kitchenpos/application/dto/MenuCreateRequest.java
> +    private List<Long> menuProductIds;
현재 이 부분이 menus.http에 있는 요청과 다른 것 같아요

2023-10-24 10:31 UTC, seokhwan-an commented on src/main/java/kitchenpos/application/dto/OrderCreateRequest.java
> +    private List<OrderLineItemCreateRequest> orderLineItems;
여기도 orders.http 요청과 다른 것 같아요! :)

2023-10-24 10:31 UTC, seokhwan-an commented on src/main/java/kitchenpos/application/MenuService.java
>      }
현재 메뉴 금액을 검증하는 로직이 없어졌는데 MenuCreateRequest에 price 항목이 다시 생기게 되면 검증하면 좋을 것 같아요!

2023-10-24 10:31 UTC, seokhwan-an commented on src/main/java/kitchenpos/application/MenuService.java
> +        final List<MenuProduct> menuProducts = menuProductRepository.getAllById(request.getMenuProductIds());
이 부분 menuProductRepository를 이용해서 default 메소드로 검증하는 것 좋네요!

2023-10-24 10:31 UTC, seokhwan-an commented on src/main/java/kitchenpos/application/MenuService.java
혹시 이 부분은 위와 같이 repository 단에서 검증을 하는 것이 아닌 serivce에서 검증을 했던 이유가 있을까요?

2023-10-24 10:31 UTC, seokhwan-an commented on src/main/java/kitchenpos/application/OrderService.java
orderLineItem를 모두 불러오지 않고 stream을 돌면서 존재하는지 파악하는 것은 좋네요
다만 고민이 되는 것은 주문에 들어오는 orderLineItem의 개수가 많아지게 되면 날아가는 요청이 많아질 것 같은데 이 부분에 대해서 어떻게 생각하시나요?

2023-10-24 10:31 UTC, seokhwan-an commented on src/main/java/kitchenpos/application/OrderService.java
> +        final Order order = Order.forSave(OrderStatus.COOKING, orderLineItems);
이 부분은 orders.http에 맞게 request를 수정하면 따로 상태를 받을 필요 없을 것 같습니다!

2023-10-24 10:31 UTC, seokhwan-an commented on src/main/java/kitchenpos/application/TableService.java
>      }
jpa를 이용하고 있어서 response 반환할 때 굳이 save 다시 할필요가 없을 거 같아요

2023-10-24 10:31 UTC, seokhwan-an commented on src/main/java/kitchenpos/application/TableService.java
> +        return OrderTableResponse.from(orderTableRepository.save(orderTable));
여기도 위와 같은 리뷰로 다시 save할 필요가 없을 것 같아요

2023-10-24 10:31 UTC, seokhwan-an commented on src/main/java/kitchenpos/application/TableGroupService.java
>      }
혹시 여기서 savedOrderTables를 tableGroup에서 get으로 불러오지 않고 repository로 불러오는 이유가 있을까요?

2023-10-24 10:31 UTC, seokhwan-an commented on src/main/java/kitchenpos/application/TableGroupService.java
> +        orderTableRepository.saveAll(orderTables.getOrderTables());
현재 흐름을 보면 tableGroup을 먼저 만들고 ordertables를 검증한 후에 ordertable에서 tableGroup과 연관관계를 맺어주고 있는데요!
이 부분 순서를 OrderTables 이용해서 요청온 ordertable들을 검증하고 tableGroup을 생성할 때 인자로 받아 내부적으로 연관관계를 맺어주는 것 어떤가요?

2023-10-24 10:31 UTC, seokhwan-an commented on src/main/java/kitchenpos/dao/MenuDao.java
> +import kitchenpos.domain.Menu;
JDBC 구현체는 모두 삭제했는데 DAO는 삭제하지 않으신 이유가 있으신가요?

2023-10-24 10:31 UTC, seokhwan-an commented on src/test/java/kitchenpos/application/MenuGroupServiceTest.java
> +            .comparingOnlyFields("id", "name")
혹시 이 부분을 따로 명시해주신 이유가 있을까요?

2023-10-24 10:31 UTC, seokhwan-an commented on src/test/java/kitchenpos/acceptance/OrderServiceAcceptanceTest.java
> +        // given
현재 이부분 테스트 명이 명확하게 나타나 있지 않아서 명시해주면 좋을 것 같습니다!

2023-10-24 11:03 UTC, Cyma-s commented on src/main/java/kitchenpos/application/dto/MenuCreateRequest.java
> +    private List<Long> menuProductIds;
요청 응답과 dto 를 맞추는 걸 깜빡했더라고요.. 수정했습니다!

2023-10-25 05:25 UTC, Cyma-s commented on src/main/java/kitchenpos/application/MenuService.java
>      }
메뉴 금액을 검증하는 로직은 MenuPrice 가 정확하게 계산한다고 생각했는데, 누락된 로직이 있었네요 👍🏻 👍🏻 👍🏻 👍🏻  추가했습니다!

2023-10-25 05:25 UTC, Cyma-s commented on src/main/java/kitchenpos/application/MenuService.java
> +        final List<MenuProduct> menuProducts = menuProductRepository.getAllById(request.getMenuProductIds());
저도 베베 리뷰하다가 좋아보여서 가져왔는데, 데이터 유무에 대한 검증 부분이 서비스 계층에서 가려져서 훨씬 좋은 것 같아요 :)

2023-10-25 05:27 UTC, Cyma-s commented on src/main/java/kitchenpos/application/MenuService.java
해당 existsById 는 `MenuGroup` 을 리턴하는 값이 아니기 때문에 굳이 repository 에서 검증하지 않아도 된다고 생각하기는 했습니다! 아코는 해당 메서드가 repository 에서 검증되어야 한다고 생각하시나요? 의견 궁금합니다!!!!

2023-10-25 05:30 UTC, Cyma-s commented on src/main/java/kitchenpos/application/OrderService.java
맞습니다 그런 문제가 있을 수 있겠네요!! existsAllById 메서드로 변경했습니다 👍🏻

2023-10-25 05:31 UTC, Cyma-s commented on src/main/java/kitchenpos/application/OrderService.java
> +        final Order order = Order.forSave(OrderStatus.COOKING, orderLineItems);
제가 이 부분 리뷰를 잘 이해 못했는데, 상태를 받을 필요가 없다는 게 무슨 뜻인지 모르겠습니다 ㅠㅠ
`OrderStatus` 를 따로 받을 필요가 없다는 뜻일까요?

2023-10-25 05:46 UTC, Cyma-s commented on src/main/java/kitchenpos/application/TableService.java
>      }
성공 테스트를 하려다보니 save 한 객체를 from 에 넘겨줘야 제대로 ID 를 검증할 수 있는 테스트가 되더라고요. 그냥 테스트를 삭제했습니다..ㅋㅋㅋ

2023-10-25 05:48 UTC, Cyma-s commented on src/main/java/kitchenpos/application/TableGroupService.java
>      }
오 그렇네요 ㅋㅋㅋㅋ 기존 코드에서 `findAllByTableGroupId` 로 가져오는 코드가 있어서 그랬었나봐요! 수정했습니다 👍🏻

2023-10-25 05:50 UTC, Cyma-s commented on src/main/java/kitchenpos/dao/MenuDao.java
> +import kitchenpos.domain.Menu;
추후에 사용될 부분이 있다고 생각했는데 생각해보니 이제는 Repository 가 해당 역할을 하게 되겠네요. DAO 도 모두 삭제했어요!

2023-10-25 05:51 UTC, Cyma-s commented on src/test/java/kitchenpos/acceptance/OrderServiceAcceptanceTest.java
> +        // given
ㅋㅋㅋㅋ ㅜㅜㅜ 실수입니다 매의 눈 🦅

2023-10-25 06:02 UTC, Cyma-s commented on src/main/java/kitchenpos/application/TableGroupService.java
> +        orderTableRepository.saveAll(orderTables.getOrderTables());
그게 좀 더 깔끔한 것 같아요! 변경해보았습니다 👍🏻

2023-10-25 08:45 UTC, seokhwan-an commented on src/main/java/kitchenpos/application/MenuService.java
저는 통일성이 조금 떨어지는 것 같아서 물어보았습니다. db만을 이용해서 검증하는 것에 대해서 repository에서 감싸서 해결이 되고 어떤 것은 service에 명시적으로 처리가 되어 있는데요! 처음 코드를 분석하는 상황에서는 혼란이 올 수 있을 것 같아서 물어보았습니다. 저는 개인적으로는 통일성 있게 처리가 되면 좋다고 생각합니다!

2023-10-25 08:52 UTC, seokhwan-an commented on src/main/java/kitchenpos/application/OrderService.java
> +        final Order order = Order.forSave(OrderStatus.COOKING, orderLineItems);
이 부분 orderservice에서 orderStatus를 수정하는 요청처리라고 생각하고 리뷰를 잘못 남겼었네요! 혼란을 주어서 죄송합니다😅

2023-10-25 09:51 UTC, seokhwan-an approved these changes
안녕하세요 베로!

제가 제시해준 리뷰에 대해서 빠르게 반영해주셨네요! 👍👍

이번 단계에서는 크게 수정할 부분이 보이지 않아서 approve 하겠습니다.
베로가 의견 물어본 것에 대해 답변 남겨놓았습니다!

2단계도 고생하셨고 3단계 화이팅입니다!💪💪

2023-10-25 09:52 UTC, merged

2023-10-25 09:55 UTC, Cyma-s commented on src/main/java/kitchenpos/application/MenuService.java
좋습니다 동작을 변경하는 쪽으로 변경해볼게요!