[레거시 코드 리팩터링 - 2단계] 조이(김성연) 미션 제출합니다.
woowacourse/jwp-refactoring pull request #615
Opened 2023-10-24 05:10 UTC by yeonkkk

안녕하세요 도기! 🐶🐾 조이입니다~

먼저 지난 리뷰 꼼꼼하게 해주셔서 감사합니다 ㅎㅎ👍
2단계 리뷰 요청을 하기까지 상당히 오랜 시간이 걸렸네요..😓

이번 단계에서는 기존 코드에서 변화가 꽤 있어서 변경된 부분들을 간략히 설명드리고자 해요!
- 서비스에 몰려있던 로직을 도메인으로 일부 위임하였고, 그에 맞춰 도메인 테스트도 작성하였습니다.
- controller와 도메인의 의존을 고려하여 request와 response를 생성하였습니다. 
- JPA를 잘 다루지는 못 하지만 레거시 코드에서 JPA를 적용하는 경험을 해보고 싶어서 JPA도 도입을 한번 해 봤습니다. 생산성 측면에서도 변경에 용이할 것 같아서 적용해봤어요. (도기는 어떤 방식으로 진행하셨는지 궁금하네요 ㅎㅎ)
- 기존에 작성해 둔 통합 테스트는 수정하긴 했지만, 이전 코드에서 많이 바뀐 점은 없습니다.

이번 미션은 여러가지 일정들과 겹쳐서 신경을 많이 쓰지 못 했습니다..
그래서 제가 보기에도 아쉬움과 부족함이 많이 느껴지는 코드네요..리뷰 반영하면서 계속 수정해나가겠습니다.
리뷰 잘 부탁드립니다!

2023-10-24 08:56 UTC, kdkdhoho requested changes
안녕하세요 조이~ 오늘 하루 잘 보내셨나요??

전체적으로 꼼꼼하게 잘 작성해주셨네요 👏 바쁘신 와중에 정말 수고하셨습니다 👍 
다만, 2단계 요구사항이 '서비스 리팩터링'인데 아직은 많이 홀쭉해지지 못한 것 같아요.
많은 비즈니스 로직들이 충분히 도메인 객체 안으로 들어갈 수 있다고 판단해서 RC 하겠습니다..!

'JPA 연관관계 편의 메서드' 라는 키워드를 참고하셔서 서비스 계층을 홀쭉하게 만들 수 있을 것 같아요.
그럼 조금만 더 힘내주세욧..!

---

저도 JPA를 잘 다루진 못하는지만, 조이랑 같은 이유로 적용해봤습니다 ㅎㅎ

2023-10-24 08:56 UTC, kdkdhoho commented on src/main/java/kitchenpos/application/MenuGroupService.java
> +        final MenuGroup menuGroup = MenuGroupMapper.toMenuGroup(request);
`~~Mapper` 객체에서 Request -> Domain && Domain -> Response로의 변환을 모두 처리해주는군요! 참신하네요 👍 피움 팀에서 채용한 방식인가요?

그런데 Request 객체에서 `toDomain()` 같은 메서드로 Domain 객체를 생성해주는 건 어떻게 생각하세요?
반대로 Response 객체에서 파라미터를 도메인 객체를 받는 정팩메를 만드는 방법도 마찬가지입니다!

2023-10-24 08:56 UTC, kdkdhoho commented on src/main/java/kitchenpos/application/MenuService.java
> +        validateMenuPrice(menu, sum);
뭔가,, 이 로직들 도메인 내부로 넣을 수 있을 것 같은데요 🤔

2023-10-24 08:56 UTC, kdkdhoho commented on src/main/java/kitchenpos/domain/Menu.java
> +    @JoinColumn(name = "menu_group_id", nullable = false)
nullable 속성까지 꼼꼼하시네요 👍

2023-10-24 08:56 UTC, kdkdhoho commented on src/main/java/kitchenpos/domain/Menu.java
>      private BigDecimal price;
이 price 라는 필드를 값 객체로 만들어주는건 어떠신가요??

2023-10-24 08:56 UTC, kdkdhoho commented on src/main/java/kitchenpos/domain/Order.java
>      private String orderStatus;
얘도 필드 타입을 String이 아니라 `OrderStatus` 타입으로 해주는게 좋아보여요.
JPA의 `@Enumurated` 라는 키워드를 참고해보세용

2023-10-24 08:56 UTC, kdkdhoho commented on src/main/java/kitchenpos/domain/Order.java
> +    private OrderTable orderTable;
주문과 테이블의 관계를 1:1로 매핑해주셨네요!
테이블 하나당 주문을 한 번밖에 못하나요??

현재 요구사항에는 관련된 내용이 없는 것 같아서 질문드립니다.
만약 조이가 나름대로 비즈니스 규칙을 만든거라면 검증 로직이 추가로 필요할 것 같아요.

2023-10-24 08:56 UTC, kdkdhoho commented on src/main/java/kitchenpos/domain/OrderLineItem.java
>      }
오 전 이 부분 놓친 것 같은데 진짜 꼼꼼하시네요 👍

그런데 메서드의 결과가 null이 나올 수 있다는 걸 명시해줘야 할 것 같은데,, 어떻게 생각하시나요??

2023-10-24 08:56 UTC, kdkdhoho commented on src/main/java/kitchenpos/domain/OrderTable.java
> +    }
이 부분도 딱 보니 VO로 뺄 수 있겠군요.

2023-10-24 08:56 UTC, kdkdhoho commented on src/main/java/kitchenpos/domain/OrderLineItem.java
>      private long quantity;
얘도 VO로..? 🤔

2023-10-25 04:52 UTC, yeonkkk commented on src/main/java/kitchenpos/application/MenuGroupService.java
> +        final MenuGroup menuGroup = MenuGroupMapper.toMenuGroup(request);
네 프로젝트하면서 사용했었는데, 제가 느끼기엔 좋아서 적용해봤습니다 ㅎㅎ
저는 Request, Response dto 에서 객체를 변환해주는 것도 좋은 것 같아요 ~ 
그런데 변환 역할을 Mapper로 분리해서 가져가면 특정 도메인에 대한 변환 로직을 한 곳에서 관리하기 때문에 편하더라구요.
그래서 저는 이번에  Mapper 를 사용했습니다🙂

도기는 어떤 방식을 선호하시나요?

2023-10-25 04:52 UTC, yeonkkk commented on src/main/java/kitchenpos/application/MenuService.java
> +        validateMenuPrice(menu, sum);
후딱 넣어봤습니다ㅎ

2023-10-25 04:52 UTC, yeonkkk commented on src/main/java/kitchenpos/domain/Menu.java
>      private BigDecimal price;
너무 좋은 것 같아요! 
사실 VO로 만들 생각을 하긴 했는데,,, 시간과 타협해버렸네요,, 
리뷰 보고 정신차리고 적용했습니다!

2023-10-25 04:52 UTC, yeonkkk commented on src/main/java/kitchenpos/domain/Order.java
>      private String orderStatus;
놓친 부분인데 챙겨주셔서 감사합니다! 짱🫡

2023-10-25 04:52 UTC, yeonkkk commented on src/main/java/kitchenpos/domain/OrderLineItem.java
>      }
좋은 조언입니다. 
예상하지 못한 NPE 를 방지하려면 명시해주는 것이 좋을 것 같네요. 
적용했습니다!

2023-10-25 04:52 UTC, yeonkkk commented on src/main/java/kitchenpos/domain/OrderLineItem.java
>      private long quantity;
좋은 것 같아요.
내부에서 검증도 하면 되겠네요👍

2023-10-25 04:52 UTC, yeonkkk commented on src/main/java/kitchenpos/domain/OrderTable.java
> +    }
완료입니당

2023-10-25 04:52 UTC, yeonkkk commented on src/main/java/kitchenpos/domain/Order.java
> +    private OrderTable orderTable;
저는 1:1 매핑이라고 생각했었는데..service 로직을 보니 orderTable에 대한 order가 여러개더라구요..
짚어주셔서 감사해요! 변경했습니다 ㅎㅎ

2023-10-26 01:08 UTC, kdkdhoho commented on src/main/java/kitchenpos/application/MenuGroupService.java
> +        final MenuGroup menuGroup = MenuGroupMapper.toMenuGroup(request);
저는 DTO에서 도메인 객체를 변환해주는 방식을 선호합니다.
사실 중간에 Mapper를 둘 생각을 하지 못했던 것 같아요 😅

2023-10-26 01:17 UTC, kdkdhoho approved these changes
안녕하세요 조이~ 어제 밤에 리뷰남기려고 했는데 집가니까 기절해버려서 이제야 리뷰 남기네요 ㅜㅜ
늦어서 죄송합니다 :시든피우미:

그나저나 변경 사항이 꽤 있었을텐데 리팩터링 너무너무 고생하셨어요!
2단계 요구사항은 만족한 것 같아 이만 머지하겠습니다.
남은 단계도 화이팅입니다 !!!!!!!!!!!!

2023-10-26 01:18 UTC, merged