[레거시 코드 리팩터링 - 1단계] 에밀(김대희) 미션 제출합니다.
woowacourse/jwp-refactoring pull request #619
Opened 2023-10-24 05:48 UTC by CFalws

저문 제가 많이 늦었습니다... 
테스트는 서비스 테스트 보다는 현재는 인수 테스트를 하는 것이 더 적합할 것이라 생각하여 인수테스트로 진행해보았습니다! 
감사합니다.

2023-10-24 12:02 UTC, jeomxon requested changes
안녕하세요 에밀 :)
바쁘신 와중에 미션하느라 고생 많으셨어요 ㅎㅎ

요구사항 파악여부를 중점적으로 리뷰 드렸어요.
궁금하신 부분이나 이야기 나누고 싶은 부분이 있다면 코멘트 혹은 DM 언제든지 환영입니다!

2023-10-24 12:02 UTC, jeomxon commented on README.md
> +    - ex) 주문1은 메뉴a 1개, 메뉴b 2개로 구성될 수 있다.
예시를 들어서 적어주신 부분이 인상깊네요.
저도 에밀이 적어주신 방식으로 이해하려고 했는데, 빠르게 이해하는데 도움이 되고 기억에 오래 남았어요.
👍🏻

2023-10-24 12:02 UTC, jeomxon commented on README.md
> +    - ex) 메뉴a가 메뉴 상품1을 2개 가질 수 없다.
이 부분이 잘 이해가 가질 않는데, 코드의 어떤 부분을 보고 이렇게 적어주셨나요?

2023-10-24 12:02 UTC, jeomxon commented on README.md
> +  - 테이블 그룹에 속할 수 있다(필수 x)
이것도 필수사항이 아닌가요??🧐

2023-10-24 12:02 UTC, jeomxon commented on README.md
> +  - 주문 테이블은 빈 상태로 만들 수 있다. 단, 테이블 그룹에 속해 있을 때는 빈 상태로 만들 수 없다.
빈 상태, 아닌 상태 모두 만들 수 있을 것 같은데 수정해보는 것은 어떨까요?

2023-10-24 12:02 UTC, jeomxon commented on src/main/java/kitchenpos/domain/OrderTable.java
> +    }
두 개의 클래스에 대해서만 `equals & hashCode`를 재정의 해주신 이유가 있을까요?

2023-10-24 12:02 UTC, jeomxon commented on src/test/java/kitchenpos/DatabaseSetter.java
> +    }
클래스로 만들어서 컴포넌트로 등록하여 사용해주셨군요!
.sql파일로도 만들 수 있을 것 같은데 어떤 차이가 있으며,
왜 이런 방식을 선택했는지 궁금합니다!

2023-10-24 12:02 UTC, jeomxon commented on src/test/java/kitchenpos/MenuGroupIntegrationTest.java
> +    void create_success_duplicate_name() {
테스트 전반적으로 반영해주셨으면 하는 부분이 있어서 적어둡니다!
제이슨께서 be-5기-공지채널에 올려주셨던 공지사항인데요.
`@DisplayName`을 통해 테스트의 의미를 한글로 풀어내야 한다. 고 적혀있더라구요..ㅎㅎ

현재는 메서드 명만 보고 어떤 검증을 하는지 명확하게 파악하기 어려운 것 같아요.
반영해보시는 것이 어떨까요?

<img width="692" alt="image" src="https://github.com/woowacourse/jwp-refactoring/assets/51906604/2e9ff88c-db80-4254-a218-bebbe9ebebde">

2023-10-24 12:02 UTC, jeomxon commented on src/test/java/kitchenpos/MenuIntegrationTest.java
> +    }
이 테스트는 현재 실패하고 있는 것 같아요!

2023-10-24 12:02 UTC, jeomxon commented on src/test/java/kitchenpos/fixture/MenuGroupFixture.java
> +public enum MenuGroupFixture {
처음 보는 픽스처 방식인데, 이렇게도 픽스처를 만들 수 있군요!
한수 배워갑니다..ㅎㅎ

다만 추후에 도메인으로 로직을 옮기게되면서 setter를 삭제한다면 어떻게 변경하실 생각인지 궁금하네요!

2023-10-24 12:02 UTC, jeomxon commented on src/test/java/kitchenpos/steps/IntegrationTestSteps.java
> +                      .put(ORDER_TABLE_API + "/" + tableId + "/empty")
```suggestion
                      .put(ORDER_TABLE_API + "/{tableId}/empty", tableId)
```
저는 개인적으로 concat하는 것 보다 위와 같은 방식이 더 깔끔한 것 같더라구요!
이 부분은 선택적으로 반영해주시면 됩니다.

2023-10-24 13:30 UTC, CFalws commented on README.md
> +    - ex) 메뉴a가 메뉴 상품1을 2개 가질 수 없다.
이건 제가 개인적으로 추가한 요구사항인데요 
MenuProduct는 Product와 quantity라는 속성을 가지고 있으므로 중복된 MenuProduct가 하나의 Menu에 있는 것은 검증 대상이지 않을까 하는 생각이었어요
그런데 생각해보니 굳이? 그런 제한 사항을 둘 필요가 있을까라는 생각이 드네요!

2023-10-24 13:37 UTC, CFalws commented on README.md
> +  - 테이블 그룹에 속할 수 있다(필수 x)
테이블 그룹 같은 경우에는 nullable 하다고 판단했어요! 
처음 생성될 때 null로 저장되니까요! 
그런데 손님 수 같은 경우에는 not null이 도메인 로직 상 더 맞다고 판단이 드네요!

2023-10-24 13:38 UTC, CFalws commented on README.md
> +  - 테이블 그룹에 속할 수 있다(필수 x)
하지만 처음에 Table이 생성될 때 검증 로직이 없어서 아마 처음에 그렇게 판단했던 것 같아요

2023-10-24 13:41 UTC, CFalws commented on README.md
> +  - 주문 테이블은 빈 상태로 만들 수 있다. 단, 테이블 그룹에 속해 있을 때는 빈 상태로 만들 수 없다.
```
@Transactional
    public OrderTable changeEmpty(final Long orderTableId, final OrderTable orderTable) {
        final OrderTable savedOrderTable = orderTableDao.findById(orderTableId)
                .orElseThrow(IllegalArgumentException::new);

        if (Objects.nonNull(savedOrderTable.getTableGroupId())) {
            throw new IllegalArgumentException();
        }
```
해당 코드에서 savedOrderTable의 tablegroup이 non-null이면 예외를 터뜨리게 되어서 
```
단, 테이블 그룹에 속해 있을 때는 빈 상태로 만들 수 없다.
```
라고 판단했습니다. 
혹시 코멘트 내용이 제가 생각한 방향과 같을까요?

2023-10-24 13:42 UTC, CFalws commented on src/main/java/kitchenpos/domain/OrderTable.java
> +    }
전 테스트를 위해서 equals, hashcode를 편하게 재정의하는 편이라 이렇게 작성했는데요
생각해보니 일관성이 떨어진다고 판단이 되기도 하네요!

2023-10-24 13:45 UTC, CFalws commented on src/test/java/kitchenpos/fixture/MenuGroupFixture.java
> +public enum MenuGroupFixture {
추후에 해당 domain 객체들은 dto로 변경할 생각입니다! 
dto 같은 경우에는 setter를 둬도 괜찮다고 생각해요
도메인 객체처럼 로직을 수행하지 않기 때문에, 응집성을 가질 필요가 없다고 생각하고 캡슐화를 위반하는 것이 문제가 되지 않는다고 생각하기 때문입니다

2023-10-24 13:46 UTC, CFalws commented on src/test/java/kitchenpos/steps/IntegrationTestSteps.java
> +                      .put(ORDER_TABLE_API + "/" + tableId + "/empty")
오 이렇게 할 수 있군요! bb

2023-10-24 14:10 UTC, CFalws commented on src/test/java/kitchenpos/MenuGroupIntegrationTest.java
> +    void create_success_duplicate_name() {
앗 놓쳤네요! 
반영했습니다

2023-10-24 14:23 UTC, CFalws commented on src/test/java/kitchenpos/DatabaseSetter.java
> +    }
sql 파일은 override 하기가 상당히 불편하다고 느껴졌어요! 
특정 메서드에서는 a.sql을 실행하고 다른 메서드에서는 a.sql, b.sql을 모두 실행하고 싶을 수가 있는데요 
그럴 때 여러 sql 파일이 생기는 것보다 메서드를 호출하는 것이 더 유지보수성이 좋다고 느꼈습니다! 
물론 지금은 그런 경우가 없지만 복잡도가 높아지는 경우에는 파일 실행보다 메서드 호출이 더 편하더라구요

2023-10-24 14:23 UTC, CFalws commented on src/test/java/kitchenpos/DatabaseSetter.java
> +    }
또한 저도 방금 찾아보면서 알았는데 이런 경우도 있다고 합니다 !
https://stackoverflow.com/questions/47775560/how-can-springs-test-annotation-sql-behave-like-beforeclass

2023-10-25 00:37 UTC, jeomxon commented on README.md
> +    - ex) 메뉴a가 메뉴 상품1을 2개 가질 수 없다.
이해했습니다!

2023-10-25 00:40 UTC, jeomxon commented on README.md
> +  - 테이블 그룹에 속할 수 있다(필수 x)
<img width="426" alt="image" src="https://github.com/woowacourse/jwp-refactoring/assets/51906604/d2d61ff8-00c7-44cb-88a7-d2848cb3de3d">

에밀이 적어주신 `(필수 x)`라는 부분은 nullable할 수 있다는 것을 의미였군요!
저는 위의 이미지처럼 용어사전에 적혀있던 용어 기준으로 생각했을 때 방문한 손님 수만 필수사항이 아니라고 생각했어요.
용어에 대한 오해로 인해 생긴 문제였군요..ㅎㅎ

2023-10-25 00:43 UTC, jeomxon commented on README.md
> +  - 주문 테이블은 빈 상태로 만들 수 있다. 단, 테이블 그룹에 속해 있을 때는 빈 상태로 만들 수 없다.
이것도 용어에 오해가 있었던 것 같아요.
저는 README.md의 용어사전 기준으로 단어를 이해했습니다!
따라서 빈 테이블 -> OrderTable의 empty상태인 boolean의 값으로 이해했어요.
`changeEmpty()`를 통해서 만들 수 있는 테이블의 empty상태는 true와 false 모두 가능하다는 의미에서 위의 코멘트를 남겼어요.

2023-10-25 00:46 UTC, jeomxon commented on src/main/java/kitchenpos/domain/OrderTable.java
> +    }
좋습니다!
저도 `AutoIncrement`로 id자체가 식별자가 될 수 있는 경우 `equals & hashCode`를 재정의하는 것을 선호합니다!
일관성을 유지하면 좋을 것 같아 말씀 드렸습니다.

2023-10-25 00:54 UTC, jeomxon commented on src/test/java/kitchenpos/DatabaseSetter.java
> +    }
좋은 의견과 자료 공유 감사합니다!
저도 덕분에 하나 배워가네요~

2023-10-25 00:56 UTC, jeomxon commented on src/test/java/kitchenpos/fixture/MenuGroupFixture.java
> +public enum MenuGroupFixture {
👍🏻 2단계 때 어떻게 변하는지 확인해볼게요 ㅎㅎ

2023-10-25 01:02 UTC, jeomxon approved these changes
리뷰 반영해주시느라 고생하셨습니다!
에밀의 인수테스트를 보면서 경험치를 많이 쌓을 수 있었네요 :)
2단계 바로 진행하시면 될 것 같아요 ㅎㅎ

2023-10-25 01:02 UTC, merged