[레거시 코드 리팩터링 - 2단계] 후추(주찬민) 미션 제출합니다.
woowacourse/jwp-refactoring pull request #620
Opened 2023-10-24 05:55 UTC by Combi153

안녕하세요 로이스!

2단계 미션 제출합니다.

정신없던 2단계 미션이어서, 놓친 부분이 많을 것만 같네요 😭 

미션하면서 객체에게 책임을 부여하도록 리팩터링 하는 것에 목적을 두었습니다.

리뷰 잘 부탁드려요 😄

2023-10-24 07:42 UTC, TaeyeonRoyce requested changes
안녕하세요, 후추!
File changed를 보니 후추의 수고가 느껴지네요..! 고생 많으셨습니다.
잘 정리된 요구사항과 도메인으로 로직들을 담아내려는 의도가 잘 담긴것 같습니다!
값객체와 일급컬렉션 도입한 부분들이 인상깊네요!

몇가지 코멘트 남겨두었으니 확인해주세요!!

2023-10-24 07:42 UTC, TaeyeonRoyce commented on README.md
> +- [ ] Repository 도입
요구사항 잘 만족하신거 같은데 체크하시죠!!

2023-10-24 07:42 UTC, TaeyeonRoyce commented on README.md
> +- 주문 테이블이 비었다면 주문할 수 없다.
꼼꼼한 정리👍

2023-10-24 07:42 UTC, TaeyeonRoyce commented on src/main/java/kitchenpos/application/MenuService.java
> +        Menu menu = request.toMenu(menuProducts);
사소하지만, 네이밍의 차이를 주면 어떨까요?
`request.toMenu(menuProducts)`메서드는 `request`를 `Menu`로 반환하는 기대를 하게 되었는데,
private한 `toMenuProducts()` 메서드는 외부에서 호출할 일 없이 `인자`를 전달하여 `MenuProducts`로 반환하니 조금 헷갈렸어요!

<br/>

```java
List<MenuProduct> menuProducts = menuProductsFrom(request.getMenuProducts())
```
 는 어떠신가요?

2023-10-24 07:42 UTC, TaeyeonRoyce commented on src/main/java/kitchenpos/application/OrderService.java
> +    private final OrderLineItemRepository orderLineItemRepository;
사용하지 않으니 지워주시죠!

2023-10-24 07:42 UTC, TaeyeonRoyce commented on src/main/java/kitchenpos/application/MenuService.java
> +    public List<MenuResponse> list() {
`@Transactional(readOnly = true)` 를 명시해주어도 좋을 것 같아요!

2023-10-24 07:42 UTC, TaeyeonRoyce commented on src/main/java/kitchenpos/application/TableGroupService.java
> +        savedTableGroup.group();
`OrderTable`을 `group`하기 위한 검증은 `TableGroup`을 생성하면서 실행되고 있는데요.
실제 `grouping`하는 로직을 따로 분리해둔 이유가 있을까요?

2023-10-24 07:42 UTC, TaeyeonRoyce commented on src/main/java/kitchenpos/application/TableGroupService.java
> +        );
이 부분은 DB에 의존적이지 않게 분리해보는건 어떨까요?
`TableGroup`을 `ungroup`하는 정책이 DB 쿼리에 담겨있는 것 같아요. 만약 정책이 변경되면, 조회하는 쿼리 로직을 변경해야 하는데 어플리케이션 레벨에서 해결해도 좋아보입니다.

`tableGroup.ungroup()`의 검증은 boolean으로 결정되는데, 조회된 `orders`를 통해서 검증하여 어떤 정책인지 드러내도 좋을 것 같아요!

2023-10-24 07:42 UTC, TaeyeonRoyce commented on src/main/java/kitchenpos/dto/table/OrderTableCreateRequest.java
> +    }
TableGroup이 없는 OrderTable을 의미하는 걸까요?
그렇다면, empty라는 필드가 존재하니 `toOrderTableWithoutGroup` 이런식으로 명시하면 좋을 것 같아요.

2023-10-24 07:42 UTC, TaeyeonRoyce commented on src/main/java/kitchenpos/application/TableService.java
> +        );
얘도 고민해봐도 좋을 것 같네요!!

2023-10-24 07:42 UTC, TaeyeonRoyce commented on src/main/java/kitchenpos/domain/Menu.java
> +    private MenuProducts menuProducts;
일급 컬렉션👍👍

2023-10-24 07:42 UTC, TaeyeonRoyce commented on src/main/java/kitchenpos/domain/Menu.java
> +        this(null, name, price, menuGroupId, menuProducts);
이 생성자를 통해 생성되는 Menu는 MenuProducts에 대한 검증은 불필요한걸까요?

2023-10-24 07:42 UTC, TaeyeonRoyce commented on src/main/java/kitchenpos/domain/Menu.java
> +        }
이 검증은 `Money`에서 이루어져도 괜찮을 것 같습니다!

2023-10-24 07:42 UTC, TaeyeonRoyce commented on src/main/java/kitchenpos/domain/Menu.java
>      private Long id;
얘만 순서가 다르네요!!
```suggestion
    @GeneratedValue(strategy = IDENTITY)
    @Id
    private Long id;
```

2023-10-24 07:42 UTC, TaeyeonRoyce commented on src/main/java/kitchenpos/domain/MenuProduct.java
> +    private Quantity quantity;
👍👍
quantity 분리도 좋네요!!

2023-10-24 07:42 UTC, TaeyeonRoyce commented on src/main/java/kitchenpos/domain/MenuProducts.java
> +    }
```suggestion
    protected MenuProducts() {
    }
```

2023-10-24 07:42 UTC, TaeyeonRoyce commented on src/main/java/kitchenpos/domain/Order.java
>      private LocalDateTime orderedTime;
명시적인 표현 좋네요!

`JpaAuditing`을 활용해서 `persist` 되기 직전에 시간을 자동으로 저장 할 수도 있습니다!
(반영하실 필요는 없어요!!)

2023-10-24 07:42 UTC, TaeyeonRoyce commented on src/main/java/kitchenpos/domain/OrderTable.java
> +    private TableGroup tableGroup;
JoinColumn은 의도적으로 제거하신 걸까요?

2023-10-24 07:42 UTC, TaeyeonRoyce commented on src/main/java/kitchenpos/domain/TableGroup.java
>      }
정적 팩토리 메서드에서만 검증을 두신 이유가 있을까요?
외부에서 `TableGroup`의 도메인 규칙을 무시한채 생성하고 사용 할 수 있을 것 같아요!
테스트를 위해 검증 없는 기존 생성자를 남겨두었다면 다른 방식으로도 해결해 볼 수 있을 것 같습니다..!!

2023-10-24 07:42 UTC, TaeyeonRoyce commented on src/main/java/kitchenpos/dto/order/OrderLineItemCreateRequest.java
> +    }
다른 dto 클래스들과 메서드 순서도 일관되게 getter 위로 옮기면 좋을 것 같습니다!

2023-10-24 07:42 UTC, TaeyeonRoyce commented on src/main/java/kitchenpos/repository/OrderRepository.java
> +    );
쿼리가 명시적으로 표현되어 있어 역할을 파악하기 용이하네요!
Spring data jpa에서 제공하는 `method query`를 사용해도 좋아보이네요!
https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.query-methods.details

아래처럼 수정 할 수 있어요

```suggestion
    boolean existsByOrderTableIdAndOrderStatusIn(
            Long orderTableId,
            List<OrderStatus> orderStatuses
    );
```

2023-10-24 07:42 UTC, TaeyeonRoyce commented on src/test/java/kitchenpos/domain/MenuProductsTest.java
> +        assertThatNoException().isThrownBy(() -> MenuProducts.from(menuProducts));
` assertThatNoException()` 배워 갑니다👍👍

2023-10-24 07:49 UTC, Combi153 commented on README.md
> +- [ ] Repository 도입
잊고 있었네요 😅 바로 체크하겠습니다!

2023-10-24 07:50 UTC, Combi153 commented on src/main/java/kitchenpos/application/MenuService.java
> +        Menu menu = request.toMenu(menuProducts);
이제보니 분명 두 메서드가 헷갈릴 수 있겠어요! 로이스가 말씀해주신 이름 좋은데요? 반영하겠습니다~

2023-10-24 07:55 UTC, Combi153 commented on src/main/java/kitchenpos/application/MenuService.java
> +    public List<MenuResponse> list() {
`@Transactional`을 클래스 상단에 적용하고, 조회 메서드에만 `@Transactioanl(readOnly = true)`를 설정하도록 리팩터링 했습니다 👍

2023-10-24 07:58 UTC, Combi153 commented on src/main/java/kitchenpos/dto/table/OrderTableCreateRequest.java
> +    }
empty 필드를 놓쳤네요! 확실히 구분해주는 것이 좋을 것 같습니다 👍

2023-10-24 07:58 UTC, Combi153 commented on src/main/java/kitchenpos/domain/Menu.java
> +    private MenuProducts menuProducts;
로이스 리뷰 👍 👍

2023-10-24 08:04 UTC, Combi153 commented on src/main/java/kitchenpos/domain/Menu.java
> +        }
처음에 검증을 Money에 두었다가, 다시 Menu, Product로 검증 위치를 옮겼습니다.

Menu, Product의 검증 로직이 서로 다르게 변경될 경우를 대비하기 위해서 입니다! 

만약 Menu의 최솟값이 1000으로 변경되었는데 Product의 최솟값이 이전과 동일하게 0이라면, Money에 검증 로직이 있는 경우 이 변화에 대응하기 어려울 것 같아요. 반면, Menu, Product가 검증로직을 따로 관리한다면 변화에 대응하기 쉬울 것으로 예상됩니다!

2023-10-24 08:05 UTC, Combi153 commented on src/main/java/kitchenpos/domain/Menu.java
>      private Long id;
오와 열!

2023-10-24 08:07 UTC, Combi153 commented on src/main/java/kitchenpos/domain/MenuProducts.java
> +    }
로이스의 매의 눈 발동!!

2023-10-24 08:16 UTC, Combi153 commented on src/main/java/kitchenpos/domain/Order.java
>      private LocalDateTime orderedTime;
JpaAuditing 알려주셔서 감사해요!

근데 실제 서비스라면 orderedTime을 위해 Auditing을 사용할지 궁금하네요. 만약 고객이 주문 버튼을 누른 시각과 persist 되는 시각이 차이가 난다면 문제가 될 가능성이 있지 않을까요? 예를 들어 배달 애플리케이션의 서버에서 어떠한 사유(주문 폭발로 인한 병목?)로 persist 되는 시간이 1~2분 늦춰지면, 추후 고객 서비스센터에서 orderedTime을 사용할 때 문제가 생길 수 있다고 생각해요.

저는 위와 같은 이유에서 Auditing 을 사용하지 않았습니다. 로이스는 어떻게 생각하시는지 궁금해요!

2023-10-24 08:18 UTC, Combi153 commented on src/main/java/kitchenpos/dto/order/OrderLineItemCreateRequest.java
> +    }
오와 열!!!

2023-10-24 08:22 UTC, Combi153 commented on src/main/java/kitchenpos/repository/OrderRepository.java
> +    );
JPA 진짜 멋쟁이네요!
남겨주신 공식문서도 감사합니다. 읽다보니 [어떤 키워드들을 지원해주는지](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#appendix.query.method.predicate) 상세하게 나와있는 것을 발견했어요. 앞으로 JPA 를 사용할 때 편리하겠네요 👍

2023-10-24 08:24 UTC, Combi153 commented on src/test/java/kitchenpos/domain/MenuProductsTest.java
> +        assertThatNoException().isThrownBy(() -> MenuProducts.from(menuProducts));
assertThat() 메서드가 Assertions의 메서드인데, 같은 Assertions의 메서드를 사용하고 싶어서 assertThatThrownBy 랑 같이 사용하는 편이에요!

2023-10-24 08:36 UTC, TaeyeonRoyce commented on src/main/java/kitchenpos/domain/Menu.java
> +        }
그렇네요! 분리해서 논리를 담아두는게 더 유연한 것 같습니다!
더 나가보면, `MenuPrice`와  `ProductPrice`로 분리해서 만들어도 괜찮겠네요..!!
단순 의견이니 반영 안 하셔도 됩니다~!😎

2023-10-24 08:49 UTC, TaeyeonRoyce commented on src/main/java/kitchenpos/domain/Order.java
>      private LocalDateTime orderedTime;
이런 관점도 있군요!!
말씀대로 그런 오차가 발생하면 문제가 있겠네요. 더 나아가서 글로벌 서비스라면 시간대에 따라 시간 관리를 하는게 중요 할 수도 있겠네요!

`persist(save)`가 호출 되었는데 `DB connection` 을 받아오는 동안 발생한 지연에 대해서는 문제가 없을 겁니다!


하지만 request가 발생 한 뒤 충분한 지연 이후에 persist가 된다면 문제가 있겠네요. 이런 경우는 `LocalDateTime.now()`로 직접 명시하는 것도 좋지만 요청 시간을 클라이언트한테 받는 방식으로도 고민해볼 수 있겠네요!!😀

2023-10-24 08:50 UTC, TaeyeonRoyce commented on src/test/java/kitchenpos/domain/MenuProductsTest.java
> +        assertThatNoException().isThrownBy(() -> MenuProducts.from(menuProducts));
```java
assertThatCode(() -> MenuProducts.from(menuProducts)).doesNotThrowAnyException();
```

요런 것도 있습니다!

2023-10-24 08:54 UTC, Combi153 commented on src/main/java/kitchenpos/domain/Menu.java
> +        }
패키지를 분리하게 된다면 그럴 계획이었어요! 의견주셔서 감사합니다~~ 😄

2023-10-24 08:57 UTC, Combi153 commented on src/main/java/kitchenpos/domain/Order.java
>      private LocalDateTime orderedTime;
글로벌 서비스에 대한 관점은 생각해보지 않았는데 새롭네요! 감사합니다. 
> 하지만 request가 발생 한 뒤 충분한 지연 이후에 persist가 된다면 문제가 있겠네요.
제가 말씀드리고 싶었던 부분이에요. 시각에 예민한 서비스라면 LocalDateTime 자체를 클라이언트에서 받는 게 좋다고 생각합니다!

2023-10-24 14:49 UTC, Combi153 commented on src/main/java/kitchenpos/domain/OrderTable.java
> +    private TableGroup tableGroup;
얼른 추가하겠습니다!

2023-10-24 14:52 UTC, Combi153 commented on src/main/java/kitchenpos/domain/TableGroup.java
>      }
생성자에 검증 로직이 많아지면 생성자의 부피가 커져서 가독성이 떨어지더라구요.

그래서 가능하다면 정적 팩토리 메서드에 검증 책임을 부여하고, 생성자는 순수한 상태로 사용하는 것을 선호합니다.

말씀하신대로 생성자가 public 으로 열려있는 점은 문제가 되겠네요. default 로 바꾸도록 하겠습니다!

2023-10-24 14:54 UTC, Combi153 commented on src/main/java/kitchenpos/domain/Menu.java
> +        this(null, name, price, menuGroupId, menuProducts);
의도한 바에 의하면 검증을 하지 않는 것이 맞습니다! 

리팩터링을 통해 보다 의도를 드러내겠습니다. 생성자를 default로 접근 제어자로 제한하고, 애플리케이션 코드에서는 MenuProducts를 정적 팩터리 메서드로만 생성할 수 있게 한다면 될 것이라 생각합니다!

2023-10-24 14:56 UTC, Combi153 commented on src/test/java/kitchenpos/domain/MenuProductsTest.java
> +        assertThatNoException().isThrownBy(() -> MenuProducts.from(menuProducts));
이 친구도 직관적이네요 다음에 사용해봐야겠습니다 👍

2023-10-25 08:06 UTC, Combi153 commented on src/main/java/kitchenpos/application/TableGroupService.java
> +        savedTableGroup.group();
group 이라는 메서드를 통해 객체가 행위의 주체가 될 수 있도록 하고 싶었습니다. 생성 로직에서 바로 grouping 이 되기 보다 group 메서드를 호출하는 것이 보다 명시적이라고 느꼈고요. 하지만 검증과 행위가 따로 분리된 느낌이어서 어색하네요. grouping 하기 위한 검증을 group 메서드에서 수행할 수 있도록 리팩터링 하겠습니다!

2023-10-25 08:09 UTC, Combi153 commented on src/main/java/kitchenpos/application/TableGroupService.java
> +        );
동의합니다. 해당 부분은 애플리케이션 레벨에서 해결하는 것이 맞겠네요. 그게 더 변화에 대처하기 쉬운 형태라고 생각해요!

OrderTable 목록을 조회하고 해당 OrderTable을 통해서 검증하도록 변경하겠습니다.

2023-10-25 08:10 UTC, Combi153 commented on src/main/java/kitchenpos/application/TableService.java
> +        );
맞아요! 위와 동일하게 변경했습니다!

2023-10-25 08:11 UTC, Combi153 commented
안녕하세요 로이스!

생각보다 고민해볼 거리가 많아서 이것저것 만져보다가 리뷰 요청이 늦어졌네요.

바로 내고 싶었는데 아쉽습니다!

리뷰해주신 부분 모두 보고, 필요에 따라 리팩터링했어요

확인해주시면 감사하겠습니다 😄

2023-10-25 08:29 UTC, TaeyeonRoyce approved these changes
후추, 고생 많으셨습니다!
변경 사항도 많았고, 리뷰도 많이 드렸는데 잘 반영해주셨네요!👍👍
질문 드린 부분들에 대해서도 답변 모두 남겨주셔서 코드에 담긴 후추의 의도를 파악하기 좋았습니다.
몇가지 코멘트 남겨두었는데 확인만 해주세요!

3단계 넘어가시죠! 고생하셨습니다~!
3단계 화이팅💪

2023-10-25 08:29 UTC, TaeyeonRoyce commented on src/main/java/kitchenpos/domain/table/OrderTable.java
> +        }
이 메서드는 테스트에서만 사용 되는 것 같네요.
1:N 양방향 관계 설정을 `1`과 `N`측 모두에서 검증과 함께 이루어지고 있는데요.
한 곳에서만 관리하는 방식으로 구현 하면 파악하기 더 용이 할 것 같아요!

2023-10-25 08:29 UTC, TaeyeonRoyce commented on src/main/java/kitchenpos/domain/table/OrderTableRepository.java
> +    List<OrderTable> findAllByTableGroupId(Long tableGroupId);
👍👍

2023-10-25 08:29 UTC, TaeyeonRoyce commented on src/main/java/kitchenpos/domain/table/TableGroup.java
> +    private List<Long> orderTableIds;
간접 참조로 사용하기 위해 비영속 설정을 해두신걸까요?
값객체로 분리해봐도 괜찮아 보이네요!

2023-10-25 08:29 UTC, TaeyeonRoyce commented on src/main/java/kitchenpos/domain/table/TableGroup.java
> +        validateOrderTableStatus(orderTables);
Table들을 group하는데 요구되는 도메인 규칙을이 모여있어서 파악 하기 좋네요!👍

2023-10-25 08:29 UTC, merged