[리팩터링 3단계] 오현서(오리) 미션 제출합니다.
woowacourse/jwp-refactoring pull request #629
Opened 2023-10-24 09:13 UTC by carsago

반가워요 지토.
제가 2단계에서 재리뷰 요청을 보낼때, 실수로 push를 안하고 리뷰 요청을 보냈더군요 ㅠㅠ; 입코딩으로 이해하셨던 내용은 이번 PR 포함되어 있습니다.

이번 미션에서 주로 한 것은 패키지를 도메인 단위로 쪼개고, 이에 대한 양방향 참조를 없애는 것에 주력을 두었습니다.

제가 나눈 도메인 패키지는 menu, order, table, product 4개 (그리고 ui와 vo 객체를 포함하는 common 패키지) 입니다.

product 패키지 - Product
menu 패키지 - Menu, MenuGroup, MenuProduct
Order 패키지 - Order, OrderStatus, OrderLineItem
Table 패키지 - TableGroup, OrderTable

패키지의 의존성은 다음과 같아요.

Product < - Menu <- Order -> Table

리뷰 요청 날리기전에 왜 이런식으로 했는지에 대한 코멘트를 남겨놓을게요~

2023-10-24 09:14 UTC, carsago commented on src/main/java/kitchenpos/menu/MenuGroup.java
MenuGroup은 Menu와 라이프 사이클은 다르지만, Menu를 생성하기 위한 필수 불가결한 조건이며, 그외에는 별다른 역할이 없다고 보아서 Menu와 같은 패키지에 두었어요.

2023-10-24 09:17 UTC, carsago commented on src/main/java/kitchenpos/menu/MenuProduct.java
> +    private Price price;
Menu가 Product가 변경됨에 따라 바뀌지 않도록 필드(테이블 입장에선 컬럼)에 저장당시 price와 name을 넣어주었습니다.
다만 이렇게 되니 menu_id가 객체도, 테이블도 필요없어졌는데, 그래도 넣어놓는게 괜찮지 않나,,? 라는 생각 반, 필요 없는데 걍 지우자 라는 생각 반이 드네요.

2023-10-24 09:18 UTC, carsago commented on src/main/java/kitchenpos/table/application/OrderTableValidator.java
> +}
OrderTable을 저장할때, Order를 활용한 검증이 필요해서, 의존성을 없애기 위해 검증 로직을 인터페이스와 하였습니다.
구현체의 이름은 진짜 못짓겠어서 impl이라고 했는데, impl이 안좋은 네이밍 컨벤션 이라는 걸 알면서도 안떠오르네요. ㅠ

2023-10-24 09:19 UTC, carsago commented on src/main/java/kitchenpos/table/application/TableGroupValidator.java
> +}
이 클래스로 TableGroupService에서 Order 패키지에 대한 의존성이 필요해서 검증을 인터페이스화 하였어요

2023-10-24 09:23 UTC, carsago commented on src/main/java/kitchenpos/order/Order.java
>      private OrderTable orderTable;
Order가 OrderTable에 의존할 것이냐 그 반대로 할것이냐(패키지를 포함하여)를 고민했는데요.

전 Order가 OrderTable에 의존하는 방향으로 택했습니다.

이유는 뭔가 코드를 리팩터링하는 아이디어가 이 방식이 더 쉽게 떠올랐던게 첫번째
두번째는 Order가 영속화 될 때, OrderTable과 OrderTable의 empty 여부에 대한 검증을 가지기 때문에 Order가 OrderTable에 의존하는게 더 자연스럽다고 여겼어요.

2023-10-24 13:07 UTC, apptie requested changes
안녕하세요 오리 
반갑습니다
바쁘셔서 리뷰 적용은 패스하시는줄...그런 이슈가 있었군요..
패키지 분리도 다 해주시고 고생 많으셨습니다 

하나를 제외하고는 소소한 리뷰 혹은 질문이라서 그냥 가볍게 봐 주시면 될 것 같습니다 
현재 인텔리제이에서 애플리케이션 실행 시 일부 api 호출이 안되는 상황이라서 이 부분에 대한 수정을 부탁드리고 싶네요 
제 로컬에서 gradle, 인텔리제이 모두 동작하지 않아서..만약 제 문제라면 미리 죄송합니다 ㅎㅎ;

<img width="1312" alt="image" src="https://github.com/woowacourse/jwp-refactoring/assets/57691173/f1270b2b-5cec-4324-8ce4-d4ba54f6bc7d">

2023-10-24 13:07 UTC, apptie commented on src/main/java/kitchenpos/menu/MenuGroup.java
의견 공유 감사합니다 👍 충분히 납득이 되는 이유인 것 같습니다 

여담이지만 저랑 정확히 반대의 이유로 넣으셨군요

저는 필수 불가결한 조건이며 결국 Menu를 그룹핑하기 위한 기능만 수행하지만 라이프 사이클이 다르기 때문에 분리했었습니다 
그냥...그렇습니다 ㅎㅎ;

2023-10-24 13:07 UTC, apptie commented on src/main/java/kitchenpos/menu/MenuProduct.java
> +    private Price price;
MenuProducts.values()에 JoinColumn 옵션이 있으니 menu_id를 넣어주었다고 인지하면 되...겠죠?

저도 3단계 미션을 진행하면서 MenuProduct와 menu, product와의 관계를 그대로 유지하고 있어서 지금 코드는 제 의견이랑 동일한 것 같습니다 

요구사항에 메뉴 정보가 변경되더라도 주문 항목이 변경되지 않게 구현이라고 되어 있지만 도메인이 필요한 필수적인 정보는 클래스 의존성의 종류와는 상관 없이 도메인에서 표현되어야 한다고 생각해서 요렇게 유지를 했었습니다

만약 menu_id와 같은 관계가 없다면 도메인 만으로는 도메인끼리의 관계를 설명해줄 수 없어 좀 어색하게 느껴질 것 같습니다 
도메인에서 직접적인 관계가 없으니 서비스에서 모든 전처리/후처리를 해줘야할텐데 이거는 2단계 요구사항이랑 좀 상반되는 느낌인 것 같았습니다 

도메인끼리의 관계가 없을 때 삭제 로직이 추가된다면 어떤 부분이 삭제된건지 추적하고 처리하는 과정이 더 복잡할 것 같다는 생각도 들고 그렇습니다

2023-10-24 13:07 UTC, apptie commented on src/main/java/kitchenpos/menu/MenuProducts.java
> +    @JoinColumn(name = "menu_id", updatable = false, nullable = false)
꼼꼼하시네요 👍 
저도 이거 넣어야겠네요 ㄷㄷ;

2023-10-24 13:07 UTC, apptie commented on src/main/java/kitchenpos/order/Order.java
>      private OrderTable orderTable;
동의합니다!
OrderTable이 Order 여러개를 가질 수 있는 방식이라고는 하지만 도메인상으로는 Order가 여기저기에 많이 쓰여서 루트 애그리거트 느낌이라고 생각합니다

2023-10-24 13:07 UTC, apptie commented on src/main/java/kitchenpos/order/application/OrderTableValidatorImpl.java
> +        if (orderRepository.existsByOrderTableIdAndOrderStatusIn(orderTableId,
이제 든 생각인데 해당 부분은 쿼리를 통해 비즈니스 로직을 수행하고 있다는 생각이 들었습니다 
상태가 추가되거나, MEAL 상태에서도 OrderTable의 empty를 true로 바꾸거나 할 수 있다면 쿼리와 관련된 프로덕션 영역까지 변경이 이루어지지 않을까 싶습니다

OrderTableId과 관련된 Order를 조회하고 그 Order의 상태가 유효한지 확인하는 방법은 어떨까요?

2023-10-24 13:07 UTC, apptie commented on src/main/java/kitchenpos/table/application/OrderTableValidator.java
> +}
네이밍....어렵네요...

이 인터페이스는 empty 상태를 변경하는지만 검증하니 ChangeOrderTableValidator로 인터페이스 이름을 바꾸고 ChangeOrderTableByOrderStatusValidator...? 이런 거 밖에 떠오르지 않네요...

2023-10-24 13:07 UTC, apptie commented on src/main/java/kitchenpos/table/application/TableGroupValidator.java
> +}
👍

2023-10-24 13:07 UTC, apptie commented on src/main/resources/db/migration/V4__change_schema.sql
> +    ADD price decimal(19, 2) not null;
이런 식도 가능합니다

```
alter table menu_product add price decimal(19, 2);
alter table menu_product add name varchar(255);

update menu_product mp
set (mp.name, mp.price) = (
    select p.name, p.price
    from product p
    where p.id = mp.product_id
)
where exists (
    select 1
    from product p
    where p.id = mp.product_id
);
```

2023-10-24 13:07 UTC, apptie commented on src/test/java/kitchenpos/order/OrderTest.java
> +        return new Order(new OrderTable(5, false), orderStatus, orderLineItems, LocalDateTime.now());
👍

2023-10-24 13:07 UTC, apptie commented on src/main/java/kitchenpos/menu/MenuProduct.java
> +    }
네이밍이 좀 헷갈리는 것 같습니다...
getTotalPrice나 calculateTotalPrice 정도로 표현해보시는건 어떤가 건의드려봅니다

2023-10-24 13:07 UTC, apptie commented on src/main/java/kitchenpos/menu/Menu.java
> +    @Embedded
여기는 아니지만 `private Long menuGroupId;` 필드에 궁금한 부분이 있어서 여기에 코멘트를 남깁니다...

같은 패키지 안에 두셨는데도 불구하고 직접 참조가 아닌 간접 참조로 설정해주신 이유가 궁금합니다

2023-10-25 05:13 UTC, carsago commented on src/main/java/kitchenpos/menu/MenuProduct.java
> +    }
calculateTotalPrice가 좋네용

2023-10-25 05:21 UTC, carsago commented on src/main/java/kitchenpos/menu/Menu.java
> +    @Embedded
저는 직접참조가 필요없다면 항상 간접참조로 걸려고 했습니다(같은 패키지임에도 불구하고).
왜냐하면 그게 객체 생성이 더 쉬워지기 때문에, 테스트 & 유지 보수가 더 쉬운 코드라고 여겼기 때문이에요.

구체적으로 제가 판단한 직접참조가 필요한 경우라면, 직접적으로 객체간의 협력이 필요한 경우, 생성시 다른 객체를 통한 유효성 검증이 필요한 경우라고 여겼어요. 그런데 Menu에게 MenuGroup은 그런 존재가 아니기에에 간접참조로 풀었습니다.

2023-10-25 05:29 UTC, carsago commented on src/main/java/kitchenpos/order/application/OrderTableValidatorImpl.java
> +        if (orderRepository.existsByOrderTableIdAndOrderStatusIn(orderTableId,
저도 이 부분을 조금 고민하다가 결국 바꾸지 않기로 고민했는데 이유는 다음과 같아요.

1. 단순히 ```orderRepository.findByOrderTableId(Long orderTableId)```와 같은 메소드를 통해 해결한다면, 주문이 완료된 Order까지 모두 조회해서 성능상 좋지 않다고 보았어요(물론 미션에서는 성능보다는 유지보수성, 가독성을 중시하는 편이긴 합니다.)

2. 또한 그렇게 찾은 ```List<Order>``` 을 통해 서비스 레이어에서 stream이나 반복문을 통해서 검증 로직을 진행하기에, 서비스 레이어에 관련된 로직을 분리하기가 어려웠어요.

3. Order에게 OrderStatus를 통해 OrderTable의 상태를 변경시킬 수 있는지 알려줘!! 라는 메시지를 보낸다는게 조금 어색하다는 생각도 들었어요.

4. 현재 쿼리를 통해 검증을 진행하지만, 단순히 service layer에서 List로 OrderStatus로 넘겨줄뿐이라 완전히 쿼리로 푸는 것은 아니다! 라고 생각했습니다.

저도 지토가 의견을 주신 것처럼 코드가 마음에 안드는 부분이 있었는데, 고민을 해보니 뭔가 좋게 바꾸기도 애매하다.. 라는 생각이 들어서 유지하기로 했었어요.

2023-10-25 05:32 UTC, carsago commented
지토가 말씀해주신 부분은 DTO가 1개의 필드를 가질때 noArgsConstructor가 필요한 문제였네요.
레벨 2때 알게된 거였는데, 다시 떠올릴 수 있었습니다.. API 호출 관련된 테스트를 안짜다 보니 이런 문제가 있었네요. 
더불어 원시값을 ```@RequestBody```로 받았을 때 매핑이 안되는 경우가 있어서 이 부분도 다 DTO 객체로 포장해주는 부분을 넣었습니다 ㅎㅎ;

2023-10-25 05:35 UTC, carsago commented on src/main/resources/db/migration/V4__change_schema.sql
> +    ADD price decimal(19, 2) not null;
마법같네요

2023-10-25 06:27 UTC, apptie approved these changes
고생하셨습니다 

추가적으로 소소한 제 의견과 질문을 남기기는 했는데 여유가 되신다면...답변해주시면 감사할 것 같습니다
바쁘시면 패스하셔도 괜찮습니다 

approve 하겠습니다!

2023-10-25 06:27 UTC, apptie commented on src/main/java/kitchenpos/menu/Menu.java
> +    @Embedded
좋은 의견인 것 같네요!

저는 같은 패키지에 있으면서 같이 조회하는 경우는 성능을 고려해 직접 참조로 설정해주었는데 저랑 반대되는 방식으로 진행해주셔서 궁금해서 질문 드렸습니다 

조회를 전혀 고려하지 않고 본다면 오리가 선택해주신 경우가 더 명확해질 것 같네요

2023-10-25 06:27 UTC, apptie commented on src/main/java/kitchenpos/order/application/OrderTableValidatorImpl.java
> +        if (orderRepository.existsByOrderTableIdAndOrderStatusIn(orderTableId,
이해했습니다! 왜 그대로 유지하셨는지 충분히 납득이 되네요
그래서 너무 리뷰를 날로 먹은 거 같아서 추가로 제 의견을 적어보도록 하겠습니다 ㅎㅎ;

---

1번과 같은 성능 이슈는 전적으로 동의하고 4번은 제가 헷갈린 부분입니다...
말씀해주신 대로 미션 환경에서는 Service Layer에서 호출 시 파라미터값만 추가되고 끝나겠네요 ㅎㅎ; 죄송합니다 
그래도 다른 부분에 대한 제 추가적인 생각을 적어보도록 하겠습니다 

> `List<Order>` 을 통해 서비스 레이어에서 stream이나 반복문을 통해서 검증 로직을 진행하기에, 서비스 레이어에 관련된 로직을 분리하기가 어려웠어요.

이 부분은 `OrderTableValidatorImpl`로 검증 로직을 분리하면서 자연스럽게 해소되었다고 느껴졌습니다 
`OrderTableValidatorImpl.validateChangeEmpty()`에서 `List<Order>`를 찾아서 반복문으로 검증하면 되지 않을까 생각이 들었습니다
`TableGroupValidatorImpl.ungroup`에서 `Order`를 찾아서 확인하는 느낌을 생각했습니다 

> Order에게 OrderStatus를 통해 OrderTable의 상태를 변경시킬 수 있는지 알려줘!! 라는 메시지를 보낸다는게 조금 어색하다는 생각도 들었어요.

이거는 `Order`에게 상태를 변경할 수 있는지 여부를 묻는 것이 아닌 `Order`가 특정 상태인지만 물어보고 그 상태에 따라 분기처리를 하면 되지 않을까 싶었습니다
이미 `Order.isNotCompletion()` 메서드가 있으니 이 주문이 계산되었는지 여부를 반환해주고 이를 통해 터뜨리면 문맥 상 어색하지는 않게 느껴지기도 하고, 이미 존재하고 있는 도메인 비즈니스 로직을 재활용한다는 생각이 들었습니다

2023-10-25 06:27 UTC, apptie commented on src/main/java/kitchenpos/table/application/TableGroupValidator.java
> +package kitchenpos.table.application;
이 부분을 지금 발견했는데 Validator를 application 패키지에 위치시킨 이유가 궁금합니다 

Repository를 DB 기술을 구현하는 외부 기술로 보고 Validator가 Repository에 의존해서 이렇게 작성해주신게 맞을까요?
아니면 구현체를 스프링 빈으로 등록해주셔서 그런걸까요?

다른 분들은 DDD 스타일로 작성해 Repository를 도메인으로 보고 Validator를 스프링 빈으로 등록시킨것과 무관하게 도메인 영역에 위치시키는 모습을 많이 봐서 질문드립니다

이렇게 하면 TableGroup도 도메인이고 Validator 인터페이스도 도메인이기 때문에 TableGroup.upgroup()에서 validator를 전달해 ungroup() 메서드 내에서 검증을 수행하는 식으로 도메인에 존재하는 비즈니스 로직이 항상 유효한 상태에서 진행될 수 있도록 할 수 있을 것 같기는 합니다 
대신 테스트는 그만큼 좀 까다로울 것 같기는 하네요

2023-10-25 06:27 UTC, apptie commented on src/main/java/kitchenpos/menu/MenuProduct.java
> +    private Long productId;
소소한 내용이기는 한데... productId가 다시 추가되었으니 getter도 추가하면 좋을 것 같네요

2023-10-25 06:27 UTC, apptie commented on src/main/java/kitchenpos/menu/MenuProducts.java
> +            .map(MenuProduct::calculateTotalPrice)
MenuProduct의 경우 단위 테스트가 존재하는데 MenuProducts는 단위 테스트가 없는 것 같았습니다
OrderLineItems는 테스트가 있는데 얘만 테스트가 누락된 느낌이기는 하네요 

요것도 추가하면 더 탄탄한 애플리케이션이 될 수 있을 것 같습니다만 선택의 영역으로...두겠습니다

2023-10-25 06:27 UTC, apptie commented on src/main/java/kitchenpos/menu/MenuProduct.java
> +    public BigDecimal calculateTotalPrice() {
👍

2023-10-25 06:28 UTC, merged