[ refactoring - 4단계 ] 박스터 미션 제출합니다
woowacourse/jwp-refactoring pull request #664
Opened 2023-10-25 13:49 UTC by drunkenhw

안녕하세요 헙크 
이번 미션은 멀티 모듈로 분리하는 것이었는데요 컨텍스트를 기준으로 나눌까, 혹은 레이어로 나눌까 많은 고민을 했지만, 
컨텍스트로 나누는 것은 너무 복잡해질 것 같다는 생각에 외부와 소통하는 api 모듈과 도메인 로직을 가지고 있는 core 모듈로 나눠봤습니다
하지만 멀티 모듈을 나누는 경험은 처음이라 잘한 것인지 모르겠네요 .. 테스트에서 spring bean을 찾지 못해 꽤나 고생했습니다.
감사합니다 화이팅입니다.

2023-10-26 11:54 UTC, HubCreator requested changes
안녕하세여 박스터~ 이번 미션도 빠르게 진행해주셨군요. 로직이나 테스트에 대한 피드백보다는 이번 단계 미션 주제인 멀티모듈에 관련해서 얘기를 나눠보고 싶군여! 아래에 코멘트 달아놓겠습니다 감사합니다.

2023-10-26 11:54 UTC, HubCreator commented on kitchenpos-api/src/main/java/kitchenpos/ui/OrderRestController.java
>          final OrderResponse created = orderService.create(request);
이부분 API 호출시 500 에러가 나서 확인 한 번 해주세요!

2023-10-26 12:06 UTC, drunkenhw commented on kitchenpos-api/src/main/java/kitchenpos/ui/OrderRestController.java
>          final OrderResponse created = orderService.create(request);
<img width="767" alt="image" src="https://github.com/woowacourse/jwp-refactoring/assets/106640954/c7ecba41-53c5-4786-a197-3a50603fabfd">

저 다 돌아가는거 확인해보고 제출했는데 호출해보니
처음 넣은 더미데이터의 주문이 빈 테이블이 아니라서 그렇다네요 ㅎㅎ..
더미데이터가 아닌 다른 정보를 넣으면 잘 되는데 한번 확인해보시겠어요?

2023-10-26 12:07 UTC, HubCreator commented on kitchenpos-api/src/main/java/kitchenpos/ui/OrderRestController.java
>          final OrderResponse created = orderService.create(request);
ㅎㅎㅎ 넵넵 :) 확인 감사합니다

2023-10-26 12:08 UTC, HubCreator commented
박스터어어. 위에서 언급해주신 용어에 대해서 먼저 질문드리고 싶습니다. 
1. 박스터가 생각하는 컨텍스트란 무엇이고, 컨텍스트로 모듈을 나누면 어떤 부분이 복잡해질 것으로 예상하셨나요? (제가 파악하기론 컨텍스트가 도메인에 대응될 것 같은데 맞을까요?!?) 반대로 어떤 장점이 있을까요?
2. 모듈화의 장점은 무엇이고, 현재 구현해주신 모듈화 구조는 이전과 대비해 어떤 이점이 생겼나요?

2023-10-29 04:20 UTC, HubCreator commented
박스터 바쁜 와중에도 빠르게 미션도 구현해주시고, 직접 찾아와 친절하게 답변해주셔서 감사합니다 ㅎㅎㅎ 
이번 미션과 그동안의 과정 모두 고생하셨습니다. 이만 머지하겠습니다! :)

2023-10-29 04:20 UTC, merged