[레거시 코드 리팩터링 - 3단계] 망고(고재철) 미션 제출합니다.
woowacourse/jwp-refactoring pull request #680
Opened 2023-10-26 09:35 UTC by Go-Jaecheol

안녕하세요 주노..
2단계에 이어서 3단계는 빨리 돌아왔습니다.
리팩터링.. 정신 나갈 것 같네요 🥲

우선 이번에 의존성 끊어주고 수정한 방향부터 설명드릴게요.
- Menu -> MenuGroup
  - AS-IS : 단방향 직접 참조
  ```mermaid
  graph LR
    Menu --> MenuGroup
  ```
  - TO-BE : 단방향 간접 참조
  ```mermaid
  graph LR
    Menu -.-> MenuGroup
  ```
- Menu <-> MenuProduct
  - AS-IS : 양방향 직접 참조
  ```mermaid
  graph LR
    Menu --> MenuProduct
    MenuProduct --> Menu
  ```
  - TO-BE : 단방향 직접 참조
  ```mermaid
  graph LR
    Menu --> MenuProduct
  ```
- MenuProduct -> Product
  - AS-IS : 단방향 직접 참조
  ```mermaid
  graph LR
    MenuProduct --> Product
  ```
  - TO-BE : 단방향 간접 참조
  ```mermaid
  graph LR
    MenuProduct -.-> Product
  ```
- OrderLineItem -> Menu
  - AS-IS : 단방향 직접 참조
  ```mermaid
  graph LR
    OrderLineItem --> Menu
  ```
  - TO-BE : 단방향 간접 참조
  ```mermaid
  graph LR
    OrderLineItem -.-> Menu
  ```
- Order <-> OrderLineItem
  - AS-IS : 양방향 직접 참조
  ```mermaid
  graph LR
    Order --> OrderLineItem
    OrderLineItem --> Order
  ```
  - TO-BE : 단방향 직접 참조
  ```mermaid
  graph LR
    Order --> OrderLineItem
  ```
- Order -> OrderTable
  - AS-IS : 단방향 직접 참조
  ```mermaid
  graph LR
    Order --> OrderTable
  ```
  - TO-BE : 단방향 간접 참조
  ```mermaid
  graph LR
    Order -.-> OrderTable
  ```
- OrderTable <-> TableGroup
  - AS-IS : 양방향 직접 참조
  ```mermaid
  graph LR
    OrderTable --> TableGroup
    TableGroup --> OrderTable
  ```
  - TO-BE : 단방향 간접 참조
  ```mermaid
  graph LR
    OrderTable -.-> TableGroup
  ```

---

영상 보고 어떤 부분에서 의존성을 끊어줘야 할지 고민할 때는 시간 오래 걸려도 재밌었는데,
실제로 리팩터링 과정을 거치니까 생각보다 복잡하고 시간 오래 걸리고 정신 나갈 뻔 했네요 ㅎㅎ,,

파일 체인지가 많은데 그건 아마 패키지 수정 때문일 거예요.
이벤트... 처음 사용해봐서 매우 이상할 수 있는데 리뷰 잘 부탁드립니다 :)

2023-10-26 15:55 UTC, Choi-JJunho requested changes
망고! 3단계도 꼼꼼하게 잘 진행해주셨네요~!

항상 느끼지만 망고의 꼼꼼한 테스트에 항상 감동을 받고갑니다 🥹

TableGroup에 대한 Validator가 없는 이유가 궁금하여 잠시 RC 드립니다~
해당 질문에대한 답변 남겨주시면 Approve 하겠습니다!

2023-10-26 15:55 UTC, Choi-JJunho commented on README.md
> +## 의존성 리팩터링
mermaid 예쁘네요 👍
덕분에 구조를 한눈에 파악하기 좋았습니다.

2023-10-26 15:55 UTC, Choi-JJunho commented on src/main/java/kitchenpos/application/tablegroup/TableGroupEventHandler.java
> +    public void handleGroup(final TableGroupGroupedEvent event) {
파라미터에 Event가 선언되어있으면 ArgumentResolver로 인식합니다!
크게 상관은 없지만 명시적으로 선언해준 이유가 있을까요?

```suggestion
    @EventListener
    public void handleGroup(final TableGroupGroupedEvent event) {
```

2023-10-26 15:55 UTC, Choi-JJunho commented on src/main/java/kitchenpos/application/tablegroup/TableGroupService.java
> +        }
요친구는 Validator가 없는 이유가 있나요??

2023-10-27 03:29 UTC, Go-Jaecheol commented on src/main/java/kitchenpos/application/tablegroup/TableGroupEventHandler.java
> +    public void handleGroup(final TableGroupGroupedEvent event) {
오.. 이 부분은 솔직히 시간이 부족해서 제가 제대로 모르고 사용한 것 같아요 🥲

이벤트를 발행하는 방식 말고 다른 방식을 사용할까 생각하다가 한 번 써보자!라는 마인드로 썼는데 하하,,

하나 더 알아갑니당

2023-10-27 03:34 UTC, Go-Jaecheol commented on src/main/java/kitchenpos/application/tablegroup/TableGroupService.java
> +        }
지금까지 만든 다른 Validator들은 전부 도메인에 대한 검증 로직만 두도록 만들었는데, 이 부분은 request에 대한 검증이라고 생각해서 Service에서 검증하는 게 자연스럽다고 생각했습니다!

주노는 어떻게 생각하시나요??

2023-10-27 06:08 UTC, Choi-JJunho commented on src/main/java/kitchenpos/application/tablegroup/TableGroupService.java
> +        }
오~! request에 대한 검증이라는 부분에서 해당 부분에 존재하는 것 동의합니다~ 👍

2023-10-27 06:37 UTC, Choi-JJunho requested changes
망고~ 안녕하세요!
반영해주신 내용 확인했습니다~
DB Cleaner까지 깔끔하게 구성하셨네요! 👏👏

한가지 3단계에서 요구하고있는 `메뉴의 이름과 가격이 변경되면 주문 항목도 함께 변경된다. 메뉴 정보가 변경되더라도 주문 항목이 변경되지 않게 구현한다.` 에 대한 요구사항이 반영되어있지 않은 것 같아요~!

<img width="781" alt="image" src="https://github.com/woowacourse/jwp-refactoring/assets/49794401/c61c2a17-27d4-4e61-a313-e6b056c54547">

이전 리뷰에서 미처 발견하지 못했던 부분이라 죄송합니다 🙏
요구사항 다시한번 확인 후 반영 부탁드릴게요!!

2023-10-29 03:22 UTC, Choi-JJunho approved these changes
반영해주신 내용 확인했습니다!
4단계도 화이팅!!

2023-10-29 03:22 UTC, merged