[레거시 코드 리팩터링 - 3단계] 저문(유정훈) 미션 제출합니다.
woowacourse/jwp-refactoring pull request #747
Opened 2023-10-27 11:50 UTC by jeomxon

안녕하세요 성하 :)
원래 개발하면서 의존성에 대해서는 잘 생각해본 적이 없는데,
막상 해보니 정말 생각할 부분이 많고 어려운 것 같아요...

제가 맞게 한지는 모르겠는데, 

![image](https://github.com/woowacourse/jwp-refactoring/assets/51906604/57f8def4-98ea-4a3c-8a9f-bfbb82a60aee)
![image](https://github.com/woowacourse/jwp-refactoring/assets/51906604/11692722-4b96-490e-9995-257989f48426)

위의 그림에서 아래 그림으로 변경했어요!
(제가 엄청난 악필이라 죄송합니다ㅠㅠ 알아보기 힘드시면 툴을 사용해서 다시 만들어볼게요..!)

이번 리뷰도 잘 부탁드립니다!🙇🏻‍♂️🙇🏻‍♂️🙇🏻‍♂️

2023-10-27 13:08 UTC, sh111-coder requested changes
안녕하세요 저문!!! 빠르게 리뷰 드립니다 ㅎㅎㅎㅎ 👍🏻👍🏻

한번에 모든 패키지 양방향 의존을 해결해주셨네요!! 
짧은 시간 안에 잘 해주신 것 같아요!!

몇 가지 저문의 설계 방향이나 궁금한 부분들, 개선 제안 사항들을 코멘트로 남겼습니다!!
답변 부탁드려요 ㅎㅎㅎ 👍🏻👍🏻👍🏻
모르는 부분이 있으면 편하게 DM 주세요! 

얼마 안 남았지만 화이팅해봅시다!!!

2023-10-27 13:08 UTC, sh111-coder commented on src/main/java/kitchenpos/common/OrderStatus.java
> +package kitchenpos.common;
제이슨이 잡담에 남겨주신 말보고 커밋 메시지 `컨텍스트별 패키지 분리`라고 하신거죠?ㅋㅋㅋㅋㅋㅋ
큐트하시네요 ❤️

그 전에 했다면 대단하신데요? ❤️

2023-10-27 13:08 UTC, sh111-coder commented on src/main/java/kitchenpos/common/OrderStatus.java
>      COOKING, MEAL, COMPLETION
`OrderStatus` 클래스는 `common` 패키지 보다는 `domain.order` 패키지 하위에 두는 것이 어떨까요?
주문 상태 목록이 추가되거나 삭제되는 등 변경되는 것도 `Order` 컨텍스트의 비즈니스 로직이라고 생각해서
변경이 될 때 `common` 패키지가 변경되는 것 보다는 `domain.order` 패키지에서 비즈니스 로직이 변하는 느낌이 더 좋을 것 같아요!

2023-10-27 13:08 UTC, sh111-coder commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +    private List<MenuProduct> getMenuProducts(final List<MenuProductRequest> menuProductRequests) {
이 부분은 2단계에서 놓쳤던 것 같은데,
Request 부분은 DTO를 만드시고, Response는 엔티티 그대로 반환하는 이유가 따로 있을까요?

그리고 이렇게 Response DTO를 만들어서 반환하지 않고 그대로 반환했을 경우에 어떤 문제가 발생할 수 있는지 
인지하고 계시는지 궁금합니다!!

(Menu와 MenuProduct에서 List<MenuProduct>와 Menu Getter가 존재하지 않는데 해당 문제를 방지하기 위해서
일부러 제거해주신 것인지 궁금합니다!)

2023-10-27 13:08 UTC, sh111-coder commented on src/main/java/kitchenpos/table/domain/OrderTable.java
>  public class OrderTable {
`OrderTable`과 `TableGroup`을 별도의 컨텍스트(패키지)로 분리해주신 이유가 있을까요?!

2023-10-27 13:08 UTC, sh111-coder commented on src/main/java/kitchenpos/tablegroup/domain/TableGroupGenerator.java
> +public class TableGroupGenerator {
해당 클래스명을 `setOrderTableGroupId` 때문에 `Validator`가 아닌 `Generator`로 지어주신 걸까요?
`validate` 로직만 해당 클래스에서 처리하도록 해서 `Validator`로 책임을 명확히 하고,

`setOrderTableGroupId` 로직은 서비스에서 처리하도록 하는게 어떨까요??

2023-10-27 13:08 UTC, sh111-coder commented on src/main/java/kitchenpos/menu/domain/Menu.java
>  public class Menu {
이번 3단계 의존성 리팩토링을 진행하면서 
`DDD`와 `애그리거트`에 대한 개념을 생각하시면서 적용하신 걸까요? 
아니면 단순히 의존성 해결만 생각해서 적용하신 걸까요?!

어떻게 생각하셨는지에 따라서 객체 간 의존에 관한 리뷰 방향이 달라질 것 같아서 질문드립니다!!

이에 대한 추가 질문으로
다른 패키지 간의 객체 간 의존은 모두 간접 참조를 통해 끊어주시고,
같은 패키지 간에서 객체 간 의존은 모두 직접 참조를 통해 양방향으로 의존해주셨는데
어떤 생각을 가지고 설계하셨는지 저문의 의존성 설계 기준이 궁금합니다!

2023-10-27 13:08 UTC, sh111-coder commented on src/main/java/kitchenpos/table/dto/OrderStatusValidated.java
> +public class OrderStatusValidated {
`Event` 관련한 DTO는 접미사로 `Event`를 붙이는게 명시적으로 좋은 것 같아요!
처음에 `Event`가 없어서 이벤트에 사용되는 DTO라고 생각을 못하게 됐었습니다!!

2023-10-27 13:08 UTC, sh111-coder commented on src/main/java/kitchenpos/order/application/OrderEventListener.java
> +    @EventListener
이벤트 리슨에 관해서 `@EventListener` 외의 다른 방법으로 리슨할 수 있다는 것도 알고 계신가요?!
이는 이벤트 리슨 시점과 트랜잭션과 관련이 있는데요!
혹시 알고 계시다면 왜 기본인 `@EventListener`를 사용했는지 설계 시 고려했던 부분을 알 수 있을까요?
모르신다면 `@TransactionalEventListener`와 스프링 이벤트 사용 시 고려할 부분들을 추가로 알아보시면 좋을 것 같아요!!

2023-10-27 13:08 UTC, sh111-coder commented on src/main/java/kitchenpos/table/application/TableService.java
> +    private final ApplicationEventPublisher applicationEventPublisher;
이벤트를 Service Layer에서 ApplicationEventPublisher를 사용하여 발행하는 방법도 있지만, AbstractAggregateRoot를 사용하는 방법도 있는데요, 다음과 같이도 가능합니다.
```java
@MappedSuperclass
@EntityListeners(AuditingEntityListener.class)
public class CommonDomainModel extends AbstractAggregateRoot<CommonDomainModel> {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    private Long id;

    @CreatedDate
    private LocalDateTime createdDate;

    @Override
    public List<Object> domainEvents() {
        return new ArrayList<>(super.domainEvents());
    }
}
```
```java
public class Order extends CommonDomainModel {

    public void place() {
         registerEvent(new OrderCreateValidationExcetion());
    }
}
```
말랑이 저한테 알려준 코멘트 그대로 복붙해봤습니다 ㅎㅎㅎㅎ 저런 방법도 있더라구요!

저는 이벤트를 적용하면서 서비스 필드에 ApplicationEventPublisher 객체를 의존하는 것이 조금 찝찝했는데요!
`AbstractAggregateRoot`를 상속받아서 `registerEvent`를 하면 도메인 내에서 이벤트를 발행할 수 있어서
비즈니스 로직이 더 도메인에 속하게 되어 도메인만 봐도 비즈니스 로직을 이해할 수 있을 것 같아서 좋을 것 같다고 생각하게 됐습니다!
적용은 안하셔도 되고 이러한 방법이 있다는 것을 알아두셨으면 좋겠어서 코멘트 남겼습니다!! 👍🏻👍🏻👍🏻

2023-10-27 13:08 UTC, sh111-coder commented on src/main/java/kitchenpos/table/application/TableService.java
> +        applicationEventPublisher.publishEvent(new OrderStatusValidated(orderTableId));
현재 Table에서 Order로의 의존을 분리하기 위해 이벤트를 통해 의존성을 분리한 것으로 보이는데요!

이벤트는 한 도메인의 어떤 로직이 발생한 것을 트리거로 해서 다른 도메인의 로직을 발생시킬 때 주로 쓰이는 것 같아요!
(ex : '팀' 도메인에서 팀이 생성됐을 때 팀 생성 이벤트 발행 -> '게시글' 도메인에서 이벤트를 받아서 '팀 생성 알림' 생성)

그런데 저문이 구현해주신 이벤트를 보면 OrderTable의 changeEmpty 시 이벤트를 발행하고,
이벤트를 리슨하는 리스너의 로직 주체가 리슨하는 'Order'가 아닌 'OrderTable'의 검증에 대해 로직을 실행하고 있는데요!
이러한 경우에는 이벤트가 적절하지 않은 것 같습니다!!

그래서 해당 의존성을 분리하기 위해서는 인터페이스를 통한 의존성 역전을 구현해보는게 어떨까 싶어요!
지금 구현하신 이벤트 리슨 로직을 `Validator`로 따로 인터페이스 클래스로 추출해서 의존성을 역전시키면
Table -> Order로의 의존성을 해결할 수 있을 것 같습니다!

해당 부분은 LMS에 있는 우아한 객체지향의 1:27:13초 부분부터 참고하시면 도움이 될 것 같아요!

2023-10-27 13:44 UTC, jeomxon commented on src/main/java/kitchenpos/common/OrderStatus.java
> +package kitchenpos.common;
사실 LMS보고..ㅎㅎ 아무생각없이 적었는데 봐주셨군요 :)

2023-10-28 06:25 UTC, jeomxon commented on src/main/java/kitchenpos/common/OrderStatus.java
>      COOKING, MEAL, COMPLETION
처음에는 Order 패키지뿐만아니라  TableGroup에서도 참조하고 있다고 생각해서 공통된 부분이라 생각했어요.
그래서 어쩔 수 없이 패키지를 분리했었는데요.
단방향으로 잘 흐르고 있기에 order패키지 내부에 두어도 상관없을 것 같네요!

2023-10-28 06:31 UTC, jeomxon commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +    private List<MenuProduct> getMenuProducts(final List<MenuProductRequest> menuProductRequests) {
먼저 response를 위한 dto를 따로 만들지 않는 경우, 도메인 객체가 변경될 때 API스펙이 변경되게 됩니다.

2단계를 진행하는데 꽤 오랜시간이 걸렸고 학습의 주된 목적을 고려해봤을 때 request, response에 대한 dto보다
다른 부분에서 얻어가야할 것이 많았다고 생각했습니다. 따라서 최대한 리소스를 줄이기 위해서 변경하지 않았습니다.

다만, request dto를 사용했던 것은 요청에서 필요한 검증과 도메인에서 필요한 검증이 분리되어야 테스트 작성에 용이하다고 생각했고,
서비스 계층에 비즈니스 로직이 뭉쳐있는 경우 request로 받는 데이터들에 대한 구분이 있어야 제가 로직을 파악하기 더 쉬울 것 같다고 생각헀습니다!
따라서 통일성을 위해서 request만 dto를 전부 만들어주는 방식을 택했습니다.

2023-10-28 06:32 UTC, jeomxon commented on src/main/java/kitchenpos/table/domain/OrderTable.java
>  public class OrderTable {
컨텍스트를 생명주기 단위로 분리하려고 했습니다.
둘은 생명주기가 다르다고 판단해서 컨텍스트 분리를 했습니다!

2023-10-28 06:37 UTC, jeomxon commented on src/main/java/kitchenpos/table/dto/OrderStatusValidated.java
> +public class OrderStatusValidated {
네이밍을 하는데 많은 고민을 했었어요.
LMS에서 적혀있는 글을 하나 확인했었는데, 이벤트는 과거에 벌어진 내용을 나타내기 때문에 과거 시제를 사용한다고 되어있더라구요.
일반적으로 클래스 명을 작성할 때 과거를 포함시키지 않는데, 이벤트 관련 객체는 과거시제를 사용하고 있으므로 충분히 구분할 수 있다고 생각했어요.
오히려 Event라는 접미사를 붙이는 경우 명시적일 수는 있지만, 네이밍이 불필요하게 길어진다는 느낌이 들기도 했습니다!

2023-10-28 06:54 UTC, jeomxon commented on src/main/java/kitchenpos/menu/domain/Menu.java
>  public class Menu {
DDD의 애그리거트 개념을 생각하고 적용한다기보다, 우아한 객체지향의 영상에서 생각나는 포인트를 기준으로 의존성 리팩터링을 진행했어요.
영상에서는 직접적으로 언급하고있지 않지만, 현재와 같은 방식으로 분리하게되면, 결국 애그리거트 단위로 나눠지게 되는 것 같아요.
하지만 제가 DDD가 뭔지 잘 모르기 때문에... 용어가 익숙치 않다는 점 양해 부탁드립니다..!

결론을 말씀드리자면, 생명주기를 기준으로 도메인을 묶었어요.
그리고 그것들이 하나의 패키지 내부에 존재하도록 했구요.
다음으로 각각의 패키지 간의 의존을 끊어주는 방식을 적용했습니다.
추후 패키지 단위로 모듈이 분리될 수 있기에 패키지 내부에서의 양방향 참조는 문제없다고 판단했어요.
따라서 패키지 내부 객체들은 직접참조, 외부는 간접참조를 사용했습니다!

2023-10-28 07:46 UTC, jeomxon commented on src/main/java/kitchenpos/order/application/OrderEventListener.java
> +    @EventListener
`@TransactionalEventListener`를 사용하지 않고 `@EventListener`를 사용한 이유를 여쭤보신 것으로 이해하고 코멘트 남기겠습니다!
(혹시라도 아니라면 다시 코멘트 남겨주세요..ㅎㅎ)
`@EventListener`를 사용하는 경우 해당 리스너 메서드에서 예외가 발생하면 트랜잭션이 롤백된다고 알고 있습니다.
트랜잭션의 추가적인 옵션이 필요하지 않아서 `@EventListener`를 사용했는데, 혹시 제가 생각하지 못한 부분이 있을까요?

2023-10-28 07:58 UTC, jeomxon commented on src/main/java/kitchenpos/tablegroup/domain/TableGroupGenerator.java
> +public class TableGroupGenerator {
성하가 이해하신 부분이 맞습니다!
제가 생각을 하다가 오류가 있었던 것 같은데, 서비스로 로직을 빼는게 훨씬 더 자연스러워 보이네요!

2023-10-28 09:18 UTC, jeomxon commented on src/main/java/kitchenpos/table/application/TableService.java
> +    private final ApplicationEventPublisher applicationEventPublisher;
오 사실 이 방법도 적용해보고 싶긴 했는데 숙련도 이슈가 좀 있어서 한번 사용해봤던 방식으로 했어요.
아직은 새로운 것을 학습하는데 시간이 좀 걸려서 3단계를 진행하는데도 꽤나 오랜 시간이 걸렸어요.
얼마 전 이벤트에 대한 학습을 하면서 AbstractAggregateRoot를 사용할 수 있는 방법이 있다고만 알고 넘어갔는데,
성하가 말씀해주신 이유 때문이었군요!
이후에 추가적으로 학습해보겠습니다 :)

2023-10-28 10:42 UTC, jeomxon commented on src/main/java/kitchenpos/table/application/TableService.java
> +        applicationEventPublisher.publishEvent(new OrderStatusValidated(orderTableId));
이벤트를 사용하는데 적절한 경우가 있는지가 의문이 들어요.
결국 조금 더 상단에서 봤을 때 이벤트를 사용하는 방법, 인터페이스를 통해 의존성을 역전시키는 방법 모두 의존성을 분리하는 과정에서 사용될 수 있다고 생각해요.
또한 OrderTable에 대한 검증이 이루어지고 있지만, 결국 OrderRepository를 호출해서 검증해야하는 부분이므로 order에 대한 검증이라고도 볼 수 있을 것 같아요.

Validator를 통해서 구현하게 된다면 인터페이스, 클래스 등을 확인해야하는 복잡도도 증가할 것으로 예상돼요.
해당하는 검증 메서드 하나만을 위해서 인터페이스와 클래스를 여럿 구현하는 것이 괜찮은가?라는 생각도 들어요.
성하의 추가적인 의견이 궁금합니다!

2023-10-28 10:52 UTC, sh111-coder commented on src/main/java/kitchenpos/menu/application/MenuService.java
> +    private List<MenuProduct> getMenuProducts(final List<MenuProductRequest> menuProductRequests) {
리소스상 의도적으로 Response는 생략했던 것이군요!! 현재 시간이 없으니 생략해도 괜찮을 것 같습니다!!

> (Menu와 MenuProduct에서 List와 Menu Getter가 존재하지 않는데 해당 문제를 방지하기 위해서
일부러 제거해주신 것인지 궁금합니다!)

엔티티를 직접 Response로 사용할 때는 말씀해주신 문제와 더불어서 양방향 연관관계 시 순환참조가 발생하는 문제가 있습니다!

그래서 순환참조를 방지하기 위해 이 부분은 일부러 제거해주신 것일까요??
이러한 부분을 인지하시고 미리 제거해 두신 것인지 궁금했습니다!!

현재는 비즈니스 로직 상 `GET api/menus`를 호출했을 때 MenuProduct 정보도 함께 Response에 담겨야 하는데
Getter가 존재하지 않아서 직렬화가 되지 않아 Response에 담기지 않는 것 같아요!

이때, Menu에서 List<MenuProduct>의 Getter를 생성하고, MenuProduct에서도 Menu의 Getter를 생성하면
직렬화 시에 순환 참조가 발생하여 에러가 발생하게 됩니다!!

비즈니스 로직 상으로 MenuProduct 정보도 함께 Response에 담겨야 하므로 
현재 상황에서는 MenuProduct에서 Menu의 Getter를 생성하지 않고
Menu에서 List<MenuProduct>만 Getter를 생성해두면 될 것 같습니다!!

2023-10-28 11:03 UTC, sh111-coder commented on src/main/java/kitchenpos/table/domain/OrderTable.java
>  public class OrderTable {
저도 처음에는 생명주기를 기준으로 분리를 했었는데요!
생명주기 외에도 비즈니스 로직 상으로도 한번 분리 기준을 추가하는 것도 괜찮은 것 같아요!

주문을 나타내는 Order와 주문 항목을 나타내는 OrderLineItem의 경우 
생명주기도 같지만 비즈니스적으로도 주문과 주문 항목이 하나의 컨텍스트로 묶이는 것이 자연스럽다고 느껴집니다!

이처럼 OrderTable의 그룹인 TableGroup도 생명주기는 다르지만,
하나의 컨텍스트로 묶여도 자연스럽지 않을까 생각이 되네요!

저도 아직 이 부분이 좀 어려워서 컨텍스트를 분리하는 정확한 기준을 정립하기가 어렵더라구요 ㅠㅠ
하나의 의견일 뿐 현재 구조를 유지해도 괜찮습니다 ㅎㅎ

2023-10-28 11:16 UTC, sh111-coder commented on src/main/java/kitchenpos/menu/domain/Menu.java
>  public class Menu {
아하!! 그렇군요!! 
저문이 생각한 방향대로 잘 설계하고 의존성을 분리해주신 것 같아요!!

조금 더 나아가면 같은 패키지 안에서의 객체 간 의존은 단방향으로 의존을 끊어주는 방법도 생각해보시면 좋을 것 같아요!
DDD 개념이긴 한데 외부에서는 애그리거트 루트 (부모 엔티티? Order - OrderLineItem에서 Order)를 접근하여
자식 엔티티(OrderLineItem)들을 접근합니다!

그렇기 때문에 자식 엔티티(OrderLineItem)에서 부모 엔티티(Order)를 접근하는 일은 거의 없을 것 같아요!
그래서 OrderLineItem에서 Order로의 의존을 끊어줘도 된다고 생각합니다!!
OrderLineItem에서 불필요하게 Order를 알고 있어서 OrderLineItem 내부에서 Order.changeOrderStatus 같은 행위를
호출할 수도 있으니까요!!

이러한 부분들도 함께 고민해보시면 좋을 것 같아서 코멘트 남기게 되었습니다 ㅎㅎㅎㅎ

2023-10-28 11:19 UTC, sh111-coder commented on src/main/java/kitchenpos/table/dto/OrderStatusValidated.java
> +public class OrderStatusValidated {
아하 그렇군요!!!
저는 이런 네이밍 같은 경우도 근거 없이 대충 짓는 경우가 많은데
저문은 리뷰하면서 의문이 생겨서 질문을 남기면 항상 근거를 가지고 짠 코드라는 게 답변에서 느껴져서 대단하신 것 같습니다!!
> 이벤트는 과거에 벌어진 내용을 나타내기 때문에 과거 시제를 사용한다고 되어있더라구요.
이 부분은 저도 배워갑니다!!

저는 그래도 이벤트라는 의미를 명시하는 게 좋을 것 같아서 앞으로 과거 시제 + Event 네이밍을 사용할 것 같네요!!

지식 공유 감사합니다 ㅎㅎㅎ

2023-10-28 11:28 UTC, sh111-coder commented on src/main/java/kitchenpos/order/application/OrderEventListener.java
> +    @EventListener
제가 코멘트남긴 부분은 미션에 적용된다기 보다는 스프링 이벤트 기술에 대한 전반적인 내용을 알고 계시는지
여쭤보는 것이었습니다!!

`@TransactionalEventListener`와 트랜잭션의 전파 속성인 Propagation에 대해서 알고 계시면
스프링 이벤트를 좀 더 깊게 사용할 수 있습니다!!

보투게더에서 예시를 들어보면,
투표 게시글이 등록됐을 때 게시글 등록 알림을 이벤트를 통해서 생성한다고 해볼게요!
게시글 Create가 이벤트 발행 로직, 게시글 등록 알림 생성이 이벤트 리슨 로직이라고 했을 때
`@EventListener`를 사용하게 되면 다음과 같은 문제 상황을 해결할 수 없어요!

- 게시글 등록 후에 게시글 등록 알림을 생성할 떄 알림 생성에 예외가 되어서 롤백될 때 게시글 등록도 함께 롤백된다.
비즈니스 상황에 따라 알림 생성이 롤백되어도 게시글 등록은 롤백되지 않게 하는 경우가 있을 텐데요!
이러한 문제는 해결할 수 없게 됩니다!!

이때 `@TransactionalEventListener` 또는 트랜잭션의 전파 속성인 Propagation을 적절히 사용하면
이러한 문제를 해결할 수 있습니다!!

자세한 내용은 제 블로그에도 작성해놨어요 ㅎㅎㅎ... 슬쩍 홍보하고 갑니다
[스프링 이벤트를 사용하여 도메인 의존성 분리하기 - 성하](https://ksh-coding.tistory.com/111)

(이미 아시는 내용이면 죄송합니다 ㅠㅠ 단순 지식 공유로 받아주세요!! ❤️)

2023-10-28 11:43 UTC, sh111-coder commented on src/main/java/kitchenpos/table/application/TableService.java
> +        applicationEventPublisher.publishEvent(new OrderStatusValidated(orderTableId));
저도 의존성을 분리하는 방법으로 이벤트와 인터페이스가 있다는 점에는 동의합니다!

이벤트를 사용하는데 적절한 경우에 대해서는 아직 이벤트를 많이 사용해보지 않아서 저도 기준이 정립되지는 않은 것 같아요 ㅠㅠ
이벤트를 사용하기에 적절하지 않다고 느낀 경우가 이번 미션 진행하면서 검증을 이벤트로 사용하는 사례 1가지만 경험해봐서 
그런 것 같습니다!

그래서 제 나름대로 생각한건 이벤트를 리슨하는 곳에서 어떤 행위가 일어나는가?를 기준으로 삼을 것 같아요!
말로하기 조금 애매하긴 한데, 현재 검증 이벤트는 이벤트를 리슨하는 곳에서 단순히 검증?만 하고 
Order 입장에서는 아무런 조회나 변경이 이루어지지 않고 끝나는데
이런 경우에는 이벤트가 아니라 인터페이스를 사용해서 OrderTable이 직접 검증한다는 느낌을 주는 것이 좋다고 생각이 듭니다!
 
반대로 제가 적절하다고 생각하는 이벤트의 예시를 들어보면
저희 팀바팀 서비스의 경우에 이전에 '일정이 등록되면 일정 등록 알림이 생성되어야 한다'라는 요구사항이 있었어요!
해당 요구사항을 이벤트로 구현해서
'일정' 도메인에서 등록 이벤트를 발행하고 '알림' 도메인에서 알림을 생성하는 로직을 이벤트 리슨 로직으로 설정했었습니다.
이렇게 했을 때 이벤트 리슨 로직에서 '알림' 도메인의 생성이라는 행위가 발생하므로 이벤트가 적절한 것 같아요!

뭔가 말로 설명하기 애매한 부분이라 조금 길어진 것 같네요 ㅠㅠㅠ
지금은 시간이 바쁘니 제 의견만 전달드리고 따로 Validator로 반영은 안해주셔도 괜찮을 것 같아요 ㅎㅎㅎㅎ
제 생각은 이렇다는 걸 전달하기 위한 코멘트였습니다!

2023-10-28 11:46 UTC, sh111-coder approved these changes
안녕하세요 저문!!
저문의 설계나 의견을 물어보는 코멘트가 많았는데, 답변을 잘 해주셔서 감사합니다!!

저문이 재질문 해주신 부분에 대해서는 다 코멘트로 남겨놨어요!
요구사항은 다 만족해주신 것 같아서 Approve & Merge 하지만
남겨둔 코멘트들 열심히 남겼으니 꼭 한번은 읽어주시면 감사하곘습니다 ㅎㅎㅎ ❤️

1단계부터 저문의 의견을 물어보는 코멘트들이 많았는데
항상 근거를 가지고 코드를 짠다는 것이 느껴져서 대단하다고 느꼈습니다!! 👍🏻👍🏻👍🏻

그럼 마지막 4단계도 화이팅 해봐요!!

2023-10-28 11:47 UTC, merged